### ISSUE TITLE
Will there be a license?

### ISSUE THREAD

**Issue by naltun** [willmcgugan/rich#1]
First off, _AWESOME_ project. I'll definitely be tinkering with this.

Question: will you be applying a license to the code? I'm not here to push any license, but I do think at least _having_ a license is a good idea.

Good job on the project 👏 👏

**Comment by willmcgugan** [comment]
Glad you like it! I chose MIT license, but I neglected to copy it to the repos. I’ll fix that in the next update.

**Comment by naltun** [comment]
Great. Closing this. 🙏

**Comment by willmcgugan** [comment]
I’ll keep it open as a reminder.

**Comment by willmcgugan** [comment]
Fixed in 0.3.2
