### ISSUE TITLE
Table border cannot be aligned in windows 7 cmd

### ISSUE THREAD

**Issue by Gwill** [willmcgugan/rich#100]
![image](https://user-images.githubusercontent.com/692980/83595986-18532100-a596-11ea-8948-075a595d574f.png)

**Comment by willmcgugan** [comment]
I think I see the problem from your screenshot. The box characters are rendering too wide. Not sure why that would be as I've tested cmd on Window 10, but you might want to try a different font.

A workaround would be to use `box=box.ASCII` in your tables. Or use the new Windows Terminal which is better all round.

**Comment by Gwill** [comment]
I found this problem is related to Windows's code page. 

after I change the code page to 65001 (utf-8)

```
>chcp 65001
```

alignment looks ok.

**Comment by willmcgugan** [comment]
Good to know. Thanks.
