### ISSUE TITLE
[REQUEST] How to use it to render jupyternotebook withour print

### ISSUE THREAD

**Issue by chenboshuo** [willmcgugan/rich#1004]
Consider posting in https://github.com/willmcgugan/rich/discussions for feedback before raising a feature request.

Have you checked the issues for a similar suggestions?

**How would you improve Rich?**

Give as much detail as you can. Example code of how you would like it to work would help.

**What problem does it solved for you?**

What problem do you have that this feature would solve? I may be able to suggest an existing way of solving it.

Now I can use the print function to print rich contents

![image](https://user-images.githubusercontent.com/43953268/107770647-b2e63f80-6d74-11eb-8357-ae14281ddb77.png)

but I hpoe to render rich directly (omitting print)

![image](https://user-images.githubusercontent.com/43953268/107770899-ecb74600-6d74-11eb-9f1d-41dbeef5dfa3.png)

How can I setting my jupyter notebook to do this?

**Comment by nathanrpage97** [comment]
https://rich.readthedocs.io/en/latest/introduction.html?highlight=pretty#python-in-the-repl

**Comment by chenboshuo** [comment]
Thank you,it works.
