### ISSUE TITLE
[BUG] Links in terminal maintain color, but not if we export to HTML

### ISSUE THREAD

**Issue by koaning** [willmcgugan/rich#1009]
I'm working on a little cron-dashboard. This is what it looks like; from the terminal.

![image](https://user-images.githubusercontent.com/1019791/107872865-cba64080-6ead-11eb-99fa-ce978d2f7081.png)

The idea is that my app will keep track of where all the logs are and that you can easily find the logs of the jobs that failed. But I don't just want to have users find logs in the terminal. I also want to export these to HTML. So I was super stoked when I learned rich basically just supports this. 

I've printed the table via a `Console` which I've set to record and I've taken the liberty to also export it to HTML. This is where there is a subtle bug. Notice the subtle difference in the link-line under the red `x`.

![image](https://user-images.githubusercontent.com/1019791/107872875-dcef4d00-6ead-11eb-8364-97a492b6635f.png)

I might imagine that we'd like to keep the colors consistent here. The link in the browser should carry the color of the parent. I think this is a bug, but if this is by design I'll gladly hear it. 

## Code 

This is the code that is used inside the table. 

```python
f"[red][link={make_link()}.html]x[/link][/red]"
```

**Comment by willmcgugan** [comment]
Hi Vincent,

I think that's due to the order of the <a> and <span> tags. It's probably generating <span><a>X</a></span> So the link style is taking preference. It should probably be <a><span>X</span></a> .

I'll have a look a that shortly. Unless you want to tackle that yourself? It should be an easy fix in `export_html`.

**Comment by koaning** [comment]
I've had a quick look but the code-base looked a tad bit too much to take in all in one go. I might try again later, but don't let me hold you!

**Comment by willmcgugan** [comment]
Got a fix. Will be in the next version.

**Comment by willmcgugan** [comment]
Please try 9.11.1
