### ISSUE TITLE
Progress on generator

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [willmcgugan/rich#1022]
Hi @willmcgugan ,

I hope to find you well. Thank you for this amazing library. I was wondering how can I use the `progress.track` function to track a generator since `total` is required but generators have no length.

Thank you.

Cheers,

Francesco

**Comment by willmcgugan** [comment]
I'm afraid there is no way to track progress if you don't have a total. If you create a task with ``start=False`` you can display an animation to show *something* is working.

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you for your reply. Well, in `tqdm` you can avoid to set the `total` and update the progress bar during the iteration

**Comment by willmcgugan** [comment]
You can set the total after you have created a task with `progress.update(task_id, total=TOTAL)`, but the track method requires you know the total in advance.

**Comment by FrancescoSaverioZuppichini** [comment]
okay, I guess I will stick with `tqdm` then! Thank you
