### ISSUE TITLE
[REQUEST] Callback before refresh is executed

### ISSUE THREAD

**Issue by bobatsar** [willmcgugan/rich#1025]
I have to update a live view quite often.
My input data is up to 100Hz but I want to create the rich tables only when a refresh is executed (e.g. refresh_per_second=10).
Calling update() every-time new data is received doesn't make sense, as only every tenth data will finally be printed to screen.

It would be good to have a callback which is called before refresh() is executed to finally create the tables to display.
In my implementation I did it now by overriding refresh(), but I don't know if anybody else could need this.

````python
class MyRichLive(Live):
    def __init__(
        self,
        refresh_callback,
        **kwargs
    ):
        self.refresh_callback = refresh_callback
        super(MyRichLive, self).__init__(**kwargs)

    def refresh(self) -> None:
        self.refresh_callback()
        super(MyRichLive, self).refresh()
````

**Comment by willmcgugan** [comment]
Try using the [console protocol](https://rich.readthedocs.io/en/latest/protocol.html) to accomplish this.

Create a renderable object to generate whatever data you want to display:

```python
class MyThing:
    def __rich__(self):
        table = make_table()
        return table
```

Use a MyThing instance with Live and the `__rich__` method will be called on every refresh.

**Comment by bobatsar** [comment]
Ah, I didn't see this. Sounds exactly what I was looking for. Thanks.
