### ISSUE TITLE
[BUG]Weird spinner animations.

### ISSUE THREAD

**Issue by BlueFalconHD** [willmcgugan/rich#1026]
**Describe the bug**
On windows Powershell, the spinners render per line and are very buggy. Meaning it prints new lines for every frame which lags my device.

**To Reproduce**
In PowerShell : python -m rich.spinner

**Platform**
Windows 10 with Windows Powershell and vs code running a terminal via Windows Powershell.

**Comment by willmcgugan** [comment]
https://github.com/willmcgugan/rich/issues/1023
