### ISSUE TITLE
[Bug] Blink

### ISSUE THREAD

**Issue by pylogic555** [willmcgugan/rich#1035]
**Read the docs**
You might find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) -- consider using the search function there.

**Describe the bug**
Blink style does not work in PyCharm IDE or Python 3.9 terminal

**To Reproduce**
>>> console.print("Danger, Will Robinson!", style="blink bold red underline on white")
Danger, Will Robinson!
>>> console.print("Danger, Will Robinson!", style="blink2 bold red")
Danger, Will Robinson!
>>> console.print("Danger, Will Robinson!", style="blink bold red")
Danger, Will Robinson!
>>> from rich.style import Style
>>> danger_style = Style(color="red", blink=True, bold=True)
>>> console.print("Danger, Will Robinson!", style=danger_style)
Danger, Will Robinson!

All of the commands above did not produce blink text

**Platform**
Python 3.9.1 (64-bit) and PyCharm 2020.3.3
Rich 9.51
Windows 10 (64-bit)

**Diagnose**
I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

```
python -m rich.diagnose
python -m rich._windows
pip freeze | grep rich
```

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by willmcgugan** [comment]
Not all terminals support blink. Often it’s a conscious choice, because some find it an irritating feature. Windows doesn’t support it.

**Comment by pylogic555** [comment]
Ok fair play. 

Computer joke: You mean to tell me my intel i7-7700HQ 7th gen 64 bit processor with 32gb ddr4 ram cannot manufacture or process the bits required to display blinking text in my terminal?
