### ISSUE TITLE
[request] No breaking changes between minor version bumps

### ISSUE THREAD

**Issue by nathanph** [willmcgugan/rich#104]
Hey @willmcgugan, thanks for the hard work on this library! 
I have wow'd my co-workers with it. 

I'd like to request that breaking changes produce a major version bump.
The specific regression I ran into was introduced in release v1.2.0 when `__console__` was replaced with `__rich_console__`.

Thanks again!

**Comment by willmcgugan** [comment]
I'll adhere to semver in future. Sorry about that, I had assumed nobody was yet using the console protocol. Glad somebody is reading the docs!
