### ISSUE TITLE
[REQUEST] For print, let the terminal do line breaks instead of manually adding line breaks

### ISSUE THREAD

**Issue by GeekDuanLian** [willmcgugan/rich#1041]
When you need to copy the printed content, the manually added line breaks will disrupt the content.
If you don’t realize it when you paste it, it may cause other consequences.

For example, execute `from rich import print; print({'key': 'a'*150})` and copy value in the output result, you will get:
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aa
```
The width of the terminal is 80, so a line break is automatically added at the position of 80 characters.
But the result we want to get should be without line breaks.

**Comment by willmcgugan** [comment]
The default is too hard wrap, which is required for word wrapping text. If you want to be able to cut and paste, or consume output by a machine, use “soft wrapping”. See docs for details.

**Comment by GeekDuanLian** [comment]
@willmcgugan OK, but `rich.print` does not support this parameter, I think it does not support this feature.

**Comment by willmcgugan** [comment]
That’s right, it’s limited to signature of the builtin print. Create a Console for more options...
