### ISSUE TITLE
Currently `rich` supports printing tables without columns, but the title will be set to 1 character width:

### ISSUE THREAD

**Issue by willmcgugan** [willmcgugan/rich#1044]
Currently `rich` supports printing tables without columns, but the title will be set to 1 character width:
```
from rich.console import Console
from rich.table import Table

table = Table(title="Star Wars Movies")

console = Console()
console.print(table)
```
output:
```
S
t
a
r

W
a
r
s

M
o
v
i
e
s
┏┓
└┘
```

So I want to set a min-width for the table, but raised a AssertionError:
```
....
File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/console.py", line 893, in render
    for render_output in iter_render:
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/table.py", line 411, in __rich_console__
    widths = self._calculate_column_widths(console, max_width - extra_width)
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/table.py", line 500, in _calculate_column_widths
    pad_widths = ratio_distribute(_max_width - table_width, widths)
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/_ratio.py", line 53, in ratio_distribute
    assert total_ratio > 0, "Sum of ratios must be > 0"
AssertionError: Sum of ratios must be > 0
```
I take response from a API to generate columns and rows dynamically so they could be None.

Is there any way I can properly print a table without columns?

_Originally posted by @waynerv in https://github.com/willmcgugan/rich/discussions/1043_

**Comment by waynerv** [comment]
It looks like the table width was calculated without taking into account the case of that `Table.columns` is an empty list. Perhaps the table width should be set to the character width of `title` if `title` is presented.

The width calculation process in source code looks a bit complicated, but I can take some effort to fix it if you need.

**Comment by willmcgugan** [comment]
Actually, what should a table with no column display? You could argue that it should display nothing other than the title.

**Comment by waynerv** [comment]
Are you talking about not rendering the empty box?

I think both are acceptable, as long as there's consistent behaviour.

But for customize I would choose to rendering box, in this way we can decide whether to render box or just title by manually check its columns.

**Comment by willmcgugan** [comment]
v9.12.0 will display a blank line for tables with no columns, regardless of minimum width.  You can test for emptiness with `table.columns`
