### ISSUE TITLE
[BUG] Can't show in jupyter pdf

### ISSUE THREAD

**Issue by chenboshuo** [willmcgugan/rich#1045]
In jupyter notebook, the rich render correctly
![image](https://user-images.githubusercontent.com/43953268/108708153-03675500-754c-11eb-86db-cc48c88d6932.png)

But when I downloads the pdf via LaTex, it can't show 
![image](https://user-images.githubusercontent.com/43953268/108708285-33165d00-754c-11eb-8976-07fa627ffe02.png)

It also can't show in sphinx pdf (buecause it build by latex)
![image](https://user-images.githubusercontent.com/43953268/108708805-dff0da00-754c-11eb-8156-c970908d9497.png)

![image](https://user-images.githubusercontent.com/43953268/108708783-d9626280-754c-11eb-8f2b-b98903e1e753.png)

**Comment by willmcgugan** [comment]
I think this is an issue for the Jupyter devs. Rich generates HTML according to the Jupyter spec, I would have expected Jupyter to include the output in the pdf.

**Comment by chenboshuo** [comment]
It is hard to implement. HTML is hard to render in LaTeX file.

**Comment by willmcgugan** [comment]
I don't think there is much Rich can do to fix this. You might want to report it to the Jupyter devs.
