### ISSUE TITLE
[BUG] Syntax class does not display all content

### ISSUE THREAD

**Issue by abotsis** [willmcgugan/rich#1050]
**Describe the bug**

When nesting a Syntax class (with line_numbers and word_wrap enabled) inside a Panel inside a Layout, only the first line is displayed.

**To Reproduce**

`print(Layout(Panel(Syntax('import stuff\nwhile True:\n  print("hello!!!!")\n','python',line_numbers=True, word_wrap=True))))`

**Platform**
Linux

**Comment by willmcgugan** [comment]
Please try 9.12.0

**Comment by abotsis** [comment]
Looks good to me! Thanks a ton, and awesome project!
