### ISSUE TITLE
[BUG] pdb/breakpoint() isn't very usable during progress

### ISSUE THREAD

**Issue by The-Compiler** [willmcgugan/rich#1053]
**Describe the bug**
When calling `breakpoint()` during progress, the `pdb` prompt doesn't echo typed characters. Thus, it's not really possible to debug anything in the code running while progress is shown.

I suppose rich could set [sys.breakpointhook](https://docs.python.org/3/library/sys.html#sys.breakpointhook) to first get the terminal out of raw mode when `breakpoint()` is used?

(This is probably somewhere between bug report and feature request)

**To Reproduce**

```python3
import time
import rich.progress

for n in rich.progress.track(range(5)):
    time.sleep(0.5)
    if n == 3:
        breakpoint()
```

**Platform**
Arch Linux, Kitty

**Diagnose**
See #1052.

**Comment by willmcgugan** [comment]
Setting `breakpointhook` is an interesting idea. It would have to wrap whatever is already there so it doesn't break pdb. 

My only issue with that is debugging changes what's being debugged. Might be fine if you are debugging some unrelated code, but if you are debugging anything related to the progress bar or what it renders, it's going to change things.

I wonder what other TUI libraries do.

**Comment by The-Compiler** [comment]
Perhaps as a compromise, there should be a manual escape hatch? If I could blindly type `rich.reset()` or whatever and then go on with debugging, I suppose that'd work - though it's not particularly discoverable, I guess.

**Comment by willmcgugan** [comment]
That might be useful, bit I don't think it would help you much in the case of Live / progress. I think the reason you are not seeing input is that the thread to refresh the progress bars is still active. You could try `auto_refresh=False` on track, that should prevent the refresh thread from running.

**Comment by littlebeat23** [comment]
Spam

**Comment by willmcgugan** [comment]
Closing because I can’t think of a good solution, but it’s something I’m thinking about. Going to be doing more work in the area.

**Comment by The-Compiler** [comment]
Alright - feel free to tag me if you need feedback or testing for something!

**Comment by jacobian** [comment]
I ran into this the other day as well, and was surprised by it as well. I worked around it by just removing the progress bars while debugging and then adding 'em back once I figured it out. I'd love to see a solution here as well (but agree that a good one seems elusive).

**Comment by willmcgugan** [comment]
@jacobian Only thing that occurs to me is to disable the refresh thread if the debugger is active. That's probably good enough, assuming you didn't want to debug the progress bars themselves.

**Comment by d-chambers** [comment]
I ran into this as well. Is there an easy way to disable the refresh thread?

**Comment by supersergiy** [comment]
I do not believe this issue can be marked as resolved. Currently, `rich.progress` influences the debugging process of the user codebase.

With a custom breakpoint hook, the user would expect the trace to be set at frame `sys._getframe().f_back`. Using a wrong frame will cause great confusion for the user. Thus it is impossible to override `sys.breakpointhook` while respecting what is already there, because what's already there may not take in a frame as input -- even `pdb.set_trace` does not. The only way is to do it is to disrespect what's already there, and use:
```python
pdb.Pdb(sys._getframe().f_back).set_trace()
``` 
It is a tough ask to expect each `rich` user to know how to do this correctly.

**Comment by yohan-pg** [comment]
Could this be reopened? This is a complete dealbreaker if you use breakpoint()

**Comment by DanCardin** [comment]
For my own purposes, setting `force_terminal=False` makes rich stop doing fancy output and causes breakpoint/pdb to function correctly. Which obviously only works if you're debugging the actual code and not the rich output, but that's good enough for me.

**Comment by yohan-pg** [comment]
> For my own purposes, setting `force_terminal=False` makes rich stop doing fancy output and causes breakpoint/pdb to function correctly. Which obviously only works if you're debugging the actual code and not the rich output, but that's good enough for me.

I'm not too familiar with `rich` in general, this is an argument to `rich.console.Console`? Do you have an example of using this with `track`?

**Comment by MatthiasZepper** [comment]
A solution that works for ninnies like me is using a pipe when debugging instead of fiddling with the `rich.progress.Progress` code or environment variables. Since Rich detects the pipe, it omits all the eye candy and at least `pdb.set_trace()` works like a charm. Conveniently, you get a free log on top if you pipe to `tee` instead of `cat`/`tail`.

`my_cli_tool_with_rich buggy_command --some param | tee output.log`

**Comment by skytwosea** [comment]
> A solution that works for ninnies like me is using a pipe when debugging instead of fiddling with the `rich.progress.Progress` code or environment variables. Since Rich detects the pipe, it omits all the eye candy and at least `pdb.set_trace()` works like a charm. Conveniently, you get a free log on top if you pipe to `tee` instead of `cat`/`tail`.
> 
> `my_cli_tool_with_rich buggy_command --some param | tee output.log`

or `| tee /dev/null` if you don't need the log. But note that using `cat` or a redirect just sends you into a quiet black hole.

Writing to note that I'm seeing this issue as well (Linux 6.8, ubuntu 24.04, rich 13.9.4). The pipe is a convenient temp solution but if you rely heavily on pdb it won't do long-term.
