### ISSUE TITLE
Rich Traceback not working

### ISSUE THREAD

**Issue by nisarg-ujjainkar** [willmcgugan/rich#106]
I tried installing rich traceback, but the tracebacks are still not rendered by rich.

I am using python 3.8 on Ubuntu WSL.

**Comment by willmcgugan** [comment]
Hi @nisarg-ujjainkar 

I can confirm that tracebacks work with Python3.8 on Ubuntu. Have you put the following at the start of your script / app ?

```python
from rich.traceback import install
install()
```

**Comment by nisarg-ujjainkar** [comment]
I thought it had to be installed once, like [pretty_error](https://pypi.org/project/pretty-errors/). My bad.

Is this a feature that will be available in a future release?

**Comment by willmcgugan** [comment]
I'm not keen on installing it system wide. But if you would like to do it yourself, you could add it to your "sitecustomize" module.

This should give you the path to customize.py:

```
python3 -c "import sitecustomize;print(sitecustomize.__file__)"
```

**Comment by nisarg-ujjainkar** [comment]
this should be imported in the file `/home/<user>/.local/lib/python3.8/site-packages/usercustomize.py`

**Comment by FrancescoSaverioZuppichini** [comment]
```
ModuleNotFoundError: No module named 'usercustomize
```

**Comment by FrancescoSaverioZuppichini** [comment]
Okay, I got it. You need to 

```
cd $(python -c 'import site; print(site.getsitepackages()[0])')
mkdir sitecustomize  
cd sitecustomize 
echo "from rich.traceback import install\ninstall()" >> __init__.py
```

**Comment by nisarg-ujjainkar** [comment]
> ```
> ModuleNotFoundError: No module named 'usercustomize
> ```

You will have to manually create usercustomize.py. Or, your method works just fine.
