### ISSUE TITLE
[REQUEST] Colors in file output

### ISSUE THREAD

**Issue by jackeown** [willmcgugan/rich#1064]
Not sure if this is a feature request, bug report, or just a question, but I'll try to make it clear.

I have replaced `sys.stdout` with a custom object such that a normal python `print` statement will log to a file in addition to printing to stdout.

For completeness, the object looks like this:
```python
    class Logger(object):
        def __init__(self, logfile):
            self.terminal = sys.stdout
            self.log = open(logfile, "a")

        def write(self, message):
            self.terminal.write(message)
            self.log.write(message)  

        def flush(self):
            pass
```

When I do this, I no longer see colors (or underlining for instance) in the output from rich.
+ Is this intended behavior because sometimes people don't want colors in their output files?
+ Is there a way to have it output colors both to terminal and to the logfile?
+ If not, is there a way to output colors to terminal at least while using a setup like this?

Thanks in advance.
Rich seems awesome so far!

**Comment by willmcgugan** [comment]
Try adding the following method to your Logger object:

```python
def isatty(self):
    return True
```

This tells Rich you are writing to a terminal and not a file.

TBH You probably want to use the logging module for this, which can write output to multiple destinations.

**Comment by jackeown** [comment]
Thanks! I'll look into the logging module
