### ISSUE TITLE
[BUG] Terminal colors are overriding Rich styles

### ISSUE THREAD

**Issue by evprkr** [willmcgugan/rich#1077]
I'm using iTerm 2 (dev build) and even though I'm using ``console.print('0', style='green')`` it is always coming out as magenta, no matter what. Only when it's a number though... Regular text works fine.

If I use ``style='dim green`` the text comes out dim, but still magenta.

**Comment by willmcgugan** [comment]
Please see docs on [highlighting](https://rich.readthedocs.io/en/latest/highlighting.html).

**Comment by evprkr** [comment]
> Please see docs on [highlighting](https://rich.readthedocs.io/en/latest/highlighting.html).

Thank you. I was searching all over the place on the docs for this, but didn't find what I was looking for, I was using the wrong words!
