### ISSUE TITLE
[BUG] no_wrap=True and overflow="crop" not behaving as expected

### ISSUE THREAD

**Issue by joshuakoh1** [willmcgugan/rich#1078]
**Read the docs**
You might find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) -- consider using the search function there.

**Describe the bug**

Using overflow = "crop" on a column that is too long does not crop the column but sends the remaining output to the next line.

When no_wrap=True is used together, the entire column just takes up all the space in the row and all the other columns get reduced to padding only. 

Desired behaviour is for text to be cropped at the end of the line and keep the rows single height.

**To Reproduce**
A minimal code example that reproduces the problem would be a big help if you can provide it. If the issue is visual in nature, consider posting a screenshot.

```
from rich.table import Table
from rich.live import Live
from rich.console import Console

table = Table()
table.add_column("A")
table.add_column("B")
table.add_column("C")
table.add_column("D")
table.add_column("E",overflow="crop", no_wrap=True)
for i in range(0,10):
    table.add_row(
        f"Short Text", f"Short Text", f"Short Text", f"Short Text", f"Super Long Text That Overflows Off The Screen................................................................................"
    )

console = Console()
console.print(table)
```

**Platform**
What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

Windows, Command Prompt

**Comment by willmcgugan** [comment]
Overflow won't affect text wrapping. Overflow will only occur when a word can't fit in the width or if no_wrap=True.

**Comment by joshuakoh1** [comment]
@willmcgugan What am I looking for to cut off the excess of one column without affecting the size of the rest of the columns?

**Comment by willmcgugan** [comment]
Put no_wrap on the columns you don't want to shrink. For the long column, wrap it in Text("long text", no_wrap=True). This will allow the long column to shrink, while preventing the text from wrapping.

**Comment by joshuakoh1** [comment]
Thank you. This worked. Fantastic package.
