### ISSUE TITLE
[REQUEST] Table without headers?

### ISSUE THREAD

**Issue by joshuakoh1** [willmcgugan/rich#1087]
**How would you improve Rich?**
Is there a possibility for Table headers to be optional?

**What problem does it solved for you?**
I'm trying to display 3 different small tables in a single row. 
There doesn't seem to be a way to stack Panels horizontally so I tried using a 3 column Table. 
Unfortunately, seems like there's no way to remove the headers for the larger table nor is there a way to format the borders.

**Comment by willmcgugan** [comment]
Yes, see the Table reference.

https://rich.readthedocs.io/en/latest/reference/table.html#module-rich.table

**Comment by joshuakoh1** [comment]
@willmcgugan I can't seem to hide the header at all. 
```
table = Table()
table.add_column() # table.add_column(header=None) throws error
table.add_row("Hello")
console.print(table)
```
┌───────┐
│                   │
├───────┤
│ Hello         │
└───────┘

**Comment by joshuakoh1** [comment]
I think I figured out how to do it. I should put the render group inside the "header" section and not add_row.

**Comment by willmcgugan** [comment]
You want show_header = False
