### ISSUE TITLE
[QUESTION] Capture RichHandler traceback formatting

### ISSUE THREAD

**Issue by boonhapus** [willmcgugan/rich#1097]
Hey Will,

Been working with `rich` now for about a month now and I absolutely love it, moving a lot of my projects over to using the library. One thing I'd like to do is to capture the exception output from `log.exception()` when using `RichHandler`.

The formatting is perfect and concise for what I need, and I don't care much about the color. My destination is a discord bot, and not the console, so I most only care about the formatting of the traceback.

I tried doing something like ..
```python
            # if unhandled, propogate up to the CLI
            try:
                raise error.original
            except Exception as e:
                with rich.console.Console().capture() as cap:
                    log.exception(e)

                s = cap.get()  # ==> ''
```
... but it looks like that's slicing the buffer of the newly created console and totally ignoring the log handler - which makes sense to me considering we're using two different consoles at that point. Unfortunately, I'm at a loss on how to grab/rebuild the renderable and would love your thoughts.

![image](https://user-images.githubusercontent.com/14192437/110221599-bf9d1580-7e92-11eb-81cc-444ae33730bb.png)

**Comment by willmcgugan** [comment]
Hi @boonhapus 

Glad you like Rich.

If you don't specify a Console in the RichHandler, then it will use a global instance as a default. You can get that instance like this:

```python
from rich import get_console
console = get_console()
```

Alternatively you could capture the traceback and print it however you like. Here's an example (untested):

```python
from rich.traceback import Traceback
try:
    1/0
except:
    traceback = Traceback(). # Contains a snapshot of the last exception
    console = Console(width=100, no_color=True)
    with console.capture() as capture:
        console.print(traceback)
    traceback_str = capture.get()
```

Hope that helps.

**Comment by boonhapus** [comment]
Thanks @willmcgugan! I think that's almost there... I used a width of 120, but everything else is the same. The content prints fine to the console, but something in how you build the trace isn't serializing too great.

![image](https://user-images.githubusercontent.com/14192437/110257797-04917c80-7f65-11eb-9c09-cd65ce6c73c8.png)

**Comment by willmcgugan** [comment]
No_color removes colour, but there are still ANSI codes for bold and dim etc. Try color_system=None

**Comment by boonhapus** [comment]
Perfect, this was what we needed. Thanks @willmcgugan !
