### ISSUE TITLE
[REQUEST] Re-splittable Layouts

### ISSUE THREAD

**Issue by JoshKarpel** [willmcgugan/rich#1098]
I'm playing with some TUI-like ideas using Rich, in particular, adjustable layouts like `tmux` can do. I find myself wanting to change the splits for a layout dynamically.

If I understand the API correctly, once a `Layout` is split using `Layout.split`, there is no way to "unsplit" it - you can call `split` again to add more sub-layouts or change the direction, but you can't "start over". For my own experimentation I've been manually setting `layout._children = []` and then calling `split` again with the new set of children I'd like it to have, like this:

```python
header = Layout(Header(options), name="header", size=1)
footer = Layout(Footer(state=state, options=options), name="footer", size=1)
body = Layout(name="body", ratio=1)

root = Layout(name="root")
root.split(header, body, footer)

def resplit():
    body._children = []
    verts = []
    for group in state.tile_groups:
        v = Layout()
        v.split(*(tile.layout for tile in group), direction="vertical")
        verts.append(v)
    body.split(*verts, direction="horizontal")
```

... which is obviously not part of the public API :)

You can already dynamically change the renderable attached to a `Layout` using `Layout.update`, so I'm imagining a feature that provides a parallel capability for sub-layouts. It seems like the alternative is rebuilding `Layout` from scratch on every refresh, which would certainly work, but since the parents are also split `Layouts`, I would need to build the entire tree. So, this seems like a natural extension of the existing API and would lessen the need to store the desired layout structure externally to Rich.

Some possibilities I thought of for the implementation:
- Add a keyword argument to `split` that make it split "from scratch" (`Layout.split(..., resplit=True)` ?). Given that you can already change the split direction by calling `split` again with a different keyword argument, this seems like the most natural implementation.
- Add a separate method (`Layout.resplit`?) that clears the internal `_children`, then calls `split`.
- Make the `children` property writeable (exposes much more API surface than I imagine you want to expose).

If you like the idea, I'm happy to do a PR to add the feature if you can provide some guidance on your preferred solution!

**Comment by willmcgugan** [comment]
Hi Josh,

Perhaps an `unsplit` method that sets children to `[]`?  Then you could call split again.

Let me think about that one. In the meantime, you have my permission to use the private method... :-)

**Comment by willmcgugan** [comment]
There will be an `unsplit()` method in the next version. `split()` will reset the splits as though you set children to [], and there will be a `add_split()` which adds additional layouts to the current split.
