### ISSUE TITLE
Setting up coverage reporting via CI / linting?

### ISSUE THREAD

**Issue by blueyed** [willmcgugan/rich#11]
1. Are you interested on having coverage reports via CI?

I suggest using codecov for that (with a config that disables its comments, so that only PR/commit statuses are reported).

I also suggest having a tox configuration for this then, so that `tox -e py38-coverage` could be used on CI, but also locally in the same way.

2. Are you interested in having some linting via CI / tox also?
For that using flake8 might be good enough, but would require some fixes / running black/autopep8 once.

I'd be happy to contribute whatever you prefer.

**Comment by willmcgugan** [comment]
Yeah, I plan on setting up coverage reporting soon. Once I have more coverage to report, its currently at 52%

At the moment I'm relying on Mypy, but I'll think about some additional linting.

Thanks for the offer of help, but I can set that up.
