### ISSUE TITLE
Disabling visibility of progress

### ISSUE THREAD

**Issue by calebstewart** [willmcgugan/rich#110]
Hi,

I wanted to implement a progress bar for a long running process, but have the entire progress bar disappear after completion. In reality, it would be replaced with a log entry of w/ the result of the operation. Specifically, I'm using this in a "searching" context, so a search runs which may take a while to complete. I'd like to have a progress bar indicating what the application is doing, but replace this line with the search results after completion.

This almost works by using `progress.update(task_id, visible=False)`, but an extra new line ends up in the output, which causes weird gaps in the log output after completion (especially if a progress bar is used during two separate operations).

Is there are way to remove the extra newline or completely erase the progress bar output, and return the cursor the the beginning of the original line?

Thanks!

## Edit: I did some digging in the code...

From what I can see, the table that is built to render the progress bar shouldn't have any rows if there are no visible tasks, and from looking at the `_render` method in the Table class, it shouldn't render any lines if there are no rows, so I can't quite track down why there is a new line happening anyway. I thought it may have been the "padding" argument supplied to the Table used to render the progress bar, but I tried to make that configurable and using `(0,0)` for the padding (vice `(0,1)`) and it still ends up with a blank line.

## Edit 2: Example

I realized in hindsight, my explanation may be a little lacking. This example code:

```python
#!/usr/bin/env python3
from rich.progress import Progress
from rich.console import Console
import time

console = Console()

console.log("Here we go!")

with Progress(console=console) as progress:
    task = progress.add_task("test", total=10)
    for i in range(10):
        time.sleep(0.5)
        progress.update(task, advance=1)
    progress.update(task, visible=False)

console.log("Is there a blank line?")
```

Produces the following output after the progress has completed.

```
➜ python3 ./test.py
[19:09:38] Here we go!                                                                     test.py:8

[19:09:42] Is there a blank line?                                                         test.py:17
```

I'd like there to be no blank line between the two log statements. The progress bar is only to indicate that a process which could hang is still working, and not for any lasting output that is helpful. 

Hopefully that better describes the issue I'm having.

**Comment by willmcgugan** [comment]
Hi @calebstewart 

The Progress class assume you want to keep the progress display even if you make the task invisible.

I've been thinking about this myself. I think I should add a boolean, say "transient", that clears the progress and resets the cursor on exiting the context manager. I'll add that to a future release.

If you want to hack it in the short term, try adding this after the exiting the progress: 

```python
console.control("\x1b[2A")
```

**Comment by calebstewart** [comment]
I completely understand. Normally, a progress bar would stick around. I just think that if you have the ability to hide the individual tasks, then it's natural to assume if all tasks are hidden (and there's no title/caption), then the entire thing would be invisible.

Your suggested workaround was close. I appear to only need to move the cursor up 1 line, so I opted for this: `console.control("\x1b[1A")` and it seems to work well. Thanks!

**Comment by willmcgugan** [comment]
Give v2.1.0 a try. It adds the "transient" flag to the Progress class.

**Comment by calebstewart** [comment]
Oh, wow, that was quick! I just gave it a try, and it works perfectly for me. Thanks for the quick turnaround on this. Loving your project. Absolutely beautiful output. :+1:

**Comment by alexisthual** [comment]
In vscode interactive windows, this still prints a newline. I could find a workaround, but I had expected `rich` would handle this case on its own.
Thank you for the nice librairie anyways!

**Comment by anoe** [comment]
@alexisthual: what was the workaround in vscode? I have the same issue :-)

**Comment by alexisthual** [comment]
I don't remember, sorry :sweat_smile:
