### ISSUE TITLE
[BUG] Progressbar doesn't update

### ISSUE THREAD

**Issue by AOTY-szy** [willmcgugan/rich#1120]
```python
import time

from rich.progress import Progress
from torch.multiprocessing import Process

def func(job, pbar):
    for i in range(100):
        time.sleep(0.1)
        pbar.update(job, advance=1)

def entry():
    with Progress() as pbar:
        task1 = pbar.add_task(description="Process 1", total=100)
        p1 = Process(target=func, args=(task1, pbar, ))

        p1.start()
        p1.join()

if __name__ == '__main__': 
    entry()
```
**The progressbar couldn't be updated normally as the following figure shows.**
![2021-03-20 14-54-14 的屏幕截图](https://user-images.githubusercontent.com/55872870/111861821-2ab71380-898c-11eb-8a9b-0166116b7b1d.png)

**Platform**
ProductName: Ubuntu
ProductVersion: 20.04

**DIagnose**

![2021-03-20 14-27-37 的屏幕截图](https://user-images.githubusercontent.com/55872870/111861345-78318180-8988-11eb-8f86-0405981ef1cc.png)

**Comment by willmcgugan** [comment]
Progress bars won't work when serialized across processes.

For multiprocessing, don't attempt to pass the progress bar. You can communicate progress information from the workers via a queue or pipe, and update the progress bar in the main thread.

Search closed issues for "multiprocessing" for more information.

**Comment by AOTY-szy** [comment]
> Progress bars won't work when serialized across processes.
> 
> For multiprocessing, don't attempt to pass the progress bar. You can communicate progress information from the workers via a queue or pipe, and update the progress bar in the main thread.
> 
> Search closed issues for "multiprocessing" for more information.

thanks very much!

**Comment by willmcgugan** [comment]
You can run the queue or pipe in a thread, just as long as it's launched from the main process.

**Comment by AOTY-szy** [comment]
> You can run the queue or pipe in a thread, just as long as it's launched from the main process.

I get it, thanks!

**Comment by AOTY-szy** [comment]
> You can run the queue or pipe in a thread, just as long as it's launched from the main process.

I make it.
'''python
import time
import numpy as np

from torch.multiprocessing import Process, Queue
from threading import Lock
from rich.progress import *


def func(l1, l2, queue, task_id):
    l1.acquire()
    if l2.locked():
        l2.release()
    l1.release()
    for i in range(100):
        time.sleep(0.1)
        if not queue.full():
            queue.put_nowait(task_id)


def update(l2, queue, taskq):
    with Progress() as pbar:
        while True:
            if np.all([task.finished for task in pbar.tasks]):
                print("A")
                l2.acquire()
                print('B')
            if not taskq.empty():
                task = taskq.get()
                _ = pbar.add_task(description="Task " + str(task), total=100)
            if not queue.empty():
                task_id = queue.get()
                pbar.update(task_id, advance=1)


def entry():
    l1 = Lock()
    l2 = Lock()

    sum = 2

    Task_queue = Queue(sum)

    queue = Queue(100 * sum)

    p1 = Process(target=update, args=(l2, queue, Task_queue))
    p1.start()

    Task_queue.put_nowait(0)
    p2 = Process(target=func, args=(l1, l2, queue, 0))
    p2.start()

    Task_queue.put_nowait(1)
    p3 = Process(target=func, args=(l1, l2, queue, 1))
    p3.start()

    p1.join()
    p2.join()
    p3.join()


if __name__ == '__main__':
    entry()
'''

**Comment by willmcgugan** [comment]
Great!

**Comment by karwankarwan** [comment]
Hack is acckawnt @maten2002

في السبت، ٢٠ مارس ٢٠٢١ ٦:٤٤ ص AOTY-szy ***@***.***> كتب:
