### ISSUE TITLE
[BUG] Console Status not working with Spyder

### ISSUE THREAD

**Issue by FabioRosado** [willmcgugan/rich#1149]
**Read the docs**
You might find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) -- consider using the search function there.

**Describe the bug**

I am using status to get a spinner while things are being done in the background. I'm essentially running:

```python
 console = Console()

        with console.status(
            "[bold green] Creating Cluster. This takes about a minute..."
        ):
```

That spews a lot of these in a Spyder console:

```
<rich.jupyter.JupyterRenderable at **0x1c0ffeaaee0**>
```

I'm guessing that perhaps Rich is detecting the Spyder IPyython window as a Jupyter one.

**To Reproduce**
A minimal code example that reproduces the problem would be a big help if you can provide it. If the issue is visual in nature, consider posting a screenshot.

- Install Anaconda (or just Spyder) on a Windows machine
- Create a dummy code similar to above
- See the output

**Platform**
What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

Windows, IPython console on Spyder

**Diagnose**
I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

```
python -m rich.diagnose
python -m rich._windows
pip freeze | grep rich
```

```
# python -m rich.diagnose
+---------------------- <class 'rich.console.Console'> -----------------------+
| A high level console interface.                                             |
|                                                                             |
| +-------------------------------------------------------------------------+ |
| | <console width=79 None>                                                 | |
| +-------------------------------------------------------------------------+ |
|                                                                             |
|     color_system = None                                                     |
|         encoding = 'cp1252'                                                 |
|             file = <colorama.ansitowin32.StreamWrapper object at            |
|                    0x000001843F9A0EB0>                                      |
|           height = 24                                                       |
|    is_alt_screen = False                                                    |
| is_dumb_terminal = False                                                    |
|   is_interactive = False                                                    |
|       is_jupyter = False                                                    |
|      is_terminal = False                                                    |
|   legacy_windows = True                                                     |
|         no_color = False                                                    |
|          options = ConsoleOptions(                                          |
|                        size=ConsoleDimensions(width=79, height=24),         |
|                        legacy_windows=True,                                 |
|                        min_width=1,                                         |
|                        max_width=79,                                        |
|                        is_terminal=False,                                   |
|                        encoding='cp1252',                                   |
|                        justify=None,                                        |
|                        overflow=None,                                       |
|                        no_wrap=False,                                       |
|                        highlight=None,                                      |
|                        markup=None,                                         |
|                        height=None                                          |
|                    )                                                        |
|            quiet = False                                                    |
|           record = False                                                    |
|         safe_box = True                                                     |
|             size = ConsoleDimensions(width=79, height=24)                   |
|        soft_wrap = False                                                    |
|           stderr = False                                                    |
|            style = None                                                     |
|         tab_size = 8                                                        |
|            width = 79                                                       |
+-----------------------------------------------------------------------------+

# python -m rich._windows

platform="Windows"
WindowsConsoleFeatures(vt=False, truecolor=False)

#  !pip freeze | grep rich
rich==10.0.0

```

I've testing things on my side and I figured that as a workaround I can check if `SpyderKernelApp` exists when running `get_ipython().config` and toggle `force_jupyter=False` on `Console`. The only issue I am finding is that now it keeps sending the same message over and over. Example:

```
⠴  Creating Cluster. This takes about a minute... Creating Cluster. This takes about a minute... Creating Cluster. This takes about a minute...⠦  Creating Cluster. This takes about a minute... Creating Cluster. This takes about a minute... Creating Cluster. This takes about a minute...
```

I haven't dug into the source code yet, but if you can give me some pointers I would be happy to contribute and submit a bug fix for this 👍 

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by willmcgugan** [comment]
That does appear to be what is happening. You can see the code to detect Jupyter [here](https://github.com/willmcgugan/rich/blob/master/rich/console.py#L447)

Does this print False?

```python
from rich.console import _is_jupyter
print(_is_jupyter())
```

**Comment by FabioRosado** [comment]
Thank you for the quick reply @willmcgugan  `_is_jupyter()` is printing True, because Spyder is using ZMQInteractiveShell as well, this seems a easy fix as we could check if `SpyderKernelApp` exists in `ipythong.config` and return false otherwise.

It's still unclear for me as to why the message keeps being printed over and over while waiting for things 🤔

**Comment by willmcgugan** [comment]
force_terminal should work around the broken auto detection. I wonder if Spyder doesn’t fully support terminal output.

I’ll experiment with it at some point, but if you find any more clues let me know.

**Comment by FabioRosado** [comment]
I've set `force_terminal` but that didn't work, I've tested all the "force" options and just seems broken I'll keep testing and see if I can figure out

**Comment by willmcgugan** [comment]
I may have a more future-proof solution. Could you checkout the jupyer-echosystem branch and try that?

**Comment by FabioRosado** [comment]
Sure thing will do thank you 👍

**Comment by FabioRosado** [comment]
I've just tested the branch and that works nicely, the only issue that I see is the text inside `console.status` being print on a new line. Perhaps that is just some Spider weirdness 🤔 
![EkMErEBqv7](https://user-images.githubusercontent.com/3131401/113448430-bd779980-93f3-11eb-870a-983fece16e76.gif)

**Comment by willmcgugan** [comment]
I'm afraid the repeating status probably means that Spyder doesn't support some standard control characters. There isn't anything that Rich can do about that. You may want to raise an issue with the Spyder devs.

BTW that branch is not on Pypi, v10.1.0
