### ISSUE TITLE
[BUG] Certain line characters (\r particularly) aren't functioning.

### ISSUE THREAD

**Issue by ii-Python** [willmcgugan/rich#1151]
**Read the docs**
documentation read 😄 

**Describe the bug**
I'm making a text-based transfer system that takes pages off of a remote server and sends them to clients.
This works well, the problem happens with my "interaction menus."

They are designed in a way to use `\r` to erase the current line and reprint it, however using this library,
my `\r` calls don't seem to work (the text goes down on the next line). The parameters I've given the print function are
`print("\r", text, sep = "", end = "")`

**To Reproduce**
![image](https://user-images.githubusercontent.com/35084023/113336449-0cd2a280-92ec-11eb-9dfa-ac33a3fe1ab5.png)
^ Normally clears the current line and reprints, as to make it look smooth almost like `input()`.

**Platform**
Running on Windows 10 (64-bit), Python v3.9.1, using VSC's built-in terminal, running git bash.

**Diagnose**
![image](https://user-images.githubusercontent.com/35084023/113336677-5f13c380-92ec-11eb-8347-d1f183e54eb6.png)
![image](https://user-images.githubusercontent.com/35084023/113336720-6cc94900-92ec-11eb-9c56-cf7cb8abcbc0.png)
![image](https://user-images.githubusercontent.com/35084023/113336813-89fe1780-92ec-11eb-90d7-e37672644198.png)

**Comment by willmcgugan** [comment]
Rich will strip out `\r` because it breaks formatting that Rich does.

I'd suggest either accepting a line per input, which is generally expected with CLI apps, or drop to builtin `input()` for this.
