### ISSUE TITLE
[REQUEST] Add color to custom log levels.

### ISSUE THREAD

**Issue by DeemOnSecurity** [willmcgugan/rich#1161]
**Have you checked the issues for a similar suggestions?**

I have reviewed #407 (closed) and #419, which allows subclassing the RichHandler, but there is not an obvious way to style levels.

**How would you improve Rich?**

Allow markup of custom log levels provided from the logging module in stdlib.

```python
# Current behavior 
import logging
from rich.logging import RichHandler

logging.basicConfig(
    level=LOG_LEVEL,
    format="%(message)s",
    datefmt="%X",
    handlers=[RichHandler(rich_tracebacks=True, tracebacks_show_locals=True, console=_CONSOLE)],
)
logging.addLevelName(70, "[green]CUSTOM[/]")
logging.log(70, "<MESSAGE>")

"""
Literally prints:
<TIME> [green]CUSTOM[/] <MESSAGE>
"""

# Desired behavior
logging.addLevelName(70, "[green]CUSTOM[/]")

"""
Literally prints (with color):
<TIME> CUSTOM <MESSAGE>
"""
```

**What problem does it solved for you?**

This would allow for more clear custom logging for our plugin-based architecture.

**Comment by Daddy2200** [comment]
@jimms

**Comment by willmcgugan** [comment]
You can set a theme style for "logging.level.level name".

```python
import logging
from rich.logging import RichHandler

from rich.console import Console
from rich.theme import Theme

console = Console(theme=Theme({"logging.level.custom": "green"}))

logging.basicConfig(
    level=logging.DEBUG,
    format="%(message)s",
    datefmt="%X",
    handlers=[RichHandler(rich_tracebacks=True, tracebacks_show_locals=True, console=console)],
)
logging.addLevelName(70, "CUSTOM")
logging.log(70, "<MESSAGE>")
```

or extend [get_level_text](https://github.com/willmcgugan/rich/blob/master/rich/logging.py#L102)

**Comment by DeemOnSecurity** [comment]
> You can set a theme style for "logging.level.level name".
> 
> ```python
> import logging
> from rich.logging import RichHandler
> 
> from rich.console import Console
> from rich.theme import Theme
> 
> console = Console(theme=Theme({"logging.level.custom": "green"}))
> 
> logging.basicConfig(
>     level=logging.DEBUG,
>     format="%(message)s",
>     datefmt="%X",
>     handlers=[RichHandler(rich_tracebacks=True, tracebacks_show_locals=True, console=console)],
> )
> logging.addLevelName(70, "CUSTOM")
> logging.log(70, "<MESSAGE>")
> ```
> 
> or extend [get_level_text](https://github.com/willmcgugan/rich/blob/master/rich/logging.py#L102)

Awesome! Did not realize you could do that, thank you very much!

> Previous Behavior
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/19997347/113711592-23de0f80-96b3-11eb-94f3-4c937442df27.png">

> Code Addition
<img width="748" alt="image" src="https://user-images.githubusercontent.com/19997347/113711667-3bb59380-96b3-11eb-9413-c456d787d8f5.png">

> Current Behavior
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/19997347/113711558-158ff380-96b3-11eb-9ace-ce14396db06b.png">

**Comment by imegeek** [comment]
> You can set a theme style for "logging.level.level name".
> 
> ```python
> import logging
> from rich.logging import RichHandler
> 
> from rich.console import Console
> from rich.theme import Theme
> 
> console = Console(theme=Theme({"logging.level.custom": "green"}))
> 
> logging.basicConfig(
>     level=logging.DEBUG,
>     format="%(message)s",
>     datefmt="%X",
>     handlers=[RichHandler(rich_tracebacks=True, tracebacks_show_locals=True, console=console)],
> )
> logging.addLevelName(70, "CUSTOM")
> logging.log(70, "<MESSAGE>")
> ```
> 
> or extend [get_level_text](https://github.com/willmcgugan/rich/blob/master/rich/logging.py#L102)

**Why this happening when i set: RichHandler(console=Console())**

```python
import logging
from rich.logging import RichHandler
from time import sleep
from rich.theme import Theme
from rich.console import Console

FORMAT = "%(message)s"
logging.basicConfig(
    level="NOTSET", format=FORMAT, datefmt="[%X]", handlers=[RichHandler(
        console=Console(theme=Theme({"logging.level.success": "green"}))
    )]
)

log = logging.getLogger("rich")
log.info("Hello, World!")

#log.error("[bold red blink]Server is shutting down![/]", extra={"markup": True})

#log.error("123 will not be highlighted", extra={"highlighter": None})

logging.addLevelName(25, "SUCCESS")

import time
from rich.progress import Progress

with Progress() as progress:
    task = progress.add_task("Working", total=None)
    for i in range(0,100):
        if i < 30:
            logging.log(25, i+1)
        elif i > 30:
            log.warning(i+1)
        elif i >= 30 and i < 50:
            log.error(i+1)
        elif i >= 50 and i < 70:
            log.debug(i+1)
        elif i >= 70:
            log.critical(i+1)
        sleep(0.05)
```
![image](https://github.com/Textualize/rich/assets/63346676/a37af0c7-02b4-4509-be9a-8b09c8b8db70)

**Comment by ysaquib** [comment]
for @imegeek and anyone who may be coming from google, this is happening because the console in the logging config's RichHandler and the console of the Progress are not the same. You would need to declare a variable eg `my_console=Console()` at the top and pass that to the `RichHandler(console=my_console)` and `Progress(console=my_console)`
