### ISSUE TITLE
[REQUEST] Enable support for OSC8 terminal escape codes

### ISSUE THREAD

**Issue by zachriggle** [willmcgugan/rich#1163]
> Consider posting in https://github.com/willmcgugan/rich/discussions for feedback before raising a feature request.

I think it's worth filing a feature request for.

> Have you checked the issues for a similar suggestions?

Yes

**How would you improve Rich?**

Rich is GREAT for formatting and coloring text in a terminal, but it does not have support for OSC8 hyperlinks, as supported by e.g. iTerm2.

In short OSC8 is a special escape sequence that allows console output to be clickable hyperlinks.  In Python, a OSC8 hyperlink can be generated pretty trivially:

```py
>>> url='https://google.com'
>>> name='Google'
>>> print(f'\x1b]8;;{url}\x07{name}\x1b]8;;\x07')
Google
```

If you are using a compliant shell (most are, notably Terminal.app on macOS does not) you should see an underline below "Google" and e.g. ⌘-clicking the link will open it in your browser.  Custom URI schemes can also be used, which makes it easy to cross-reference things in other apps.

In iTerm2, this looks like the below screenshot, when the cursor is over "Google" and ⌘ is being held down.

<img width="395" alt="Screen Shot 2021-04-06 at 4 55 13 PM" src="https://user-images.githubusercontent.com/111640/113783165-f6b45000-96f8-11eb-8753-f683984e225c.png">

**What problem does it solved for you?**

This would allow more seamless experience with hyperlinking e.g. Markdown content, or adding hyperlinks to items in the Tree view.

This is useful for me specifically, since I want to use Rich for my OmniFocus python bindings to generate a task tree on the command-line, where each node in the tree is also a hyperlink with the `omnifocus://` URI scheme, to jump to that task from the CLI.

**Comment by Daddy2200** [comment]
[Daddy2200]()

**Comment by willmcgugan** [comment]
Rich has supported [hyperlinks](https://rich.readthedocs.io/en/latest/markup.html#links) since v1.1

**Comment by zachriggle** [comment]
Neat!  I just searched for OSC8 in the repo, didn't think to look for
existing "Link" functionality.

Thanks for the tip!
