### ISSUE TITLE
[REQUEST] Support image shown on iTerm2 or tmux

### ISSUE THREAD

**Issue by Rhythmicc** [willmcgugan/rich#1168]
Consider posting in https://github.com/willmcgugan/rich/discussions for feedback before raising a feature request.

Have you checked the issues for a similar suggestions? YES

**How would you improve Rich?**

I want to use Rich and [python-imgcat](https://github.com/wookayin/python-imgcat). If rich can support display image, the experience of using the command line will get a qualitative leap.

**What problem does it solved for you?**

Make my command line app more beautiful ~

**Did I help**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by willmcgugan** [comment]
Image support would be nice. But any non-well supported extensions would need to be in a third-party library.

Rich has a [console protocol](https://rich.readthedocs.io/en/latest/protocol.html) which you can use to build renderables. If a library such as python-imgcat added support, then you could put an image inside table(s) etc.

So it's not something I have any immediate plans to implement, but I'd happy work with anyone who wanted to add support to their lib...
