### ISSUE TITLE
[REQUEST]Raw output method for Text Class

### ISSUE THREAD

**Issue by bgmonroe** [willmcgugan/rich#1179]
**How would you improve Rich?**

As mentioned in #67 and #855, I think it would be useful to integrate the chocolate of rich with the peanut-butter of argparse.  I'm not super familiar with the code base but I think a way to get "most" of the way there would be to extend the Text class with a "raw" (or some more descriptive term) method that returns a string-type object with all escape-sequences and text exposed.  This would allow argparse to consume the contents of a rich.text.Text object and print the string and leave it up to the user's terminal to render.   I am sure there are other use-cases beyond argparse for this method too.

A simple example might look like:
```python
>>> foo = Text.assemble("foobar", style="red")
>>> foo.raw()
'\x1b[31mfoobar\x1b[00m'
```

**What problem does it solved for you?**

I think this could provide more options for integration.

**Comment by willmcgugan** [comment]
I'm not keen on that. The Text object contains only part of the information needed to render the escape sequences. You also need a Console instance, which offers a lot of configuration options and would complicate the `raw()` method.

If there is a `Text.raw()` it might suggest to some people that is the right way of getting output to the terminal, and they would miss out on many other capabilities. The `raw` method would needed to be added to all the renderables, which I don't see the need for given that [capturing output](https://rich.readthedocs.io/en/latest/console.html#capturing-output) is well catered for, should you need it...

**Comment by bgmonroe** [comment]
Thank you for the context, @willmcgugan.  The capture pattern is totally feasible, as you suggest, but it's rather "clunky" for this use case.  That said, it sounds like there isn't a better option.
