### ISSUE TITLE
long output is truncated

### ISSUE THREAD

**Issue by derekn** [willmcgugan/rich#119]
when printing large output, for example debuging json/body responses, the output width is limited to half the terminal width and scrolling to the top is truncated (may be my terminal issue). can there be an arg to not limit output width, or print raw like the stdlib print works? currently i have to comment out the rich import for testing

**Comment by willmcgugan** [comment]
Can you add a screenshot of that?

**Comment by willmcgugan** [comment]
If the width is truncated, check if you have a COLUMNS env var set, as this will override auto detection of the terminal width.

If you can’t scroll back far enough, then have a look in your terminal settings. There is usually a setting for that.

**Comment by derekn** [comment]
well... it must have been an issue on my end with the terminal, i cant reproduce it today. but weird that using the std print worked as expected. you can close for now and ill re-post with screenshots if i encounter it again

**Comment by derekn** [comment]
reopening as i was able to reproduce the issue. it happens when output is piped, i.e. through less or tee. screenshot attached

<img width="1375" alt="Untitled" src="https://user-images.githubusercontent.com/1420397/85889442-1b19ee00-b7b1-11ea-90a5-b203a047c963.png">

**Comment by willmcgugan** [comment]
When you pipe the output, the Python code isn't connected to a terminal, so Rich can't detect the width of the terminal and defaults to 80 columns. That's why you are seeing the output not filling the full width of the terminal. Rich will also not render the control codes when its not connected to the terminal.

I'm not sure what your use case is, but Rich will insert new lines in order to word wrap text. The upshot of this is that you can't expect to print something like JSON with Rich and expect to parse the output as JSON. If you need that functionality, you can detect you are not writing to a terminal and instead write directly to the file. For example:

```python
if console.is_terminal:
    console.print(my_json)
else:
    console.file.write(my_json)
```

**Comment by derekn** [comment]
that makes sense, and I didn't expect control codes to be rendered (as with std print) when detached from a terminal. the use case is this example is just debugging. but piping output to other scripts/files is a pretty standard convention in Linux, so I expected it to be a drop-in replacement for print. inserting unexpected newlines in output will break most piping scenarios, especially with structure data like json/csv.

is there a reason it can't just output the string untouched when width can't be determined, like the std print does? what is the use case for wrapping to 80 columns when the terminal will do that automatically?

**Comment by willmcgugan** [comment]
> is there a reason it can't just output the string untouched when width can't be determined, like the std print does? 

That may fit your use case, but the next developer might want the text wrapping when piping to a file other other program.

> what is the use case for wrapping to 80 columns when the terminal will do that automatically?

Rich does *word* wrapping, which the terminal won't do automatically. There is also a plethora of other options, such as justify, overflow, panels, tables, etc which simply don't make sense without a width. An exception for printing a plain string would break output for many applications.

It's just a safer default for Rich to be consistent and format the output the same way regardless if its in a terminal or not. 

I'd suggest wrapping the snippet above in a function, if you want to write unformatted json.

**Comment by derekn** [comment]
fair enough. i guess i was misunderstanding that it was a drop-in replacement for print. ill close the issue; with this suggestion... it would be really nice to have it disable all control codes, formatting, lists, etc when output is not a terminal. a lot of people will have to import rich.print aliased and use both print functions depending on whether or not a particular output is meant for the terminal or meant to be redirected, as i mentioned this is a very common scenario. or even have a separate function that does this.
anyways, great package and i enjoy using it despite this quark
