### ISSUE TITLE
Rich.Panel does not escape square brackets correctly

### ISSUE THREAD

**Issue by ericxiao251** [willmcgugan/rich#120]
<img width="1305" alt="Screen Shot 2020-06-23 at 4 24 34 PM" src="https://user-images.githubusercontent.com/9758510/85464707-f2f27b00-b575-11ea-9e9f-e99599c05330.png">

Given the code:

```python
self.console.print(Panel("❌ []", style = "red", box=box.HEAVY))
```

it fails.

**Comment by willmcgugan** [comment]
Square brackets are interpreted as [console markup](https://rich.readthedocs.io/en/latest/markup.html). You can escape them by doubling them up. 

```
self.console.print(Panel("❌ [[]]", style = "red", box=box.HEAVY))
```

Alternatively, us a [Text](https://rich.readthedocs.io/en/latest/text.html) instance rather than a string. 

```
self.console.print(Panel(Text("❌ []"), style = "red", box=box.HEAVY))
```

Hope that helps.

**Comment by ericxiao251** [comment]
Oh thank you!
