### ISSUE TITLE
[BUG] PYTORCH CAUSES LIVE TO LOSE COLOR

### ISSUE THREAD

**Issue by dianchia** [willmcgugan/rich#1201]
Hi. I notice when importing PyTorch while using Live it causes everything to turn to black and white.
Image below is the one with torch imported.
![image](https://user-images.githubusercontent.com/32894279/116658658-e3786580-a9c2-11eb-944d-de49ab7854b1.png)

And this is the expected.
![image](https://user-images.githubusercontent.com/32894279/116658784-17538b00-a9c3-11eb-8b18-202afb6cecee.png)
 
`python -m rich.diagnose` output:
![image](https://user-images.githubusercontent.com/32894279/116658985-774a3180-a9c3-11eb-89c1-eac9af98c241.png)

`python -m rich._windows` output:
platform="Windows"
WindowsConsoleFeatures(vt=True, truecolor=True)

`pip freeze` output:
rich==10.1.0

How should I fix this?

**Comment by willmcgugan** [comment]
Can you give me a minimal piece of code that reproduces the problem?

**Comment by dianchia** [comment]
Hi, the issue seems to happen with Layout only, not Live.
Using the example `layout.py`, just include `import torch` then the screen just loses color.

```
from datetime import datetime

from time import sleep

from rich.align import Align
from rich.console import Console
from rich.layout import Layout
from rich.live import Live
from rich.text import Text

import torch    #This line causes problem. Comment out this line then the color is back

console = Console()
layout = Layout()

layout.split(
    Layout(name="header", size=1),
    Layout(ratio=1, name="main"),
    Layout(size=10, name="footer"),
)

layout["main"].split_row(Layout(name="side"), Layout(name="body", ratio=2))

layout["side"].split(Layout(), Layout())

layout["body"].update(
    Align.center(
        Text(
            """This is a demonstration of rich.Layout\n\nHit Ctrl+C to exit""",
            justify="center",
        ),
        vertical="middle",
    )
)


class Clock:
    """Renders the time in the center of the screen."""

    def __rich__(self) -> Text:
        return Text(datetime.now().ctime(), style="bold magenta", justify="center")


layout["header"].update(Clock())

with Live(layout, screen=True, redirect_stderr=False) as live:
    try:
        while True:
            sleep(1)
    except KeyboardInterrupt:
        pass
```

**Comment by willmcgugan** [comment]
It works for me on MacOS.

<img width="1186" alt="Screen Shot 2021-04-30 at 09 53 24" src="https://user-images.githubusercontent.com/554369/116672311-f0cd2a00-a999-11eb-8dd0-bb11c8ae8371.png">

Must be something in your environment.

Can you put the following lines directly after constructing the console:

```python
import sys
from rich import inspect
inspect(console)
sys.exit()
```

And paste the output...

**Comment by dianchia** [comment]
I've included the line after `console = Console()` and here's there result
![image](https://user-images.githubusercontent.com/32894279/116672851-3bb86300-a9d5-11eb-8d75-686e53e0564c.png)

**Comment by willmcgugan** [comment]
I see what has happened. Torch has initialized colorama for some reason, which wraps stdout.  Colorama isn't needed in Windows Terminal.

Try adding the following directly after the `import torch`:

```python
from colorama import deinit
deinit()
```

**Comment by dianchia** [comment]
Thanks! It works now. Man you're good.
