### ISSUE TITLE
need help with multiprocessing

### ISSUE THREAD

**Issue by nvitaly** [willmcgugan/rich#121]
What could be wrong here:

<pre>
#!/usr/bin/env python3

import time
from multiprocessing import Pool, TimeoutError

from rich.progress import Progress, TaskID, BarColumn, TextColumn

progress = Progress()

def do_work(n, task_total):
    time.sleep(1)
    progress.update(task_total, advance=1)
    return n

progress.start()
task_total  = progress.add_task("[cyan]Completed...", total=100)

with Pool(processes=8) as pool:
    data = pool.starmap(do_work, [ (n, task_total) for n in  range(100)])

progress.stop()
</pre>

Thank you in advance!

**Comment by nvitaly** [comment]
I should probably add: it draws progress bar but numbers are no increasing.

**Comment by willmcgugan** [comment]
Hi @nvitaly 

Are you on Linux? Linux uses os.fork which means you will get a copy of the Progress object in the worker processes. When you call `progress.update` in `do_work` you are modifying a copy and not the original Progress instance. 

The solution would be to use a single Progress object and update that in the main process. Something like this:

```python
#!/usr/bin/env python3

import time
from multiprocessing import Pool

from rich.progress import Progress


def do_work(n):
    time.sleep(1)
    return n


if __name__ == "__main__":
    with Progress() as progress:
        task_id = progress.add_task("[cyan]Completed...", total=100)

        with Pool(processes=8) as pool:
            results = pool.imap(do_work, range(100))
            for result in results:
                progress.print(result)
                progress.advance(task_id)
```

Hope that helps.

**Comment by nvitaly** [comment]
Yes, that is it. Thank you!

**Comment by gatto** [comment]
Hello! Sorry, I am trying to use this code to have progress reporting on a very long task, but I need to use `Pool.starmap()` because I need to pass multiple parameters. Am I missing something or this code with starmap updates the progress bar all at once after the entire job is done? I am starting now with multiprocessing and I'm not very knowledgeable of the inner working just yet.
