### ISSUE TITLE
[BUG] Console.print skip the empty lines in the beginning for Syntax

### ISSUE THREAD

**Issue by gaogaotiantian** [willmcgugan/rich#1214]
**Describe the bug**

When I try to print a Syntax with Console, it skips the empty lines in the beginning. Not sure if it's on purpose, but it messed up with the line numbers, which I think is bad.  Take the following code as an example:

```python
syn = Syntax("\n\na=3", "python", line_numbers=True)
c = Console()
c.print(syn)
```

It will show line number ``1`` for ``a=3``, which is incorrect. This is especially annoying when you try to display source code from a certain line number and that line happens to be empty. 

I'm running this on WSL, but I would guess this should be easily reproducible on any platform.

**Comment by willmcgugan** [comment]
Will have a fix for that in the next version.
