### ISSUE TITLE
How to construct something for unmeasurable processes

### ISSUE THREAD

**Issue by jamesb93** [willmcgugan/rich#122]
Hi there,

I use Rich to measure progress for processes that run iteratively but for some of the processes I cannot measure how far along they are (ala sklearn). Sometimes I'd like a function to display a pinwheel or waiting type animation. Is this possible with Rich?

**Comment by willmcgugan** [comment]
If you add a task, but don't start it, it displays an "indeterminate" progress bar. That might be what you are looking for. See https://rich.readthedocs.io/en/latest/progress.html#indeterminate-progress

For an example, run the following:

```
python -m rich.progress
```

**Comment by jamesb93** [comment]
Thanks!

So something like this is sane?

```
def staticproc(name: str, process):
    """For processes where progress can not be determined"""
    with Progress() as progress:
        task = progress.add_task(name, start=False)
        process()
```

**Comment by willmcgugan** [comment]
Yeah, that should work.

You might want to disable time remaining and percentage if you never start the task. Something like this:

```python
with Progress("[magenta]processing...", BarColumn()) as progress:
   etc...
```

**Comment by jamesb93** [comment]
Fantastic - thanks so much.
