### ISSUE TITLE
[BUG] rich.print not prettifying types.MappingProxy

### ISSUE THREAD

**Issue by jupiterbjy** [willmcgugan/rich#1224]
**Read the docs**
No search results related to `MappingProxy`.

**Describe the bug**
Despite `types.MappingProxy` being a view-only dictionary, it is not prettified like normal `dict` does.

**To Reproduce**
May have to adjust range to cause overflow in terminal depending how wide it is.
```python
>>> from types import MappingProxyType
>>> from rich import print

>>> data = {f"{n}": n for n in range(11)}

>>> print(data)
{
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

>>> print(MappingProxyType(data))
{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9,
'10': 10}
```

Best visible in `__dict__` of bulit-in like `str`, shown in this [stackoverflow answer](https://stackoverflow.com/questions/67426074/printing-a-dict-with-rich/67470750#67470750).

**Platform**
Likely platform-independent. Tested on xfce4 Terminal running in ubuntu inside WSL2 and Windows Terminal.

**Diagnose**
output from xfce4 terminal
![image](https://user-images.githubusercontent.com/26041217/117663147-4a73f680-b1db-11eb-84c7-cc011ae8036b.png)

**Comment by willmcgugan** [comment]
Fixed in v10.2.0
