### ISSUE TITLE
[Question] Combine Colorama and Rich

### ISSUE THREAD

**Issue by janaSunrise** [willmcgugan/rich#1232]
I've been working on an application, and been using colored output with Colorama so far. I feel like to use rich for the extra markdown output and more. Hence I want to combine Colorama and Rich text.

I tried
```python
from colorama import Fore
from rich import console

colorama.init(autoreset=True)

console = Console()

console.print(f"{Fore.YELLOW} Hello there!")
```

This doesn't work, and escapes the code instead. Please help me, how I can integrate both.

**Comment by willmcgugan** [comment]
You can replace the f strings with console markup:

```python
console.print("[yellow] Hello there!")
```

If you really must use colorama you can write directly to the file.

```python
colorama.file.write(f"{Fore.YELLOW} Hello there!\n")
```

**Comment by janaSunrise** [comment]
I don't want to write to file, I am making a chat app, and I want to output to console, Instead of using `[yellow]` I want to integrate colorama, since I'm already using it for everything.

**Comment by willmcgugan** [comment]
I made a mistake in the second example. You can use this code, which writes to "standard out", which will be your terminal.

```python
console.file.write(f"{Fore.YELLOW} Hello there!\n")
```

**Comment by janaSunrise** [comment]
Ah, Got it! Thanks.
