### ISSUE TITLE
[REQUEST] Extra caching for `get_character_cell_size`

### ISSUE THREAD

**Issue by JoshKarpel** [willmcgugan/rich#1247]
**How would you improve Rich?**

Add a small `lru_cache` to https://github.com/willmcgugan/rich/blob/master/rich/cells.py#L28 , similar to cache one layer down for https://github.com/willmcgugan/rich/blob/master/rich/cells.py#L46

Size `4096` was plenty for what I describe below.

**What problem does it solved for you?**

I'm working on some optimizations for a TUI application here https://github.com/JoshKarpel/spiel/pull/37

This was my first idea on how to improve rendering time, based on https://github.com/benfred/py-spy telling me that a lot of time was being spent in `get_character_cell_size`, and this was my first thought for a solution.

Adding the cache described above gives a ~30% speedup on the benchmarks I was using to work on that PR. In that application I'm repeatedly re-rendering the same content (in a `Live`), so adding a small cache to  `get_character_cell_size` represents a significant speedup since the set of characters is usually the same from frame to frame. The benchmark is mostly printing colorized ASCII, with some unicode also drawn from a small set (box-drawing characters, block shapes, etc.). 

I guess that since there's lots of `Layout` and `Padding` going on, the most common character is probably space... perhaps the ASCII set that there's already a shortcut for could just be pre-computed and stored in a set? There's probably a lot of good ways to approach this :)

**Comment by willmcgugan** [comment]
Adding `@lru_cache` to `get_character_cell_size` does seem to make a difference, although it's almost too slight to notice with my crude benchmark (`python -m rich` shows tine to render). Still, a win is a win! I'll put that in the next version.

I suspect your use-case (rendering images) is particularly sensitive to this method. Happy to accept a PR for changes to the caching strategy, as long as it doesn't negatively impact more typical usage.

BTW I think you might see bigger wins from your image rendering if you convert the image to a list of `Segment` instances, and yield these from a `__rich_console__` method. It's lower level and will avoid some additional work done in Text. You might also want to use [this function](https://github.com/willmcgugan/rich/blob/master/rich/segment.py#L328) to combine segments with the same style.

**Comment by JoshKarpel** [comment]
> Adding `@lru_cache` to `get_character_cell_size` does seem to make a difference, although it's almost too slight to notice with my crude benchmark (`python -m rich` shows tine to render). Still, a win is a win! I'll put that in the next version.
> 
> I suspect your use-case (rendering images) is particularly sensitive to this method. Happy to accept a PR for changes to the caching strategy, as long as it doesn't negatively impact more typical usage.

Sounds good! I'll play around a bit more with alternative caching strategies. 

> BTW I think you might see bigger wins from your image rendering if you convert the image to a list of `Segment` instances, and yield these from a `__rich_console__` method. It's lower level and will avoid some additional work done in Text. You might also want to use [this function](https://github.com/willmcgugan/rich/blob/master/rich/segment.py#L328) to combine segments with the same style.

Thanks for the tip! I'll give this a try.

**Comment by JoshKarpel** [comment]
`Segment`s worked great! Got a little extra speed and the code is a little cleaner now too.

I played around a bit more with alternate caching strategies but didn't find anything particularly interesting, especially on the more-generic `python -m rich` test.

**Comment by willmcgugan** [comment]
Great!

One more optimization tip. The Style class has an [from_color](https://github.com/willmcgugan/rich/blob/master/rich/style.py#L179) alternative constructor which creates a style with only colors set. It's faster because it can skip processing of the styles.
