### ISSUE TITLE
[BUG] RichHandler unexpected green log output

### ISSUE THREAD

**Issue by pikeas** [willmcgugan/rich#1259]
**Describe the bug**
Certain combinations of logger name and text cause `RichHandler` to output text that is unexpectedly colorized.

**To Reproduce**
```
import logging

from rich.logging import RichHandler

logging.basicConfig(
    level=logging.INFO,
    handlers=[RichHandler()],
)

for c1 in "abcdefg":
    for c2 in "abcdefg":
        logging.getLogger(c1).info(c2)

```

<img width="251" alt="Screen Shot 2021-05-27 at 10 29 22" src="https://user-images.githubusercontent.com/686573/119870604-69aa9d80-bed6-11eb-8a2a-75f758e99970.png">

(screen shot for "efg" only, "abcd" also display as green)

**Platform**
macOS / iTerm

**Diagnose**
```
<console width=178 ColorSystem.TRUECOLOR>
color_system = 'truecolor'
encoding = 'utf-8'
file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
height = 31
is_alt_screen = False
is_dumb_terminal = False
is_interactive = True
is_jupyter = False
is_terminal = True
legacy_windows = False
no_color = False
options = ConsoleOptions(
    size=ConsoleDimensions(width=178, height=31),
    legacy_windows=False,
    min_width=1,
    max_width=178,
    is_terminal=True,
    encoding='utf-8',
    justify=None,
    overflow=None,
    no_wrap=False,
    highlight=None,
    markup=None,
    height=None
)
quiet = False
record = False
safe_box = True
size = ConsoleDimensions(width=178, height=31)
soft_wrap = False
stderr = False
style = None
tab_size = 8
width = 178

platform="Darwin"
WindowsConsoleFeatures(vt=False, truecolor=False)

rich @ file:///Users/[me]/Library/Caches/pypoetry/artifacts/86/d4/e6/4b64e2da645c0db113dd0a98eea75adb255570e4f0e3f597b6c5c0f557/rich-10.2.2-py3-none-any.whl
```

**Comment by willmcgugan** [comment]
They are probably being highlighted as IpV6 addresses which are colons with hex digits between.

You can supply a custom highlighter to the RichHandler, so it will only highlight according to your tests. I'd suggest reading the docs on highlighting and perhaps customizing the [default highlighter](https://github.com/willmcgugan/rich/blob/master/rich/highlighter.py#L79).

**Comment by pikeas** [comment]
> They are probably being highlighted as IpV6 addresses which are colons with hex digits between.
> 
> You can supply a custom highlighter to the RichHandler, so it will only highlight according to your tests. I'd suggest reading the docs on highlighting and perhaps customizing the [default highlighter](https://github.com/willmcgugan/rich/blob/master/rich/highlighter.py#L79).

IPv6 addresses have more than two octets, perhaps a [more robust regex](https://stackoverflow.com/questions/53497/regular-expression-that-matches-valid-ipv6-addresses) would help?

**Comment by willmcgugan** [comment]
It might, but to do it precisely its a quite ridiculous regex. If you want to propose a change, I'd welcome a PR.

Another option, if you don't care about ipV6 would be to [theme](https://rich.readthedocs.io/en/latest/style.html#customizing-defaults) the `"repr.ipv6"` style to `"default"`.
