### ISSUE TITLE
[Request] How to install rich.print globally

### ISSUE THREAD

**Issue by bobatsar** [willmcgugan/rich#1266]
I would like to make sure that for every print statement which is used, rich.print is used even when it is not imported by that module.

Is it possible to install rich.print globally and not only when importing it directly in a file?

Thanks

**Comment by ziofil** [comment]
I know this is not exactly what you asked for, but have you tried this?
```python
from rich.pretty import install
install()
```

**Comment by bobatsar** [comment]
Yes I have tried that but this does not help with print statements.

**Comment by willmcgugan** [comment]
The following may work:

```python
import rich
globals()["print"] = rich.print
```

Not sure if I'd *recommend* it.

**Comment by ziofil** [comment]
maybe this can help: https://docs.python.org/3/using/cmdline.html#envvar-PYTHONSTARTUP

**Comment by bobatsar** [comment]
Thanks for the suggestions.
