### ISSUE TITLE
Output under MPI

### ISSUE THREAD

**Issue by mrzv** [willmcgugan/rich#127]
If I try to use rich output under MPI, I get blank lines. Here's an example:
```python
# test.py
from mpi4py import MPI
rank = MPI.COMM_WORLD.Get_rank()

from rich import print
print(rank)
```

```
mpirun -n 2 python3 test.py
```
Produces four blank lines.

Even if I wrap the output to only run on rank 0, i.e.,
```python
if rank == 0:
    from rich import print
    print(rank)
```
I still get only blank lines (this time two of them).

What's causing this, and how can I fix it?

**Comment by willmcgugan** [comment]
What happens if you use the builtin `print`?

**Comment by mrzv** [comment]
Normal print works just fine: prints out the two respective ranks.

**Comment by willmcgugan** [comment]
I've never used MPI and it seems a pain to install, but this is unlikely to be an issue with Rich.

MPI must capture output. Perhaps it's not handling the ansi control codes. If you print a number if will highlight it in bold blue. Try replacing the rich import with the following:

```python
from rich.console import Console
console = Console()
console.print(rank, highlight=False)
```

That will disable highlighting and be equivalent to builtin print.

**Comment by mrzv** [comment]
`highlight=False` didn't help. But it's also clearly a problem with OpenMPI. If I switch to MPICH, then all the output is printed out, in all versions of the above code, but without any formatting, color, etc. Under OpenMPI, I always just get blank lines, when using rich. I haven't found a way to disable output capture, but I'll keep looking.

Ideally, I'd like to find an option, where if I only output from one of the processes, I get the full output formatting. Curiously, if I run `mpirun -n 2 python -m rich`, under MPICH I get the full output formatting, twice — except the width is limited, compared to the full terminal. Under OpenMPI, I just get blank lines again.

**Comment by mrzv** [comment]
Just to make this a little more constructive, two mysteries remain:
1. Why doesn't `highlight=False` produce output under OpenMPI? If it's supposed to be equivalent to builtin print, something is not working.
2. Why, under MPICH, does `mpirun -n 2 python -m rich` produce colored formatted output, but `print(rank, style='yellow')` doesn't?

**Comment by willmcgugan** [comment]
Try replacing print with `sys.stdout.write("foo\n")`.  If that doesn't work, then I suspect that the builtin `print` is being monkey patched somehow.

**Comment by mrzv** [comment]
`sys.stdout.write` works fine.

**Comment by willmcgugan** [comment]
Not sure what else to suggest tbh. Don't suppose you have a file called `rich.py` in your project?

**Comment by mrzv** [comment]
No, this is a clean directory with just the above example.

Do you mind installing OpenMPI and trying it yourself? On most Linux distributions and Homebrew on a Mac, it's a one-liner.

**Comment by willmcgugan** [comment]
Tried on Unbuntu and OSX and I was missing some libraries.

I'll give it another go at some point.

**Comment by willmcgugan** [comment]
I've figure out what is going on. When run with MPI, the `shutil.get_terminal_size` function reports a terminal size of (0, 0). Rich wraps text to the column width, and when you wrap to a width of 0 all you are left with is blank lines.

I think this must be a bug in how MPI sets the environment for processes.

A workaround would be to define a `COLUMNS` environment var with your desired terminal width. Or construct Console with an explicit width.

```python
console = Console(width=80)
console.print(rank). # This works!
```

**Comment by mrzv** [comment]
Ah, great. Thanks for figuring it out. I think this qualifies as a bug I should report upstream to OpenMPI. And the workaround is great, too.
