### ISSUE TITLE
[REQUEST] Auto-install features for rich.traceback (and possibly rich.pretty)

### ISSUE THREAD

**Issue by JulesGM** [willmcgugan/rich#1271]
[colored-traceback](https://github.com/staticshock/colored-traceback.py) does this thing where if you do `import colored_traceback.auto` it automatically calls `colored_traceback.install()` (actually `colored_traceback.add_hook()`). This is prettier than having `colored_traceback.install()`, and I think the same could be easily implemented with rich.traceback.

I was also thinking that the same could be done with something else like `rich.pretty`.

The way this is done is really simple. Just create a subfolder with an `__init__.py` file that calls `.install()`. See https://github.com/staticshock/colored-traceback.py/blob/master/colored_traceback/auto/__init__.py.

**Comment by willmcgugan** [comment]
I'm not overly keen on that. Import time side-effects are generally a bad idea.

Presumably you wouldn't want this as part of an app, and its for the REPL? It's probably better to add this to your PYTHONSTARTUP file so you won't even need an import.

**Comment by willmcgugan** [comment]
I'll think about it. I might change my mind.
