### ISSUE TITLE
[REQUEST]: Add support to track() for printing above the current progress bar

### ISSUE THREAD

**Issue by birdistheword96** [willmcgugan/rich#1273]
While the progress() class is a nice and fairly easy to use, sometimes it is just the simpler 'track' function that's required. However, because it isn't possible to nicely print in a track function, it limits it's use cases.

It also means that if you try to write code that supports rich if available, but falls back to basic python without, you can't easily do it with progress class. With track you can simply add: `track = lambda x, *args, **kwargs : x` if rich is not available, but with a progress bar, you have to implement a full null context manager.

If possible, it would nice if you could pass track() the console object and it will print above the progress bar

**Comment by willmcgugan** [comment]
> If possible, it would nice if you could pass track() the console object and it will print above the progress bar

You can.

**Comment by birdistheword96** [comment]
I apologise, I couldn't see it in the documentation but I have now found it in the reference. It was obvious for the Progress object but not so obvious for the track function!
