### ISSUE TITLE
[BUG]Control cursor error

### ISSUE THREAD

**Issue by waylonwang** [willmcgugan/rich#1289]
1. In control.py, CURSOR_MOVE_TO_ROW should be  be named CURSOR_MOVE_TO_COL, because "CSI n G" changes columns.
2. In move_to_row function, the absolute position of the x-coordinate, whether or not it has a y-coordinate, should be (ControlType.CURSOR_MOVE_TO_ROW, x), and should not have y-coordinates where the absolute position of the x-coordinate is (ControlType.CURSOR_MOVE_TO_ROW, x + 1).

**Comment by willmcgugan** [comment]
1. Yep, thanks
2. Sorry, I don't quite follow. Could you elaborate?
