### ISSUE TITLE
How to log grey text? (like comments)

### ISSUE THREAD

**Issue by John-Theo** [willmcgugan/rich#129]
Tried a few things, like:

```python
console.log(f'[grey0]some text[/grey0]')
console.log(f'[dim white]some text[/dim white]')
console.log(f'[grey_0]some text[/grey_0]')
```

But they all failed the purpose. 
What is the right way?

Windows 10 / Python 3.7 / vscode / console emulator

**Comment by willmcgugan** [comment]
The classic Windows terminal has a limited range of colors I'm afraid. Try the new Windows terminal which supports more colors, then you can pick one from https://rich.readthedocs.io/en/latest/appendix/colors.html

**Comment by John-Theo** [comment]
Much appreciated! And really awesome project BTW!
