### ISSUE TITLE
[BUG] No repr for pandas.Timestamp in JupyterLab when using rich.pretty

### ISSUE THREAD

**Issue by dlukes** [willmcgugan/rich#1305]
**Describe the bug**

In JupyterLab, after globally enabling `rich` reprs, no repr is shown for `pandas.Timestamp` objects. In both IPython and the default Python REPL, this problem does not occur.

**To Reproduce**

Start JupyterLab:

```console
$ jupyter lab
```

Create a new notebook and enable `rich` reprs -- either like this:

```ipython
%load_ext rich
```

Or like this:

```python
from rich import pretty
pretty.install()
```

Then enter the following code into the next cell and evaluate it:

```python
import pandas
pandas.Timestamp("2021-06-18T16:55:00")
```

No repr is shown. If the same code is run in a terminal REPL (both `ipython` and `python`), a repr is shown, as expected.

**Platform**

Linux (Solus)

**Diagnose**

```console
$ pip freeze | grep -P '(rich|jupyterlab)='
jupyterlab==3.0.16
rich==10.4.0
```

**Comment by willmcgugan** [comment]
Found the problem. There will be a fix in the next release.

**Comment by willmcgugan** [comment]
Can you give 10.5.0 a try and let me know if that fixes it?

**Comment by dlukes** [comment]
It does indeed, thank you very much!

**Comment by saiwing-yeung** [comment]
@willmcgugan I noticed an issue that might be related.

```
df = pd.DataFrame({'datadate': ['2021-01-01']})
df['datadate']  # doesn't print anything
```

This works if I don't `pretty.install()`.
