### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pepplejoshua** [willmcgugan/rich#1316]
**Read the docs**
You might find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) -- consider using the search function there.

**Describe the bug**
When I create a link in terminal (using Console or rich.print()), it does not stylize as a clickable link, but just regular text.

**To Reproduce**
```
from rich.console import Console
c = Console()
c.print("[green bold]Google[/]", style="link https://google.com")
```

```
from rich import print as rprint
rprint("[green bold link=https://google.com]Google[/]")
```

**Platform**
MacOS running latest OS using ZSH.

**Diagnose**
```
python -m rich.diagnose
python -m rich._windows
pip freeze | grep rich
```
After running these commands, I don't encounter any problems. Feels like the output might be too long to include in this report. I can if it is required subsequently.

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by willmcgugan** [comment]
I guess you figured out it is terminal dependent? Try iTerm for MacOS

**Comment by pepplejoshua** [comment]
Yes I did! I was in the midst of reading. Sorry about that.

Cheers!
