### ISSUE TITLE
[REQUEST] Support emoji variation selectors

### ISSUE THREAD

**Issue by pd93** [willmcgugan/rich#1318]
**How would you improve Rich?**

Add support for [variation selectors](https://stackoverflow.com/questions/38100329/some-emojis-e-g-have-two-unicode-u-u2601-and-u-u2601-ufe0f-what-does). I have recently stated using `rich` and want to migrate from the [emoji package](https://pypi.org/project/emoji/). However, the `emoji` package lets me specify a `variant_type` when printing. This will then append a sequence after every emoji to ensure that the correct variation is printed. See the `emoji` package [code in action](https://github.com/carpedm20/emoji/blob/70e7ba12dfaf3449a5d445b1e7de4ae2c6245d19/emoji/core.py#L72).

**What problem does it solve for you?**

Current behaviour:
```py
from rich.console import Console

def print_test():
    console = Console()
    console.print(":thumbs_up:")
    console.print(":warning:")
```
Results in:
![image](https://user-images.githubusercontent.com/9294862/123637993-8ceaa480-d816-11eb-92d8-696696c57e1f.png)

The equivellent code for the `emoji` package with `variant="emoji_type"` results in:
![image](https://user-images.githubusercontent.com/9294862/123638270-e521a680-d816-11eb-9a3d-9001955b77bb.png)

We can obtain this behaviour with `rich` by changing the code to
```py
console.print(":warning:\uFE0F")
```

But it would nice to have a flag on `Console` that automatically adds the sequence, so I don't have to append it every time an emoji doesn't render how I want it to.

**Comment by willmcgugan** [comment]
That's possible. But would you ever want to mix emoji variants?

**Comment by pd93** [comment]
My suggestion would be a flag on the `Console` class that allows you to set the value globally and to allow people to override that setting with a keyword parameter on `console.print()`

For example (naming aside), it could work like this:
```py
console = Console(emoji_variant="emoji")

console.print(":warning:")
console.print(":warning:", emoji_variant="text")

# If you want them on one line
console.print(":warning:", end="")
console.print(":warning:", emoji_variant="text")
```

We could also make `emoji_variant` an `enum`.

**Comment by willmcgugan** [comment]
Using `end=""` won't allow mixing of variants within renderables, i.e. tables etc.

I'm wondering if we can encode the variant within the emoji code. Something line `print(":warning-text: :warning-emoji:")`.

Could be used in conjuction with the `emoji_variant` argument.

**Comment by pd93** [comment]
Assuming that **all** unicode tags use `_` as word separators (e.g. `:hot_pepper:`) and will continue to do so, then using `-text` (with a hyphen) as a suffix should be fine as it won't conflict with any of the tags.

We could consider using other separators to make it clearer that its not a part of the emoji tag. e.g. `:hot_pepper#text:` or `:hot_pepper;text:` might be clearer than `:hot_pepper-text:`. Ultimately, the separator doesn't bother me - Just a thought.

**Comment by willmcgugan** [comment]
I've added variants to 10.6.0 You can set `empji_variant` on the Console constructor. Or by adding `-text` or `-emoji` to the emoji code. I haven't added it to `print` since there are already quite a lot of arguments on that method, and you can reverse it with the emoji code anyway.

**Comment by pd93** [comment]
Amazing. Thanks for such a quick turnaround on this. This is already one of my favourite Python projects 👍
