### ISSUE TITLE
[BUG] Styles like bold, underline, reverse ... are not compatible with Anaconda Prompt

### ISSUE THREAD

**Issue by padmalcom** [willmcgugan/rich#1319]
Hi, I use anaconda and the anaconda prompt to run my python application in Windows 10 on python 3.8.

I tested some styles and found out that some aren't working, for example:
- bold
- underline
- reverse
- emojis

Am I missing some packages or do I need to switch my terminal?

Example code:
```
from rich import print
from rich.console import Console
if __name__ == '__main__':
	console = Console()
	console.print(all_sentences[i], style = "reverse red")
```

Here is the diagnose output:
(ttsdatasetcreator) C:\Users\admin\ttsdatasetcreator>python -m rich.diagnose
┌─────────────────────────── <class 'rich.console.Console'> ───────────────────────────┐
│ A high level console interface.                                                      │
│                                                                                      │
│ ┌──────────────────────────────────────────────────────────────────────────────────┐ │
│ │ <console width=119 ColorSystem.WINDOWS>                                          │ │
│ └──────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                      │
│     color_system = 'windows'                                                         │
│         encoding = 'utf-8'                                                           │
│             file = <colorama.ansitowin32.StreamWrapper object at 0x00000148C415E520> │
│           height = 30                                                                │
│    is_alt_screen = False                                                             │
│ is_dumb_terminal = False                                                             │
│   is_interactive = True                                                              │
│       is_jupyter = False                                                             │
│      is_terminal = True                                                              │
│   legacy_windows = True                                                              │
│         no_color = False                                                             │
│          options = ConsoleOptions(                                                   │
│                        size=ConsoleDimensions(width=119, height=30),                 │
│                        legacy_windows=True,                                          │
│                        min_width=1,                                                  │
│                        max_width=119,                                                │
│                        is_terminal=True,                                             │
│                        encoding='utf-8',                                             │
│                        justify=None,                                                 │
│                        overflow=None,                                                │
│                        no_wrap=False,                                                │
│                        highlight=None,                                               │
│                        markup=None,                                                  │
│                        height=None                                                   │
│                    )                                                                 │
│            quiet = False                                                             │
│           record = False                                                             │
│         safe_box = True                                                              │
│             size = ConsoleDimensions(width=119, height=30)                           │
│        soft_wrap = False                                                             │
│           stderr = False                                                             │
│            style = None                                                              │
│         tab_size = 8                                                                 │
│            width = 119                                                               │
└──────────────────────────────────────────────────────────────────────────────────────┘

(ttsdatasetcreator) C:\Users\admin\ttsdatasetcreator>python -m rich._windows
platform="Windows"
WindowsConsoleFeatures(vt=False, truecolor=False)

pip freeze shows rich==10.4.0 is installed.

**Comment by willmcgugan** [comment]
Windows historically has had very poor support for ansi styles. However, the new Windows Terminal has good support now. If you install it, it *may* even get you styles in the Anaconda prompt which I suspect embeds a console.

https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab
