### ISSUE TITLE
shrink some columns more than the others

### ISSUE THREAD

**Issue by htarnacki** [willmcgugan/rich#132]
I have a question.
How to force selected columns to be more susceptible to shrinkage than others?

for example on the screenshot below i want the first 3 columns to be fully visible but the other columns could be shrinked when overflow exists
![Zaznaczenie_001](https://user-images.githubusercontent.com/49711873/86377392-946d8100-bc88-11ea-924f-bbcc7c940ffd.png)

I tried to use 'ratio' argument but didn't see any efect of it

**Comment by willmcgugan** [comment]
You can set `no_wrap=True` on the columns you don't want to wrap.

**Comment by htarnacki** [comment]
Look at the screenshot i have provided before. The first 3 columns have followings properties:
overflow = fold
no_wrap = True
So i have alredy tried to set no_wrap but without success. First 3 columns are shrinked even the last column have a lot of space. The last column has: overflow = ellipsis and no_wrap is not set.
Version 3.0.1

**Comment by willmcgugan** [comment]
That should work. I’ll need to see the code you use to generate the table to offer more suggestions.

**Comment by willmcgugan** [comment]
I think the issue may be that all four columns can't wrap (the last column can't wrap because there are no spaces).

Try v3.0.2 there is a change that prioritizes no_wrap columns.

**Comment by htarnacki** [comment]
a little bit better right now but not perfect ;-)
let us see how it behaves right now:

```
headers = [
    {'name': 'Name', 'overflow': 'fold', 'no_wrap': True},
    {'name': 'State', 'overflow': 'fold', 'no_wrap': True},
    {'name': 'Healthcheck', 'overflow': 'fold', 'no_wrap': True},
    {'name': 'Image', 'overflow': 'ellipsis'},
    {'name': 'Container name', 'overflow': 'ellipsis'},
    {'name': 'Version', 'overflow': 'ellipsis'},
    {'name': 'Ports', 'overflow': 'ellipsis'}]

```

1.
![1](https://user-images.githubusercontent.com/49711873/86443438-8f074980-bd0f-11ea-9840-4d93be72116f.png)

2. as we can see last 4 columns start shrinking
![2](https://user-images.githubusercontent.com/49711873/86443411-84e54b00-bd0f-11ea-92c0-70ca6fe04483.png)

3. ports column has vanished
![3](https://user-images.githubusercontent.com/49711873/86443787-0e951880-bd10-11ea-8a40-7341f9616830.png)

4. last columns shrink more then "Image" column, header for "Container name" column is both wrapping and shrinking
![4](https://user-images.githubusercontent.com/49711873/86443961-4f8d2d00-bd10-11ea-8aff-3b5834f30382.png)

5. "Name" column starts shrinking and header for "Healthcheck" columns starts shrinking
![5](https://user-images.githubusercontent.com/49711873/86444262-c7f3ee00-bd10-11ea-908c-1c383e2c9a1d.png)

6. "State" column starts shrinking. 'Image' column still have a lot of space
![6](https://user-images.githubusercontent.com/49711873/86444384-f671c900-bd10-11ea-82d4-900e349059a1.png)


How i see wrapping/shrinking functionality should work:

1. we should have following column attributes:

**overflow behaviour:** 
wrap:
```
first
second
```
cut_start:
```
irst second
```
cut_end:
```
first sec
```
ellipsis_start:
```
...st second
```
ellipsis_end:
```
first se...
```
no_change (keep string unchanged, fixed width, no wrap, no shrink):
```
first second
```
[wrap, cut_start]:
```
irst
econd
```
[wrap, cut_end]:
```
firs
seco
```
[wrap, ellipsis_start]:
```
...st
...nd
```
[wrap, ellipsis_end]:
```
fi...
se...
```

**overflow headers behaviour:** 
wrap, cut_start, cut_end, ellipsis_start, ellipsis_end, no_change, [wrap, cut_start], [wrap, cut_end], [wrap, ellipsis_start], [wrap, ellipsis_end], None (default, means use the same value as for 'overflow behaviour')

_so there are generally 2 groups of overflow actions:_
wrapping: wrap
shrinking: cut_start, cut_end, ellipsis_start, ellipsis_end

**shrink column priority/ratio:** 
1, 3, 5, ... (any positive int value)
so for example if we need to shrink table row by 10 chars then: 
1 + 3 + 5 = 9
shrink first column by 1/9 * 10 characters
shrink second column by 3/9 * 10 characters
shrink third column by 5/9 * 10 characters

**wrap_chars:** 
' \t\n,:;/-()[]{}' -> configurable list of characters that can be used for wrapping
None -> wrap by any character (if overflow action is set to 'wrap')
default -> wrap by whitespace characters


2. general overflow logic:
- first try to do wrapping on columns with overflow wrap action
- repeat wrapping until there is nothing more that can be wrapped
- next if still not enogh space then start shrinking taking shrink priorities/ratios into consideration
- column values shouldn't be shrinked more than their headers so for example if header has 'no_change' overflow action then len(header) is the minimum width for the whole column

**Comment by willmcgugan** [comment]
The excess space is currently removed evenly from the non `no_wrap` columns. Which is why small columns will disappear first.

I'm sure there is improvements to be had in the column shrinking logic, I'm not convinced its worth going to such efforts with regards to configuring priorities and extra overflow methods. I'm using HTML tables as my guide and if the browser doesn't do it, it's going to be a hard sell to ask me to implement something. 

At the end of the day, if you have more text than can fit, it's going to be imperfect no matter how it's configured. My suggestion for your table would be to make more of the columns `no_wrap` and allow wrapping on the Image column. If those are URLs, consider the `link` attribute which will work even if the text overflows.

If you want to tackle the table shrinking algorithm yourself, see `Table._calculate_column_widths`. I'll consider any suggestions for improvements, and I'd be happy to accept a PR.

I like the idea of specifying the characters to wrap on. I think that would be worthwhile adding to the Text class.

**Comment by willmcgugan** [comment]
You might want to give the `table-shrink` branch a try. I'm experimenting with a different algorithm to reduce table sizes.

**Comment by htarnacki** [comment]
It is much, much better right now ;-) thx!
![Zrzut_ekranu_2020-07-03-165054](https://user-images.githubusercontent.com/49711873/86479977-70c03e80-bd4d-11ea-88f3-1738de17448f.png)

could you at least consider adding: ellipsis_start?
This should be extremely simple. In my case there are columns where last part of the string is more important then beginning:
 abcdefgh... -> ...defghijk

**Comment by willmcgugan** [comment]
New algorithm is in v3.0.3

> could you at least consider adding: ellipsis_start?

I'll consider it for a future update.

**Comment by htarnacki** [comment]
thx!
