### ISSUE TITLE
[BUG] Progress(): Terminal size mis-detected if run in multiprocessing sub-process

### ISSUE THREAD

**Issue by amirmkang** [willmcgugan/rich#1321]
**Describe the bug**
Using `multiprocessing` to run a sub process, initializing Progress() under that process fails to detect the terminal size, using the fallback (80, 25) instead.

**To Reproduce**
Sample code:
```
from multiprocessing import Process, Queue

from rich.console import Console
from rich.progress import Progress


def sub_process():
    pre_console = Console()
    print(f"Sub process PRE console size: {pre_console.size}\n")

    with Progress() as progress:
        print(f"Sub process progress.console.size: {progress.console.size}")

        console = Console()
        print(f"Sub process console size: {console.size}\n")


if __name__ == "__main__":
    with Progress() as main_progress:

        print(f"Main progress.console.size: {main_progress.console.size}")

        main_console = Console()
        print(f"Main console size: {main_console.size}\n")

        q = Queue()
        process = Process(target=sub_process)
        process.start()
        process.join()
```
Output is:
```
Main progress.console.size: ConsoleDimensions(width=151, height=45)
Main console size: ConsoleDimensions(width=151, height=45)

Sub process PRE console size: ConsoleDimensions(width=151, height=45)

Sub process progress.console.size: ConsoleDimensions(width=80, height=25)
Sub process console size: ConsoleDimensions(width=80, height=25)
```

-> Note the difference between the 3 variants:
- instances in main module (correct terminal size)
- instance in sub process, _before_ Progress() is called (correct)
- instances in sub process, _after_ Progress() is called (*fallback*)

**Platform**
Macos 11.4 (Big Sur)
iTerm 2
python 3.9.4

**Diagnose**
I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

rich.diagnose
```
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=151 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 45                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=151, height=45),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=151,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=151, height=45)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 151                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
```

rich._windows
```
platform="Darwin"
WindowsConsoleFeatures(vt=False, truecolor=False)
```
pip freeze | grep rich
```
rich==10.2.2
```

** Workaround **
Initalize a Console() with width and height from shutil.get_terminal_size(), then initialize Progress() with that console:
```
    terminal_size: os.terminal_size = shutil.get_terminal_size()
    console = Console(width=terminal_size.columns, height=terminal_size.lines)
    progress = Progress(console=console)
```
It would seem that Console() only uses shutil.get_terminal_size() under Windows. Otherwise it uses os.get_terminal_size() for stdin or stdout - but I guess (I haven't fully explored your code, sorry) that the redirects that are enabled by Progress() / Live(), coupled with the multiprocessing, somehow mess that up. Perhaps shutil could be tried first, regardless of platform?

Thanks for an awesome library!

**Comment by willmcgugan** [comment]
The Progress class will wrap stdout to capture print statements. This breaks auto-detecting size when inside the Progress block. It is an edge case, but why would you want to do it? Is your workaround acceptable?

shutil.get_terminal_size calls os.get_terminal_size under the hood.

You will likely find things progress bars break if you are using them from the main process and a sub procress. There's no way for Rich to render correctly if another process is writing to stdout.

**Comment by amirmkang** [comment]
I use multiprocessing to parallelize my workload (nothing special, I believe) (my example above is over-simplified, and doesn't present the 10 workers I usually run via `multiprocessing`).

I want to display progress, and, as you recommend, I am avoiding writing output from several processes. I do this by starting another sub process that is dedicated to output, and receives updates via a `multiprocessing.Queue` queue, which it then translates to `progress.add_task()`, `progress.update()`, and `progress.remove_task()` calls, as required. This, I believe, allows Rich to render correctly (nothing else writes to stdout while all of this is going on).

However, if I leave things as-is, and create the `Progress()` instance inside this dedicated output process, I end up with a display that is limited to 80 columns, regardless of my actual window / terminal size. It took me a bit of experimenting until I figured out (that my configuration was correct and) in which exact scenario this happens. I do not explicitly try to auto-detect the terminal size, this is what Rich does on its own, ending up with this result.

Indeed, `shutil.get_terminal_size()` calls `os.get_terminal_size()` under the hood, but (I checked this only now) it uses `sys.__stdout__.fileno()` as the argument, instead of `sys.stdout.fileno()`, which (stdout) has been redirected at this point, and does not support this request.
(BTW, it would seem that at this point `sys.stdin` is also modified, with its `name` property changing value from `"<stdin>"` to `5` (the integer 5); this leads `os.get_terminal_size(sys.stdin.fileno())` to fail, as well)

**Comment by amirmkang** [comment]
(and BTW: I really appreciate your quick response here! 🙏 )

**Comment by willmcgugan** [comment]
Please try 10.6.0 It will use sys.__stdin__ etc. so it should still work even when wrapper.

**Comment by mboquien** [comment]
I ran into the same issue and the new release appears to have solved it. Thanks a lot!
