### ISSUE TITLE
[BUG] Cosmetic bug for __rich_repr__  repr-error

### ISSUE THREAD

**Issue by aroberge** [willmcgugan/rich#1326]
I'm sorry, I tried to come up with a simple example, but I could not create a simple example that generated a repr-error. I'm using Rich 10.4.0 and (ab)use `__rich_repr__` to create some translatable help. 

Basically, when a repr-error is generated, it contains an item enclosed in single quotes. This item can contain terms that are also enclosed in single quotes. If so, the result is not highlighted properly.

![image](https://user-images.githubusercontent.com/629698/124383924-678de880-dca5-11eb-9d2c-32a3bf3927b6.png)

For info, here's what it looks like when I fix the error in my code, using my own colour scheme  (I love this feature of Rich)

![image](https://user-images.githubusercontent.com/629698/124383981-b76caf80-dca5-11eb-8dc8-54e6be9e1eea.png)

**Comment by willmcgugan** [comment]
Easy fix, will be in the next version.

I wonder if I should offer alternative themes in Rich...

**Comment by aroberge** [comment]
Regarding additional themes: I found it easy enough to design my own themes - although I did have to dig up in the code to figure out [some "repr" attribute names, like `repr.bool_true`](https://github.com/friendly-traceback/friendly/blob/31643658b1e19d6bc44f5829cf692e8fb4e0e645/friendly/theme/brunante.py#L64).

If I were you, I would just invite people to design their own themes, and provide links.

One thing that I am not too fond of in the default theme for Rich when using Pygments for highlighting some code blocks is that, by default, Rich uses three different colours for True, False, and None for their "repr"  while Pygments uses a single colour for all three.  So, depending on how True/False/None are processed, they can show up in different colours in the terminal.  For example, in your README, we can see `True` and `False` showing up in light blue in a code block on the left-hand side, and respectively green and red on the right-hand side.  I think I understand why you chose to use different colours for these three singletons, but I prefer a single colour myself.

**Comment by willmcgugan** [comment]
Should be fixed in 10.5.0

I find the different highlighting of True / False / None helps when scanning a data dump. The color alone is enough to know what it is.

I see your point that the styles don't match syntax highlighting. In tracebacks I forced the reprs to use the colors from the Pygments theme, because the difference is more jarring when the two are right next to each other. But for printing data structure I find the utility of the default theme to be worth it.

**Comment by aroberge** [comment]
Sorry for not replying sooner: as far as I can tell from my tests, it is fixed. Thanks!
