### ISSUE TITLE
[REQUEST] Please include a version string in the code

### ISSUE THREAD

**Issue by kseistrup** [willmcgugan/rich#1329]
**How would you improve Rich?**

I would like Rich to have its version included in the code — possibly in `__init__.__version__` — so that I can introspectively find the version of Rich installed.

**What problem does it solve for you?**

* Do I have the latest version installed?
* When filing an issue, which version should I report?
* In IPython, I would like to print out the version of Rich in the startup banner.

I am currently running v10.5.0. In order to find out, I first visited `/usr/lib/python3.9/site-packages/rich` and grepped case-insensitively for `version` and `ver` to no avail. Then I backed up to `..` and did

```sh
$ ls -d1 rich*
rich
rich-10.5.0.dist-info
```

to be able to conclude that I am running v10.5.0. With a builtin version string I would be able to e.g.:

```sh
$ python -c 'import rich; print(rich.__version__)'
rich/10.5.0 (2021-05-07)
```

Cheers.

**Comment by willmcgugan** [comment]
Please see previous issues on this 

https://github.com/willmcgugan/rich/issues?q=is%3Aissue+__version__+is%3Aclosed

**Comment by kseistrup** [comment]
I'm awfully sorry for having wasted your time. I did search and look through the closed issues before submitting my request, but apparently I wasn't thorough enough.

**Comment by willmcgugan** [comment]
No worries, @kseistrup
