### ISSUE TITLE
Feature Request: Conda package

### ISSUE THREAD

**Issue by Zethson** [willmcgugan/rich#134]
Dear @willmcgugan ,

would it be possible for you to create a Conda package for Rich (and keep it up to date)?
I would like to create a Conda package for my own package, which has Rich as a dependency. 

If you're not familiar with Conda, this will help: https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html

Thank you very much!
Cheers

**Comment by willmcgugan** [comment]
I'll look in to it. Not a Coda user myself.

**Comment by ewels** [comment]
Note that once you've set it up in the first place, maintenance is typically very easy if the package is on PyPI, so it shouldn't be a big commitment. Usually it means just merging automated PRs after PyPI releases (I think even the merge can be automated now).

There are different channels for conda, the go-to for most packages like this is probably `conda-forge`: https://conda-forge.org/ - instructions for adding a new recipe here: https://conda-forge.org/#add_recipe

**Comment by jaimergp** [comment]
`rich` seems to be available on conda-forge already:

- https://github.com/conda-forge/rich-feedstock
- https://anaconda.org/conda-forge/rich

**Comment by ewels** [comment]
Ah nice! Added only 10 days ago, after @Zethson's original comment 😅  Thanks @jan-janssen! Might be nice to add @willmcgugan as a [recipe maintainer](https://github.com/conda-forge/rich-feedstock/blob/c4fc39a1c796cef0e6a76086c87a276118d471a4/recipe/meta.yaml#L56-L58)..

**Comment by willmcgugan** [comment]
Great! Saved me the work. 👍

**Comment by jan-janssen** [comment]
@willmcgugan if you want to join me maintaining the recipe I would be happy to add you as a maintainer.

**Comment by willmcgugan** [comment]
@jan-janssen  sounds good, thanks.

**Comment by willmcgugan** [comment]
Guess I can close this one now. 👍

**Comment by ManavalanG** [comment]
Would be nice to mention if conda route is mentioned in readme's `install` section.
