### ISSUE TITLE
[BUG] console.print with Syntax ignores "\n"

### ISSUE THREAD

**Issue by aroberge** [willmcgugan/rich#1341]
**Describe the bug**
Printing highlighting code using Syntax with a console results in ignoring the end="" parameter.
![image](https://user-images.githubusercontent.com/629698/125198304-c7513a00-e237-11eb-8ad6-6006022eef7b.png)

**To Reproduce**
```
>>> from rich.syntax import Syntax
>>> from rich.console import Console
>>> out = Syntax("print('Hello world')", "python")
>>> con = Console()
>>> con.print(out)
print('Hello world')
>>> con.print(out, end="")
print('Hello world')
```

I suspect that this is done on purpose by adding "\n" to the code passed to Pygments ... which may be due to a limitation of Pygment (?).  

**Platform**
Windows terminal, latest version of Rich.

**Comment by willmcgugan** [comment]
Might not be clear in the docs, but the `end` argument only applies to strings since it will be appended to the output. Renderables like Syntax have no ability to append strings.
