### ISSUE TITLE
[BUG] Docs and Code inconsistent about `Markdown.inline_code_lexer` default value

### ISSUE THREAD

**Issue by mustafaquraish** [willmcgugan/rich#1350]
[The documentation](https://rich.readthedocs.io/en/stable/reference/markdown.html#rich.markdown.Markdown) for the `Markdown` class specifies that the default value of `inline_code_lexer` is `"python"`, however this does not seem to be the case.

The fix for this should be simple, and I can fix it myself, I just was not sure what the intended default is supposed to be.

**Comment by willmcgugan** [comment]
The default is None which means there will be no highlighting of inline code. So the docs are in error. Happy to accept a PR with a dox!
