### ISSUE TITLE
[BUG] Inconsistent `overflow="ignore"` behavior on `table.Table`

### ISSUE THREAD

**Issue by paw-lu** [willmcgugan/rich#1357]
**Read the docs**
- [x] Done

**Describe the bug**
Tables do not seem to respect `overflow="ignore"`

**To Reproduce**

This script

```python
import io

from rich import console
from rich import table

con = console.Console(file=io.StringIO(), width=30)
grid = table.Table.grid()
grid.add_column(overflow="ignore", width=50)
grid.add_row("a" * 50)
con.print(grid, crop=False, highlight=False, overflow="ignore")
output = con.file.getvalue()
print(len(output))  # Output: 31 (expceted 51)
```

Gives an output of 31—meaning it cuts off the remaining characters even though `overflow` is set to `"ignore"`. I had expected it to output the full 51 characters, as it does when `rich.text.Text` and a string are printed by rich with `overflow="ignore"`.
This causes issues when trying to insert characters stylized by another process (like in https://github.com/willmcgugan/rich/discussions/384#discussioncomment-987416).

**Platform**
macOS 11.4

**Diagnose**

<details>
<summary>Diagnose</summary>

```
python -m rich.diagnose
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=250 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 72                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=250, height=72),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=250,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=250, height=72)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 250                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯

python -m rich._windows
platform="Darwin"
WindowsConsoleFeatures(vt=False, truecolor=False)

pip freeze | grep rich
rich @ file:///Users/pawlu/Library/Caches/pypoetry/artifacts/d8/09/d1/c1e297bde3276fe5289c3fc9cf6804eb531e28372b527f854b1427b012/rich-10.5.0-py3-none-any.whl
```
</details>

**Comment by willmcgugan** [comment]
`overflow="ignore"` is only relevant when you print text directly to the console. There's no way to ignore overflow in the context of a table because it would break the alignment.

If you are trying to insert text with color codes it's not going to work in a context where Rich has to measure the length of the text. The invisible control codes will throw off the measurement.

You can convert text with ansi codes in to a Text instance which you will be able to insert in a table. Have a look at the undocumented [AnsiDecoder](https://github.com/willmcgugan/rich/blob/master/rich/ansi.py#L108) class. If you feed it strings with color codes it will yield Text objects.

**Comment by paw-lu** [comment]
> Have a look at the undocumented [AnsiDecoder](https://github.com/willmcgugan/rich/blob/master/rich/ansi.py#L108) class. If you feed it strings with color codes it will yield Text objects.

This is exactly what I was looking to build myself if it wansn't implimented. Thanks for pointing me in the right direction. It works perfectly for my needs here.

> `overflow="ignore"` is only relevant when you print text directly to the console.

Yeah this is what I thought. Thanks for confirming. Does `overflow="ignore"` have _any_ effect on `rich.column.Column`?

If not, should we throw and exception/warning when the user inputs `"ignore"` as an `overflow` arg?

**Comment by willmcgugan** [comment]
> Yeah this is what I thought. Thanks for confirming. Does overflow="ignore" have any effect on rich.table.Column?

Not as such. The overflow refers to the right hand side of the terminal. Text in a table etc, text will never overflow. The table itself may overflow, if you create a table with width 100 and print it on a terminal with width 80, for example.

> If not, should we throw and exception/warning when the user inputs "ignore" as an overflow arg?

I would say not. Consider it a null operation. Like `foo += 0`. Doesn't change anything, but it's not strictly an error.  Of course, if the docs aren't clear on this, then that should be addressed.
