### ISSUE TITLE
Can't finish a task on a progress

### ISSUE THREAD

**Issue by k4ch0** [willmcgugan/rich#137]
Hello,

I'm trying to implement some progress bar, but when I use a `track` function within a `for` when the task finishes it renders green. From my point of view, this means, that the task finished successfully.

```python
for customer in track(get_credentials, description="Getting credentials..."):
    LOGIC WITHIN A FOR LOOP
```
Renders as:
![this](https://i.imgur.com/wu1BWo1.png)

I like this because after the process ends, the process bar renders on green color.

But when I use the following approach, when the task finishes it shows like a `working` state, instead of a `green` state.

```python
from rich.progress import Progress, track, BarColumn, TimeRemainingColumn, TaskID, TextColumn

progress = Progress(
    "[progress.description]{task.description}",
    BarColumn(),# bar_width=None),
    "[progress.percentage]{task.percentage:>3.0f}%",
    TimeRemainingColumn(),
    auto_refresh=False,
)

with progress:
    task_1 = progress.add_task("[black]Getting ALL certs...", start=False, total=100)
    task_2 = progress.add_task("[black]Getting ALL servers...", start=False, total=100)
    task_3 = progress.add_task("[black]Getting ALL dns...", start=False, total=100)

    while not progress.finished:
        df_all_certs = get_all_certs(session)
        progress.update(task_1, advance=100, total=100, completed=100, refresh=True)

        df_all_servers = get_all_servers(session)
        progress.update(task_2, advance=100, total=100, completed=100,refresh=True)

        df_all_dns = get_all_dns(session)
        progress.update(task_3, advance=100, total=100, completed=100,refresh=True)
```

Renders as:

![this](https://i.imgur.com/MW8v9ju.png)

As those functions are not using a `for` loop, for my understanding, I'm not able to use `track`.

What I'm doing, is after any function ends, I update the task from 0 to 100, complete the task and perform a manual refresh, so I expected it will show the progressbar as `OK` (green) but instead, is showing was `working`

How can I get the same behavior from `track` on other tasks that do not have a sequence?

Any help will be appreciated.

Thank you

**Comment by willmcgugan** [comment]
You’ve created your tasks with start=False, which shows the working state. You’ll need to start them before you call update.

**Comment by k4ch0** [comment]
@willmcgugan, that works like a charm, the change was:

```python
    task_1 = progress.add_task("[black]Getting ALL certs...", start=True, total=100)
    task_2 = progress.add_task("[black]Getting ALL servers...", start=True, total=100)
    task_3 = progress.add_task("[black]Getting ALL dns...", start=True, total=100)
```

Thank you
