### ISSUE TITLE
[BUG] inconsistent highlighting of version numbers

### ISSUE THREAD

**Issue by thorstenkampe** [willmcgugan/rich#1377]
**Describe the bug**
highlighting version strings (decimal point separated) results in confusing highlighting

**To Reproduce**
```python
from rich import console, table

row = ('1', '1.2', '1.2.3', '1.2.3.4', '1.2.3.4.5', '1.2.3.4.5.6')
tab = table.Table(highlight=True, show_header=False)
con = console.Console()

tab.add_row(*row)
con.print(tab)
```

![image](https://user-images.githubusercontent.com/475462/127970729-fdc600ea-0403-4844-bf3e-9fd214da77db.png)

**Platform**
rich 10.6.0 on Windows

**Comment by willmcgugan** [comment]
The blue is highlighted as a floating point number, and the green is highlighted as an IP address. The highlighting is only ever going to be a best guess. In situations where it doesn't highlight as desired, you can disable it or explicitly highlight a cell at a time. See docs for details.
