### ISSUE TITLE
[BUG] In Traceback documentation: `console.print_exception()` is not enough information

### ISSUE THREAD

**Issue by simonw** [willmcgugan/rich#1380]
This page currently says: https://rich.readthedocs.io/en/latest/traceback.html

> ### Printing tracebacks
>
> The [print_exception()](https://rich.readthedocs.io/en/latest/reference/console.html#rich.console.Console.print_exception) method will print a traceback for the current exception being handled. Here’s an example:
>
> ```python
> try:
>     do_something()
> except:
>     console.print_exception()
> ```
That's not enough information though (especially for someone like myself who just landed directly on that page of the documentation from a Google search) because it doesn't tell you how to create the `console` object.

The subsequent example code on that page *does* tell you exactly what to do:

> ```python
> from rich.traceback import install
> install()
> ```

**Comment by simonw** [comment]
I ended up using this recipe:
```python
rich.console.Console().print_exception(show_locals=True)
```
I think `show_locals=True` deserves to be mentioned on the https://rich.readthedocs.io/en/latest/traceback.html page (rather than being only tucked away in the API reference section) because it is *such* an improvement over the Python default tracebacks!

**Comment by willmcgugan** [comment]
Yeah, that page could use an update.

**Comment by willmcgugan** [comment]
I might make show_locals the default. It was disabled because it could get spammy if you have a large data structure in locals. It will abbreviate large containers and strings now, so that's less of a problem.
