### ISSUE TITLE
[BUG]rich.text.Text changed to str if imported typing

### ISSUE THREAD

**Issue by timsu92** [willmcgugan/rich#1389]
**Describe the bug**
```python
from typing import *
```
AFTER
```python
from rich.text import Text
```
makes Text become normal str.

However, if I change
```python
from typing import *
```
to
```python
from typing import Literal, Union, List, Dict, OrderedDict, Optional
```
it works.

**To Reproduce**
```python
from rich.text import Text
from typing import *
print(f'{Text=}')
# output: Text=<class 'str'>
```

**Platform**
OS: Windows 10 21H1, build 19043.1110
Terminal: Windows Terminal and the built-in in PyCharm

**Diagnose**
![image](https://user-images.githubusercontent.com/33785401/128516918-dd6b5959-1b27-4904-b4f6-5a4f7a7a839a.png)
![image](https://user-images.githubusercontent.com/33785401/128516968-f024bb88-d34e-4d9a-85ff-52a3c14dc1ca.png)
![image](https://user-images.githubusercontent.com/33785401/128517533-20728e74-7c41-4c1b-8a0d-901b93314077.png)
"rich" in pip freeze:
rich @ file:///D:/bld/rich_1626123387078/work

**Comment by willmcgugan** [comment]
This is one of the reasons why it best to avoid `import *`. If you only import what you need you may be able to avoid that trap.

`typing.Text` is only required if you are writing code that uses Python2.7, so you may not need to import it. If you do you can alias rich Text with the following:

```python
from rich.text import Text as RichText
```

**Comment by timsu92** [comment]
God... I've found the line and didn't realize it...
Thanks for your answer and sorry for the stupid noob question😥
