### ISSUE TITLE
Bug: 24-bit color should work on conhost as of Windows 10.0.15063

### ISSUE THREAD

**Issue by DHowett** [willmcgugan/rich#139]
According to [this blog post](https://devblogs.microsoft.com/commandline/24-bit-color-in-the-windows-console/), the windows console host added support for 24-bit color in build 14931.

It is safer and easier to gate the use of 24-bit color on the Windows version and _not_ the presence of Windows Terminal, especially as WT is not the only terminal emulator that benefits from conhost enhancements.

**Comment by willmcgugan** [comment]
Fixed in v3.05
