### ISSUE TITLE
[REQUEST] Add a single function call that would replace all native functionality with rich's

### ISSUE THREAD

**Issue by tomergt45** [willmcgugan/rich#1390]
Every time I create a new project, I add the following lines so that `rich` would replace the native functionality

```
from rich import get_console, traceback, pretty

traceback.install()
pretty.install()

print = get_console().print
```

It would be nice to have a single `install` function that would install all of rich's functionality instead of needing to write that...

**Comment by willmcgugan** [comment]
It's only 4 lines. A global install function would only reduce that to 2. But there are a lot of parameters to both traceback and pretty which I would need to support and not everybody will want to replace the print method since its not fully compatible with the default print.

Glad you install Rich by default, but this is something best left to the developer.

**Comment by tomergt45** [comment]
I don't think that "it's only 4 lines" is such a good approach, why not simplify something if it can be simplified?
This can potentially attract more users to the library since it would reduce the lines of code required for integration.

I've taken a look into the source code and found the following `load_ipython_extension` which is located in `_extention`:
```
from typing import Any


def load_ipython_extension(ip: Any) -> None:  # pragma: no cover
    # prevent circular import
    from rich.pretty import install
    from rich.traceback import install as tr_install

    install()
    tr_install()
```

This function seems to be doing something very similar and is already imported into rich's main module (although seems to be unused internally & has a broken implementation, i.e. an unused argument).

I suggest renaming `_extention.py` into `install.py` and replacing `load_ipython_extension` into the following `install_rich`:

```
from rich import pretty as rich_pretty, traceback as rich_traceback, get_console

def install_rich(pretty=True, traceback=True, replace_print=False):
    global print
    if pretty:
        rich_pretty.install()
    if traceback:
        rich_traceback.install()
    if replace_print:
        print = get_console().print
```

I don't mind contributing the changes myself if needed.
