### ISSUE TITLE
[REQUEST] Link to relevant reference pages, at the end of explanation pages

### ISSUE THREAD

**Issue by pradyunsg** [willmcgugan/rich#1402]
**How would you improve Rich?**

The title says it all, honestly.

To give a specific example of what this would look like... At the end of https://rich.readthedocs.io/en/stable/tables.html, it would be good to have links to:

- https://rich.readthedocs.io/en/stable/reference/table.html
- https://rich.readthedocs.io/en/stable/appendix/box.html
- *maybe* https://rich.readthedocs.io/en/stable/reference/columns.html

**What problem does it solved for you?**

(psst: there's a typo in this question)

Helps with discoverability in the documentation, by providing additional ways to get to the API reference from the relevant explanation pages. In my opinion, this would help make it easier to get from not-knowing-about-a-thing-in-rich to using-that-thing-beyond-the-canned-examples.

PS: Thanks for making this library. ❤️
PPS: Have you considered adopting [Furo](https://pradyunsg.me/furo/)?

**Comment by willmcgugan** [comment]
There is a link to Tables ref in the docs. I tend not to have a list of links at the end, and have them embedded in the body of the docs somewhere. But you're right, it could use more relevant links. Happy to accept a PR if you want to make those changes?

I haven't given themes for the docs much thought, to be honest. But looking at Furo it does look very elegant! Cleaner and more modern than the default RTD theme. I'll probably use it for Textual docs. But if somebody was to submit a PR for the Rich docs I would probably merge it... ;-)

**Comment by pradyunsg** [comment]
Ahhhh. The monospace "Table" is a link!

**Comment by willmcgugan** [comment]
They're not very obvious are they? I'll look in to a new theme soon. Maybe Furo!
