### ISSUE TITLE
Print custom exception messages with rich?

### ISSUE THREAD

**Issue by Imipenem** [willmcgugan/rich#1403]
Hey,

Let's say I've defined a custom exception class like:
```
def MyCustomExc(Exception):
    pass
```
Is it possible to, when I raise the exception like `raise MyCustomExc("[bold red]my error msg")`, somehow print this message with rich rather than just the string "as it is"?

Many thanks

**Comment by willmcgugan** [comment]
Not currently, no. I would be wary of doing that in case the markup contains errors. But it might be nice to have a way for exceptions to explicitly add Rich output. I'll think about that...
