### ISSUE TITLE
What About Rendering Pandas's Dataframes Into Rich Tables ? If This Feature Is Already Supported Then Please Help Me With Examples.

### ISSUE THREAD

**Issue by adarsh4u218** [willmcgugan/rich#1406]
I Searched It On Internet And Found A Package From PYPI And The Name Was ```rich-dataframe``` As Identifier Of Package.
I Won't Install Because I Want Offically Supported Feature

**Comment by willmcgugan** [comment]
There's nothing which prints Panda Dataframes out-of-the-box, but you could build something.
