### ISSUE TITLE
Emojis (and tables) not rendered in markdown (GitHub-flavoured markdown)

### ISSUE THREAD

**Issue by vlerenc** [willmcgugan/rich#142]
I have some markdown with emojis and while `rich` can render them fine, they are not rendered in markdown, which may be correct, but somewhat sad. Is there a way to reach that goal? Maybe some post-processing/re-ingesting I could do?

``` python
text = ":smiley: :vampire: :pile_of_poo: :thumbs_up: :raccoon: :white_large_square: :green_heart: :green_heart: :grey_question: :large_blue_diamond: :large_blue_diamond: :large_orange_diamond: :red_circle: :heavy_exclamation_mark: :bangbang: :boom:"
console.print(text)
console.print(Markdown(text))
```

**Comment by willmcgugan** [comment]
No I'm afraid not. Pre-processing would probably work. Something like this:

```python
from rich.emoji import Emoji
emojified_text = Emoji.replace(text)
console.print(Markdown(emojified_text))
```

**Comment by vlerenc** [comment]
Wow, awesome, thank you @willmcgugan! Pre- or post-processing, either way, this is just what I was looking for. Thank you!

I am not yet familiar with your work - just saw it yesterday on HN. Really great! I was thinking the other day that such a technology would be neat to help me with a tool of mine that can report back into a GitHub issue (as a robot of sorts), but that can be also used stand-alone in the terminal, but then I need to support different output formats, which makes everything quite complex.

On a related note, I also noticed that tables are not rendered. Now, what I should say/wrote above, the markdown I want to render in the terminal is GitHub-flavored markdown, so nothing `rich` says it would render. I was thinking, I need to find the tables myself and invoke your table API directly or is there also a simple solution to tables, too?

**Comment by willmcgugan** [comment]
The markdown renderer I use is "commonmark" which doesn't do tables. There is an unofficial extension which parses tables, but it's not maintained so I'm reluctant to use it.

Tables would be a nice to have feature in the Markdown class, especially since Rich already has good support for tables. Its just a fair but of work to make it happen, so it's not high on my list of priorities. That might change if I get sponsorship...

**Comment by vlerenc** [comment]
Sure, fair, thanks for the answer @willmcgugan. Let me close this then.
