### ISSUE TITLE
Styled tables are very slow vscode console

### ISSUE THREAD

**Issue by erezsh** [willmcgugan/rich#143]
Here is a minimal script that reproduces the issue:

```python
import time

from rich.console import Console
from rich.table import Table

table = Table(title="Test")

columns = range(20)
for i in columns:
    table.add_column(str(i), style="green")

for row in range(20):
    table.add_row(*[f"{row}-{i}" for i in columns])

console = Console()

start = time.time()
console.print(table)
total = time.time() - start
console.print(f"[red]This took {total:.2f} seconds")
```

Inside the vscode console (Windows 10): `This took 1.29 seconds`

In regular shell (Windows 10 / Ubuntu): `This took 0.10 seconds`

It seems that the issue comes from using colors. Without style, the table renders much faster under vscode (0.2 seconds).

I realize this probably isn't a high-priority issue, but I thought you might like to know!

P.S. Great library, I just discovered it and it's a lot of fun! I wish I could use it to replace everything prompt-toolkit does

**Comment by willmcgugan** [comment]
What you are timing there is mostly the terminal. Dedicated terminals tend to be faster than HTML terminals.

Try the following change, which separates generating the table from the time it takes to render on the terminal:

```python
import time

from rich.console import Console
from rich.table import Table

table = Table(title="Test")

columns = range(20)
for i in columns:
    table.add_column(str(i), style="green")

for row in range(20):
    table.add_row(*[f"{row}-{i}" for i in columns])

import io
console = Console(file=io.StringIO(), force_terminal=True)

start = time.time()
console.print(table)
result = console.file.getvalue()
total = time.time() - start
print(result)
print(f"This took {total:.2f} seconds")
```

**Comment by erezsh** [comment]
I see, so it seems that the problem is with the way the vscode terminal handles color escaping.

Thanks for the quick reply!

**Comment by Tyriar** [comment]
Old thread, but adding some context in case anyone finds it useful. VS Code's terminal has 3 different renderers which are now driven by the `terminal.integrated.gpuAcceleration` setting. The best experience by far is if you have that as `"on"` (or `"auto"`, but that will fallback if a problem is detected) which will use WebGL2 to render the buffer and should generally be on par with native terminals.

Unfortunately WebGL2 doesn't work on all environments though and rarely there are strange issues that come with it typically related to GPU drivers/Chromium.
