### ISSUE TITLE
[BUG] Path does not  get highlighted.

### ISSUE THREAD

**Issue by szsdk** [willmcgugan/rich#1450]
Paths in the form of `foo/bar` do get highlighted correctly.
https://github.com/willmcgugan/rich/blob/62b00db0d2f130cc0087a7a50c80bfbaaed66218/rich/highlighter.py#L114

I suppose this is a bug, not a feature.

**Comment by willmcgugan** [comment]
I assume you mean *do not* get highlighted correctly.

The problem is that it is ambiguous, is "foo/bar/baz" a path or a math expression? See the docs how to implement a highlighter if you need relative paths highlighted.

**Comment by szsdk** [comment]
I see. I did not notice that form could be interpreted as a math expreesion. Thanks for pointing this out.
