### ISSUE TITLE
[QUESTION] Tree within a Table?

### ISSUE THREAD

**Issue by dsully** [willmcgugan/rich#1462]
Hi - is it possible to have a Tree within a Table? I see the inverse is possible.

Thanks

**Comment by willmcgugan** [comment]
It is!

**Comment by willmcgugan** [comment]
Not sure I follow. Could you do make a mock-up or sketch?

**Comment by dsully** [comment]
<img width="898" alt="CleanShot 2021-09-01 at 15 10 44@2x" src="https://user-images.githubusercontent.com/22371/131752043-1e84f742-5aa2-4f71-bd53-3096f7381dd7.png">

**Comment by dsully** [comment]
<img width="882" alt="CleanShot 2021-09-01 at 15 11 41@2x" src="https://user-images.githubusercontent.com/22371/131752122-9ae88d1a-6654-47b7-b356-963e439627d6.png">

**Comment by willmcgugan** [comment]
Ah. That’s easy. Call add_row with a Tree instance.

**Comment by dsully** [comment]
I'm doing that already. Unless you mean each `Tree()` instance should be in a `table.add_row()`?

**Comment by willmcgugan** [comment]
Do you want the bottom rows of your table to align with the branches of the tree? To get that you would have to add them to a single row.

for instance, in the second column you could add "user1\nuser2\nuser3" etc.

**Comment by dsully** [comment]
Yes, that's my desired output. Thinking about how best to do this though.

It doesn't look like `rich.table.Column` has any way to add a row just to that column, which would be ideal.
