### ISSUE TITLE
Is there any way to render a _rich_ object to `str`?

### ISSUE THREAD

**Issue by Congee** [willmcgugan/rich#147]
I currently use io.StringIO to get a `str`. Is there any simpler way to do it?

``` python
from io import StringIO

from rich.table import Table
from rich.console import Console

buf = StringIO()
table = Table(...)
console(file=buf)
console.print(table)
buf.getvalue()  # this is the `str` I would like
```

I find `__repr__` and `__str__` output the same thing like `<rich.table.Table object at 0x7fc9cd308ac0>`, may be rich can provide an api of `__str__` or `.to_str()`

**Comment by willmcgugan** [comment]
That's a reasonable solution. I do it the same way in tests.

A method wouldn't capture all use cases as rendering with rich isn't as simple as `__str__`. You would need to know the width for example, in your code above you may get a different result with a differently sized terminal. It would also generate different output for each platform.

If you need that functionality I'd suggest defining a `render_to_str` function somewhere.

**Comment by Congee** [comment]
Hmmm, thank you for prompt reply. I did define a helper function like `render_to_str`.

**Comment by Congee** [comment]
FWIW, `io.StringIO().isatty() is False`. One might want `Console(force_terminal=True)`

**Comment by Honno** [comment]
For reference to futurelings,  if you have objects which you want to be rendered both by a command-line interface AND in Jupyter environments, you do NOT want to do the following:
```python
class MyClass():
    ...
    def __rich__:   # or __rich_console__
        ...

    def __str__(self):
        buf = StringIO()
        console = Console(file=buf)
        console.print(self)

        return buf.getvalue()
```
This will work fine for your CLI as `console.print(instance_of_MyClass)` will only care about the `__rich__`/`__rich_console__` method.

However if you `print(instance_of_MyClass)` (Python's top-level `print` statement), the `console` instantiation inside `__str__` will actually detect that it is inside a Jupyter environment, and subsequently `console.print(self)` will RENDER (not print!) to Jupyter. `buf` won't get anything, so the `buf.getvalue()` being returned will result in Jupyter's output being empty.

---

I'm just designating a separate method `pprint()` so notebook users can nicely render the contents of the object.

```python
from my_package import console  # console is an instance of rich.Console
...
class MyClass():
    ...
    def __rich__:
        ...

    def pprint(self):
        console.print(self)
```

**Comment by willmcgugan** [comment]
Perhaps the `force_jupyter` parameter in the Console constructor should have three states; `False` to disable jupyter, `True` to enable it, and a default of `None` to auto detect.

That way you could `force_jupyter=False` in `__str__` so you always get a string.

**Comment by willmcgugan** [comment]
The three-state `force_jupyter` is in 6.1.0

**Comment by Honno** [comment]
Awesome, thanks so much!

(I had actually encountered a problem with the notebook hosting platform Kaggle today, where Jupyter-rendered text is printed white... on a white background! So to use my library on it nicely, I really did need this behaviour in the end.)

For future reference, the below worked well for me.

```python
class MyClass():
    ...
    def __rich__(self):   # or __rich_console__
        ...

    def __str__(self):
        buf = StringIO()
        console = Console(file=buf, force_jupyter=False)
        console.print(self)

        return buf.getvalue()
```
