### ISSUE TITLE
[QUESTION] How to edit text after it's printed?

### ISSUE THREAD

**Issue by Stijn-Verhelst** [willmcgugan/rich#1470]
Hi,

First of all, thank you so much for the time you spent making this library!

I was wondering if it was possible to edit a text after it was printed? For example, change the text "One" to "Two".

Kind regards

**Comment by willmcgugan** [comment]
The answer is no, but *maybe*.

There are ansi codes which move the cursor, so you could in theory print something then go back and overwrite it.

If you want to do something like that with Rich, see the [Live](https://rich.readthedocs.io/en/latest/live.html)
