### ISSUE TITLE
[QUESTION] Ability to set color for Confirm.ask()

### ISSUE THREAD

**Issue by sureshdsk** [willmcgugan/rich#1476]
**Describe the bug**
Not possible to set color/style for Confirm.ask(). If there is a way to do this, the doc needs to be updated. 

```
from rich.prompt import Confirm
is_rich_great = Confirm.ask("Do you like rich?")
```
Would like style support for Prompt and Confirm.

**Comment by willmcgugan** [comment]
```python
Confirm.ask("[magenta]Do [red]you [green]like [blue]rich?")
```

**Comment by sureshdsk** [comment]
@willmcgugan looks good.
