### ISSUE TITLE
Emojis in tables messes up the column alignment

### ISSUE THREAD

**Issue by traviscook21** [willmcgugan/rich#148]
My assumption is this is due to emojis taking up two unicode codepoints but getting rendered using only spot.  As a result, the columns are off.

![image](https://user-images.githubusercontent.com/3671851/86951825-e722bf00-c106-11ea-8cd2-fe163b88d923.png)

Reproduction:
```
from rich.console import Console
from rich.table import Table
console = Console()
table = Table(title="Emoji Table")
table.add_column("emoji", justify="left", no_wrap=True)
table.add_row(":smiley:")
table.add_row(":no_entry:")
table.add_row(":white_heavy_check_mark:")
console.print(table)
```

**Comment by willmcgugan** [comment]
Your assumption is correct!

I'm afraid there is not much that can be done. Terminals don't always keep up with the latest changes to the unicode database.

My suggestion would be to find another "tick" symbol. There are a few in unicode. You should be able to find one that existed in unicode for longer, and will render with the correct size in the terminal.

**Comment by traviscook21** [comment]
Ah - interesting.  I would've assumed the issue was in the padding / measuring libraries in this repo and not in the terminal implementation.

**Comment by willmcgugan** [comment]
It's kind of an interaction of both. The only real solution would be to know what version of the unicode database the given terminal is using, and that's just not exposed anywhere.

btw what terminal are you using? Those characters work fine in iTerm, Ubuntu, and Windows Terminal.

**Comment by traviscook21** [comment]
Got it.  I use OSX's terminal

**Comment by ssbarnea** [comment]
I tried to use ⭐ emoji and it seems impossible to make render ok when using export_html. I am using iTerm2 but the fact that the outcome is dependent on current terminal make the emoji and tables a real issue. Any idea on how to address it?

**Comment by willmcgugan** [comment]
As you have discovered, the browser renders emoji differently from the terminal.

The only solution I have thought of would be to parse out emoji, and force them in to a span with a width that matches the terminal. I think that would work, but it will make the export function more complex.

It’s not high on my list of priorities. But if you file an issue for this I’ll Likely get to it eventually. Maybe sooner if I get sponsorship.
