### ISSUE TITLE
Spurious comma in markdown example

### ISSUE THREAD

**Issue by danr** [willmcgugan/rich#1483]
https://github.com/willmcgugan/rich/blob/6f09ae226c26a2be52e3214ee93e6d704756d282/rich/__main__.py#L198

```diff
- Supports much of the *markdown*, __syntax__! 
+ Supports much of the *markdown* __syntax__! 
```

Remove this comma?

**Comment by willmcgugan** [comment]
Yeah, fair. Would you like to PR for that? Bear in mind, it will need updating in a test as well.
