### ISSUE TITLE
[BUG] Status  and logging overlap

### ISSUE THREAD

**Issue by Peterpig** [willmcgugan/rich#1484]
**Read the docs**
<img width="803" alt="微信截图_20210913180849" src="https://user-images.githubusercontent.com/7956973/133065795-e89c2305-7848-4179-9f01-4bf59309fcc2.png">

**To Reproduce**

```
``import logging
import time

from rich.console import Console
from rich.logging import RichHandler
console = Console()

logging.basicConfig(level="NOTSET", format="%(message)s", datefmt="[%X]", handlers=[RichHandler(rich_tracebacks=True, tracebacks_show_locals=True)])

with console.status(f"Process ...") as status:
    logging.error("aaaa")
    time.sleep(2)
    logging.error("aaaa")
    time.sleep(2)
    logging.error("aaaa")
    time.sleep(2)
    logging.error("aaaa")
    time.sleep(2)


```

**Platform**
windows + wsl

**Diagnose**
I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

rich==10.9.0
<img width="401" alt="微信截图_20210913181114" src="https://user-images.githubusercontent.com/7956973/133066129-133fff9f-40f0-4264-af3e-11f28b2ed5f7.png">

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by GBeauregard** [comment]
You can set the console in the handler definition too (`console=console`)

**Comment by willmcgugan** [comment]
@Peterpig See @GBeauregard suggestion. Set `console=console` on the RichHandler.

**Comment by willmcgugan** [comment]
I think the above suggestion will fix it.

**Comment by Peterpig** [comment]
> @Peterpig See @GBeauregard suggestion. Set `console=console` on the RichHandler.

sorry.  i don't know
console=console  set where

logging's handler? such as 
`
logging.basicConfig(
    level="NOTSET",
    format="%(message)s",
    datefmt="[%X]",
    handlers=[console]
)
`

**Comment by Peterpig** [comment]
> I think the above suggestion will fix it.

i test it , it still has bugs


code is
`
import time, logging

logging.basicConfig(
    level="NOTSET",
    format="%(message)s",
    datefmt="[%X]",
    handlers=[RichHandler(console=console)]
)

from rich.console import Console
from rich.logging import RichHandler
console = Console()

logging.basicConfig(level="NOTSET", format="%(message)s", datefmt="[%X]", handlers=[RichHandler(rich_tracebacks=True, tracebacks_show_locals=True)])

with console.status(f"Process ...") as status:
    logging.error("aaaa")
    time.sleep(2)
    logging.error("aaaa")
    time.sleep(2)
    logging.error("aaaa")
    time.sleep(2)
    logging.error("aaaa")
    time.sleep(2)
`
![image](https://user-images.githubusercontent.com/7956973/135055813-f1762866-5050-423f-b7d0-352a8da3818c.png)

**Comment by Peterpig** [comment]
> > logging.basicConfig(level="NOTSET", format="%(message)s", datefmt="[%X]", handlers=[RichHandler(rich_tracebacks=True, tracebacks_show_locals=True)])
> 
> Inside the call to `RichHandler`

it's ok, thanks

**Comment by Peterpig** [comment]
> @Peterpig See @GBeauregard suggestion. Set `console=console` on the RichHandler.

when log is vary fast, it will be still has bug, code  such as below

`
import logging
import time

from rich.console import Console
from rich.logging import RichHandler
console = Console()

logging.basicConfig(level="NOTSET", format="%(message)s", datefmt="[%X]", handlers=[RichHandler(rich_tracebacks=True, tracebacks_show_locals=True)])

with console.status(f"Process ...") as status:
    while True:
        logging.error("aaaa")
        logging.error("aaaa")
`

**Comment by GBeauregard** [comment]
Yeah, the rich handler doesn't seem to play nice with console status in some edge cases either. Maybe file a new bug?

**Comment by willmcgugan** [comment]
@Peterpig Can you reproduce this outside of iPython? i.e. run a script directly in the terminal.

**Comment by GBeauregard** [comment]
My mentioned issue with it has to do with threading I think; there's some racy condition when the status is closing and the rich handler tries to print a log. However, I'm not sure it's possible to fix it outside of the internals of the rich library.

**Comment by GBeauregard** [comment]
The above race condition happens quite easily if your rich handler is attached to a queue listener. In this case log messages precipitating the status closing tend to get eaten.

See:
https://github.com/GBeauregard/pyffstream/blob/71e9080799283f6ccfa701c9255a90edfa93f3e5/src/pyffstream/cli.py#L607-L613

If you consider this a bug I can open a separate issue I guess; it seems hard to fix on my end, but I'm not sure if you have a trick for it. (I think I need to subclass the handler to try to add a lock somewhere?)

**Comment by Peterpig** [comment]
> @Peterpig你能在 iPython 之外重现这个吗？即直接在终端中运行脚本。

i test it in py script,  logging is very fast, console.status  cant show anything.

code is same as top
