### ISSUE TITLE
[REQUEST] current item of a progress

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [willmcgugan/rich#1489]
when creating progress bars for logical items (that are then supported with additional progress pars,
i would consider it helpful if it was possible to add a name/render able for the current item, and to push those in updates

i`m not yet sure how this is best expressed/implemented

**Comment by willmcgugan** [comment]
Not sure I follow. You can add arbitrary fields in `add_task`, which could be renderables.

**Comment by RonnyPfannschmidt** [comment]
For example progress.track will not update a task with the current item, i can Elaborate more once back to the computer

**Comment by willmcgugan** [comment]
More details please.

**Comment by RonnyPfannschmidt** [comment]
for example in the progress configured in https://github.com/pytest-dev/regendoc/blob/19cfd54ff9b5353a58b11a2dbafb73a3ba37fb5b/src/regendoc/__init__.py#L76-L82

i progress files in https://github.com/pytest-dev/regendoc/blob/19cfd54ff9b5353a58b11a2dbafb73a3ba37fb5b/src/regendoc/__init__.py#L113-L116

instead of just writing processing files, i'd like to add to the bar something that which which is the current file

for that having a `task.current_item` (which is set by `progress.track`) would be a nice help

**Comment by willmcgugan** [comment]
You can add arbitrary fields like this:

```python
progress.update(task_id, filename=name)
```

And you can refer to those in the columns with `task.fields.filename`.

Does that help?
