### ISSUE TITLE
[REQUEST] Coloring email's in assignment if there is dot in between

### ISSUE THREAD

**Issue by avatar-lavventura** [willmcgugan/rich#1498]
When I do `log("provider_email=user.here@gmail.com")`

It prints as:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/18537398/133891611-37f8b4d6-81bc-4979-87e4-67b0345ebc2c.png">

Would it be possible to detect string as whole where print `user.here@gmail.com"` as yellow. 

If not how can I disable coloring for the `user.here@gmail.com` and print is just white?

**Comment by yashrathi-git** [comment]
![image](https://user-images.githubusercontent.com/57002207/133892434-f7fdf340-144b-443a-b770-75d699ad89e0.png)
You could use `highlight=False`, to disable that behaviour. 

You could also define your own highlighter [like this](https://github.com/willmcgugan/rich/blob/master/examples/highlighter.py)

**Comment by avatar-lavventura** [comment]
> ![image](https://user-images.githubusercontent.com/57002207/133892434-f7fdf340-144b-443a-b770-75d699ad89e0.png)
> You could use `highlight=False`, to disable that behaviour.
> 
> You could also define your own highlighter [like this](https://github.com/willmcgugan/rich/blob/master/examples/highlighter.py)
> 
> For your use case you could do:
> 
> ```python
> from rich.console import Console
> from rich.highlighter import RegexHighlighter
> from rich.theme import Theme
> 
> 
> class EmailHighlighter(RegexHighlighter):
>     """Apply style to anything that looks like an email."""
> 
>     base_style = "example."
>     highlights = [r"(?P<email>[\w-]+@([\w-]+\.)+[\w-]+)"]
> 
> 
> theme = Theme({"example.email": "yellow"})
> console = Console(highlighter=EmailHighlighter(), theme=theme)
> 
> console.print("Send funds to money@example.org")
> ```

Thanks but it does not work for `provider_email=user.here@gmail.com` 

I am seeing as:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/18537398/133896096-027c0af0-decc-4491-96f3-ab23e7abbc5a.png">

**Comment by yashrathi-git** [comment]
@avatar-lavventura You could simply modify the regex
```py
from rich.console import Console
from rich.highlighter import RegexHighlighter
from rich.theme import Theme


class EmailHighlighter(RegexHighlighter):
    """Apply style to anything that looks like an email."""

    base_style = "example."
    highlights = [r"(?P<email>[-\w\.]+@([\w-]+\.)+[\w-]+)"]


theme = Theme({"example.email": "bold u yellow"})
console = Console(highlighter=EmailHighlighter(), theme=theme)

console.print("provider_email=user.here@gmail.com")
```
You could also just use something like:
```py
console.print('provider = [yellow]user.here@gmail.com')
```
