### ISSUE TITLE
Add rich.__version__

### ISSUE THREAD

**Issue by wookayin** [willmcgugan/rich#15]
`rich` should have `__version__` property.

```
AttributeError: module 'rich' has no attribute '__version__'
```

This is a common python convention to tell package version easily.

**Comment by willmcgugan** [comment]
I use poetry to do packaging, which recommends `pkg_resources` to get the version from meta data. They initially recommended dropping `__version__` entirely. Fortunately there some to be some [movement](https://github.com/python-poetry/poetry/issues/144) on that front, and we may get `__version__` back.

**Comment by wookayin** [comment]
Thanks for the feedback. But why is it closed (it's still unimplemented)? Even though poetry is used, we could add this property with a workaround.

**Comment by willmcgugan** [comment]
Keeping the version in two places is problematic. But if poetry hasn't got a solution when I release a 1.0 version, that's what I might have to do. In the meantime, the lack of a `__version__` isn't going to break anything that I know of, and `pkg_resources.get_distribution("rich").version` can be used to get the version.

**Comment by thebigmunch** [comment]
Just a note. For Python 3.8+, [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html) should probably be used instead. And the [importlib_metadata](https://pypi.org/project/importlib-metadata/) backaport exists for other Python 3 versions. It was created to replace pkgresources metadata functionality.

[Here's](https://github.com/thebigmunch/audio-metadata/blob/master/src/audio_metadata/__about__.py) how I use it to deduplicate my package metadata. I use poetry, too, and I couldn't wait any longer. I already had that module and was manually updating it.

**Comment by willmcgugan** [comment]
I may end up doing something similar...

**Comment by LewisGaul** [comment]
> Thanks for the feedback. But why is it closed (it's still unimplemented)? Even though poetry is used, we could add this property with a workaround.

Still seems to missing `__version__`, if the intention was for it to be added by v1.0 then perhaps this issue should have been left open...

**Comment by willmcgugan** [comment]
Don't know where you got that idea from.

**Comment by LewisGaul** [comment]
I didn't mean to sound adversarial! It was your message above that gave me this impression:

> Keeping the version in two places is problematic. But if poetry hasn't got a solution when I release a 1.0 version, that's what I might have to do.

Personally I agree with the OP that it's pretty standard to provide this, but it's up to you of course.

**Comment by willmcgugan** [comment]
It *was* a standard of sorts, but now importlib is recommended, and `__version__` is a convenience.

Unless poetry has an answer to this that doesn't require a backport of importlib, I'm afraid there is no motivation to change it.
