### ISSUE TITLE
[help] How can I write my output into a file while keeping color

### ISSUE THREAD

**Issue by avatar-lavventura** [willmcgugan/rich#1501]
Is it possible to write our output into a file while keeping the color. And when we do `less -R` see it with color?

I have tried following:

```
from rich.console import Console
from datetime import datetime

with open("report.txt", "wt") as report_file:
    console = Console(file=report_file)
    console.rule(f"Report Generated {datetime.now().ctime()}")
    console.print("[blue]hello[/blue]")
    console.file.write("[blue]hello[/blue]")
```

but `hello` is written without color into the `report.txt` file.

-------

When I try `console.file.write("[blue]hello[/blue]")` 

screenshot for `cat report.txt | less -R`:

<img width="354" alt="image" src="https://user-images.githubusercontent.com/18537398/133898064-1e77fc73-bce1-4b6a-a307-b167413dec94.png">

**Comment by willmcgugan** [comment]
Please see https://rich.readthedocs.io/en/latest/console.html#terminal-detection

**Comment by avatar-lavventura** [comment]
@willmcgugan Thanks making `console = Console(file=report_file, force_terminal=True)` solved my issue.

But for each write operation are we required to do following operations:

```
with open("report.txt", "wt") as report_file:
    console = Console(file=report_file, force_terminal=True )
```

------


When I try:

```
console = Console(file="doo", force_terminal=True)
console.file.write("[blue]hello[/blue]")
```

I am having following error: `AttributeError: 'str' object has no attribute 'write'`

**Comment by willmcgugan** [comment]
Either works. Create a single Console for as long as you need to write to the file.

**Comment by avatar-lavventura** [comment]
I will write into the same file as long as the my daemon program runs. I am not sure would it be overkill to create `Console` when ever my print wrapper function is called.

Should I create single `Console` when the  script starts running (I believe file should remains open) or create `Console` whenever print is called that.

**Comment by willmcgugan** [comment]
Single Console is generally better.
