### ISSUE TITLE
[BUG] Rich suppresses next output, randomly

### ISSUE THREAD

**Issue by FallenSpaces** [willmcgugan/rich#1502]
**Describe the bug**

Sometimes output will be ignore when printing using rich.console print. It happens very randomly, as seen when I restart my program without changes, multiple times. 

Now, the bug affects the newline I need right before my input() prompt.

Edit: I forgot earlier, but this can happen to entire outputs. For instance, when using (unmodified) RichHandler for logging, the same thing I'm describing will suppress an entire log statement.

This makes debugging a huge pain, because I have to restart the program multiple times to make sure that a change I made worked, since I'm constantly worrying if the issue is Rich suppressing something. 

Sometimes I'll restart 6 times, and an output only renders 2 out of those times, even though nothing has changed.

**To Reproduce**

```
utils.py:

def query(): return input("\n>>> ")

main.py:

console.print("Hi, what's up?")
utils.query()

```

Run 1:

```
Hi, what's up?
>>>
```

Run 2:

```
Hi, what's up?

>>>
```

**Platform**

Windows 10, CMDer (Also happens in win CMD)

**Diagnose**
```
┌──────────────── <class 'rich.console.Console'> ────────────────┐
│ A high level console interface.                                │
│                                                                │
│ ┌────────────────────────────────────────────────────────────┐ │
│ │ <console width=66 ColorSystem.WINDOWS>                     │ │
│ └────────────────────────────────────────────────────────────┘ │
│                                                                │
│     color_system = 'windows'                                   │
│         encoding = 'utf-8'                                     │
│             file = <colorama.ansitowin32.StreamWrapper object  │
│                    at 0x0000024C969A6400>                      │
│           height = 60                                          │
│    is_alt_screen = False                                       │
│ is_dumb_terminal = False                                       │
│   is_interactive = True                                        │
│       is_jupyter = False                                       │
│      is_terminal = True                                        │
│   legacy_windows = True                                        │
│         no_color = False                                       │
│          options = ConsoleOptions(                             │
│                        size=ConsoleDimensions(width=66,        │
│                    height=60),                                 │
│                        legacy_windows=True,                    │
│                        min_width=1,                            │
│                        max_width=66,                           │
│                        is_terminal=True,                       │
│                        encoding='utf-8',                       │
│                        max_height=60,                          │
│                        justify=None,                           │
│                        overflow=None,                          │
│                        no_wrap=False,                          │
│                        highlight=None,                         │
│                        markup=None,                            │
│                        height=None                             │
│                    )                                           │
│            quiet = False                                       │
│           record = False                                       │
│         safe_box = True                                        │
│             size = ConsoleDimensions(width=66, height=60)      │
│        soft_wrap = False                                       │
│           stderr = False                                       │
│            style = None                                        │
│         tab_size = 8                                           │
│            width = 66                                          │
└────────────────────────────────────────────────────────────────┘

WindowsConsoleFeatures(vt=False, truecolor=False)

rich @ file:///D:/bld/rich_1631970325879/work
```

It's weird that it shows rich on D: drive? I don't have anything connected as D:

**Comment by willmcgugan** [comment]
There is clearly more code running than given above so I would suspect that the issues isn't with Rich.

If you can give me a working example that reproduces the problem, I'll take another look.

**Comment by FallenSpaces** [comment]
> There is clearly more code running than given above so I would suspect that the issues isn't with Rich.

Rich was my first guess because it renders everything I put on the screen. But now I'm remembering (I just came back to this project) that I get errors similar to this: I am running a regex search, but getting a TypeError complaining about the input still being an integer, even though the function is only taking a 1, and using str(input) before the regex call.

I can run this multiple times, with nothing changing. Half the time, it works perfectly, but the other half will throw the error. Just like the print statements randomly not printing. I don't understand if it's a memory issue, or what. Like, can my program just "lose" a variable because of memory overflow/shenanigan's from the last run? Can a program jumble variables between seemingly identical back to back runs?

Anyways, it's a lot of code, and this happens very randomly, so I'll start with turning Rich prints into regular prints. If it stops happening after that, I'll report that here, and probably switch to another styling package, because this is over my head and I have no idea how to debug an issue like this.

Sorry if I'm over explaining things!

**Comment by FallenSpaces** [comment]
Thank you for your time and this awesome package. 

Apparently the problem was happening because of packages and imports. I have to rebuild & reinstall my package before I make changes to bugfix. That still doesn't explain why it's switching between installed code, and local repo code though smh. 

Either way, this probably explains the missing newline too. Thanks again
