### ISSUE TITLE
Suggestions: show not only the percentage, but also the number of completed tasks

### ISSUE THREAD

**Issue by yumere** [willmcgugan/rich#151]
I appreciated that you create this library. This library is very easy to use and has a beautiful console style. I love it.

**BTW, I ask you to add a little functionality to the `track` function in progress. (Of course, the `track` function is awesome!)**

I'm a research engineer and generally train deep learning models. So I would like to know how many steps have progressed in the current epoch, not a percentage because of the number of checkpoints.

When I try to add the text that shows current steps, I must define a new class that inherits from `ProgressColumn`, and create `Progress` instance as same to the `track` function.

![image](https://user-images.githubusercontent.com/3658421/87108486-6944ec00-c29d-11ea-96ae-4ac8bcfc7b8f.png)

Thank you for your attention to this suggestion.

**Comment by willmcgugan** [comment]
Hi @yumere 

You don't need to define a new `ProgressColumn` for this. You can do this:

```python
progress = Progress(BarColumn(), "[magenta]{task.completed} of {task.total}")
for i in progress.track(range(123)):
    time.sleep(0.1)
```

Does that work for you?

**Comment by yumere** [comment]
Oh... Very thank you for your reply.
