### ISSUE TITLE
[BUG] Table word wrap doesn't seem to work in the output of Jenkins console, limted to 80 chars

### ISSUE THREAD

**Issue by MiMiMeowMeow** [willmcgugan/rich#1518]
**Read the docs**
You might find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) -- consider using the search function there.

**Describe the bug**
Using rich tables in a build script.   The output of some text get cutoff when I expected it to wrap.  It renders the � character.

+-----------------------------------------------------------------------------+
| PYTHON DETAILS     | PATH                                                   |
|--------------------+--------------------------------------------------------|
| PYTHON_PATH        | C:\Users\jenkins\AppData\Local\pypoetry\Cache\virtual� |
| PYTHON_SCRIPT_PATH | C:\Users\jenkins\AppData\Local\pypoetry\Cache\virtual� |
| PYTHON_EXE_PATH    | C:\Users\jenkins\AppData\Local\pypoetry\Cache\virtual� |
+-----------------------------------------------------------------------------+

There's other text that exceeds the 80 character writen from other fuctions in the script, but the output of rich seems limited to 80.

**Reproduce/Platform**
Jenkins cosole output.  Jenkin server running linux, job running on a Windows 10 node, powershell core script.  There's other text that seems to exceed the 80 character limit but the output of rich seems limited to 80.

**Diagnose**

rich (10.10.0)
+---------------------- <class 'rich.console.Console'> -----------------------+
| A high level console interface.                                             |
|                                                                             |
| +-------------------------------------------------------------------------+ |
| | <console width=79 None>                                                 | |
| +-------------------------------------------------------------------------+ |
|                                                                             |
|     color_system = None                                                     |
|         encoding = 'cp1252'                                                 |
|             file = <_io.TextIOWrapper name='<stdout>' mode='w'              |
|                    encoding='cp1252'>                                       |
|           height = 24                                                       |
|    is_alt_screen = False                                                    |
| is_dumb_terminal = False                                                    |
|   is_interactive = False                                                    |
|       is_jupyter = False                                                    |
|      is_terminal = False                                                    |
|   legacy_windows = True                                                     |
|         no_color = False                                                    |
|          options = ConsoleOptions(                                          |
|                        size=ConsoleDimensions(width=79, height=24),         |
|                        legacy_windows=True,                                 |
|                        min_width=1,                                         |
|                        max_width=79,                                        |
|                        is_terminal=False,                                   |
|                        encoding='cp1252',                                   |
|                        max_height=24,                                       |
|                        justify=None,                                        |
|                        overflow=None,                                       |
|                        no_wrap=False,                                       |
|                        highlight=None,                                      |
|                        markup=None,                                         |
|                        height=None                                          |
|                    )                                                        |
|            quiet = False                                                    |
|           record = False                                                    |
|         safe_box = True                                                     |
|             size = ConsoleDimensions(width=79, height=24)                   |
|        soft_wrap = False                                                    |
|           stderr = False                                                    |
|            style = None                                                     |
|         tab_size = 8                                                        |
|            width = 79                                                       |
+-----------------------------------------------------------------------------+

**Comment by willmcgugan** [comment]
Have you got `overflow="ellipsis"` in your code? I suspect the � character may be the result of the ellipsis not encoding on to cp1252, you might want to set it to "fold" or "crop".

Re the terminal width, there is no way for Rich to detect the width when not running from a real terminal. You can set it on the Console, or set the COLUMNS env var.

**Comment by MiMiMeowMeow** [comment]
Okay, it was fixed with overflow='fold' when calling add_column from the table object.
I just thought 'fold' was the default. I think you can close this issue.  Thanks for you help and creating such an awesome libary!
