### ISSUE TITLE
[REQUEST] Emphasize the compatible Python versions - Good First Issue

### ISSUE THREAD

**Issue by YahelB05** [willmcgugan/rich#1520]
**How would it improve Rich?**
- Update the demo pictures to the latest Python version terminal.
- **Emphasize** more in the 'Compatibility' section that the range of compatible python versions is 'Python 3.6.1 and above'.

**What problem does it solve for you?**
It clarifies and makes it easy to see what compatible python versions are sufficient.
This simple update could have helped me, might help others, and might not - but why not try :)

Happy Coding 👍

**Comment by willmcgugan** [comment]
How would you emphasize it?

**Comment by neutrinoceros** [comment]
Here's a usable shield badge
[![Supported Python Versions](https://img.shields.io/pypi/pyversions/rich/10.11.0)](https://pypi.org/project/rich/)
```markdown
[![Supported Python Versions](https://img.shields.io/pypi/pyversions/rich/10.11.0)](https://pypi.org/project/rich/)
```

**Comment by willmcgugan** [comment]
<img width="810" alt="Screen Shot 2021-09-24 at 13 56 55" src="https://user-images.githubusercontent.com/554369/134677819-e3a1f4e6-e222-45a3-a69c-4902ab36bddc.png">

**Comment by YahelB05** [comment]
@willmcgugan & @neutrinoceros - You are right!
Didn't see that, hope that others will see it atleast...

Have a good day 👍 :)

**Comment by neutrinoceros** [comment]
@willmcgugan just added it upon your request, no wonder you didn't see it prior to opening an issue. Anyway, thanks Will, keep it up :)
