### ISSUE TITLE
[QUESTION] Unstable live table rendering for large renderable

### ISSUE THREAD

**Issue by Justaus3r** [willmcgugan/rich#1521]
#### Describe the issue:
I am using ``psutil`` to get all the user processes and display them in a table using rich.displaying all the processes statically works perfectly fine,the problem is only when i use Live Display to show the table dynamically.since all the processes cannot be shown on the terminal at once, the table gets bigger than the screen.usually rich will show ellipsis in this case,but i want all of the renderable to be shown so i am passing ``vertical_overflow="visible"`` to Live(). while this does display the table,the problem is when i use my mouse to scroll up,everything messes-up.mostly it shows me the table rendered previously and sometimes a blank screen.from the documentation it seems like while using this argument,the screen won't be cleared properly,so it doesn't seem to be a bug.is there a work around for this?

<details>
<summary>Minimal reproducing example(mostly from docs)</summary>
<br>

```python
import random
import time

from rich.live import Live
from rich.table import Table


def generate_table() -> Table:
    """Make a new table."""
    table = Table()
    table.add_column("ID")
    table.add_column("Value")
    table.add_column("Status")

    for row in range(1,100):
        value = random.random() * 100
        table.add_row(
            f"{row}", f"{value:3.2f}", "[red]ERROR" if value < 50 else "[green]SUCCESS"
        )
    return table
with Live(generate_table(), refresh_per_second=4,vertical_overflow="visible") as live:
    while True:
        time.sleep(0.4)
        live.update(generate_table())
```

</details>

#### Os/Terminal:
I am using Pop_Os! and terminal is Gnome 3.36.2.haven't checked if this problem also persists on windows.

**Comment by willmcgugan** [comment]
There's no way around it using Live. If you want to have a scrolling window containing your table, you could use RIch's sister project, Textual.

**Comment by Justaus3r** [comment]
> There's no way around it using Live. If you want to have a scrolling window containing your table, you could use RIch's sister project, Textual.

I see thanks.i am thinking about it,tho documentation for textual is very scarce and as of now it doesn't seem to be supporting windows yet and i wanted a cross-platform solution .well thanks anyway .i check it out!.
