### ISSUE TITLE
pyright: "Table" is not exported from module "rich.table"

### ISSUE THREAD

**Issue by nschloe** [willmcgugan/rich#1523]
Running [pyright](https://github.com/microsoft/pyright) 1.1.172 on
```
from rich.table import Table
```
gives
```
/tmp/b.py:1:24 - error: "Table" is not exported from module "rich.table" (reportPrivateImportUsage)
```

**Comment by lovetox** [comment]
What version of pyright are you using? There have been changes to this specific check in pyright recently

**Comment by nschloe** [comment]
pyright 1.1.169

**Comment by willmcgugan** [comment]
I suspect that may be because of the code in the main block, which imports Table. I don’t think it’s a real error to be concerned about, but I’ll see if there is a workaround.

**Comment by lovetox** [comment]
I looked into this longer than i would have liked.
The check is very new. The solution could be to import it like this

`from rich.table import Table as Table`

its called a redundant alias and it signals pyright that this symbol has to be re-exported ..

though i don’t really understand the reasoning behind it, and because this check is a few weeks old its not out of the question that this is a pyright bug.

**Comment by chan-vince** [comment]
I also see what I think is the same issue, but in pylance:

```
{
	"resource": "/path/to/source.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "reportPrivateImportUsage",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 8,
	"message": "\"Table\" is not exported from module \"rich.table\"",
	"source": "Pylance",
	"startLineNumber": 8,
	"startColumn": 24,
	"endLineNumber": 8,
	"endColumn": 29
}
```

**Comment by GBeauregard** [comment]
I get a similar issue with Live: `/home/gregory/Documents/projects/pyffstream/src/pyffstream/cli.py:486:24 - error: "Live" is not exported from module "rich.box.live" (reportPrivateImportUsage)`

**Comment by Akopov4** [comment]
I saw this issue again
versions of rich and pyright below

```
Name: rich
Version: 10.7.0


Name: pyright
Version: 1.1.408

```

**Comment by Akopov4** [comment]
@willmcgugan see above

**Comment by TomJGooding** [comment]
@Akopov4 Looks like you need to update rich - v10.7.0 was back in Aug 2021!
