### ISSUE TITLE
[BUG] Table borders include strange replacement characters which cause misalignment

### ISSUE THREAD

**Issue by mattaustin** [willmcgugan/rich#1527]
**Describe the bug**
When rendering certain tables, extra characters are sometimes shown which causes misalignment of the table borders.

**To Reproduce**
The `python -m rich.diagnose` command can be run to show this problem (screenshot below).

**Platform**
Linux (Docker, Ubuntu 20.04LTS with --tty --interactive switches and bash terminal) on Ubuntu 20.04 host. Using gnome-terminal or terminal from within vscode (same result).

**Diagnose**

```
python -m rich.diagnose
```
![image](https://user-images.githubusercontent.com/426026/135012462-c52c8e06-3233-414c-bfed-6189859cfcfa.png)

```
python -m rich._windows
```
![image](https://user-images.githubusercontent.com/426026/135012499-7156f614-c2cd-4b9f-996b-191c9fc636ac.png)

```
pip freeze | grep rich
```
![image](https://user-images.githubusercontent.com/426026/135012534-e2f5aa3a-d9c2-45e8-a82e-09e6021cee43.png)

```
locale
```
```
user@e4576850d59b:/opt/project$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=C.UTF-8
```

**Comment by mattaustin** [comment]
With a wider terminal, the characters causing misalignment appear in a different place:
![image](https://user-images.githubusercontent.com/426026/135013248-2c258e41-cff3-45dc-9c5e-8fd362e0bd15.png)

**Comment by willmcgugan** [comment]
I suspected this is Docker related. Those type of errors occur when Unicode is chopped in the middle of a codepoint. They are almost certainly not in the output generated by Rich.

Could you try piping the output to a file then catting that file. You may find that there are no errors in the file, but they appear when written to the terminal.

**Comment by mattaustin** [comment]
Thanks for the tip - indeed it does look like an issue with Docker, sorry for reporting here.

If I write the output to a file and cat the file from within Docker I still see the characters and misalignment. If I cat the file from outside Docker, all is fine.

I'll close the issue.
