### ISSUE TITLE
Plugin request

### ISSUE THREAD

**Issue by cansarigol** [willmcgugan/rich#153]
I've created a repository with rich library. I was wondering if it is possible to include it into the rich's doc as a plugin? 

https://github.com/cansarigol/pdbr

**Comment by willmcgugan** [comment]
Hi @cansarigol 

Not sure what you mean re a plugin? Do you mean add it to the Rich repos? I'd rather not add any code I don't maintain myself.

I could keep a "projects using rich" document and link to it in the readme. How does that sound?

**Comment by cansarigol** [comment]
Hi, @willmcgugan I thought like that [PR](https://github.com/willmcgugan/rich/pull/154) when I opened this issue but "projects using rich" is great.

**Comment by willmcgugan** [comment]
Ok, I'll add that soon.

btw you might want to submit pdbr to Hacker News under "Show HN".

**Comment by cansarigol** [comment]
Thanks for the advice, I submitted a Show HN entry.

**Comment by cansarigol** [comment]
Hi @willmcgugan Do you need a PR about "projects using rich" or Will you include it into the document?

**Comment by willmcgugan** [comment]
Been debating where it should go. How about a list at the end of the Readme ?

**Comment by cansarigol** [comment]
Sure, Readme also looks good. it's up to you, I just wanted to remind you.

**Comment by willmcgugan** [comment]
Added pdbr to the [readme](https://github.com/willmcgugan/rich#project-using-rich)
