### ISSUE TITLE
[BUG] emoji alignment issues with different terminals (vscode vs gnome terminal vs kitty)

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [willmcgugan/rich#1541]
while checking out how well different terminals mnage things, i took note of the fact that different emoji are decomposed/composed differently
and the terminal with of them is not necessarily correct for the "rendered well cases

i ran experiments with gnome terminal, kitty and vs code

kitty has the best rendering, but suffers from slowly growing displacement

it may be a necessary evil too explicitly set cursor placement after cells with emoji to ensure its in place for most terminals

![gnome-term-fedora-34](https://user-images.githubusercontent.com/156838/135759687-6d6f2932-c81a-4421-a5e7-b0a919c7cbee.png)

![kitty](https://user-images.githubusercontent.com/156838/135759689-1e59f075-ec28-4800-b58e-b8656ddc05a7.png)

![vscode](https://user-images.githubusercontent.com/156838/135759690-9a28fdca-578f-4246-87ab-55192a3dd43a.png)

**Comment by willmcgugan** [comment]
Would you mind searching the issues for emoji alignment. If I ever write a FAQ, this will be the first question I do. Short story is that there is no way to know how a terminal will render a emoji.

**Comment by amirouche** [comment]
Thanks :-)
