### ISSUE TITLE
[Consult] Progress bars style depending on the terminal

### ISSUE THREAD

**Issue by vergelli** [willmcgugan/rich#1568]
Hello there, sorry if this is repeated but I didn't find anything close on a quick search.

Ok, so this may not be related to Rich, in that case, sorry in advance, but maybe you can give me an insight of where to look at.

_os: w10_
I found I have, different progress bars styles, depending on the terminal I'm running.
**How?** like this:

On the Visual Studio Code's terminal, the progress bars look like this:

(On progress):
![progress_bars3](https://user-images.githubusercontent.com/21988764/136945686-e05313be-d168-4d98-aeed-e74b777b967e.jpg)

(Complete):
![progress_bars2](https://user-images.githubusercontent.com/21988764/136945812-ba620b19-45f8-4897-9ae7-a3ca3364bf7f.jpg)

While in the CMD or PowerShell it looks like this:

(On progress):
![progress_bars4](https://user-images.githubusercontent.com/21988764/136946151-a6d968ed-9c2b-4dbc-98c8-6da61465ffe3.jpg)

(Complete):
![progress_bars1](https://user-images.githubusercontent.com/21988764/136946078-75349161-0728-4fcd-ab00-18d69d94f923.jpg)

Now, I'd like to know, where do these changes lie. The Terminal configuration? a VSC Feature? 
Rich?

Thank you and sorry in Advance again

Regards

**Comment by willmcgugan** [comment]
Rich will detect the encoding on the system it runs on. For CMD the unicode characters for the bars aren't supported, so it defaults to the less pretty ascii versions.

If you use the new Windows Terminal you will get the nicer looking progress bars.
