### ISSUE TITLE
Issues with table wrapping

### ISSUE THREAD

**Issue by AcidWeb** [willmcgugan/rich#157]
Not sure if it is a bug or expected behavior for version 3.3.0 and fact that ratio/flexible feature is undocumented is not helping.

I have table with three columns. All three using default settings + `no_wrap=True` as I want them always to occupy a single line.
There is scenario where column B is so wide that even with overflow column A have width 0 and it barely reacting to `width` argument.

This is my dream configuration. It is even achievable with this library?
Column A - No wrap. No overflow. Always display entire content.
Column B - No wrap. Overflow. Let it take most of the space.
Column C - No wrap. Overflow only if B is really, really wide.

**Comment by willmcgugan** [comment]
Column.no_wrap prevents wrapping by not allowing the column to shrink to a point that would require contents to wrap. If you set *every* column to `no_wrap` you haven't given Rich any way of shrinking the table. As a last resort, Rich will reduce the columns evenly.

I think you may have a misunderstanding of the overflow concept. Perhaps mock up what you expect to happen.

You will need at least one column that Rich can reduce. You can set `no_wrap=True` on a Text instance to prevent it from wrapping even if the cell is smaller than the optimal width. This may be closer to what you are looking for.

```python
from rich.text import Text
from rich.console import Console
from rich.table import Table

console = Console()

table = Table()
table.add_column("Column A", no_wrap=True)
table.add_column("Column B")
table.add_column("Column C")
table.add_row("Foo "*20, Text("Bar "*20, no_wrap=True), Text("Baz " * 10, no_wrap=True))

console.print(table)
```

**Comment by AcidWeb** [comment]
Thank you for explanations. Yes - moving `no_wrap=True` to `add_row` was solution for my problem.
