### ISSUE TITLE
[Question][Markdown] Why are double hyphens replaced with en-dash even in code blocks?

### ISSUE THREAD

**Issue by jpfeuffer** [willmcgugan/rich#158]
Hi!

The following line was a bit surprising to me since I somehow expected pure commonmark.
https://github.com/willmcgugan/rich/blob/master/rich/markdown.py#L103
Is this documented somewhere?

Anyway, I would be fine with this rule, if it would not be applied in code blocks.
I was trying to document the help of a command-line tool with parameters like
```
--foo
--bar
```

but unfortunately failed.

<img width="252" alt="Bildschirmfoto 2020-07-13 um 14 16 28" src="https://user-images.githubusercontent.com/8102638/87303451-7cf98800-c513-11ea-9011-c0706e08c5ca.png">

Can I opt-out of this custom rule somehow?

**Comment by willmcgugan** [comment]
That line may have been a mistake. I'll consider removing it or making it off by default in the next release.

**Comment by jpfeuffer** [comment]
Great. Thanks for the quick reply.

**Comment by willmcgugan** [comment]
I've removed the text replacements in v3.3.1
