### ISSUE TITLE
rich.traceback -- do not wrap long lines

### ISSUE THREAD

**Issue by wookayin** [willmcgugan/rich#16]
`rich.traceback` makes stacktrace nicer but it wraps everything in 80 characters.

For example, see a screenshot in your blog post -- https://www.willmcgugan.com/blog/tech/post/better-python-tracebacks-with-rich/.

```
Traceback (most recent call last):
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│ File                                                                                             │
│"/home/USERNAME/.miniconda3/envs/longer-paths-for-reasons/lib/python3.7/site-packages/numpy/core/f│
│line 1477, in squeeze                                                                             │
    (... omitted)
│
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

As it truncates the full stacktrace line at certain characters, it becomes inconvenient for users to see which file to look at. I suggest we should not wrap them inside a box.

**Comment by willmcgugan** [comment]
It's the width of the code or the width of the terminal that defines how much space is used for the traceback (whichever is smaller). To make the traceback wider so it doesn't wrap, set `width` to your desired value, or set it to `None` to use all available width. See [traceback docs](https://rich.readthedocs.io/en/latest/reference/traceback.html#rich.traceback.install).

**Comment by wookayin** [comment]
Thanks. The `width=None` option works for me. Is there any option to disable drawing box as well?

**Comment by wookayin** [comment]
However, with `width=None` log messages are still truncated at the terminal width. I think there should be a way (i) to disable boxes or (ii) to print the whole line wrapped and continued on the next line.
