### ISSUE TITLE
[BUG] unnecessary line breaks added in the output on windows

### ISSUE THREAD

**Issue by carlodri** [willmcgugan/rich#1617]
**Describe the bug**
It seems like `rich` is adding unnecessary line break in the output. The following is an extract of `python -m rich`:

![image](https://user-images.githubusercontent.com/5230366/138055191-57fde6ad-e519-472d-9c21-c139bb35578a.png)

If I slightly enlarge the terminal window, the output goes into place correctly and the additional lines disappear:
![image](https://user-images.githubusercontent.com/5230366/138056014-c0bdf4c6-e850-4372-9d6f-3bf3fa0d9eee.png)

**To Reproduce**
I'm using [cmder](https://cmder.net/) as a terminal on windows.

```python
python -m rich
```

**Platform**
Win10

**Diagnose**
I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

```
python -m rich.diagnose
python -m rich._windows
pip freeze | grep rich
```
![image](https://user-images.githubusercontent.com/5230366/138055315-c06b37ee-07a6-439c-8fff-b58846a7e0ec.png)

![image](https://user-images.githubusercontent.com/5230366/138055411-ecd93e9a-a456-4aa7-993b-783c363296b5.png)

This is the output of `conda list | grep rich` (I'm using conda, not pip):
![image](https://user-images.githubusercontent.com/5230366/138055650-d0d590d7-0a5f-4db6-beb0-dc622987bd9a.png)

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by willmcgugan** [comment]
Please try 10.13.0

**Comment by carlodri** [comment]
same happens with 10.13.0.

An excerpt from `python -m rich.progress`:

![image](https://user-images.githubusercontent.com/89844771/140727465-611ea61e-3728-4066-8f90-f200e4d46846.png)
