### ISSUE TITLE
Console.print with f-strings featuring variables containing a list do not print the list

### ISSUE THREAD

**Issue by nmstoker** [willmcgugan/rich#162]
**Describe the bug**
When using Console.print with an f-string featuring variables containing a list, the list does not get printed (but other non-list content from the variable is correctly printed).  It does not occur with a regular print.

**To Reproduce**

````python
from rich.console import Console
console = Console()
results = {'result1':'something', 'result2':[1,2,3]}
print(f'Comment {results}') # this works as expected
# outputs: Comment {'result1': 'something', 'result2': [1, 2, 3]}
console.print(f'Comment {results}') # this nicely colours the structure but it has lost the list
# outputs: Comment {'result1': 'something', 'result2': }
````

**Platform**
Arch Linux on x86_64
Terminal software: Konsole version 20.04.3
Python version: 3.7.6
Rich version: 3.3.2

This is hardly the most critical of issues, and there's an easy work around (`console.print(f'Comment ', results, end='')`) but as it is easy to miss, it might catch some people out if they're not aware of it.

**Comment by willmcgugan** [comment]
Anything in square brackets is interpreted as console markup, see https://rich.readthedocs.io/en/latest/markup.html which has information on how to disable / escape markup.

**Comment by willmcgugan** [comment]
This isn't a bug per se, but perhaps something that could be elaborated on in the docs. Any suggestions how to clarify in the documentation would be welcome.

**Comment by nmstoker** [comment]
Thanks for the explanation.

I had suspected it was something along those lines and did look through the (*excellent*) docs but unfortunately I wasn't looking in the right sections; I'd started in the Console API section, then tried the Styles and Rich Text sections (drawing a blank; looking there seems silly now that I know where it is but seemed more reasonable at the time!).  Sorry to have taken your time, especially as the docs you pointed to specifically mention f-string issues!

It's difficult to suggest a different organisation that might help here - I think it's largely a matter of me just getting the hang of how things fit together better.  I've had a few cases where I know there's something documented and it just takes time to learn the mental model.

**Comment by willmcgugan** [comment]
There were some recent changes that you might be interested in. Rich is now a bit more clever re markup, and shouldn’t confuse lists with tags. Your original example should work without changes now.

**Comment by nmstoker** [comment]
Thanks Will, it's kind of you to mention that. I'll take a look.
