### ISSUE TITLE
[REQUEST] Demo how to work in conjunction with `loguru`

### ISSUE THREAD

**Issue by leej11** [willmcgugan/rich#163]
Have you checked the issues for a similar suggestions?
Yes

**How would you improve Rich?**

`Loguru` is kind of a wrapper around the `logging` library. I've seen in your docs that you can pass the RichHandler() to `logging` to generate "rich" logs. 

https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure

However in my current project, we are using loguru, so I'm trying to figure out how to do a similar thing (if it's even possible), to pass RichHandler() to loguru, so I can generate these rich logs that are great.

It would be great if you could explain if this is possible, and if so share how it works, perhaps appending this detail to the rich docs [here](https://rich.readthedocs.io/en/latest/logging.html).

My naive attempt at getting this to work:

```python
from loguru import logger
from rich.logging import RichHandler

logger.configure(handlers=[RichHandler()])
logger.debug("This is a debug statement")
logger.info("This is an info statement")
```

But I get fairly confused with the traceback. Hoping you may be able to enlighten me!

**What problem does it solved for you?**

It would enable me to use rich formatting on logs in conjunction with the loguru package. Perhaps other users of loguru would be interested in this as well.

**Comment by willmcgugan** [comment]
Haven't used loguru before, but I got it working with Rich. You were close, the `configure` method takes a list of dicts.

```python
from loguru import logger
from rich.logging import RichHandler

logger.configure(handlers=[{"sink":RichHandler(), "format":"{message}"}])
logger.debug("This is a debug statement")
logger.info("This is an info statement")
```

Only thing I couldn't figure out was how to change loguru date format.

**Comment by leej11** [comment]
Ah amazing. So I can copy the format argument in the configure method.

https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add

So I copied the default that loguru has in the link above. So I guess you can move around the YYYY-MM-DD to whatever date format you want?

```python
from loguru import logger
from rich.logging import RichHandler

logger.configure(handlers=[{
    "sink":RichHandler(), 
    "format":"<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
}])
logger.debug("This is a debug statement")
logger.info("This is an info statement")
```

Now this works I tried doing:
```python
logger.info("[bold red blink]Server is shutting down![/]", extra={"markup": True})
```

But it just literally prints the [bold red blink]

![image](https://user-images.githubusercontent.com/17391902/87957850-b9dff480-caa8-11ea-8de8-683a7472e0f8.png)

**Comment by willmcgugan** [comment]
The Rich handler renders date / level / file itself, which means it can format columns more nicely. But it does mean you can't configure it via the message format. 

As for markup not working, that looks like a bug in loguru. According to stdlib docs, keys in `extra` should be copied to attributes of the log record. That doesn't appear to be happening.

**Comment by remisphere** [comment]
@leej11, console markup works if you directly configure at the handler level rather than the log message, like this:
```python
from loguru import logger as log
from rich.logging import RichHandler

log.configure(handlers=[{"sink": RichHandler(markup=True),
                         "format": "{message}"}])
```

**Comment by sizhky** [comment]
Is there a way to get the function name as well?

Checkout the below image. Logger by default, clearly tells that the call is being made from `__main__:yolo:5` whereas rich logging only prints `test.py:5` which is the file name and line number
![image](https://user-images.githubusercontent.com/3656100/111473866-7b8ef800-8751-11eb-8397-81a7b9ae6af4.png)

**Comment by remisphere** [comment]
@sizhky you can change the format string:
```python
log.configure(handlers=[{"sink": RichHandler(markup=True),
                         "format": "[red]{function}[/red] {message}"}])
```
I don't know the list of all the available keywords like `function` and `message`, but a few can be found in the default of the [add method](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add).

**Comment by sizhky** [comment]
Any chance to put it as part of the file name?

![image](https://user-images.githubusercontent.com/3656100/111489706-61a8e180-8760-11eb-889b-7d3f76eca2df.png)

**Comment by remisphere** [comment]
I think this might be a subject for a new issue then, as this is not directly related to loguru,
maybe asking for something like a `log_path_format` argument in [`rich.logging.RichHandler`](https://rich.readthedocs.io/en/stable/reference/logging.html#rich.logging.RichHandler) ?

**Comment by aniketmaurya** [comment]
my logs look prettier now 🔥

**Comment by NoPlagiarism** [comment]
Seems related

https://github.com/GreyElaina/richuru/
