### ISSUE TITLE
[BUG] "clear" not recognized as an internal or external command, operable program or batch file. python rich module

### ISSUE THREAD

**Issue by Rooooopert** [willmcgugan/rich#1632]
Every time i wanna print table, it writes me:
""clear" not recognized as an internal or external command, operable program or batch file. python rich module"
![image](https://user-images.githubusercontent.com/78444980/139534086-dfd02c83-2001-48f8-a1c1-04eab5074386.png)

What can I do with that?

**Comment by willmcgugan** [comment]
I doubt this is anything to do with Rich. If this is a Windows batch file, you want `cls` not `clear`
