### ISSUE TITLE
Implement 'colspan' for tables

### ISSUE THREAD

**Issue by The-Judge** [willmcgugan/rich#164]
**How would you improve Rich?**

I am writing a script for time bookings currently, which generates tables with a simple row-setup:

```
| Clock-in | Clock-out | Duration |
|     8:00 |     10:00 |     2:00 |
```

Then, after each column, I'd like to enter another row to display the period between the current and the next record, but this one should consist of 2 fields only and maybe also has a different style (color, italics, ...), with the first two merged to match the overall column alignment:

```
| Clock-in | Clock-out | Duration |
|     8:00 |     10:00 |     2:00 |
|        PAUSE         |     0:45 |
|    10:45 |     17:00 |     6:15 |
```

Another use-case for this is, when you want to end the table with a sum-footer:

```
| Clock-in | Clock-out | Duration |
|     8:00 |     10:00 |     2:00 |
|        PAUSE         |     0:45 |
|    10:45 |     17:00 |     6:15 |
| Sum of working hours |     8:15 |
```

Maybe I am reading the docs wrong, but I couldn't find an obvious way to achieve that; tables in rich seem to be defined once and rows can only be appended from there. Yes, it is possible to enter None as a value, but this just leaves the existing cell empty and does not solve the feature for an alternate style of that rows:

```
|      Clock-in        | Clock-out | Duration |
|                 8:00 |     10:00 |     2:00 |
|                10:45 |     17:00 |     6:15 |
| Sum of working hours |           |     8:15 |
```

**What problem does it solved for you?**

This feature would make the table rendering an even greater way to produce great tables for more representation use-cases than it can serve currently.

**Comment by willmcgugan** [comment]
I think what you are asking for is like "rowspan" in HTML, where a cell extends in to neighbouring cells. Something like this?

<img width="691" alt="Screen Shot 2020-07-21 at 10 00 25" src="https://user-images.githubusercontent.com/554369/88034769-11c63c00-cb39-11ea-8f13-267201047155.png">

**Comment by The-Judge** [comment]
Hi @willmcgugan ;

exactly, when it comes to the column layout.
If something like that could be implemented, plus the possibility to define different colors, font style (bold, blue, ...) to it, that would be a 100% match for this request.

BR

**Comment by willmcgugan** [comment]
This is something I've been thinking about for a while. It's tricky to implement, but would be a nice feature. I'm hoping to get sponsorship for enhancements such as these. I'll keep this ticket open as a reminder.

**Comment by elicoten** [comment]
I think in this case it's actually the equivalent of the html `colspan` attribute.

`rowspan` is where a single cell covers multiple rows (i.e. the content extends into space where the cells below would be) as shown in the [w3schools example](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_td_rowspan).

Whilst rowspan may also be a useful addition, I'm also here in search of a feature that enables an individual cell to expand across multiple columns - i.e. it extends horizontally, in the way shown in the image in https://github.com/willmcgugan/rich/issues/164#issuecomment-661731962.

**Comment by ericsaintetienne** [comment]
Other table libraries like dashtables support `rowspan` and `colspan` semantics. This is how it's done using dashtables:
```
from dashtable import data2rst

table = [
        ["Header 1", "Header 2", "Header3", "Header 4"],
        ["row 1", "column 2", "column 3", "column 4"],
        ["row 2", "Cells span columns.", "", ""],
        ["row 3", "Cells\nspan rows.", "- Cells\n- contain\n- blocks", ""],
        ["row 4", "", "", ""]
    ]

# [Row, Column] pairs of merged cells -- zero-based indexing
span0 = [[2, 1], [2, 2], [2, 3]]
span1 = [[3, 1], [4, 1]]
span2 = [[3, 2], [3, 3], [4, 2], [4, 3]]

my_spans = [span0, span1, span2]

print(data2rst(table, spans=my_spans, use_headers=True))
```
Which outputs this:
```
+----------+------------+----------+----------+
| Header 1 | Header 2   | Header3  | Header 4 |
+==========+============+==========+==========+
| row 1    | column 2   | column 3 | column 4 |
+----------+------------+----------+----------+
| row 2    | Cells span columns.              |
+----------+------------+---------------------+
| row 3    | Cells      | - Cells             |
+----------+ span rows. | - contain           |
| row 4    |            | - blocks            |
+----------+------------+---------------------+
```

**Comment by willmcgugan** [comment]
Closing this to tidy issues, but keeping a note of it.

**Comment by ronf** [comment]
This is something I have a couple of uses for, but for my use cases right now I'd be happy to start off with just being able to request space across multiple columns in a single row, but not multiple rows. This seems like it would be simpler to implement, and might be a stepping stone toward full colspan/rowspan capabilities.

Really, all I need is a way for some cell values to grow beyond the width available to that column, overwriting vertical separators and data in neighboring columns in that row. I'm thinking one might be able to request this behavior on a table cell with a new value for "overflow". I know this wouldn't provide true colspan functionality (particularly about removing the grid separators regardless of the size of the values inside), but I can see people possibly wanting this kind of dynamic behavior in some cases as an independent feature, without setting up colspan explicitly in every place it is needed.

**Comment by teneon** [comment]
Hi there guys ;) Nice work with Rich!
Just wondering, i could use colspan (and perhaps rowspan) as well. Is it already available?
best regards,
Jim

**Comment by Abdur-rahmaanJ** [comment]
Very useful feature to have

**Comment by eric-saintetienne** [comment]
> I think what you are asking for is like "rowspan" in HTML, where a cell extends in to neighbouring cells. Something like this?
> 
> <img alt="Screen Shot 2020-07-21 at 10 00 25" width="691" src="https://user-images.githubusercontent.com/554369/88034769-11c63c00-cb39-11ea-8f13-267201047155.png">

What you're showing in the screenshot is `colspan` (not `rowspan`)

But both `rowspan` and `colspan` would be useful.

**Comment by urobasa** [comment]
I really need this feature, has anything been done or can work be started?

**Comment by brandon-fryslie** [comment]
Does anyone have recommendations on an alternate library that supports this?  I've spent a couple hours trying fake this functionality with Rich using other components but the library isn't really structured like that.  That's not a problem w/ the library in any way (IMO), since the library is meant to make hard things easy, not make every single feature possible.  But every use case outside of the most basic tables is going to need some ability to render cells that span multiple columns.

I'll spend a few more hours seeing if I can get a basic PR ready to get the functionality added to Rich itself.  If that doesn't pan out, it would be great to know of an alternative with a more fleshed out table component.

**Comment by soamicharan** [comment]
I created a python package
https://pypi.org/project/span-table/
You can use python rich markup syntaxes to render a table,

**Comment by anentropic** [comment]
> I created a python package https://pypi.org/project/span-table/ You can use python rich markup syntaxes to render a table,

thanks for this!

wish it had the width fitting behaviour of Rich though, this has no auto word wrap

or if Rich supported colspan :)
