### ISSUE TITLE
[BUG] `rich.table` documentation output example is messed up!

### ISSUE THREAD

**Issue by pybash1** [willmcgugan/rich#1645]
**Describe the bug**
The example output for the first code snippet is messed up. Maybe using an image there instead of raw output might be better.

**To Reproduce**
Visit the [`rich.table` docs](https://rich.readthedocs.io/en/stable/tables.html).

**Comment by willmcgugan** [comment]
Can you elaborate on "messed up". Screenshot pls?

**Comment by pybash1** [comment]
@willmcgugan Here it is...
![image](https://user-images.githubusercontent.com/67195650/140642132-277f748c-9ea6-4010-8a32-7333e2fffda7.png)

**Comment by willmcgugan** [comment]
For some reason your browser is not using a monospace font there. It looks fine everywhere I've tested it.

**Comment by pybash1** [comment]
Hmm ok then, thanks.
