### ISSUE TITLE
Can pprint/pretty be temporarily be disabled?

### ISSUE THREAD

**Issue by willmcgugan** [willmcgugan/rich#1646]
### Discussed in https://github.com/willmcgugan/rich/discussions/1603

<div type='discussions-op-text'>

<sup>Originally posted by **aroberge** October 16, 2021</sup>
This question came as the result of an issue [1] filed in one of my projects.

When using IPython (on its own), it is possible to toggle on and off the pretty printing.  For example, doing

```
dir(__builtins__)
In [1]: dir(__builtins__)
Out[1]:
['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
...
```
outputs names one at a time on a line.  However, after turning off the pretty printing with the magic command `%pprint`,  the display is shown without pretty formatting:
```
In [2]: %pprint
Pretty printing has been turned OFF

In [3]: dir(__builtins__)
Out[3]: ['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EnvironmentError', 'Exception', 'False', 'FileExistsError', ...
```

When using Rich with IPython, attempting to use the magic toggle `%pprint` results in a traceback.
In [4]: from rich import pretty

In [5]: pretty.install()

In [6]: %pprint
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-1efe34cfb034> in <module>
----> 1 get_ipython().run_line_magic('pprint', '')
    306         """Toggle pretty printing on/off."""
    307         ptformatter = self.shell.display_formatter.formatters['text/plain']
--> 308         ptformatter.pprint = bool(1 - ptformatter.pprint)
    309         print('Pretty printing has been turned',
    310               ['OFF','ON'][ptformatter.pprint])

AttributeError: 'BaseFormatter' object has no attribute 'pprint'
...

Looking at the source code for Rich, this is not surprising since I can see that it monkeypatches IPython's code, substituting its own pretty printer.

I am wondering if there is a way to (temporarily) disable Rich's pretty printer once it is installed.

[1] https://github.com/friendly-traceback/friendly/issues/14</div>

**Comment by willmcgugan** [comment]
@aroberge any thoughts on https://github.com/willmcgugan/rich/pull/1647 ?

**Comment by aroberge** [comment]
@willmcgugan It almost looks too simple! :-D   

I would have to try and experiment with it ... I'll see if I can do this right away.

**Comment by aroberge** [comment]
It works perfectly here!  So much simpler too.

**Comment by aroberge** [comment]
I have tested it with iPython in a terminal as well as in a Jupyter notebook and it works flawlessly.
