### ISSUE TITLE
[BUG] Right-justified text overflowing

### ISSUE THREAD

**Issue by steven-murray** [willmcgugan/rich#165]
**Describe the bug**
Using `justify='right'` on a console with smaller width than full width over-reaches the width:

![image](https://user-images.githubusercontent.com/1272030/88106430-531b1380-cb5a-11ea-8536-01b2a4bfd086.png)

**To Reproduce**
A minimal code example that reproduces the problem would be a big help if you can provide it. If the issue is visual in nature, 
consider posting a screenshot.

```python
from rich.console import Console
from rich.rule import Rule

console = Console(width=100)

console.print(Rule('A Title'))
console.print("Some normal text", end='')
console.print("right-justified", justify='right')
```
![image](https://user-images.githubusercontent.com/1272030/88106659-b147f680-cb5a-11ea-95f9-61bb44d4ba8e.png)

**Platform**
What platform (Win/Linux/Mac) are you running on? What terminal software are you using. Which version of Rich?

On Manjaro linux. Problem seen in Terminator and also the Pycharm terminal.

**Comment by steven-murray** [comment]
Hmmm, OK if I take out the left-justified text with `end=''` the right-justified text looks fine. Perhaps the calculation is not taking into account text that's already on the line?

**Comment by willmcgugan** [comment]
Yes, the print method assumes it is starting at the beginning of the line. You can print left and right justified text on the same line, by printing a table with two columns. See Table.grid which creates a table without borders.

**Comment by steven-murray** [comment]
Ah, OK. I think I don't quite understand the Table.grid solution (I can't see an example in the docs). I tried this:

```
        table = Table.grid()
        table.add_column(f"Calculated {lab}:", style="bold", justify='left')
        table.add_column(f"[[{time() - t:.2f} sec]]", style="blue", justify="right")
        console.print(table)
```

But it doesn't print anything at all?

**Comment by willmcgugan** [comment]
The first argument in `add_column` is the header, but a grid has the table header disabled. You want to add two columns then add a row. Something like this...

```python
from rich.table import Table
from rich.text import Text
from rich import print

table = Table.grid()
table.expand = True
table.add_column(style="bold")
table.add_column(style="blue", justify="right")
table.add_row("foo", "bar")
print(table)
```

**Comment by steven-murray** [comment]
Excellent, thanks! It might be useful to have this use-case in the docs
somewhere.
