### ISSUE TITLE
[BUG] Text object is styled different than  markup text 

### ISSUE THREAD

**Issue by ocurero** [willmcgugan/rich#166]
**Describe the bug**
First of all, very nice library, keep up good job!

I'm trying to convert all my code to use rich, but I hav a table that I can't style it properly. This is the code:

```
from rich.console import Console
from rich.table import Table
from rich.text import Text

console = Console()

table = Table()
table.add_column('Column1', justify='center')
table.add_row(Text('BAD', style='white on red'))
table.add_row('[white on red]GOOD[/white on red]')
table.add_row('Row', style='white on red')

console.print(table)
```

**To Reproduce**
This is how it looks. Notice that in the first row, the style is applied to the entire "cell" whereas in the second row the style is only applied to the text, leaving the padding as is :
![Sin título](https://user-images.githubusercontent.com/2606647/88194003-964eb280-cc3e-11ea-98ee-49fe247ffd9f.png)

This is how I would like it to show:
![Sin título2](https://user-images.githubusercontent.com/2606647/88194505-3573aa00-cc3f-11ea-9306-644d19b41393.png)

I would rather use Text over markup because that way the code seems more readable.

Is this a bug or I'm supposed to use markup inside a table?

Thanks!

**Platform**
Linux with Putty

**Comment by willmcgugan** [comment]
The style attribute on a Text instance is used when the text is justified (as you have observed). I guess what you want is for the style to apply to the first few characters, which is what happens when console markup is rendered.

Here's one way to do that:

```python
table.add_row(Text.assemble(("GOOD", "white on red")))
```

**Comment by willmcgugan** [comment]
It's perhaps a little verbose. I could be tempted to add the following shortcut...

```python
table.add_row(Text.styled("GOOD", "white on red"))
```

**Comment by willmcgugan** [comment]
You're in luck. I was about to release a new version and I squeezed in `Text.styled` (in 3.4.0).

**Comment by ocurero** [comment]
> Here's one way to do that:
> 
> ```python
> table.add_row(Text.assemble(("GOOD", "white on red")))
> ```

Mmm, yeah, too verbose for my taste.

> 
> It's perhaps a little verbose. I could be tempted to add the following shortcut...
> 
> ```python
> table.add_row(Text.styled("GOOD", "white on red"))
> ```

That would be super, this is much better !

Thanks!

**Comment by willmcgugan** [comment]
Give 3.4.0 a try :)
