### ISSUE TITLE
rich.progress compatibility with urlretrieve

### ISSUE THREAD

**Issue by shim94kr** [willmcgugan/rich#1663]
Hello.

I use Progress() with urlretrieve in downloading a dataset.
But, my current implementation below makes some annoying results (multiple parallel lines, not synchronizing with datasize).
I searched google to improve it, but I couldn't find any solution.

Can you tell me whether these are compatible?
It would be great if you provide me a workaround to cope with this issue!
Thank you.
```
import urllib.request
from rich.progress import Progress

task = None
progress = Progress()
def show_progress(block_num, block_size, total_size):
    global progress, task
    with progress as pbar:
        if task is None:
            task = pbar.add_task("Downloading...", total=100)

        downloaded = block_num * block_size
        if downloaded < total_size:
                pbar.update(task, advance=downloaded / total_size)
        
        if pbar.finished:
            task = None

urllib.request.urlretrieve("http://www.iro.umontreal.ca/~lisa/icml2007data/mnist_rotation_new.zip", './mnist_rot.zip', show_progress)
```

![스크린샷 2021-11-09 오후 9 25 55](https://user-images.githubusercontent.com/4125005/140924033-308cecf0-0a3d-4c5c-abd1-d11e48c886ee.png)

**Comment by willmcgugan** [comment]
You are entering and exiting the context manager every time you get data. Put the urlretrieve within the Progress context.

**Comment by shim94kr** [comment]
Awesome! I have one more question.
I manually set the total step size to 3600 to fit one hundred percent at the last moment.
Is there a way to automatically set this up?
(setting total = total size and advance = downloaded does not work either)
Thank you so much!

```
import urllib.request
from rich.progress import Progress

task = None
with Progress() as pbar:
            def show_progress(block_num, block_size, total_size):
                global task
                if task is None:
                    task = pbar.add_task("Downloading...", total=3600)

                downloaded = block_num * block_size
                if downloaded < total_size:
                        pbar.update(task, advance=downloaded / total_size)

                if pbar.finished:
                    task = None

            urllib.request.urlretrieve("http://www.iro.umontreal.ca/~lisa/icml2007data/mnist_rotation_new.zip", zip_path, show_progress)

```
