### ISSUE TITLE
[BUG] Table print is corrupted when multiple columns have no_wrap=True

### ISSUE THREAD

**Issue by akrk1986** [willmcgugan/rich#1664]
I have a table with 4 columns, first two can be wide ID, name), last two are small ints (number of x, number of y).

Code:
```
        table_no_screens = Table(title="Custom fields w/o screens or contexts")
        table_no_screens.add_column("ID", justify="right", style="cyan", no_wrap=True)
        table_no_screens.add_column("Name", style="magenta", no_wrap=True)
        table_no_screens.add_column("# of screens", style="magenta", no_wrap=True)
        table_no_screens.add_column("# of contexts", style="magenta", no_wrap=True)
...
        table_no_screens.add_row(one_field['id'], one_field['name'], f'{sc}', f'{cc}')
```

Expected Output:
```
|           ID      | Name                 | # of screens | # of contexts|
| customfield_12345 | some-long-field-name |    0         |      1       |
```
Actual output:
```
|   ID    | Name                 |  | ... |
| cust... | some-long-field-name |  |  1  |
```
If I leave the no_wrap only on the 2nd column, the table looks OK, but 2nd column has no wrap (as expected).

**Platform**
Windows, inside PyCharm or in bash shell.
![2021-11-09 15_08_27-Window](https://user-images.githubusercontent.com/6705868/140929787-b52a0247-dc34-4a8f-bc87-bf9bcab219e1.png)

**Diagnose**
```
python -m rich.diagnose
```
>> see attachment above

```
$ python -m rich._windows
platform="Windows"
WindowsConsoleFeatures(vt=False, truecolor=False)

pip freeze | grep rich
rich==10.13.0
```

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by willmcgugan** [comment]
What width are you trying to print the table?

**Comment by willmcgugan** [comment]
@ibnesayeed When you print a table, you can set `width` and  also `soft_wrap=True`.

**Comment by ibnesayeed** [comment]
Thanks @willmcgugan for the quick response. That trick sure works, but the width is not known to me in advance, unless I perform some not-so-easy calculations. I really wish there was a configuration, such as `max_width` or `fit_content` at the `Table` level.

**Comment by willmcgugan** [comment]
See rich.measure.measure_renderables

**Comment by ibnesayeed** [comment]
Well, I handled it by setting the width of the table right before rendering it, after the columns and rows were all populated. I iterated over columns and their cells instead of the original data because I was performing some transformations on the data when adding rows/cols, such as adding thousand separators, and I did not want to iterate through the data twice and perform all the transformations again to calculate the width.

```py
table.width = sum([max([len(cell) for cell in list(col.cells) + [col.header, col.footer]]) for col in table.columns]) + 3 * len(table.columns) + 1
```

That said, a configuration option to automate this would be wonderful.

**Comment by willmcgugan** [comment]
Yeah that’s not going to always work. Suggest you look in to rich.measure

**Comment by willmcgugan** [comment]
@akrk1986 I suspect your problem is that you simply trying to render a table with not enough space to display all your columns.

If that's not the case, please give me a full working example, that I can cut and paste.

**Comment by akrk1986** [comment]
Here are the first 10 entries in the dict that is later printed. I can pre-calculate the max widths of the columns (as someone mentioned in the comments), but it will require another iteration on the data before defining the table.
Also, I can accept truncation of data ('abcdefghijk' printed as 'abc...') but not printing anything (that is, truncating to empty string) is problematic.
```
key='customfield_10010', val='('Request Type', 0, 1)'
key='customfield_10012', val='('Epic Status', 0, 1)'
key='customfield_10013', val='('Epic Color', 0, 1)'
key='customfield_10016', val='('Story point estimate', 0, 1)'
key='customfield_10022', val='('Target start', 0, 1)'
key='customfield_10023', val='('Target end', 0, 1)'
key='customfield_10024', val='('[CHART] Date of First Response', 0, 1)'
key='customfield_10026', val='('uuid', 0, 0)'
key='customfield_10027', val='('Location', 0, 0)'
key='customfield_10029', val='('Approvals', 0, 1)'
```
Thanks,
Amir
