### ISSUE TITLE
[REQUEST] Why is "meta serialization" 100% required and can it be got rid of or replaced with something less dangerous than `pickle` and `marshal`? 

### ISSUE THREAD

**Issue by KOLANICH** [willmcgugan/rich#1674]
**How would you improve Rich?**

Having `rich` installed on a machine would feel more secure.

**What problem does it solve for you?**

I saw that `rich` uses dangerous modules (currently, `marshal`). For usage of such dangerous modules an enough strong justification is needed.

I saw it used for so called `meta serialization`, but I haven't found any docs describing what is it and why it is 100% needed and why `marshal` is needed for it.

**Comment by willmcgugan** [comment]
There's nothing dangerous about marshal, as long as you aren't serializing untrusted data. It's used by Textual to associate meta data with a Style.

**Comment by KOLANICH** [comment]
>as long as you aren't serializing untrusted data. 

1. I guess you mean `deserializing`.
2. How is it guarandeed that no untrust**worthy** data is deserialized? I.e. if it is stored on disk, where are the guarantees that these data cannot be substituted? Or if the blob is sent via socker, again how is it guaranteed that no untrusted processes can connect to such a socket? If it is used only internally, and never stored on disk or sent via a socket, what is the point to serialize it at all, instead of just dealing with objects?

>It's used by Textual to associate meta data with a Style.

It doesn't clarify much.

**Comment by willmcgugan** [comment]
I meant serializing. It's not stored and its not sent over a socket. Its marshalled to make arbitrary data immutable.

**Comment by KOLANICH** [comment]
Would `deepcopy` do the trick better (the data in the variable won't become immutable, but would be detacued from the original object, so if nothing changes `_meta`, it should be OK, shouldn't it)?
