### ISSUE TITLE
[REQUEST] Account for file:// URLs in the default highlighter's regexes

### ISSUE THREAD

**Issue by pradyunsg** [willmcgugan/rich#1681]
Have you checked the issues for a similar suggestions? Yup. :)

**How would you improve Rich?**

https://github.com/willmcgugan/rich/blob/1b12bb68f9a0376f3da69e372058f7af56600eed/rich/highlighter.py#L99

Include `file` scheme on this line.

**What problem does it solve for you?**

It'd make the `file://` URLs printed out by pip look better.

<img width="733" alt="Screenshot 2021-11-12 at 12 41 14" src="https://user-images.githubusercontent.com/3275593/141468826-28c999bd-1728-4c2d-be5f-f3e5e4052dc3.png">

**Did I help**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by willmcgugan** [comment]
I'll add that to the next update.

If you need it in a hurry, you could create a custom Highlighter class (based on ReprHighlighter) and pass that in to your Console instance.

**Comment by pradyunsg** [comment]
Neato! Thanks! ^>^

**Comment by willmcgugan** [comment]
That's in 10.14.0
