### ISSUE TITLE
[BUG] change of behaviour in rich 10.13 (small regression)

### ISSUE THREAD

**Issue by neutrinoceros** [willmcgugan/rich#1691]
**Describe the bug**

Seems like a change in rich 10.13 broke CI for my project https://github.com/neutrinoceros/wxc/actions
I was able to boil it down to a minimal example

**To Reproduce**

Invoking `pytest t.py`
```python
# t.py
from rich.progress import Progress

def test_transient(capsys):
    with Progress(transient=True) as progress:
        pass
    out, err = capsys.readouterr()
    assert out == ""
```
This test pass with rich from 10.7 to 10.12 but breaks on 10.13.0 (stdout now contains a single newline character instead of nothing)

**Platform**
I'm seeing this on macOS and ubuntu.

**Diagnose**
I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

```
python -m rich.diagnose
python -m rich._windows
pip freeze | grep rich
```
```
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=222 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 61                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=222, height=61),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=222,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=61,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=222, height=61)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 222                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
platform="Darwin"
WindowsConsoleFeatures(vt=False, truecolor=False)
rich==10.13.0
```

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by neutrinoceros** [comment]
bisects down to f5f67a9ebb494dd65ad3eeb3437567e9da44d559

**Comment by willmcgugan** [comment]
There is a fix for this in master. You might want to go back to 10.12.0 in the meantime.

**Comment by neutrinoceros** [comment]
I'm not sure that's right, I've run my test against the current state of the master branch and it still failed. I got another fix in. #1693, is it not correct ?

**Comment by willmcgugan** [comment]
Can you describe the bug in terms of what broke for you, other than your test failed?

Testing the output of Rich is not always a good approach for tests. The output may change depending on your CI environment.

**Comment by neutrinoceros** [comment]
> Can you describe the bug in terms of what broke for you, other than your test failed?

No. In fact I don't even see a difference in the final result when I call my application. I should probably mention at this point that my tests were written _before_ I adopted rich. The fact that they didn't break when I made the switch was one of the reason adopting was trivial, which is why I value consistency here.
Now, I can easily patch my tests if you don't think it's relevant to do it in rich itself, I imagine how hard it must be to see this kind of trivial implementation detail be considered as a regression when you're supporting thousands of other projects, and I don't mean to be annoying.

**Comment by willmcgugan** [comment]
It's cool. I think what broke your tests was that I fixed an issue where there was no newline after a progress bar when to a file, i.e. when the output is non-interactive and you don't want to render multiple progress bars. Your tests are probably testing output in non-interactive mode since running them in CI you don't have a real terminal attached.

If nothing is broken in practice and you don't mind updating tests, that might be the way to go.

**Comment by neutrinoceros** [comment]
done. Thanks for your quick replies !
