### ISSUE TITLE
[BUG] Formatting not applied in Rich 10.13.0

### ISSUE THREAD

**Issue by flamofrog** [willmcgugan/rich#1692]
**Describe the bug**
Formatting of text e.g. colours does not get applied, instead, the below output is produced. Occurs in windows CMD and PyCharm (with emulated terminal). Previous versions of rich did not have this issue e.g., version 10.0.0, after upgrading, the issue is present.

**To Reproduce**
![image](https://user-images.githubusercontent.com/16073141/141756627-e40ae72b-6b81-4c62-887e-842c3a881c10.png)

**Platform**
Windows 10/11 (Others untested)

**Comment by willmcgugan** [comment]
Unlikely to be a Rich issue. PyCharm is known to be problematic.

Please use the issue template when submitting bugs.

**Comment by flamofrog** [comment]
The issue can be replicated within the windows command line as well as PyCharm (and PowerShell). I've tried on two different computers, windows 11 & windows 10, python 3.7.4 and python 3.8, the issue is present on both.

Oddly enough, it does work in the new Windows terminal.
![comparison](https://user-images.githubusercontent.com/16073141/141761577-4e20eff3-1ff5-43a3-b288-d5a08e2a64f8.png)

Happy to provide more information if that would be of assistance.

**Comment by willmcgugan** [comment]
I can't reproduce that here. What happens if you install Rich in a fresh virtual environment?

I suspect you have some other package loaded prior to Rich which is initialising or breaking the colorama package.

**Comment by flamofrog** [comment]
Setup a new Environment and installed rich, output below;
![image](https://user-images.githubusercontent.com/16073141/141767442-5f80b6f3-4c47-4438-a44f-b439c1a7f507.png)

When downgrading to 10.12.0 in the same venv the formatting begins to work again
![image](https://user-images.githubusercontent.com/16073141/141767772-8b4c2fbf-ad8a-4646-9753-09ce68238e87.png)

![image](https://user-images.githubusercontent.com/16073141/141767828-72fc08ae-c3f2-40dc-a15b-7b862cf10efd.png)
All other package versions are unchanged
![image](https://user-images.githubusercontent.com/16073141/141767927-576fc750-2786-4855-85e2-775d39097abb.png)

**Comment by willmcgugan** [comment]
I have a possible explanation. Hopefuly there will be a fix in 10.14.0, please downgrade to 10.12.0 in the meantime.

**Comment by flamofrog** [comment]
Cheers for the help! Will downgrade as advised and await 10.14.0.
Have a great week

**Comment by s-weigand** [comment]
I have the same issue with MinGW inside ConEmu (cmder).
When running in git-bash-for-windows, without ConEmu the colors work, but the borders of the `rich.panel.Panel` get messed up (line overflow).

With `rich==10.12.0` all works fine.
Hope this helps finding the root cause and thanks for the awesome project ❤️

**Comment by willmcgugan** [comment]
Please try 10.14.0

**Comment by s-weigand** [comment]
@willmcgugan Works like a charm thanks a lot 🎉
