### ISSUE TITLE
[BUG] Please relax typing-extensions versions

### ISSUE THREAD

**Issue by asvetlov** [willmcgugan/rich#1695]
**Describe the bug**
The recent `typing-extensions` release is `4.0`. It is backward compatible, a team decided to use SemVer notation for the project.
rich is marked as compatible with `^3.7.4` which doesn't sail smoothly with other libraries.

Maybe the best solution is not pinning the top version and relay on `typing-extensions` stability.
Another option is pinning to `>=3.7.4, <5.0`.

I've tried to prepare a PR but found that `poetry lock` generates a very different lockfile than pushed on GitHub. 
So better to get help from @willmcgugan for this problem, the fix is really trivial.

A new release with relaxed dependency is very appreciated. Thanks!

**Comment by willmcgugan** [comment]
I think `>=3.7.4, <5.0` might be the way to go if they follow semver from 4.0. I'll add that to the next version.

**Comment by willmcgugan** [comment]
That's in 10.14.0

**Comment by asvetlov** [comment]
Cool! Thanks a lot!
