### ISSUE TITLE
[BUG] Printing colored strings in panels messes up the panel

### ISSUE THREAD

**Issue by Ripolak** [willmcgugan/rich#1699]
**Describe the bug**
I am attempting to catch the latest error  thrown in an IPython interactive shell and print it as part of a Rich pannel object. While any kind of normal string works great, the panel gets messed up when I try to print a colored string there.

**To Reproduce**
The following code will display the problem (required IPython to be installed):
```python
from rich import print
from rich.panel import Panel
from rich.text import Text
import IPython.core.ultratb
import sys


def print_e():
    try:
        raise Exception('Testing')
    except:
        tb = IPython.core.ultratb.VerboseTB()
        text = tb.text(*sys.exc_info())
    rich_text = Text(text)
    panel = Panel(rich_text, width=75S)
    print(panel)


print_e()
```

Here is the result I'm seeing:

![ipython](https://user-images.githubusercontent.com/26342860/142032886-c90d7b75-c1ce-4a74-93c0-c8b7f17ea04f.png)

However, if I'm attempting to simply use rich's `print` to print the result, it gets printed normally:

```python
from rich import print
from rich.panel import Panel
from rich.text import Text
import IPython.core.ultratb
import sys


def print_e():
    try:
        raise Exception('Testing')
    except:
        tb = IPython.core.ultratb.VerboseTB()
        text = tb.text(*sys.exc_info())
    rich_text = Text(text)
    print(rich_text)


print_e()
```

Result:

![image](https://user-images.githubusercontent.com/26342860/142033161-3308750d-f043-404a-a03d-5f009f8468c9.png)

I tried playing around with the Panel object's attributes but with no luck so far.

**Platform**
This happened on both WIndows 10 and Fedora Linux (34). Using IPython terminal as mentioned, but it happens on normal terminals as well.

PS: Rich is an awesome library, thank you for your hard work!

**Comment by paw-lu** [comment]
You'll need to convert the ansi to something rich can understand. One method to help with this is `rich.AnsiDecoder.decode`.

```python
from rich import print
from rich import ansi
from rich.panel import Panel
from rich.text import Text
import IPython.core.ultratb
import sys


def print_e():
    try:
        raise Exception('Testing')
    except:
        tb = IPython.core.ultratb.VerboseTB()
        decoder = ansi.AnsiDecoder()
        text = tb.text(*sys.exc_info())
        rendered_tb = decoder.decode(text)
        rich_text = Text("\n").join(rendered_tb)
    panel = Panel(rich_text, width=75)
    print(panel)



print_e()

```

<img width="553" alt="Screen Shot 2021-11-16 at 2 38 43 PM" src="https://user-images.githubusercontent.com/30049606/142078043-6523c605-018d-4520-9832-199eb421ec32.png">

**Comment by Ripolak** [comment]
> You'll need to convert the ansi to something rich can understand. One method to help with this is `rich.AnsiDecoder.decode`.
> 
> ```python
> from rich import print
> from rich import ansi
> from rich.panel import Panel
> from rich.text import Text
> import IPython.core.ultratb
> import sys
> 
> 
> def print_e():
>     try:
>         raise Exception('Testing')
>     except:
>         tb = IPython.core.ultratb.VerboseTB()
>         decoder = ansi.AnsiDecoder()
>         text = tb.text(*sys.exc_info())
>         rendered_tb = decoder.decode(text)
>         rich_text = Text("\n").join(rendered_tb)
>     panel = Panel(rich_text, width=75)
>     print(panel)
> 
> 
> 
> print_e()
> ```
> 
> <img alt="Screen Shot 2021-11-16 at 2 38 43 PM" width="553" src="https://user-images.githubusercontent.com/30049606/142078043-6523c605-018d-4520-9832-199eb421ec32.png">

That indeed solved my problem, thank you!

**Comment by willmcgugan** [comment]
Thanks for the assist @paw-lu !
