### ISSUE TITLE
[help] How can I update rule lenght when terminal width is changed?

### ISSUE THREAD

**Issue by avatar-lavventura** [willmcgugan/rich#1710]
I am using rules ([https://rich.readthedocs.io/en/latest/console.html?highlight=console.rule#rules](https://rich.readthedocs.io/en/latest/console.html?highlight=console.rule#rules)). I am iteratively printing 

<img width="742" alt="image" src="https://user-images.githubusercontent.com/18537398/142755493-cc1c77ad-692f-4296-9231-a4151cd9e232.png">

During the script is running, I expand or shorten the terminal width, hence ruler's length does not change.

```python
import time

while True:
   console.rule("test")
   time.sleep(10)   
```

Example output:

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/18537398/142755551-8f2bb94f-c3eb-4431-97d9-2c660e2d97bd.png">

During the print process, I extend the terminal width but now ruler size remains unchanged. Would it be possible to make ruler to update its length if terminal width is changed?

**Comment by willmcgugan** [comment]
Afraid not. Once something is written to the scroll buffer, there is no way to go back and change it.

**Comment by avatar-lavventura** [comment]
@willmcgugan Thanks
