### ISSUE TITLE
[BUG] Lower case string in brackets is printed as empty string

### ISSUE THREAD

**Issue by yaph** [willmcgugan/rich#1715]
I came across an unexpected behavior when trying to generate markdown links. A lower case string in brackets results in an empty string when printed.

```
In [1]: from rich import print
In [2]: print('[A]', '[a]')
[A] 

In [3]: 
```

I'm running Ubuntu Linux 21.10, Python 3.9.7 and rich 10.14.0

**Comment by willmcgugan** [comment]
The `[a]` is being interpreted as a markup tag. Please see the docs on [escaping](https://rich.readthedocs.io/en/latest/markup.html#escaping)
