### ISSUE TITLE
[Question] How to get time variables

### ISSUE THREAD

**Issue by GlenNicholls** [willmcgugan/rich#1716]
What is the recommended way of getting time variables for a progress task? I have a lot of progress bars and I would like to provide information to users about hotspots in task times. It's not too difficult to time these manually, but I'd rather just grab the start/stop/elapsed directly from rich since `Progress` already has this information.

**Comment by willmcgugan** [comment]
The Tasks aren't public, but you can get them with `progress._task[TASK_ID]`. On the Task object you will find `started`, `remaining` and `elapsed`.

**Comment by willmcgugan** [comment]
I'd accept a PR if you want to make that part of the public interface.
