### ISSUE TITLE
[BUG] the percent column is causing problems (flickering).

### ISSUE THREAD

**Issue by snooppr** [willmcgugan/rich#1721]
`"[progress.percentage]{task.percentage:>1.0f}%"`

During progress, appears (with each iteration update or auto update of progress) '_progress.percentage_' It should not be there. This issue is not present in rich 9.
Watch the animation with and without a problem.
Problem on Linux and Android (Windows did not check)

![rich 10 14](https://user-images.githubusercontent.com/61022210/143541642-89510fc6-2dc3-406a-807d-6ac9a49ffae0.gif)
Rich 10.14

![rich 9](https://user-images.githubusercontent.com/61022210/143541649-c8d345ce-ec99-4d72-9bde-f93066cad3ad.gif)
Rich 9

**Comment by willmcgugan** [comment]
I don't see that here. Can you give me a full working example that shows the issue.

**Comment by snooppr** [comment]
> I don't see that here. Can you give me a full working example that shows the issue.

This simple example reproduces the problem
```
from rich.progress import (track,BarColumn,TimeRemainingColumn,SpinnerColumn,TimeElapsedColumn,Progress)
import time
import sys
import random

if sys.platform != 'win32':
    progress = Progress(TimeElapsedColumn(), SpinnerColumn(spinner_name=random.choice(["dots", "dots12"])),
    "[progress.percentage]{task.percentage:>1.0f}%", BarColumn(bar_width=None, complete_style='cyan', finished_style='cyan bold'),
    refresh_per_second = 3.0)

with progress:
    task=[i for i in range(10)]
    task_perc = progress.add_task("", total=len(task))
    for i in task:
            progress.update(task_perc, advance=1)
            time.sleep(0.5)
            print(i)
```
rich-9.10.0 works correctly.
rich-9.10.0 bad.
