### ISSUE TITLE
[help] How can I change default color's hex code?

### ISSUE THREAD

**Issue by avatar-lavventura** [willmcgugan/rich#1724]
I want to change colors's hex codes into dracula theme's setting: https://github.com/dracula/dracula-theme#color-palette

Example:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/18537398/143774305-1eb4e3f5-3ba4-4c41-a532-91adabd652f8.png">

Would it be possible to change color's default value into ones I want? For example I want to change pink's color into `#ff79c6` and so on.

**Comment by willmcgugan** [comment]
Your terminal defined a color theme, which you can usually edit via the settings in your terminal software. It's not something you do in code.

**Comment by avatar-lavventura** [comment]
I am able to do something like: ```print(f"[#ff79c6]hello[/#ff79c6]")```. 

I wanted to force the color's hex definition in the code as well and also create aliases for the new colors I want to use; for exampole `b` for `bold` and so on.

**Comment by willmcgugan** [comment]
You already can use hex codes, and b works for bold. You can also created [themes](https://rich.readthedocs.io/en/latest/style.html#style-themes) to define aliases for your own colors.

**Comment by avatar-lavventura** [comment]
Got it, I can do something like following:

```
custom_theme = Theme({
        "magenta": "#ff79c6"
    })
```
