### ISSUE TITLE
[BUG]Progress: RenderableColumn not updated

### ISSUE THREAD

**Issue by snooppr** [willmcgugan/rich#1726]
This is a simple example of code that should display CPU utilization as a percentage.
Expectation: that the progress will update and output CPU data, but the value is constant and not updated [72.3, 68.0].
'RenderableColumn' - not updating data?
```
from rich.progress import (TimeRemainingColumn,RenderableColumn,TimeElapsedColumn,Progress)
import psutil
import time

progress = Progress(TimeElapsedColumn(), RenderableColumn(str(psutil.cpu_percent(interval=1, percpu=True))), refresh_per_second = 3.0)
task = progress.add_task("", total=20)
with progress:
    for i in range(20):
        progress.update(task, advance=1)
        print("rich_" + str(i))
        time.sleep(0.2)
```
![RenderableColumn](https://user-images.githubusercontent.com/61022210/143862839-2b9b7e8f-4e06-4f5d-b55d-9d224266567f.gif)

rich==10.15.0 OS: GNU/Linux.

**Comment by willmcgugan** [comment]
You are calling `cpu_percent` only once, which is why it is not updating.  If you want it to update, you will need to create a Column class of your own. See the Column classes in progress.py for examples.
