### ISSUE TITLE
[BUG] Table hyperlink

### ISSUE THREAD

**Issue by tcapelle** [willmcgugan/rich#1731]
I am really loving this little gem of python! Thanks for the awesome work!
I am trying to make an hyperlink to work on tables without success.

```python
from rich import print
from rich.console import Console
from rich.table import Table

c = Console()
table = table = Table()

#does not work
table.add_row('Hello [link="https://google.com"]World[/link]')

#does not work
table.add_row('Hello [link=https://google.com]World[/link]')

#works
table.add_row('https://google.com')

c.print(table)
```
This is the code I have been trying. I want to be able to rename links.

Mac OS Monterrey with ZSH terminal

**Comment by willmcgugan** [comment]
Not all terminals support the link code. But most will turn URLs in to link. If you are on MacOS, give iTerm a try, which support links and is better than the standard console.

**Comment by tcapelle** [comment]
Thanks for your quick answer!
It appears to be `tmux` my problem, as without it, it works.
