### ISSUE TITLE
[BUG]'Alternate screen' on windows does not clear after completion

### ISSUE THREAD

**Issue by snooppr** [willmcgugan/rich#1735]
'Alternate screen' on windows does not clear after completion.

Sample code:
```
import time
from rich.console import Console

locale.setlocale(locale.LC_ALL, '')
init(autoreset=True)
console = Console()

print("Great_Rich")

with console.screen():
    console.print("Banner")
    time.sleep(5)

for i in "Text":
    time.sleep(0.04)
    print(f"\033[31;1m{i}", end='', flush=True)
print("\n\n exit")
```
After the code completes, the terminal will print a 'Banner' which should not be in the cli.  
I checked the 'alternative scree' on Linux and Termux the results are correct (Banner missing after code completion).

OS windows 7 32bit, 1-CPU, rich 10.15.1.
I also read the paragraph that the 'alternative screen' function is experimental, in fairness on the same configuration 'progress' works (updates the cli) correctly.  
Briefly: add cli cleanup after completing 'alternate screen' for Windows.

**Comment by willmcgugan** [comment]
Please try to supply fully working test code with bug reports.

Alternate mode is not supported by Windows legacy console. The new Windows Terminal should work.

**Comment by snooppr** [comment]
> Please try to supply fully working test code with bug reports.
> 
> Alternate mode is not supported by Windows legacy console. The new Windows Terminal should work.

```
import time
from rich.console import Console

console = Console()

print("Great_Rich")

with console.screen():
    console.print("Banner")
    time.sleep(2)

for i in "Text":
    time.sleep(0.04)
    print(f"\033[31;1m{i}", end='', flush=True)
print("\n\n exit")
```

I tested this on Windows 10 and Windows 7. In both cases, the terminal was not cleared (the word "Banner" remained in the terminal). That is, in Windows, the alternative terminal works like a simple "print". On GNU/Linux everything works and is in perfect order, please check it out.

p.s. This [project](https://github.com/peterbrittain/asciimatics) here works as an alternative screen on Windows 7 and Windows 10 (the text is cleared after itself).
@willmcgugan
