### ISSUE TITLE
[BUG] Live Progress Bars Double-Render in Jupyter Notebooks 

### ISSUE THREAD

**Issue by nicholaswold** [willmcgugan/rich#1737]
**Describe the bug**

Upgrading to `10.15.1` from `10.13.0` causes a double-render when using a live progress bar in a Jupyter Notebook. You can see this easily using the following example code:

```python
from rich.progress import Progress

with Progress() as progress:
    task1 = progress.add_task("[red]Downloading...", total=2)
    while not progress.finished:
        progress.update(task1, advance=1)
        progress.refresh()
```

![image](https://user-images.githubusercontent.com/1581984/144648258-f5867cf2-be1b-40e3-a70a-919cc9bbd036.png)

If it matters, we were using `ipywidgets==7.6.5` for this example above. Rolling back to `rich==10.13.0` fixed the issue.

You can see the section below for a description of what's happening in the Jupyter messaging protocol, but my best guess is that the ipywidgets usage is slightly off and causing this bug.

**ipywidgets specifics**

Normally when you update an output widget it fires the following messages:
1. A `comm_msg` that specifies that all future messages apply to a specific output model
2. A `clear_output` message with `wait=True`
3. A `display_data` message including the new content
4. A `comm_msg` that specifies that future messages no longer apply to a specific output model

We were noticing that this is still the case except for the final update message, in which it does the following:

1. A `comm_msg` that specifies that all future messages apply to a specific output model
2. A `clear_output` message with `wait=True`
3. A `comm_msg` that specifies that future messages no longer apply to a specific output model
4. A `display_data` message including the new content

The swap of those two messages caused the double-render, because the old render is never cleared by an output to that widget model, and the display_data is tracked as a new output for the cell.

**Platform**

Underlying platform is linux, using the classic Jupyter interface. This also happened using Noteable's interface.

```
╭─────────────────────── <class 'rich.console.Console'> ───────────────────────╮
│ A high level console interface.                                              │
│                                                                              │
│ ╭──────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=80 None>                                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│     color_system = None                                                      │
│         encoding = 'utf-8'                                                   │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w'               │
│                    encoding='utf-8'>                                         │
│           height = 25                                                        │
│    is_alt_screen = False                                                     │
│ is_dumb_terminal = False                                                     │
│   is_interactive = False                                                     │
│       is_jupyter = False                                                     │
│      is_terminal = False                                                     │
│   legacy_windows = False                                                     │
│         no_color = False                                                     │
│          options = ConsoleOptions(                                           │
│                        size=ConsoleDimensions(width=80, height=25),          │
│                        legacy_windows=False,                                 │
│                        min_width=1,                                          │
│                        max_width=80,                                         │
│                        is_terminal=False,                                    │
│                        encoding='utf-8',                                     │
│                        max_height=25,                                        │
│                        justify=None,                                         │
│                        overflow=None,                                        │
│                        no_wrap=False,                                        │
│                        highlight=None,                                       │
│                        markup=None,                                          │
│                        height=None                                           │
│                    )                                                         │
│            quiet = False                                                     │
│           record = False                                                     │
│         safe_box = True                                                      │
│             size = ConsoleDimensions(width=80, height=25)                    │
│        soft_wrap = False                                                     │
│           stderr = False                                                     │
│            style = None                                                      │
│         tab_size = 8                                                         │
│            width = 80                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
platform="Linux"
WindowsConsoleFeatures(vt=False, truecolor=False)
rich==10.15.1
```

**Comment by christina-yun** [comment]
**Narrowing this down:**

Was able to replicate the bug reported here and was able to narrow it down to differences between 10.15.0 and 10.15.1

All version of rich from 10.13.0 through 10.14 didn't have the double render.

Looking at the pull request that got merged, the code that was merged references thread safety. It might be some kind of race condition between multiple threads.

**Comment by willingc** [comment]
@christina-yun @nicholaswold Can you check if @willmcgugan's recent fix released as 10.15.2 resolves the behavior that we have seen on 10.15.1?

Thanks Will for a great library!

**Comment by christina-yun** [comment]
@willingc - Thank you for the suggestion. I went ahead and tested 10.15.2 and it still has the same issue as 10.15.1 that @nicholaswold and I were able to replicate yesterday. 
<img width="711" alt="Screen Shot 2021-12-08 at 9 15 34 AM" src="https://user-images.githubusercontent.com/86083591/145253337-cc639c76-c564-4c03-83e0-4cb81d021dd1.png">

**Comment by willmcgugan** [comment]
Thanks for narrowing this down. I'll take a look soon.

**Comment by willmcgugan** [comment]
I think I have a fix for that. Please give 10.15.3a1 a try.

There are also changes there to workaround issues with thread-safety in Jupyter. So I'd appreciate it if you could try it against any code with progress bars.

**Comment by willingc** [comment]
The fix looks like it works for the originally reported example and another notebook with some progress bars. Thanks @willmcgugan. Will let you know if I see anything else.

**Comment by willmcgugan** [comment]
That's in 10.16.0 now
