### ISSUE TITLE
[BUG] the progress bar between ubuntu 20.04 and win10 is different

### ISSUE THREAD

**Issue by bibo19842003** [willmcgugan/rich#1745]
the progress bar between ubuntu 20.04 and win10 is different

ubuntu 20.04
python version : Python 3.8.10
rich version: 10.15.2

win10
python version : Python 3.8.5
rich version: 10.15.2

when i run:  python -m rich.progress
the progress bar between ubuntu 20.04 and win10 is different
![ubuntu20 04](https://user-images.githubusercontent.com/6059036/145086024-4b061132-8727-4403-9615-39f3546b4ce1.png)

![win10](https://user-images.githubusercontent.com/6059036/145086032-7a5f4650-1b93-4285-9dcc-81fce7ab0e17.png)

**Comment by willmcgugan** [comment]
This is correct. Windows legacy terminal does not the unicode characters and will default to ascii. Try the new Windows Terminal, which is known to work well.

**Comment by bibo19842003** [comment]
thank you
