### ISSUE TITLE
[BUG] rich/examples/downloader.py does not wait for downloading

### ISSUE THREAD

**Issue by hankyul2** [willmcgugan/rich#1749]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

In `rich/example/downloader.py`, process does not wait for downloading file done. It just exit within 1 second.

```
python3 url.py https://releases.ubuntu.com/20.04/ubuntu-20.04.2.0-desktop-amd64.iso
```
![image](https://user-images.githubusercontent.com/31476895/145548548-cb47b49d-b512-4b4a-9994-52df1ddcc472.png)

**Platform**

I am using linux 18.04, python 3.7.10

![image](https://user-images.githubusercontent.com/31476895/145548965-373940ed-a14d-4413-837f-a25220af10fa.png)
![image](https://user-images.githubusercontent.com/31476895/145549038-eee976f9-7961-45df-befc-8e6a1aba3391.png)

**Comment by sanders41** [comment]
The problem is the url `https://releases.ubuntu.com/20.04/ubuntu-20.04.2.0-desktop-amd64.iso` returns a 404. Try `https://releases.ubuntu.com/20.04/ubuntu-20.04.3-desktop-amd64.iso` instead.

**Comment by hankyul2** [comment]
@sanders41  Thank you. It works
![image](https://user-images.githubusercontent.com/31476895/145657747-ff318e7c-6c8e-4a9d-8c48-ebc5226edc12.png)
