### ISSUE TITLE
[REQUEST] Column sorting for table

### ISSUE THREAD

**Issue by prabhu** [willmcgugan/rich#175]
Have you checked the issues for a similar suggestions?

**How would you improve Rich?**

Sort apis for table.

Either as part of add column
table.add_column(sort="asc")

Or once the table is fully loaded
table.add_sort(column name/column index/column ref, asc/desc, comparator=default comparator)

**What problem does it solved for you?**

Sorting is an important part of a table.

What problem do you have that this feature would solve? I may be able to suggest an existing way of solving it.
My product [scan](https://github.com/ShiftLeftSecurity/sast-scan) can display results sorted by multiple columns.

**Comment by willmcgugan** [comment]
Rich Tables intentionally have no data table functionality. They are completely agnostic as to where and how the data is stored. The only job of the Table class is to render the table.
