### ISSUE TITLE
Enable logging to display Text objects with supported Styles

### ISSUE THREAD

**Issue by jeremyschulman** [willmcgugan/rich#1751]
As a developer of network infrastructure testing systems I use Rich to display progress of testing using the logging feature and display reports using the Table feature.  In the same way that I use Text+Style to colorize my Tables, I would like to colorize/style text that is the logging output using the same Text/Style classes.  Presently the logging feature supports the "markup" color notation exclusively.  

This issue requests an enhancement so that I can pass Text objects to the logging log methods (info, error, warning, etc.) so that the output in the logs shows all color/styling that is supported by the Python logging infrastructure.  

Example desired usage; assume the variable "logger" is a Rich python logger instance:
````python
from rich.tex import Text, Style

name = Text("Jeremy", style=Style(color="blue"))
logger.info(f"Hello {name]")
````

The desired output would be "Hello Jeremy" with the text "Jeremy" colored blue.

**Comment by willmcgugan** [comment]
It probably wouldn't be quite as transparent as that. I wouldn't want to change the output of `Text.__str__` at this point. I was thinking a property `markup`. So it would be something like this in a logger:


```print
logger.info(f"hello {name.markup}")
```

**Comment by jeremyschulman** [comment]
@willmcgugan - that approach would be excellent, thank you!

**Comment by willmcgugan** [comment]
Hacked in that property. If you could give Rich 10.15.3a2 a try.

**Comment by willmcgugan** [comment]
That's in v10.16.0 now
