### ISSUE TITLE
[BUG] `rich.prompt.PromptBase.make_prompt` raises a `TypeError` when `choices` are not a `list[str]`

### ISSUE THREAD

**Issue by garciparedes** [willmcgugan/rich#1758]
**Describe the bug**

The bug is related with the `choices` argument of the `PromptBase.ask` function. Concretely, when the `PromptBase` implementation has a `response_type` distinct from `str`, it's not possible to fill the `choices` argument as it is expected to be a `list[str]`. So, cannot be any valid value to be passed (as it must be of `response_type` type and also must be in `choices`, but if, for example,  `response_type` is `int` and `choices` is a `list[str]` then the condition can never be satisfied.

The reason why this is a blocking bug is that the `make_prompt` method assumes that the `choices` attribute is  an `Optional[list[str]]`, so that when it is not `None` it does not consider the case in which `choices` is composed of `int` values and raises a `TypeError` while building the prompt.

Here is a minimal reproducible example:
```python
from rich.prompt import IntPrompt

IntPrompt.ask("foo?", default=1, choices=[1, 2, 100])
```

Here is the traceback:
```
Traceback (most recent call last):
  ...
  File "/Users/garciparedes/development/clariteia/minos-cli/.venv/lib/python3.9/site-packages/rich/prompt.py", line 141, in ask
    return _prompt(default=default, stream=stream)
  File "/Users/garciparedes/development/clariteia/minos-cli/.venv/lib/python3.9/site-packages/rich/prompt.py", line 273, in __call__
    prompt = self.make_prompt(default)
  File "/Users/garciparedes/development/clariteia/minos-cli/.venv/lib/python3.9/site-packages/rich/prompt.py", line 167, in make_prompt
    _choices = "/".join(self.choices)
TypeError: sequence item 0: expected str instance, int found
```

**Platform**

This bug is platform-agnostic, as it is related with the way how a `list` of values is casted concatenated into a ``str`` value.

**Comment by willmcgugan** [comment]
```python
IntPrompt.ask("foo?", default=1, choices=["1", "2", "100"])
```

**Comment by garciparedes** [comment]
Hi @willmcgugan, thanks for your help!
