### ISSUE TITLE
[BUG] Weird coloring middle of words [rich 10.16.1]

### ISSUE THREAD

**Issue by glensc** [willmcgugan/rich#1764]
**Describe the bug**

Weird coloring:

```
➔ python -c 'from rich.console import Console; Console().print("<local:14863:<Movie:14863:Das-Experiment>>")'
<local:14863:<Movie:14863:Das-Experiment>>
```

![image](https://user-images.githubusercontent.com/199095/146674461-0b17a071-debf-4658-b092-3e8ae59dd531.png)

1. why does it start-stop middle of the word?
2. how to disable that?

**Comment by glensc** [comment]
```
$ python -c 'from rich.console import Console; Console().print("[magenta]<local:14863:<Movie:14863:Das-Experiment>>")'
```

![image](https://user-images.githubusercontent.com/199095/146674509-1af527ae-8065-49b1-9083-30739f7b3561.png)

**Comment by glensc** [comment]
Seems it's ipv6 pattern:
- https://github.com/willmcgugan/rich/blob/b72e002a000ba5d9a58f61b9a8fcb7fec38b7ebe/rich/highlighter.py#L89

commenting out that line makes text appear normalish:

![image](https://user-images.githubusercontent.com/199095/146674975-00e9d98c-c6e5-41ba-86e3-81730cd20d44.png)

**Comment by glensc** [comment]
To disable completely can use `highlight=False`:
- https://rich.readthedocs.io/en/latest/highlighting.html

**Comment by glensc** [comment]
Can remove the specific one by implementing own highlighter class:
- https://rich.readthedocs.io/en/latest/highlighting.html#custom-highlighters

**Comment by willmcgugan** [comment]
Sounds like you figured it out! Ok to close?

**Comment by glensc** [comment]
@willmcgugan I figured out the cause, there's no fix.

**Comment by glensc** [comment]
the ipv6 pattern is too greedy, should be removed or improved

**Comment by glensc** [comment]
how was the problem solved? i don't see any related commits or merge requests

**Comment by willmcgugan** [comment]
You solved your own problem and said there was no fix. If you want to improve the ipv6 regex, a PR would be welcome.
