### ISSUE TITLE
[help] How can I keep the output of `console.status`?

### ISSUE THREAD

**Issue by avatar-lavventura** [willmcgugan/rich#1769]
When I do:

```
with console.status("Working..."):
    do_work()
```

After `do_work()` is completed `"Working..."` string is also deleted from the console. Would it be possible to keep the output of  `"Working..."` in the console when do_work() is done?

**Comment by sanders41** [comment]
Can you give some more context as to what you are trying to do? The purpose of the `status` is to display until the task is done. Maybe in your case it makes more sense to just print the `Working...`?

```py
console.print("Working...")
do_work()
```

**Comment by avatar-lavventura** [comment]
Basically I wanted do:

```
with console.status("Working..."):
    do_work()

console.print("Working...")  
```

Could it be done by the `console.status("Working...")` to re-print it when the work is done?

**Comment by sanders41** [comment]
Maybe something like this could work:

```py
with console.status("Working..."):
    do_work()

console.print("Working... [ OK ]")
```

It assumes `do_work()` would somehow stop the program if it is unsuccessful, in which case it wouldn't reach the `console.print` step.

**Comment by avatar-lavventura** [comment]
@sanders41 Thanks
