### ISSUE TITLE
[help] logger message pretty print

### ISSUE THREAD

**Issue by teneon** [willmcgugan/rich#1780]
Hi there,

i am using django and the latest version of rich. I have enabled and configured logging in django and it works pretty well.
But I can't figure one thing out.

I would like to log (to console) a medium sized object called 'market':
`logger.debug(market)`
The issue that i have is that, the object is printed in a single line (no wrapping).

I tried to fix this issue with 'pformat' and it actually works to some extend.
```
from pprint import pformat
logger.debug("\n" + pformat(market, indent=4, sort_dicts=False))
```
The problem with this approach is that 'pformat' does the formatting differently than 'print' function from your 'rich' module.
So if i print(market) with rich, the output is inconsistent with printing market with logger.debug and 'pformat'.

Is there an a method implemented in rich that i could use instead of pformat?

P.S. I cannot use json.dump() or similar because, because one of the properties in object 'market' is also Pandas dataframe, which json.dump() cannot convert.

thank you and best regards,
Neon

**Comment by willmcgugan** [comment]
You can use `rich.pretty.pretty_repr` to format an object with Rich.
