### ISSUE TITLE
[BUG] Cannot print a string represented List[str]

### ISSUE THREAD

**Issue by Simon-Chenzw** [willmcgugan/rich#179]
**Describe the bug**
I really like how this module works, so I use it in my script to get better output when running in the shell. But today, I found that rich seem to have some problems when rendering.
When I tried to use rich to print `subprocess.TimeoutExpired` , I did not get the output I expected. Is this a bug?
```python3
except subprocess.TimeoutExpired as err:
        rich.print(f"TimeoutExpired: {str(err)}")
```

**To Reproduce**
```python3
from rich import print
print("'['arg1', 'arg2']'") # will only get ''
print("['arg1', 'arg2']")   # will get nothing
```

**Platform**
platform : Linux (ubuntu 18.04)
terminal : bash
Python : 3.6.9
rich : 4.0.0

**Comment by willmcgugan** [comment]
Anything in square brackets is interpreted as console markup. See the [docs](https://rich.readthedocs.io/en/latest/markup.html) for details how to escape, or disable console markup.
