### ISSUE TITLE
[BUG] console.clear() events included in save_text() output, resulting in garbage

### ISSUE THREAD

**Issue by minimaxir** [willmcgugan/rich#181]
**Describe the bug**
console.clear() events are included in save_text() output, resulting in garbage which is likely not intended.

**To Reproduce**

```python
from rich.console import Console

console = Console(record=True)
console.clear()
console.print("What is love?")
console.save_text("test.txt")
```

Results in a text file with:

```
[2J[HWhat is love?
```

**Platform**
ZSH (via VS Code's integrated terminal), rich 4.1.0

**Comment by willmcgugan** [comment]
Please try v4.2.0

**Comment by minimaxir** [comment]
Works there. Thanks for the fast turnaround!
