### ISSUE TITLE
[BUG] Fatal error in rich-4.1.0 library. In version 3.0.3, the error is not critical.

### ISSUE THREAD

**Issue by snooppr** [willmcgugan/rich#184]
1)  rich-4.1.0 library
https://github.com/snooppr/snoop/blob/master/snoop.py#L394
```
In my code I use rich library (manual update), new version crashes.
    for social_network, net_info in progress1.track(site_data.items(), description=""):
  File "/home/snoop/.local/lib/python3.7/site-packages/rich/progress.py", line 710, in track
    progress.refresh()
NameError: name 'progress' is not defined
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
```
2) rich-3.0.3 library #I rolled back to this version of the library, but it also has a bug:
Loss of the task completion percentage and loss of bar status (indication line), as well as incorrectly colored lines.

I rolled back to the stable version of the rich == 1.2.3 library which has no problems.
https://github.com/snooppr/snoop/issues/33

**Comment by willmcgugan** [comment]
Please try v4.2.0

**Comment by snooppr** [comment]
I checked rich version 4.2.0 (GNU / Linux) fixed and it works.
How conceived or not is now the question
This is how rich 4.2.0 works
![1](https://user-images.githubusercontent.com/61022210/88585276-90503b80-d05b-11ea-8915-79e97bb854f0.png)
The mistake here is that links are colored green, but should be system-based (set by default in the terminal.)
Regarding the update line and the percentage of completion (maybe it's even better, I can't decide yet)

And this is how rich v1.2.3 works
![2](https://user-images.githubusercontent.com/61022210/88585556-e58c4d00-d05b-11ea-93cb-4baa4883b8c8.png)
Here links are colored with the system color (correct)
****************
v4.2.0 **Bug**: Lost 'calculating approximate code execution time'.
`progress = Progress(TimeRemainingColumn() #bad`

v1.2.3 'estimated estimated running time'

**Comment by willmcgugan** [comment]
See docs on [highlighting](https://rich.readthedocs.io/en/latest/highlighting.html).

I'm afraid I can't make much sense of your other problem. Please raise another issue with example code to help me understand what you are looking for.
