### ISSUE TITLE
Print invalid in-line style as is, instead of ignoring it

### ISSUE THREAD

**Issue by rajuah** [willmcgugan/rich#185]
Great job with Rich! Just love everything about about it 😄 

Currently, calling `Console.print()` with invalid in-line style within `[]`, causes the print statement to omit it from the output.

In the screenshot below, we can see that `print()` omits printing the list and the content within the `[]` if its not a valid style.

![image](https://user-images.githubusercontent.com/17533956/88602174-156d2d80-d027-11ea-97f4-6d409801cf23.png)

It would be great, if instead of ignoring invalid styles, rich just prints it as is. This will definitely be useful for printing lists through f-strings or any text that is surrounded by `[]` on purpose.

**Comment by willmcgugan** [comment]
The problem with not removing everything in square brackets it's that style names can be arbitrary. It is possible to define a style called "hello" -- so Rich can never be certain if you intended a literal "[hello]" or a style called "hello".

That said, I have been thinking of tightening the syntax for console markup, so the style name must begin with a letter. That would mean that your first example (and most repr strings) would be considered literals.
