### ISSUE TITLE
When CJK characters are included in the line, the width is displayed incorrect

### ISSUE THREAD

**Issue by GeekDuanLian** [willmcgugan/rich#19]
![image](https://user-images.githubusercontent.com/6257434/76419334-1df7fb00-63db-11ea-8d6a-9af56524f55d.png)

Because the width of a CJK character is equal to the width of two letters, special handling may be required.
See: https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

**Comment by willmcgugan** [comment]
Yeah, I plan on tackling CJK characters after the next update. Can I enlist your help for testing?

**Comment by GeekDuanLian** [comment]
Sure, what can i do?
I am new to python... I have tried to view the source code, but I don’t know what to fix.

**Comment by willmcgugan** [comment]
It's not a trivial fix I'm afraid. When I have a new version, it would be great if you could give it a quick check.

**Comment by GeekDuanLian** [comment]
No problem, if you release a new version, please reply below, I will have an email reminder to let me test it as soon as possible

**Comment by willmcgugan** [comment]
Could you please try version 0.8.0a1.

```
pip install rich==0.8.0a1
```

CJK support should be fixed. If you could re-create the traceback from your screenshot that would be a good test.

**Comment by GeekDuanLian** [comment]
![image](https://user-images.githubusercontent.com/6257434/76840882-e1ad1a80-6872-11ea-8d47-2e5ee6037db2.png)

Looks good! Thanks for the fix.

Incidentally, my platform is using mintty in cygwin under windows10. This may not be the mainstream platform. I don’t know if it can be displayed correctly on other platforms (such as cmd). Do I need to test on other platforms?

**Comment by willmcgugan** [comment]
Great, thanks. Probably no need to do more testing, I have a Windows box I can test on.

I appreciate the help. I'll make a new release soon.

**Comment by willmcgugan** [comment]
Fixed in 0.8.0
