### ISSUE TITLE
[REQUEST] Do not truncate paths and URLs in logger

### ISSUE THREAD

**Issue by aklajnert** [willmcgugan/rich#190]
Thank you for a wonderful project, it's very useful and makes my work more pleasant.

I'm using `rich` as a logger handler, and while in general it works great, that I don't like the fact that depending on terminal width it truncates some URL's, paths, and some other things that I can't identify.

See screenshot below:  
![image](https://user-images.githubusercontent.com/18279161/88783938-b840bb80-d18f-11ea-91d2-0c674f881127.png)

Is it already possible to disable this behavior? I can't find anything about it in the documentation.

**Comment by willmcgugan** [comment]
Yes, that should probably be changed to overflow=fold, but it's not currently exposed.

I'm puzzled as to why the URL doesn't wrap to the next line. Here's what happened when I tested it:

<img width="648" alt="Screen Shot 2020-07-29 at 10 46 07" src="https://user-images.githubusercontent.com/554369/88785175-c9d29500-d188-11ea-96d1-ea495676446e.png">

What version of Rich do you have, and how have you configured logging?

**Comment by aklajnert** [comment]
@willmcgugan I just did update to the newest version, and the URL's are not truncated here.  

Is the mentioned `overflow=fold` enabled in your screenshot? I see the path is still truncated.

**Comment by willmcgugan** [comment]
That was 4.2.0 in the screenshot. I'll set the overflow to fold in the next update.

**Comment by aklajnert** [comment]
Maybe it would make sense to allow changing it as an argument since this would be a breaking change and some people may not like it.

**Comment by willmcgugan** [comment]
Configuration is usually the answer to these things, but I think in this case "fold" is clearly better. It doesn't break anything in the sense that no project will be rendered non-functional, it's more of a visual thing.

Totally willing to revisit it if anyone does object...

**Comment by aklajnert** [comment]
Got it, any estimates when can we expect this change? Do you need any help with that?

**Comment by willmcgugan** [comment]
Update coming tonight or tomorrow...

**Comment by willmcgugan** [comment]
Try v4.2.1

**Comment by aklajnert** [comment]
Everything is great now, thank you!
