### ISSUE TITLE
[BUG] table not rendering properly in rich v4.2.2 in Windows CMD

### ISSUE THREAD

**Issue by Niraj-Kamdar** [willmcgugan/rich#195]
**Describe the bug**
table not rendering correctly sometime on Windows after new update. 

**To Reproduce**
I don't know how to reproduce it. It is being produced only once on latest release only but working fine on older release: 4.0.0
![rich_table_bug](https://user-images.githubusercontent.com/51387861/89033908-7bbebc80-d355-11ea-8b27-586b1194f5d0.png)

**Platform**
What platform (Win/Linux/Mac) are you running on?
Windows
What terminal software are you using?
powershell 
Which version of Rich?
4.2.2

**Comment by willmcgugan** [comment]
This is actually a bug in Python for Windows. I've tried to work around it, but any changes seem to make it pop up elsewhere. See https://github.com/willmcgugan/rich/issues/186 for background.

**Comment by willmcgugan** [comment]
Are you certain you saw the issue with 4.2.2 ? I've been unable to reproduce it. It's generally very reproducible once you find a table where it occurs.

**Comment by Niraj-Kamdar** [comment]
Yes, It is being produced everytime.

**Comment by Niraj-Kamdar** [comment]
Thanks for your prompt reply and bug fixes 👍

**Comment by willmcgugan** [comment]
Ah, fantastic. :-)
