### ISSUE TITLE
Feature Request: Add Table.title alignment

### ISSUE THREAD

**Issue by jeremyschulman** [willmcgugan/rich#196]
Have you checked the issues for a similar suggestions?
Yes

**How would you improve Rich?**

Please add a table title alignment option.  As I read the code the title is hardcoded to "center"

**What problem does it solved for you?**

User readability, having the table title left-aligned is a desired user-experience.

**Comment by willmcgugan** [comment]
Try `title=Text("My Table", justify="left")`

**Comment by jeremyschulman** [comment]
Yup, worked like a champ!  Thank you, and sorry I missed how to do this in the docs.
