### ISSUE TITLE
Console.print is broken

### ISSUE THREAD

**Issue by damontallen** [willmcgugan/rich#20]
[Screenshot](https://i.imgur.com/GOZrXCv.png)
>>> from rich.console import Console
>>> Console.print("Where there is a [bold cyan]Will[/bold cyan] there [u]is[/u] a [i]way[/i].")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/damon/src/virtualenv-16.7.6/bun/lib/python3.8/site-packages/rich/console.py", line 740, in print
    self.line()
AttributeError: 'str' object has no attribute 'line'

**Comment by damontallen** [comment]
[Screenshot](https://i.imgur.com/GOZrXCv.png)
>>> from rich.console import Console
>>> Console.print("Where there is a [bold cyan]Will[/bold cyan] there [u]is[/u] a [i]way[/i].")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/damon/src/virtualenv-16.7.6/bun/lib/python3.8/site-packages/rich/console.py", line 740, in print
    self.line()
AttributeError: 'str' object has no attribute 'line'

**Comment by willmcgugan** [comment]
You need to construct the `Console` class first.

```python
from rich import Console
console = Console()
console.print("[bold green]It works")
```

**Comment by damontallen** [comment]
OH.  I'll try that.

**Comment by damontallen** [comment]
That works.  Sorry for the misunderstanding, but there is one more thing.
[screenshot](https://i.imgur.com/s7e5KXb.png)
There seems to be an issue with quotes appearing in the string breaking print.

**Comment by damontallen** [comment]
>>> console= Console()
>>> console.print("Where there is a [bold cyan]Will[/bold cyan] there [u]is[/u] a [i]way[/i].")
Where there is a Will there is a way.
>>> console.print("Where there is a [bold cyan]Will[/bold cyan] there [u]is[/u] a [i]way[/i].")
Where there is a Will there is a way.
>>> full_path='"5"'
>>> console.print(f"\tThe full data path will be: [blue][bold]\"{full_path}\"[/bold][/blue]")
        The full data path will be: ""5""
>>> console.print(f"\tThe full data path will be: \"[blue][bold]{full_path}[/bold][/blue]\"")
        The full data path will be: ""5""
>>> full_path='5'
>>> console.print(f"\tThe full data path will be: \"[blue][bold]{full_path}[/bold][/blue]\"")
        The full data path will be: "5"
>>>

**Comment by damontallen** [comment]
Do you want me yo open up a separate issue for this?

**Comment by willmcgugan** [comment]
Rich will do some automatic syntax highlighting of things like strings and numbers. If you want to disable that feature, add `highlight=False` to the print function.

**Comment by damontallen** [comment]
Perfect! Thank you for helping me out.
