### ISSUE TITLE
[QUESTION] Information on use of TerminalTheme with save_html

### ISSUE THREAD

**Issue by jeremyschulman** [willmcgugan/rich#200]
Have you checked the issues for a similar suggestions? Yes.

I would like to use `console.save_html()` and use the `theme` parameter; but I am not clear on the process to create a theme color pallet.   I looked at the file _terminal_theme.py_ but I am still not quite clear how to proceed.  Is there documentation on this topic or could you advise? 

Ideally I would like to use a pygments style name to define the color theme if possible; for example use pygments.style.get_style_by_name("paraiso-dark") as a means to se the save_html() theme.

I really appreciate your help and guidance!

**Comment by willmcgugan** [comment]
A terminal theme defines a foreground / background color, 8 standard colors, and 8 bright versions.

In https://github.com/willmcgugan/rich/blob/master/rich/terminal_theme.py the colors are specified by tuples of three values, for red green and blue components. You should be able to extract these colors from any terminal theme, although you may have to convert the color format.

The Color class can parse most color formats. Here's how you would parse an HTML color:

```python
r, g, b = Color.parse("#ff0000").get_truecolor()
```

**Comment by jeremyschulman** [comment]
Thank you. I am not clear on what the "8 standard colors" represent or how they are used specifically. Could you please advise or share a URL that explains further?

**Comment by willmcgugan** [comment]
So the first 16 [colors](https://rich.readthedocs.io/en/latest/appendix/colors.html) are not fixed, but set by your terminal software. There is also a default foreground and a background color, which may or may not be one of the 16.

If you do `print("[red]Hello[/red]")` you will likely get red, but the exact shade is determined by the console theme. Rich can't know exactly what colors you will get, which is why it needs a TerminalTheme when it exports to html.

Perhaps this is not the theme you were thinking of? The term 'theme' can refer to several things. What is it you are exporting to html?

**Comment by jeremyschulman** [comment]
Ah, I think I understand.  I looked at iTerm2 for "colors" and they represent how the 8 colors are used, for example:

![image](https://user-images.githubusercontent.com/2607956/89126170-a0c84200-d4b1-11ea-9f57-92ed6900ac25.png)

**Comment by willmcgugan** [comment]
Yep, exactly. That’s your terminal theme.

**Comment by jeremyschulman** [comment]
got it, thank you very much!

**Comment by jeremyschulman** [comment]
Is there a way for the Rich package to give me my "current TerminalTheme" values?

**Comment by willmcgugan** [comment]
Afraid not. Every terminal emulator has a different way of storing those settings.

**Comment by jeremyschulman** [comment]
Ok, So I figured out how to export my iterm2 color settings but they look like this one, for example:

```
	<key>Ansi 1 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.0</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.10676553100347519</real>
		<key>Red Component</key>
		<real>0.789775550365448</real>
	</dict>
````

I'm not clear what to do with these floating-point values.  Any ideas on how to convert them into something I can use with Rich?

**Comment by willmcgugan** [comment]
Take the red green and blue components and multiply them by 255. That will give you a colour Tuple that rich can use.

**Comment by jeremyschulman** [comment]
Cool, giving that a try now, thank you!

**Comment by jeremyschulman** [comment]
Thank you very much for the math trick.  Works perfectly.
Really appreciate your help!  Love the Rich package!

Closing issue.

**Comment by jeremyschulman** [comment]
Since I imaging others might want to do what I am doing, I make this package, available on PyPi:
https://github.com/jeremyschulman/iterm2-colors2rgb
