### ISSUE TITLE
[BUG] BarColumn pulse_style is not changed 

### ISSUE THREAD

**Issue by ocurero** [willmcgugan/rich#203]
Hi Will

**Describe the bug**
I'm trying to implement a simple bar to show how much space a user has. This screenshot from Google Drive is how I would like it to look like:
![Sin título](https://user-images.githubusercontent.com/2606647/89203238-87f48500-d5b4-11ea-8be3-a0c91047bb5e.png)

I'm almost at it, but I would like to change the style of the bar based on how much space is in use. For example, below 50% green, between 50% and 80% yellow and above that red. While working on this feature I think I hit a bug.

**To Reproduce**

The following code should produce a blue bar inside a table. It mostly works, except that the pulse style is not blue but fucsia:
```
from rich.bar import Bar
from rich.console import Console
from rich.progress import BarColumn, Progress
from rich.table import Table


progress = Progress(
    "[progress.description]{task.description}",
    BarColumn(pulse_style="blue"),
    "[progress.percentage]{task.percentage:>3.0f}% {task.completed} MB of {task.total} MB used",
)

progress.add_task(description='Storage', completed=5, total=10)

table = Table('Example')
table.add_row(progress.get_renderable())

console = Console()
console.print(table)
```

The questions are:
- Is this a bug?
- My intention here was the subclass the BarColumn class to modify the style based on the current percentage. Is this the way to go?

**Platform**
What platform (Win/Linux/Mac) are you running on? What terminal software are you using. Which version of Rich?
rich version 5.0.0 running on linux connecting through putty. 

Thanks!

**Comment by willmcgugan** [comment]
The `pulse_style` changes the pulsing effect when a task isn't started. You want `complete_style` which shows the progress.

Subclassing BarColumn is the way to go. Customize the [render](https://github.com/willmcgugan/rich/blob/master/rich/progress.py#L246) method to change `complete_style` based on `task.percentage`.

**Comment by willmcgugan** [comment]
If you don't need the progress bar functionality, you could just add a [Bar](https://github.com/willmcgugan/rich/blob/master/rich/bar.py) to your table. No need to go through a Progress class.

**Comment by ocurero** [comment]
Thanks, works like a charm! :)
