### ISSUE TITLE
[REQUEST] support multiple chars for rule printing

### ISSUE THREAD

**Issue by hedythedev** [willmcgugan/rich#204]
Have you checked the issues for a similar suggestions? Yes

**How would you improve Rich?**

Currently for rule.py it only allows the character to have 1 cell length, it would better if it could allow more, like

```python
>>> console.print(Rule("hello", character="-+"))
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ hello -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**What problem does it solved for you?**

I was just thinking it would improve it and it looks like an ASCII rule, which is cool (like [this](https://github.com/LuRsT/hr#how-to-use-it) program)

---

If this is accepted, I would like to work on it, because I have already tried it out ”locally” (https://repl.it/@hedythedev/rich#rich/rule.py) and it works well

```python
console.print(Rule(text, character="-/-"))
```

![BDB784D3-8BA2-4978-9791-6860EEFE0384](https://user-images.githubusercontent.com/50042066/89253524-7613f000-d64f-11ea-8abf-19070df40fab.jpeg)

**Comment by hedythedev** [comment]
I will also remember do add tests for this (if accepted) of course

**Comment by willmcgugan** [comment]
Hi @hedythedev 

Works for me. Since we allow multiple characters now, it should probably take in to account multi-cell characters like emoji. See the functions in [cells.py](https://github.com/willmcgugan/rich/blob/master/rich/cells.py) for help with that.

The name of the parameter is probably wrong now. `character` implies a single character. Suggest adding additional `characters` parameter which allows for multiple characters. 

BTW there is a [rule](https://rich.readthedocs.io/en/latest/reference/console.html#rich.console.Console.rule) method on the Console class that will also need updating...

Thanks!

**Comment by hedythedev** [comment]
Got it!
Btw when you say works for m, do you mean the code in repl.it?

**Comment by willmcgugan** [comment]
> Btw when you say works for me, do you mean the code in repl.it?

Just meant its a good idea in general.

> Also would chars work better? Because characters is a bit long

It is, but I dislike abbreviations. I'd rather type it in full than recall how it was abbreviated...

**Comment by hedythedev** [comment]
So if the characters provided have a long length, this might end up happening (`|` represents terminal width)
```python
>>> console.print(Rule("hello", character="12345"))
|12345 hello 12345    |
#                 ^^^^
```
Because `12345` is longer than the width left after the right side of `12345`, there will be a number blank spaces smaller than the cell width of `characters` param, in this case it is `len(“12345”) == 5`. Which is caused by treating `characters` (12345) as a whole.

So in this case, which solution would we want? 
1. using `truncate()` to make it
`|1234512 hello 1234512 |`  (there will be an ending space if length of `characters` is odd)

2. Or just leave it as is
`|12345 hello 12345    |`

**Comment by willmcgugan** [comment]
The Rule should extend to the full width available, which may mean you need an extra character on the right hand side. To use your example:

```
|1234512 hello 12345123|
```
