### ISSUE TITLE
Is there a way to directly access one of the fields in tasks.fields in a Progress Bar?

### ISSUE THREAD

**Issue by joaqo** [willmcgugan/rich#205]
Hi, first of all this library is really really great, thank you for the great work.

As for the subject of this post, I currently have a progress bar defined by:

```python
progress_bar = Progress(
    "[blue]{task.description}",
    BarColumn(),
    "[progress.percentage]{task.percentage:>3.0f}%",
    TimeRemainingColumn(),
    "[yellow]{task.fields}",  # <-- relevant part
)
task = self.progress_bar.add_task(label, total=total_frames)
```
I am updating it with `bar.update(self.task, advance=1, fps=f"{fps:.2f}")` and it runs just fine, with the progress bar displaying my fps as part of a dict, which would look something like `{'fps': '6.60'}` at the end of the progress bar. This is a bit unsightly in my opinion, as I'd really prefer not to print it as a dict, with all its `{`s and `'`s. I would prefer to be able to chose exactly in what format my fields get printed in the progress bar.

Is there a way to chose exactly which field to show and with what format, without printing as a dict? I tried things like `"[yellow]{task.fields.fps}fps"` or `"[yellow]{task.fields['fps']}fps"` but it doesn't work.

If this is not the case of me missing something obvious, it would be great to have this as a feature as it would allow us to chose how our custom fields look like.

Thanks for the awesome library by the way!

**Comment by willmcgugan** [comment]
Hi,

The progress class uses str.format to do the formatting, which uses a counter-intuitive way of doing dictionary lookups. Try `"[yellow]{task.fields[fps]}"`

**Comment by joaqo** [comment]
Hi, thanks for answering, tried that but I get a `KeyError: 'fps'` error. If I remove the `[fps]` from your solution it works fine buy I get the whole dict ` {'fps': 6.47}`.

**Comment by willmcgugan** [comment]
Have you given `fps` an initial value in `add_task` ?

**Comment by joaqo** [comment]
No I hadn't. That fixed it! Thanks a lot! Closing the issue.

**Comment by joaqo** [comment]
Sorry to revive this issue, but I have a short question and didn't think it was worth it creating another issue for it. Is it possible to use `ipdb` while displaying a progress bar? I am currently trying and failing as the progress bar seems to take control of the cursor and deletes any character I write in `ipdb` immediately after I type it. This makes it very hard to debug programs which use progress bars. Tried setting `redirect_stderr` and `redirect_stdout` to False but no dice.

**Comment by willmcgugan** [comment]
Both are writing to stdout, so it might be a problem.

Possibly the refresh thread is making it worse. Try setting auto_refresh=False for testing

**Comment by joaqo** [comment]
Perfect, that fixed it, thanks a lot again! I don't think I've ever seen a dev answer so quickly on such a large open source project, kudos!

PD: For anyone reading this issue, if you want ipdb or pdb to work with rich set:
```python
redirect_stderr=False
redirect_stdout=False
auto_refresh=False
```
in your `Progress()` constructor, and refresh your progress bar manually in your `update` method by setting `refresh=True` there.
