### ISSUE TITLE
[BUG] Coloring does not work in PyCharm

### ISSUE THREAD

**Issue by akrk1986** [willmcgugan/rich#206]
Just checked - it seems to be a **PyCharm problem**, I will report it there, so this report is just FYI for rich users who use PyCharm.
It works in the PyCharm terminal (command line), but not inside the stdout pane of PyCharm.

Reproduction
Replace print() statement with console.print(string, style='bold red'). The string is printed, but no coloring.

```
from rich.console import Console
console = Console()
console.print('==> Mismatches were found in one or more platforms <==', style='bold red')
```

Windows 10, PyCharm Community (lastest), Python 3.8, Rich 5.0.0

**Comment by willmcgugan** [comment]
It could be a problem with auto-detection.

What does the following print in PyCharm?

```
print(console.color_system)
```

**Comment by akrk1986** [comment]
In the PyCharm stdout window, as you've suspected, it prints 'None' (and no color).
In the PyCharm terminal, it prints 'windows' (and works)

**Comment by willmcgugan** [comment]
Interesting. That suggest the stdout window is not an embedded console. Rich will disable color if it detects it is not connected to a real terminal.

You could try this:

```python
console = Console(color_system="windows")
```

That will force Rich to write color, but if PyCharm can't handle it, you may end up with garbage.

**Comment by akrk1986** [comment]
Thanks - it works. Since I only use Windows for this project, this workaround is good enough. Should I submit a bug to PyCharm?

**Comment by willmcgugan** [comment]
Might be worth filing a bug report. Tell them that `isatty()` is returning False.

**Comment by willmcgugan** [comment]
@akrk1986 going to close this one, but let me know if you get a response from PyCharm devs...

**Comment by akrk1986** [comment]
Will let you know. Thanks a lot for the quick response and great package!

**Comment by akrk1986** [comment]
Just FYI, bug was accepted by PyCharm: **Issue PY-43860**

**Comment by akrk1986** [comment]
Hi Will, 
Here is the answer I got from PyCharm:
**"Hi, have you tried to enable emulate terminal in output console option in run/debug configuration? This should do the trick."**
It seems that the non-terminal behavior is the default in PyCharm.
IMHO, it's worth mentioning in the rich documentation, perhaps under 'known issues'. 
Unfortunately, I don't have time to submit a PR for that.
Keep up the good work!
Amir

**Comment by ChristianSauer** [comment]
@akrk1986 Thank you. I have used for the first time and was wondering why no progress bar was visible at all - setting the emulation fixes this. WOuld  be great if this is in the docs.

**Comment by j4hangir** [comment]
> Hi Will,
> Here is the answer I got from PyCharm:
> **"Hi, have you tried to enable emulate terminal in output console option in run/debug configuration? This should do the trick."**
> It seems that the non-terminal behavior is the default in PyCharm.
> IMHO, it's worth mentioning in the rich documentation, perhaps under 'known issues'.
> Unfortunately, I don't have time to submit a PR for that.
> Keep up the good work!
> Amir

You're right, please add this to the docs.

**Comment by willmcgugan** [comment]
It's on the first page in a blue box. https://rich.readthedocs.io/en/latest/introduction.html

**Comment by j4hangir** [comment]
> It's on the first page in a blue box. https://rich.readthedocs.io/en/latest/introduction.html

Thanks 👍🏻  I meant in github but I guess that'll do as well.

Out of curiosity, is there no easy way to make it work out of the box? The other libs I used before usually worked in PyCharm without the need for `emulate in terminal`.

**Comment by willmcgugan** [comment]
Not without breaking things for other users.

**Comment by cowwoc** [comment]
FYI, per https://youtrack.jetbrains.com/issue/PY-29204 IntelliJ removed this feature. There is no such option in version 2021.2.3 and no indication of when it will come back. Are there any other workarounds?

**Comment by kageanrage** [comment]
> 

I'm also unable to make this work in PyCharm in Windows, and unsure how to apply Will's suggestion:

console = Console(color_system="windows")

**Comment by togrul2** [comment]
Hi, In PyCharm 2022.1.3 seems there is no emulate terminal in output console for run configurations. Still have that problem with red logs in the console. Does anyone know how to solve this problem?

**Comment by tjnd89** [comment]
@AntonyMilneQB see https://stackoverflow.com/questions/20333674/pycharm-logging-output-colours. I think if you change your streamhandler to explicitly write to stdout it should get rid of the red logs.

**Comment by Biblebrox** [comment]
![изображение](https://github.com/Textualize/rich/assets/46165137/e75994c4-e2ce-4d2d-b555-36599f8e0aeb)
![изображение](https://github.com/Textualize/rich/assets/46165137/f5b529c6-2e1c-4cec-a5e8-1c046cca802c)

**Comment by nonchris** [comment]
This solved the problem for me too.  
Note: Pycharm moved that option to "Modify option" in the Run Config menu with their UI rework.
![image](https://github.com/user-attachments/assets/f5fa6fad-a331-4115-8882-851c073a2bbc)

**Comment by Liquidmasl** [comment]
Emulate terminal works so that we have colors, but it doesnt work as debug console anymore, which is quite annoying ):

**Comment by tjnd89** [comment]
> Emulate terminal works so that we have colors, but it doesnt work as debug console anymore, which is quite annoying ):

@Liquidmasl unfortunately this is something PyCharm has to fix, not a Textualize issue.
