### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by umazanatastatura** [willmcgugan/rich#216]
When I try something like this in a table:

```
smth = f"\u001b]8;;{target}\u001b\\{text}\u001b]8;;\u001b\\"
table.add_row(smth)
```

It breaks my table. So the question would be: is it possible (and how) to add html-like links to table without breaking it?
I use tilix terminal that supports html-like links and when I print smth variable it works, and it works in a table too but also displaces right border of a cell. So request would be to enable html-like links in tables (maybe it already works but I don't know how to write it). Great library btw.

**Comment by willmcgugan** [comment]
I guess you discovered the link support?

**Comment by umazanatastatura** [comment]
yes, from your blog :D
