### ISSUE TITLE
[BUG] Progress bars not advancing in jupyter-lab notebook

### ISSUE THREAD

**Issue by ziofil** [willmcgugan/rich#218]
**Describe the bug**
The bars remain stuck until I interrupt the process; only then they get updated. However, the default `rich.progress.track()` works out of the box.

**To Reproduce**
Just copy/paste and run the 1st example in [Advanced usage](https://rich.readthedocs.io/en/latest/progress.html#advanced-usage). Must be in jupyter notebook (in the terminal it works).

**Platform**
macos 10.15.5, rich 5.0.0, jupyter-lab 2.2.0

**Comment by willmcgugan** [comment]
Auto refresh doesn't work in Jupyter. See the info panel [here](https://rich.readthedocs.io/en/latest/progress.html)

**Comment by ziofil** [comment]
Oh, I had missed that, thanks!
By the way, I just want to tell you how much I'm appreciating reading through your code!

**Comment by willmcgugan** [comment]
Good to know someone reads it. :)
