### ISSUE TITLE
rainbow.py example needs updated

### ISSUE THREAD

**Issue by ColMcp** [willmcgugan/rich#220]
The colour specification in RainbowHighlighter needs updated to use the current format. The example uses 

    `text.stylize(str(randint(16, 255)), index, index + 1)` 

which results in no colourisation. I changed it to 

    `text.stylize(f"color({randint(16, 255)})", index, index + 1)` 

which works OK.

I'm using CPython 3.8.5 in Terminal 2.10 (433) on macOS 10.15.6 (19G73).

**Comment by willmcgugan** [comment]
Good spot. I'll fix that.

**Comment by willmcgugan** [comment]
Fixed in 5.10
