### ISSUE TITLE
[REQUEST] Use of emojis in Markdown

### ISSUE THREAD

**Issue by towa** [willmcgugan/rich#231]
Hello,
I really enjoy this project. Thinking about building it into my encrypted diary project.
I would love to use markdown and emojis in my journal entries. Right now this doesn't seem to be supported.
So I would have to choose to use either emojis or markdown.

:+1: :smile:

**Comment by willmcgugan** [comment]
I guess you mean emoji code? It probably doesn't need to be part of the Markdown class as you can pre-process your markdown prior to printing it. Something like this:

```python
from rich.emoji import Emoji
markdown = "# Hello World :thumbs_up:"
markdown = Emoji.replace(markdown)
```

Send me the repos for your repos project if you like, sounds interesting...

**Comment by towa** [comment]
That does the trick. Thanks a lot!
I don't have my projekt published on github yet (since its a still a mess).
But if I do so I will let you know :)
