### ISSUE TITLE
[BUG] Installing in REPL breaks _ builtin

### ISSUE THREAD

**Issue by The-Compiler** [willmcgugan/rich#235]
**Describe the bug**
When using `from rich import pretty; pretty.install()`, the `_` (last result) functionality of Python's REPL breaks.

**To Reproduce**

Without rich:

```pycon
>>> 5 + 10
15
>>> _ / 2
7.5
```

With rich:

```pycon
>>> from rich import pretty
>>> pretty.install()
>>> 5 + 10
15
>>> _ / 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '_' is not defined
```

When rich is installed after the first expression:

```pycon
>>> 1300 + 36
1336
>>> from rich import pretty
>>> pretty.install()
>>> 21 * 2
42
>>> _ + 1
1337
```

**Platform**
Linux, rich 5.1.2 and 5.2.0, Python 3.8.5

**Comment by willmcgugan** [comment]
Please try v5.2.1
