### ISSUE TITLE
rich.logging undocumented?

### ISSUE THREAD

**Issue by bphunter1972** [willmcgugan/rich#24]
Your [blog post](https://www.willmcgugan.com/blog/tech/post/prettier-logging-with-rich) refers to `rich.logging.RichHandler`, which is present in the code, but doesn't show up in [ReadTheDocs](https://rich.readthedocs.io/en/latest/index.html).

**Comment by willmcgugan** [comment]
Added https://rich.readthedocs.io/en/latest/reference/logging.html

There's not much to it, tbh. To customize, its probably easier to copy that class and modify it.
