### ISSUE TITLE
Django Logging Formatting Issue

### ISSUE THREAD

**Issue by WayneLambert** [willmcgugan/rich#240]
Hi @willmcgugan,

I would just like to ask about configuration for the logging formatting/handling within Django.

Following [your post on your blog](https://www.willmcgugan.com/blog/tech/post/richer-django-logging/), I have attempted to configure my own logging within my Django project.

There are 2 major differences between what your blog post, and indeed the project's `README` displays when compared to my implementation.

For reference, your blog post's screenshot:

![image](https://user-images.githubusercontent.com/44729076/90659205-50383f00-e23c-11ea-899c-ad2b74fa50c4.png)

The project's README screenshot (albeit not Django):

![image](https://user-images.githubusercontent.com/44729076/90659280-63e3a580-e23c-11ea-99d2-651dabbb85e4.png)

My implementation displays as:

![django-logging-with-rich](https://user-images.githubusercontent.com/44729076/90661321-f6854400-e23e-11ea-94b1-764902121c36.png)

There are 2 issues with the way my logging is formatted:

1. You will see that my logging does not have the colorised formatting.

1. The width is somewhat constrained even though the width of my iTerm terminal window is plenty wide enough. Even when I widen it further, it remains constrained in its width.

It's worth mentioning that my project is in Docker, so I don't know if that's an issue. I have also tested reviewing the development server output within the stock `terminal` app in Mac OS which gave me the same result.

The timed grouping (with just the time element) and the warning levels both look good so it appears the Rich config is somewhat working.

@willmcgugan For reference, do you have an exact commit reference that points exactly to the `settings.py` file you referred to in your blog post? Should it matter if it's in Docker instead of just Django's local development server?

I don't know whether this is a config issue from my side, or whether there is a bug or missing feature from Rich itself.

My full logging config in my `settings.py` file is:

```python
...

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,

        'filters': {
            'skip_static_requests': {
                '()': 'django.utils.log.CallbackFilter',
                'callback': skip_static_requests,
            }
        },

        'formatters': {
            'rich': {'datefmt': '[%X]'},
        },

        'handlers': {
            'console': {
                'class': 'rich.logging.RichHandler',
                'formatter': 'rich',
                'level': 'INFO',
                'filters': ['skip_static_requests'],
            }
        },

        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        }
    }
...
```

Please could you advise?

Many thanks,

Wayne

**Comment by willmcgugan** [comment]
Hi Wayne,

I suspect what is happening is that Rich has detected that it is not writing to a terminal. When that happens, color will be disabled and the width will default to 80.

Docker might explain that, but if you are saying that you get the same result with terminal, then maybe there is something else capturing output.

If you could add this to your project somewhere, it will give us more information:

```python
from rich import get_console
print(get_console())
print(get_console().file)
```

Also, please check you are running the latest version from Pypi

**Comment by WayneLambert** [comment]
Hi Will,

Thanks for your very fast reply.

I added the snippet to my project and it gave the following output within the dev server.

![django-logging-with-rich2](https://user-images.githubusercontent.com/44729076/90664369-bcb63c80-e242-11ea-90dd-c67ced0b321d.png)

Just a few things to clarify:

I am using Docker within iTerm (like screenshot) and did an additional test still using Docker (i.e. `docker-compose up`) but within the standard terminal app. The same result appears in both.

I haven't actually tested my logging config in any other project using Django's standard `runserver` command on `localhost:8000` so I wouldn't know if that works. I am guessing it would as per your blog post because I cannot see anything wrong with my config.

Yes, I am using the most recent version from PyPi `v5.2.0`

**Comment by WayneLambert** [comment]
Hi Will,

Further to above and your original answer, I did some research and found the following [StackOverflow post](https://stackoverflow.com/questions/28072259/when-running-a-django-dev-server-with-docker-fig-why-is-some-of-the-log-output).

It suggested that I need the following key adding to my `web` service (for my setup) within my `docker-compose.yml` file:

```yml
tty: true
```

Following that addition, then rebuilding my images and bring up the containers again, I now have...

![django-logging-with-rich3](https://user-images.githubusercontent.com/44729076/90666562-7c0bf280-e245-11ea-8fa8-9eafd9065fbb.png)

As you can see, now I have colour, however the width still seems to be constrained to 80 chars.

**Comment by willmcgugan** [comment]
That's progress.

can you do `print(get_console().size)`.

I suspect that will return 80x25 which means it has failed to detect the terminal size, or it has been override somehow.

Can you also do `print(shutil.get_terminal_size())` which is the terminal size as reported by the OS.

**Comment by WayneLambert** [comment]
OK, following a bit more research, I found a solution to the issue.

There is a variable in `zsh` (and other Unix shells) called `COLUMNS`. From this discovery, I then amended the `Dockerfile` responsible for the dev build and added a step within it's build process:

```Dockerfile
...
# Set the COLUMNS variable for the terminal's output width
ENV COLUMNS 164
...
```

Someone else may need to customise that value for their desired window width.

After the rebuild, bringing the container (dev server) back up, and widening the iTerm window, it gave me the following:

![django-logging-with-rich6](https://user-images.githubusercontent.com/44729076/90677909-ee84ce80-e255-11ea-815c-90ef27e35dd0.png)

Perfect!

For anyone wanting to use Django, Docker, and Rich together, I have recorded the overall solution to the issue in a commit.

- [Changes Required Git Diff](https://github.com/WayneLambert/portfolio/commit/15de5f40b8bf2caec18710a926428dce3f35357a)
- Check the [settings.py](https://github.com/WayneLambert/portfolio/blob/15de5f40b8bf2caec18710a926428dce3f35357a/ab_back_end/settings.py#L121) file for the LOGGING config

Thanks for your help, @willmcgugan
