### ISSUE TITLE
Is it possible to print a table row by row on the console? 

### ISSUE THREAD

**Issue by bedangSen** [willmcgugan/rich#241]
I am generating a table in a for loop. And I want to print each row as I iterate through the loop. Is this possible? 

I tried printing it, but it prints the entire table at every iteration.

**Comment by willmcgugan** [comment]
Afraid not, all the rows are needed before it it can calculate the column dimensions.

You *can* move the cursor redraw the entire table so it appears to add a row. See the undocumented `live_render.py` which is what the progress bars use.

**Comment by bedangSen** [comment]
Ahh thanks for the hint, I'll check that out!
