### ISSUE TITLE
[REQUEST] validation of input beside choice and y/n

### ISSUE THREAD

**Issue by ezzra** [willmcgugan/rich#242]
Currently there is a kind of input validation when you use `Confirm` or `choices`, this could be extended to a manually validation procedure for example a regex match. I propose something like:

`Prompt.ask('please enter your birthdate', validate=r'\d\d.\d\d.\d\d\d\d')`

and it will loop as long as the input isn't matched, like with `Confirm()` or `choices=`

(yes I know, the example regex pattern does not really validate dates ;) just an example)

**Comment by willmcgugan** [comment]
That might be convenient, but you don't get the opportunity to return a friendly error message. I'll consider it.

In the meantime, you can extend prompt and override the `process_response` method. Raise `InvalidResponse` if the regex doesn't validate/
