### ISSUE TITLE
[BUG] overflow='ignore' not documented

### ISSUE THREAD

**Issue by bphunter1972** [willmcgugan/rich#243]
**Describe the bug**
I have a script that looks at some files and then prints commands to the console. In order to copy the whole command, it's important that the line not have any line breaks. With the `console.print` command, this requires `overflow` to be 'ignore', which is mentioned at https://rich.readthedocs.io/en/latest/console.html#overflow, but is undocumented in the reference.

It **also** requires `crop` to be set to False, which leads to another issue: Why is there a `crop` argument, **and** an `overflow` argument which itself can be set to 'crop'. It seems like there's something here that could be optimized out.

**Comment by willmcgugan** [comment]
Where would you expect to see it documented?

> It also requires crop to be set to False, which leads to another issue: Why is there a crop argument, and an overflow argument which itself can be set to 'crop'. It seems like there's something here that could be optimized out.

Overflow affects text only. The `crop` parameter is also used for other renderables.

The ignore overflow method may be misnamed, as its a different concept to other possible values. I'm considering a new parameter.

**Comment by bphunter1972** [comment]
> Where would you expect to see it documented?

console.py, line 663.

**Comment by willmcgugan** [comment]
v6.0.0 has a `soft_wrap` flag for this behaviour. https://rich.readthedocs.io/en/latest/console.html#soft-wrapping
