### ISSUE TITLE
[REQUEST] rich.print != rich.console.print

### ISSUE THREAD

**Issue by bphunter1972** [willmcgugan/rich#244]
Putting `from rich import print` at the top of your imports is a nice quick way to load in the power of rich without setting up a console and all that.

However, this version of `print` does not expose all of the arguments one gets from `console.print`. `rich.print` provides `sep`, `end`, `file`, and `flush`--presumably because this is intended as a drop-in replacement for Python's own `print` function.

But, I don't think there is a technical reason why it cannot also include `highlight`, `overflow`, and all the rest. Perhaps it's because one might do this and then hope it will still work everywhere:

```python
try:
    from rich import print
except ImportError:
    pass

print("This still works")
print("But this doesn't", justify='right')
```

**How would you improve Rich?**

Oh sure, one could do this:

```python
from rich.console import Console
console = Console()
print = console.print
print('But this is clunky', justify='right')
```

But, maybe offering the extended version of `print` without having to set up a console is better? Perhaps:

```python
from rich import superprint as print
print("This still works")
print("So does this!", justify='right')
```

**Comment by willmcgugan** [comment]
A few reasons...

1) I want the rich print to be interchangeable with the builtin print, which means it shouldn't break if you add or remove it. The import example you gave is a good example of that.

2) The Console.print isn't exactly a superset of builtin print. Builtin print has file and flush. Console.print has one file per console instance and doesn't need flush.

3) I want to encourage use of a console object, ideally a singleton for the project. It exposes a lot more functionality that a single function, and is configurable.

If you want it, I'd suggest putting it in a file and doing `from my_project import print`. I wouldn't say that was clunky.

**Comment by bphunter1972** [comment]
Fair enough.
