### ISSUE TITLE
[BUG] Impossible to save_html after save_text and vice versa

### ISSUE THREAD

**Issue by aquemy** [willmcgugan/rich#245]
First of all, thank you for this amazing piece of software. 🌷 

**Describe the bug**

The file saved using Console.save_html after using Console.save_txt is empty.
Same thing happens the other way around.

**To Reproduce**

```python
from rich.console import Console
console = Console(record=True)
console.print('test')

console.save_html('test.html')  # <- OK
console.save_text('test.txt')   # <- Empty
```

**Platform**
Linux (Ubuntu), using Guake (top-down), Rich v5.2

**Comment by willmcgugan** [comment]
The buffer is normally cleared after a save. Set `clear=False` to preserve the buffer.

**Comment by aquemy** [comment]
Thanks for the fast answer. I was about to say that after I checked `console.py`.
I close as it is not an issue but a PEBKAC!
