### ISSUE TITLE
is it possible to replace lines?

### ISSUE THREAD

**Issue by jeyca** [willmcgugan/rich#252]
I would like to build a custom progress indicator, very simple just a blinking `#` char at the first position of a line. In the end it should change to `✔`. Therefore i would need to replace the whole line within a loop I guess, can I solve this with `rich.console.print()` ?

(I know there is the rich progress bar, but I would like to build that more simple solution)

**Comment by jeyca** [comment]
ok, I looked it up, but I have no idea how to use that?

**Comment by willmcgugan** [comment]
Something along these lines...

```python
from rich import print
from rich.live_render import LiveRender
from time import sleep


live = LiveRender("")

for n in range(20):
    live.set_renderable(str(n))
    print(live.position_cursor())
    print(live)
    sleep(0.1)
```

**Comment by jeyca** [comment]
ok I got it working for my purpose, thanks! Do you plan, adding this as a easier available feature for rich?

**Comment by willmcgugan** [comment]
Potentially. So you want a single status line that can be updated? Maybe combined with an ascii animation to indicate something is happening.

**Comment by horseinthesky** [comment]
@willmcgugan
Hello.
Regarding your last comment, is it possible to have single status line that can be updated?
Something lime `console` example https://github.com/willmcgugan/rich#status but be able to update status text from inside `with` block?

**Comment by willmcgugan** [comment]
Yes, call [update](https://rich.readthedocs.io/en/latest/reference/status.html) on the status object.

```python
with console.status("working") as status:
    do_stuff()
    status.update(status="part 2")
    do_stuff
```

**Comment by horseinthesky** [comment]
@willmcgugan 
Just found it in a source code.
Works like a charm. Such an amazing library. Thank you =)
