### ISSUE TITLE
Document RenderGroup and render_group decorator

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#253]
I am facing an adoption issue caused by the fact that it seems not possible to treat rendable objects as string and concatenate them. This seems related to recent https://github.com/willmcgugan/rich/issues/247 so I guess I am not the only one.

I had code that produced both Markdown and tables and I wanted to display it all at once. 

Before rich (or with classic ANSI) it was easy to concatenate the strings into a result and perform a print(result) at the end. 

**Details**

I have practical example at https://github.com/ansible/ansible-lint/pull/978/files where I am trying to print a list of rules using rich formatting. Our implementation allowed printing these using various formats where each format was a function returning a string.

Now, with rich this really become an issue because I cannot return a string to be printed. In fact, even if I switch to use console.print() in all cases I am unable to return what is to be printed because each rule renders as a table. That is why in my initial PR, I tried to do console.print(table) for each rule and return an empty string.

Obviously that my implementation is more of a hack, and not a nice one. Is there a better way to implement that?

My hope was that maybe `render()` would return a string that I can later print, but apparently it returns a generator, so clearly not something that I can concatenate and print later.

**Comment by willmcgugan** [comment]
Do you have to return a str?

I gather you are mapping a format name on to a callable that gets the result. If your callable returns a renderable (which includes str), you can print that without converting to str.

There is an as yet undocumented RenderGroup class which turns a list of renderables in to a single renderable, in effect concatenating them. And a @render_group() decorator which combines a generator in to a render group.

I think you could keep your pattern, with only small changes. Something like this...

```python
formatted_rules = _rule_format_map[options.format](rules)
console.print(formatted_rules, highlight=False)  # You probably don't want auto-highlighting here
```

```python
from rich.console import render_group

@render_group
def rules_as_rich(rules: RulesCollection) -> Iterable[Table]:
    """Print documentation for a list of rules, returns empty string."""
    for d in rules:
        table = Table(show_header=True, header_style="title", box=box.MINIMAL)
        table.add_column(d.id, style="dim", width=16)
        table.add_column(Markdown(d.shortdesc))
        table.add_row("description", Markdown(d.description))
        table.add_row("version_added", d.version_added)
        table.add_row("tags", ", ".join(d.tags))
        table.add_row("severity", d.severity)
        yield table
```

The render group stuff will be documented in a future update, I've only recently finalized the interface.

In general, there is very little reason to ever convert renderables to strings. The only use I've found for it is unit tests.

**Comment by ssbarnea** [comment]
I think something is missing from this example because I was not able get it to work as you described. I tried to produce a single test file but it still fails:

```
from rich.console import render_group, Console
from rich.table import Table


@render_group
def multiple_tables():
    for d in [1, 2, 3]:
        yield Table()


console = Console()
console.print("foo")

x = multiple_tables()
console.print(x, highlight=False)
```
Outcome
```
x = multiple_tables()
TypeError: decorator() missing 1 required positional argument: 'method'
```

I tried with version 6.0.0 release today.

**Comment by willmcgugan** [comment]
My mistake, the decorator needs to be called, ie @render_group()

**Comment by willmcgugan** [comment]
Documented here... https://rich.readthedocs.io/en/latest/group.html
