### ISSUE TITLE
[Question] Most idiomatic way to mix styles in same line.

### ISSUE THREAD

**Issue by paw-lu** [willmcgugan/rich#257]
Love the library, really thankful for your work here.

## What I want to do

Use two different colors on the same line.

## How I currently achieve this

[Following the documentation on styles](https://rich.readthedocs.io/en/latest/style.html#style-themes) I use the markup api to achieve different colors, and it works great!

```python
from rich.console import Console
from rich.theme import Theme
custom_theme = Theme({
    "red": "#FF0000",
    "green": "#00FF00"
})
console = Console(theme=custom_theme)
console.print("[red]this is red[/red] [green]and this is green[/green]")
```

## Question

Is there another/better way to mix styles in the same line? Or are the markup tags the best method to achieve this?

**Comment by willmcgugan** [comment]
You can also use the rich [Text](https://rich.readthedocs.io/en/latest/text.html) class to add styles, if you want to build strings programatically.

**Comment by paw-lu** [comment]
Can't believe I missed that. This is exactly what I had in mind. Thank you so much!
