### ISSUE TITLE
[REQUEST] Default syntax rendering for inline code using Markdown

### ISSUE THREAD

**Issue by aroberge** [willmcgugan/rich#258]
No similar issue: I have checked and did not see a similar feature request in any issue (open or close) with the word "code".

**How would you improve Rich?**

It would be nice if inline markdown code, `like this`, could be rendered by pygments in a default theme+language (lexer) for consistency with the way that code blocks are rendered instead of in a uniform style defined by `markdown.code`.

**What problem does it solved for you?**

In one of my project (friendly-traceback), I use code-blocks to show where an exception was raised. I then add some text, explaining the source of the problem, in which either single identifiers or parts of a line of code  are inserted in a phrase using single backticks to identify as code. The lack of consistency in styling is less than ideal.

Note: I have looked at rich's own code to see if I could monkeypatch it (which I do for some other things in my project) and could not find an easy way to do what I would like it to do.  I've also used markdown with Sphinx, which uses Python as a default for code blocks and found that it too was not rendering inline code as Python code with the appropriate pygments theme. As far as I could tell, it does not look like something that would be easy to do and would completely understand if this issue would be closed with "won't fix".  However, if it looks like it **might** be possible to monkeypatch rich (and/or commonmark?) to do this, I would appreciate if I could get some pointers as I would be willing to experiment further on my own.

**Comment by willmcgugan** [comment]
Hi André,

I agree this would be a nice feature, but it would have to be optional. There's no way to specify the lexer with inline code, so I wouldn't want to presume.

I don't see any way to implement this without a patch to the Markdown class, but the good new is I don't think its a big change. The [Syntax._highlight](https://github.com/willmcgugan/rich/blob/master/rich/syntax.py#L176-L189) method returns a Text instance with syntax highlighting applied. That could be adapted to style the inline text in the Markdown class, probably somewhere [here](https://github.com/willmcgugan/rich/blob/master/rich/markdown.py#L461).

I think it would be worthwhile to implement this, but I'm taking a short break from Rich. If you would like to tackle it yourself and submit a PR I could advise...

**Comment by aroberge** [comment]
Hi Will,

Thanks for your prompt response. You certainly deserve a rest after the continuous enhancements you have made to rich!

I will have a look and if I can implement it as an option, I will submit a PR.

**Comment by aroberge** [comment]
Just for information: I've made some progress.

The output of
```python
from rich.markdown import Markdown
from rich.console import Console

test = "The program `print('Hello world!')` has to be test number `1`."

con1 = Console()
con1.print(Markdown(test))

con2 = Console(inline_code_lexer="python")
con2.print(Markdown(test))
```
is the following:
![image](https://user-images.githubusercontent.com/629698/91664839-1d0d6f80-eac8-11ea-9240-827ce05815fa.png)

I hope to have some time to figure out how to make it work later tonight or tomorrow.

Assuming this idea would be acceptable, would you prefer another name to `inline_code_lexer`?

**Comment by willmcgugan** [comment]
Getting there!

> Assuming this idea would be acceptable, would you prefer another name to inline_code_lexer?

Works for me.

**Comment by aroberge** [comment]
I made some small progress, but I am stumped. Please note that **this is not urgent**.  I should probably put it aside for a few days as I have other work to do...

I believe that I understand the logic of what I have to do but, somehow, I cannot find a way to do it.
I've created a class, `InlineCode(TextElement)` which does the syntax highlighting correctly.

I can use it in the markdown processing so that it correctly identifies and does the highlighting of the code.  However,
I do not know how to append/insert the resulting highlighted code in the markdown text.  As a check that I am doing the highlighting correctly, I use a `yield from` statement to render the code after I do the syntax highlighting
```python
            elif node_type == "code" and options.inline_code_lexer is not None:
                element_class = self.elements.get(node_type)
                element = element_class.create(self, current)
                context.stack.push(element)
                element.on_enter(context)
                element.on_text(context, current.literal)
                context.stack.pop()
                yield from console.render(element, context.options)
                element.on_leave(context)
```
I do know that I am not supposed to use the yield statement there. However, I cannot find a way to insert the highlighted code at its proper place.

I have added a `highlight()` method to my `InlineCode` class, based on `Syntax._highlight` so that I could get a string output, hoping that I could  insert it at the proper location. If I use it like this:

If I try to do something like
```python
                context.on_text(element.highlight(context))
```
I get a traceback with `ValueError: style must not be set when appending Text instance`.
Attempting to do `context.leave_style()` before that statement does not help.

Again, please note that this is not an urgent request; I just want to record what I have done so far.

**Comment by willmcgugan** [comment]
I think you're on the right track, but you probably aren't going to need the extra InlineCode class or condition. The inline styles are treated differently as they are rendered within the text of the "element" classes. i.e. the inline code may be in inside a list context, or paragraph, or header.

> context.on_text(element.highlight(context))

This should be enough to render the inline code with highlighting. The error you're getting is because this ultimately calls Text.append which can accept either a `str` plus `style` or a Text instance, but not a Text + style.

I think the simplest addition to get this to work would be for on_text to grow an `node_type` parameter, then [TextElement.on_text](https://github.com/willmcgugan/rich/blob/master/rich/markdown.py#L102) can handle the special case for "code" types.

**Comment by willmcgugan** [comment]
Hi @aroberge Just to let you know I've started work on this https://github.com/willmcgugan/rich/pull/277

Naturally there is more to it than I initially thought!

**Comment by aroberge** [comment]
Thanks!  I've been really busy with my day job (as a new Academic Year begins at our university) and have not had time to look at this. I really appreciate that you are tackling it.

**Comment by willmcgugan** [comment]
v6.2.0 has inline code highlighting in Markdown. Set `inline_code_lexer="python"` on the Markdown constructor to enable it...
