### ISSUE TITLE
[REQUEST] A way to pipe directly into a Console (without anything showing in the terminal instance)

### ISSUE THREAD

**Issue by tilda** [willmcgugan/rich#259]
Have you checked the issues for a similar suggestions? Yes, unless I'm searching wrong, no one else has suggested this.

**How would you improve Rich?**

Being able to just pipe something like a `Table` in and getting plaintext output out would be nice to have.

**What problem does it solved for you?**

I am currently attempting to make this library work with my Discord bot. It works great for i.e. tracebacks in console, and can also work with Discord's codeblock formatting in a way using `export_text()`: 
![image](https://user-images.githubusercontent.com/8301262/91700639-d5283000-eb3b-11ea-98ba-0f3a4465a828.png)

... There is just *one* tiny problem.

Whenever I run the `^^config list` command, it seems to log to console too:
![image](https://user-images.githubusercontent.com/8301262/91700832-0f91cd00-eb3c-11ea-8d1b-4b10a1d0b8fe.png)

This might not be bad for a small developer instance like mine where I'm just testing stuff, but it doesn't really work out in production, as I don't want to see a lot of command outputs in my logs.

This problem can very easily be tracked down to the function where I "construct" the table:

```py
    async def construct_table(self, parts):
        table = Table(show_header=True)
        table.add_column("Property")
        table.add_column("Value")
        async for part in parts:
            table.add_row(part["property"], part["value"])
        self.rich_console.print(table) # Required to "record" the output so we can export it to text
        return self.rich_console.export_text()
```

Personally not sure how to best tackle this issue; maybe a `Console.record()`?

Love this lib, thanks for all that you do!

**Comment by willmcgugan** [comment]
You have a couple of options. 

Rather than export text, you could write to a StringIO and use that to get the table as a string. Something like this: 

```python
console = Console(file=io.StringIO())
console.print(table)
str_table = console.file.getvalue()
```

Or you could keep doing it the way you are now, but set the file to dev/null so nothing is printed to the console.

```python
console = Console(file=open(os.devnull, "wt"), record=True)
console.print(table)
str_table = console.export_text()
```

Hope that helps.

**Comment by tilda** [comment]
Hi!

I tried the first method, works great. 2nd method unfortunately doesn't work at least on Windows, which is where I am currently developing for the most part.

Anyways, issue is solved, so closing. Thanks for the help!
