### ISSUE TITLE
Support for rich outputs in jupyter notebooks

### ISSUE THREAD

**Issue by jjmachan** [willmcgugan/rich#26]
I was using rich for a ML project and find it super useful! Kudos for building this awesome project. 

I did have a feature request though

Can you add support for printing into notebooks. Jupyter notebooks does support rendering HTML and your library does export HTML and I was able to hack together some awesome outputs but it would be cool to have native support. Especially some _repr_html_ for attributes like table text etc.

I would love to help add this feature!

**Comment by jjmachan** [comment]
small correction, jupyter notebooks does support ASCII colors but the default settings of Rich console does not detect its and strips away the colors. Any suggetions to fix it?

**Comment by willmcgugan** [comment]
I don’t see why not. If it’s just a matter of adding that html_repr method, it’s not a lot of work.

Rich will disable colours if it doesn’t detect a terminal. It calls ‘istty’ on the file object. I’m guessing that Jupyter is wrapping stdout and breaking that somehow. I’ll look in to that, I’m sure there is a simple workaround.

**Comment by willmcgugan** [comment]
I did some experimentation, and I was correct about Jupyter wrapping stdout. `isatty` returns False, so Rich disables ANSI styles -- even though Jupyter is capable of rendering them. If I force Rich to enable styles they do work.

Another issue is detecting the size of the terminal. When running in Jupyter, the size is detected as the size of the terminal running the server, not the output area on the screen. This leads to things wrapping incorrectly and breaking tables etc.

I'm sure some form of integration is possible. Still thinking of how it should work. Let me know if you have any ideas on that front.

**Comment by willmcgugan** [comment]
I've added experimental support to v0.8.6, now on pypi.

If you do `from rich.jupyter import print` you can print any Rich renderable to the notebook.

**Comment by jjmachan** [comment]
Awesome!
Works really well even though the width is fixed rendering is proper
Thanks for being super responsive :smile:
