### ISSUE TITLE
[REQUEST/QUERY] Demarcation between rows of a table

### ISSUE THREAD

**Issue by e0lithic** [willmcgugan/rich#261]
Hi,

Going through the documentation and the library I didn't find a way where I could add a demarcation line between two rows of a table. My understanding is the box styles for the table are limited to the headers and footer. Additionally it seems like this is in the purview of the "row_styles". If so could you please give me pointers of achieving the same.

Thanks

**Comment by willmcgugan** [comment]
You can set `show_lines=True` on the Table constructor.

**Comment by e0lithic** [comment]
Thanks a lot.
