### ISSUE TITLE
[REQUEST] Arrow Keys and cursor control?

### ISSUE THREAD

**Issue by scherrey** [willmcgugan/rich#262]
I have a little language interpreter/repl that is begging for integration with rich. What I really need to be able to support, however, is a rapid input history access (via up/down arrows) and support cursor movements on a line of text. 

Is there a method for getting access to individual keystroke input with rich?

My target environment in linux but it would be nice if the feature was platform independent. I'm running Python 3.8. 

Just being able to use up arrow to repeat the last input command and (preferably) being able to edit it before executing would be a godsend in terms of usability improvements. Pretty much something like what bash presently offers.

**Comment by willmcgugan** [comment]
Rich doesn't offer any interactivity yet. It might in the future.

In the meantime, you might want to look at [prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit).

**Comment by scherrey** [comment]
Thanks I will check it out! Will see how prompt-toolkit and rich can co-exist.

**Comment by tinchit0** [comment]
For anyone interested, I managed to make it work by extending ```rich```'s console, integrating a ```PromptSession``` from ```prompt-toolkit```, and using it to handle calls to built-in ```input()``` function.

```python
from getpass import getpass

from prompt_toolkit import PromptSession
from prompt_toolkit.history import FileHistory
from rich.console import Console


class HistoryConsole(Console):
    def __init__(self, history="session_history", *args, **kwargs):
        self.history = FileHistory(history)
        self.session = PromptSession(history=self.history)
        return super().__init__(*args, **kwargs)

    def input(
        self, prompt="", markup=True, emoji=True, password=False, stream=None
    ) -> str:
        if prompt:
            self.print(prompt, markup=markup, emoji=emoji, end="")
        if password:
            result = getpass("", stream=stream)
        else:
            if stream:
                result = stream.readline()
            else:
                result = self.session.prompt("")
        return result
```

And that works fine:
```python
console = HistoryConsole()
response = Prompt.ask("[cyan]Tell me something[/cyan]", console=console)
```

This allows the prompt to accept up/down arrows for history navigation and even reverse-i-search.

That said, I still believe it would be great if ```rich``` included history support natively, without external dependencies.
