### ISSUE TITLE
Is there a way to do this like textwrap.fill does?

### ISSUE THREAD

**Issue by legacy-code** [willmcgugan/rich#263]
I am wondering if there is a way to do this in rich (sort of how textwrap does):

MyStr = textwrap.fill(line, width=xxx, initial_indent="", subsequent_indent="      ")

I love how rich handles the width of the screen, especially with colors, but it doesn't have an option for subsequent wraps.  

I'd like the output to look something like this:

```text
definition:      this is a short definition
another here:    this is a longer definition of 
     things here, that just keeps on going
     and going 
some other term: you get the idea now
```

Rather than what I get now:

```text

definition:      this is a short definition
another here:    this is a longer definition of 
things here, that just keeps on going and going 
some other term: you get the idea now
``` 

Colors help, but I would like the extra indent to differentiate as well.

A way around this would be if there was a function that would return the (colorized) string WITHOUT printing it.  Then I could call the textwrap functions myself.  I looked, and if there is one, I missed it.

Anyway, thanks for the great software.  Really like using it!

Thanks!
Mike

**Comment by willmcgugan** [comment]
Hi Mike, there is no equivalent of `subsequent_indent` in Rich, but I think it would look better to format it in a grid. Something like this:

```python
from rich import print
from rich.table import Table
definitions = Table.grid(padding=(0, 1))
definitions.add_row("definition:", "this is a short definition")
definitions.add_row("another here:", "this is a longer definition of things here, that just keeps on going and going")
print(definitions)
```

**Comment by legacy-code** [comment]
@willmcgugan I hadn't thought of that.  

Sure, that would work.  I'll explore that and see how I like it.

Btw, is there a function that would get the colorized string from rich but NOT print it?  I have some things that the table scenario might not work with.  I would still end up calling the rich console.print(), just a little later, after calling the textwrap function.

Thanks for the quick response!
Mike

**Comment by legacy-code** [comment]
@willmcgugan just tried it with the table solution and it works, so I'll play more with the formatting to see what it can do (I've never tried using the table at all, so I'm interested in seeing what it can do).

Still curious about getting the colorized string, but other than that, you can consider this issue closed.

Thanks for the help!

**Comment by willmcgugan** [comment]
You *can* render to a string with the following pattern:

```python
console = Console(file=io.StringIO(), force_terminal=True)
console.print(text)
table_str = console.file.getvalue()
```

Unfortunately you won't be able to use the result with textwrap, which won't handle the invisible control codes correctly.

**Comment by legacy-code** [comment]
@willmcgugan Thanks for the info.  

That's unfortunate with textwrap though.  Good to know that it can be done though!

Thanks for the quick turnaround!
