### ISSUE TITLE
[BUG] use of stderr colorize trick breaks ability to produce ANSI on stderr

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#265]
**Describe the bug**
While this is an unlikely advanced use-case, I should better mention it, in hope we can find a workaround for it.

There is a shell trick that is used by some users in order to colorize output received on stderr with a different color, making easier to distinguish nature of output for programs producing output on both streams.

There are several implementations available as it may differ a little bit between platforms or shells but it mainly looks like https://github.com/cehoffman/dotfiles/blob/master/zsh/config#L174-L193  

What happens is that stderr is redirected to an unnamed pipe before being added an ANSI coloring sequence for each line. 

This works fine with one exception: programs that verify `sys.stderr.isatty()` as a side effect of this approach is that this is no longer reports true.

Programs that do use only `sys.stdout.isatty()` to determine if ANSI is supported or not are not affected, as ANSI still works on stderr.

I am not yet sure which is the best approach to avoid this issue as I see pros and cons for all cases. I do see some users wanting to avoid ANSI on stderr, for example if they redirect output for log files.

**Comment by willmcgugan** [comment]
I doubt any trick such as this would work if you are writing style to stderr -- unless its smart enough to handle existing ansi codes. So if this trick is employed you probably want the default behavior of disabling color.

I don't think there is a solution from the Rich side. The app developer might want to provide a switch or env var to configure what is rendered to stderr, and configure the Console accordingly.
