### ISSUE TITLE
[BUG] Emojis show a question mark

### ISSUE THREAD

**Issue by EvokerKing** [willmcgugan/rich#267]
**Describe the bug**
When using an emoji, instead of showing an emoji, it shows a square with a question mark (?) in it.

**To Reproduce**
Use an emoji and run  the code

**Platform**
Platform: Windows 10, and PyCharm terminal
Terminal software: Cmd and PyCharm
Rich version: 6

**Comment by willmcgugan** [comment]
How a emoji displays is more to do with the terminal you're using than Rich. If you're using cmd.exe, make sure you are using ttf fonts -- the raster fonts don't have emojis. Or use the new Windows terminal which has good support for emoji.

**Comment by EvokerKing** [comment]
There's a new Windows terminal? Can you please explain how to get to it.

**Comment by willmcgugan** [comment]
https://devblogs.microsoft.com/commandline/introducing-windows-terminal/
