### ISSUE TITLE
[Question] How to print dynamic information?

### ISSUE THREAD

**Issue by skonik** [willmcgugan/rich#268]
Hi there.

I want to print my table data in dynamic way like in downloader examples where the bar is updated dynamically and rerendered.

I tried to do it with `.clear` but it looks awful because cleaning the terminal is very noticeable.
```python
        console.clear()
        console.print(table, justify='center')
```

Could you please give me some ideas how it could be done right?

**Comment by willmcgugan** [comment]
You may get better results if you put it inside the Console context manager, which tells Rich to render in a single batch. Something like this:

```python
with console:
    console.clear()
    console.print(table, justify="center")
```

Or you can use the [LiveRender](https://github.com/willmcgugan/rich/blob/master/rich/live_render.py) class used by the progress bars which clear only the specific lines changed.

**Comment by skonik** [comment]
Great. 
Context manager gives much better result.
Thank you.
