### ISSUE TITLE
Don't highlight all numbers

### ISSUE THREAD

**Issue by GeekDuanLian** [willmcgugan/rich#27]
![image](https://user-images.githubusercontent.com/6257434/77845127-dfd24800-71de-11ea-8f65-2ce4e0e53185.png)

such as UUID, it is a good choice to only highlight numbers with spaces before and after.

**Comment by willmcgugan** [comment]
I think what is happening there is that the escaped quotes are breaking the regex for string highlighting. Your uuids should be styled as strings. Should be an easy fix.

**Comment by GeekDuanLian** [comment]
The escaped quotes are not handled properly, but uuid is still highlighted incorrectly.

![image](https://user-images.githubusercontent.com/6257434/77847129-49595300-71ed-11ea-84f3-a24322dfdab0.png)

**Comment by willmcgugan** [comment]
Please give 0.8.5 a try. I've made some changes to number / string highlighting. And added a uuid highlighter.

It's never going to be perfect, but this should be an improvement.

**Comment by GeekDuanLian** [comment]
There are indeed some improvements! My terminal has become more beautiful, thanks for the fix!
