### ISSUE TITLE
[BUG] '#' sign is treated as the end of a URL

### ISSUE THREAD

**Issue by aklajnert** [willmcgugan/rich#272]
**Describe the bug**
The `#` a valid element of the URL, but Rich seems to ignore it and treats it as the end of it. 
Consider this URL: https://github.com/willmcgugan/rich#rich-print-function

**To Reproduce**
```python
from rich.console import Console

console = Console()

console.log("https://github.com/willmcgugan/rich#rich-print-function")
```

Output:  
![image](https://user-images.githubusercontent.com/18279161/92566941-44f59380-f27d-11ea-908d-64d01e224087.png)

**Platform**
I'm using Rich on Windows and Linux, with the currently newest version `6.1.1`.

**Comment by willmcgugan** [comment]
https://github.com/willmcgugan/rich/blob/master/rich/highlighter.py#L82

Any chance of a PR ?

**Comment by aklajnert** [comment]
Sure, happy to try it.
