### ISSUE TITLE
[REQUEST] reset progress bar

### ISSUE THREAD

**Issue by nschloe** [willmcgugan/rich#274]
As far as I can see, it's only possible to `advance` progress bars, not to reset. This makes it impossible to create nested progress bars.

MWE:
```python
import time
from rich.progress import Progress

m = 7
n = 5

with Progress() as progress:
    task1 = progress.add_task("Overall", total=m)
    task2 = progress.add_task("Subtask", total=n)
    for i in range(m):
        progress.update(task1, advance=1)
        # progress.update(task2, reset=True) #?
        for j in range(n):
            progress.update(task2, advance=1)
            time.sleep(0.2)
```

**Comment by willmcgugan** [comment]
Does `progress.update(task1, completed=0)` not work?

**Comment by nschloe** [comment]
I just found that, too. Yes, it works, thank you!

**Comment by dougsouza** [comment]
> Does `progress.update(task1, completed=0)` not work?

It works partially, it resets the progress but does not reset timing estimates (elapsed and remaining, for example)

In my case, for it to work properly, I had to remove and the nested task at each iteration. It would be nice if we have an interface to completely reset the task.
