### ISSUE TITLE
[REQUEST] console print to string

### ISSUE THREAD

**Issue by nschloe** [willmcgugan/rich#275]
I would like to use rich in a `__repr__` method, meaning that I have to get hold of a `str`.
```python
console.print(table)
```
already prints the right thing for me; can I get that same output as a string?

**Comment by willmcgugan** [comment]
That's the pattern I usually recommend. Bear in mind that color and style will be disabled unless you add `force_terminal=True`, and you may want to set `width` or it will auto-detect the current terminal width.
