### ISSUE TITLE
[REQUEST]Please consider adding MAC/OUI highlighting - similar to IP Address/URL highlighting 

### ISSUE THREAD

**Issue by wilmington** [willmcgugan/rich#279]
**Add MAC-address oui highlighting**

It'd be a useful addition if Rich could consistently handle highlighting of the multiple mac-address/oui formats that exist

e.g.
000c.298c.500f
0:c:29:8c:50:f
00:0C:29:8C:50:0F
00-0C-29-8C-50-0F
00:0c:29:8c:50:0f

**Comment by willmcgugan** [comment]
It’s possible. Do you know of a regex for mac addresses?

**Comment by wilmington** [comment]
https://regex101.com/library/yS8eO4 perhaps?

**Comment by Edward-Knight** [comment]
What default style would be fitting for this?
Should we match the existing style for IP addresses?
https://github.com/willmcgugan/rich/blob/ebb4eaa26f6c557daf4d03540f21ea277a02824e/rich/default_styles.py#L62-L63
Or perhaps the same as a UUID?
https://github.com/willmcgugan/rich/blob/ebb4eaa26f6c557daf4d03540f21ea277a02824e/rich/default_styles.py#L76

**Comment by willmcgugan** [comment]
I think it's closer to a IP address, conceptually. Makes sense to use the same style.

**Comment by Edward-Knight** [comment]
Cool, I'll start working on a patch for this :+1:

**Comment by Edward-Knight** [comment]
I'll add highlighting for IEEE EUI-48 and EUI-64 (mac addresses) accepting three formats:

* Six (EUI-48) or eight (EUI-64) groups of two hex digits with hyphen separators: `01-23-45-67-89-AB` or `01-23-45-FF-FE-67-89-AB`
* Six (EUI-48) or eight (EUI-64) groups of two hex digits with colon separators: `01:23:45:67:89:AB` or `01:23:45:FF:FE:67:89:AB`
* Three (EUI-48) or four (EUI-64) groups of four hex digits with dot separators `0123.4567.89AB` or `0123.45FF.FE67.89AB`

The first two forms are seemingly the most common, and are recommended in this IEEE document: 
https://standards.ieee.org/content/dam/ieee-standards/standards/web/documents/tutorials/eui.pdf
I've found the third form scattered around places, although don't have an "authoritative" reference.

Im thinking of accepting case-insensitive hex digits (e.g. `aa`. `aA`, and `AA`), but not accepting unpadded hex groups (e.g. `00:01` but not `0:1`) .

Let me know if this sounds like the right approach :)

**Comment by wilmington** [comment]
OSX does this annoying thing where it drops leading zeroes (unless it's a double leading zero) - one to be aware of?

e.g.
OSX
```
0:18:dd:21:8:6d
```

linux (ubuntu 20)
```
00:18:dd:21:08:6d
```

**Comment by Edward-Knight** [comment]
Okay, that's easy enough to accommodate 👍
