### ISSUE TITLE
[BUG] no __version__ attribute ?

### ISSUE THREAD

**Issue by neutrinoceros** [willmcgugan/rich#282]
**Describe the bug**

Not really a bug (but I don't think this qualifies as a feature request either):
rich has no __version__ attribute, and the relevant info is rather stored in pyproject.toml

I have no experience with packaging with poetry. Would it make sense to you to use the python accessible  __version__ attribute in `rich.__init__.py` instead of `pyproject.toml[tool.poetry]` ? Thanks !

**Comment by willmcgugan** [comment]
poetry doesn't create `__version__` attributes. They recommend using `importlib.metadata` to get the version. Details here https://github.com/python-poetry/poetry/issues/144

Personally, I think its a step backwards.

**Comment by neutrinoceros** [comment]
I see !
Personally I'd be happy to have _a_ way to get the version number from outside rich, so `importlib.metadata.version` is a satisfactory solution to me, and I don't need it to be done internally. Thank you for your answer !
