### ISSUE TITLE
[BUG] Rich progress overwrites in same cell in jupyter lab

### ISSUE THREAD

**Issue by adamgayoso** [willmcgugan/rich#283]
In Jupyter lab, the following happens when two progress bars are in the same cell:

<img width="684" alt="Screen Shot 2020-09-15 at 11 36 08 AM" src="https://user-images.githubusercontent.com/10859440/93250414-a6b77100-f747-11ea-86bb-587a64eb0e55.png">

In jupyter notebook, the correct output is shown:

<img width="660" alt="Screen Shot 2020-09-15 at 11 36 26 AM" src="https://user-images.githubusercontent.com/10859440/93250447-b20a9c80-f747-11ea-88c9-6cd0a66553de.png">

**Comment by adamgayoso** [comment]
The problem actually appears to be related to not installing the @jupyter-widgets/jupyterlab-manager extension in lab. Not sure if you have any other ways to address this.

**Comment by willmcgugan** [comment]
So the extension resolves it? i.e. you get two bars in lab?

AFAICT Rich is doing the correct thing here. I suspect its an issue on the Jupyter side.

**Comment by adamgayoso** [comment]
Yes exactly. I was looking to see if there was a way to detect if the code is being executed in lab vs notebook but I couldn’t find anything. It could be nice to provide a warning?

**Comment by willmcgugan** [comment]
Don't think there is much benefit in a warning. It sounds like a bug in the Jupyter and they may just fix it in an update. You may want to file an issue with them.
