### ISSUE TITLE
[REQUEST] Syntax highlighting using standard ANSI colours.

### ISSUE THREAD

**Issue by tomchristie** [willmcgugan/rich#284]
I'm working on [an HTTP command line client using rich](https://github.com/encode/httpx/pull/1212), which is looking great, but I'm having a few problems getting the syntax highlighting just right.

The problem is that I really want to use the whatever the existing console background colour is, but also want a theme that works well on both light & dark consoles, so need to also be able to use the default foreground text colour for at least part of the theme.

An example of a tool that gets this right is `httpie` - https://github.com/httpie/httpie

Their default theme is "auto" [which uses pygment's `TerminalFormatter`](https://github.com/httpie/httpie/blob/master/httpie/output/formatters/colors.py), and which results in a theme that has a different foreground text depending on the terminal style.

![Screen Shot 2020-09-15 at 20 37 51](https://user-images.githubusercontent.com/647359/93256638-83b2ae80-f793-11ea-9116-481d08b154c6.png)

![Screen Shot 2020-09-15 at 20 38 00](https://user-images.githubusercontent.com/647359/93256644-87463580-f793-11ea-8238-9ca11e568f7e.png)

I don't think I'm currently able to replicate something similar in rich.

Similarly, for cases where a user *does* explicitly select a theme, I'd ideally still like to use the terminal background, rather than painting over it. I can do this part, but only by digging into private API...

```python
syntax._background_color = None
syntax._pygments_style_class.background_color = None
```

*Ideally* I'd love to find a good way to get two things out of this...

* The ability to use an "auto" theme, that uses standard ANSI colours, and matches the terminal theme.
* Some public API for removing any explicit background colour on syntax highlighting, so only the text is colourised.

**Comment by willmcgugan** [comment]
Thanks for the pointers.

It looks like Pygments terminal formatter essentially has its own theme that maps to ansi colors. I think I can replicate that. There are actually 2 terminal "themes" in the terminal formatter, for light and dark backgrounds.

What I might do is add a special case "ansi_light" and "ansi_dark" themes. Although I doubt the distinction is necessary unless the terminal is using the default primary colors (probably just cmd.exe).

I will also add an option to override the background color, which you can set to "default"

**Comment by willmcgugan** [comment]
@tomchristie 7.0.0 has these changes to Syntax.

You can set the theme to "ansi_dark" or "ansi_light" which will use system defined colors. You can also set `background_color="default"` to force the background to be transparent.

**Comment by tomchristie** [comment]
Love it! Looks fantastic. 💚
