### ISSUE TITLE
[REQUEST] Renderable for solid bar

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#293]
One common UI element is the display of a percentage as a small column, often also using a semaphore color gradient.
Most of the time these columns are very narrow, 4-5 chars like.

Current example with rich:
![screenshot](https://sbarnea.com/ss/Screen-Shot-2020-09-19-12-52-58.37.png)

Example of desired look (Gerrit review size )

![gerrit-review-size-column](https://sbarnea.com/ss/Screen-Shot-2020-09-19-12-54-24.62.png)

## Details

* User may want to render nothing when value is either min or max
* User may want to left or right alignment
* I am not sure if reuse of current progressbar may be possible for this special usecase, especially as this requires use of https://en.wikipedia.org/wiki/Block_Elements for drawing in a very small space.
* Computing color gradient may be tricky, so it may worth allowing user to implement in and only supporting a single color.

**Comment by willmcgugan** [comment]
You could use `rich.bar` which is what Progress uses internally. Although the line characters it uses give you a granularity of 1/2 a 'cell'.

It wouldn't be that hard to implement something like `bar.Bar` using the more granular block characters. Which is probably a nice addition to Rich. I'll tag this as an enhancement, but you might want to tackle it yourself if you need it sooner.

**Comment by ssbarnea** [comment]
I will try to look at bar, even 1/2 bars provide decent size estimate. 5 chars => 10% range which is quite precise IMHO.

**Comment by willmcgugan** [comment]
See the new Bar class in v9.0.0 https://rich.readthedocs.io/en/latest/reference/bar.html

Note that rich.bar.Bar was renamed to rich.progress_bar.ProgessBar in v9, and rich.bar.Bar is the new solid bar.
