### ISSUE TITLE
[BUG]Backspacing deletes the prompt in console.input using a custom theme

### ISSUE THREAD

**Issue by deb17** [willmcgugan/rich#299]
Hi,

When I use the backspace key to delete a value that I entered on an input prompt, the prompt itself gets deleted. `console.input` is using a custom theme. The problem does not occur if I remove `import readline` from the script. But then the cursor keys don't work.

To reproduce, code is:
```
import readline
from rich.console import Console
from rich.theme import Theme

custom_theme = Theme({
    'input': 'bold yellow'
})
console = Console(theme=custom_theme, highlight=False)

ch = console.input('[input]Enter choice: ')
print(ch)
```
Enter some text at the prompt, then delete it with backspace - the prompt gets deleted too.

**Platform**
OS - Linux (Ubuntu 18.04)
Terminal - Default
Rich - 6.2.0

Thanks.

**Comment by willmcgugan** [comment]
Please try with 7.1.0

**Comment by deb17** [comment]
It's working now. Thanks!
