### ISSUE TITLE
Markdown tables

### ISSUE THREAD

**Issue by bdice** [willmcgugan/rich#3]
Hi @willmcgugan! Looks like an awesome library. I'm really interested in using this for terminal rendering of Markdown files, but I need to be able to render Markdown tables. Is that something you think would fit in this library?

**Comment by willmcgugan** [comment]
Hi @bdice 

The markdown rendered doesn't support tables at the moment. I think the parser I'm using does support tables (I'd have to check), so in theory it shouldn't be too hard to implement.

I'll probably attempt it in the next week or two. If you keep this issue open I'll post progress here.

**Comment by willmcgugan** [comment]
I was mistaken about the parser (commonmark) supporting tables, it doesn't. There is a commonmark extension for tables, but it doesn't look well supported.

I'll come back to markup tables at some point, but for the moment its on hold I'm afraid.

**Comment by bdice** [comment]
@willmcgugan No worries! Thanks for considering it. Let me know if you decide to try it out or if I can help test/review.

**Comment by willmcgugan** [comment]
Cleaning up issues. This probably isn't going to happen in the core library I'm afraid, unless I find a solid parser that does tables.

**Comment by aurium** [comment]
Hi @willmcgugan, did you see https://github.com/GovReady/CommonMark-py-Extensions ?
It looks like it's alive. :slightly_smiling_face: 

The MD Table is a important feature to solve googlefonts/fontbakery#2559 and I would love to use rich to solve it.
Is something missed on GovReady/CommonMark-py-Extensions that I could help?
