### ISSUE TITLE
[REQUEST] Add title_justify and caption_justify options for Table, to override default "center"

### ISSUE THREAD

**Issue by ptmcg** [willmcgugan/rich#301]
**How would you improve Rich?**

I would like to output a table with the caption non-centered, as shown here:

```
                 Best 5 Star Trek:TOS Episodes                    
+---------------------------------------------------------------+
| Date       | Title                           | Rating | Votes |
|------------+---------------------------------+--------+-------|
| 1967-04-06 | The City on the Edge of Forever |    9.3 |  4393 |
| 1967-10-06 | Mirror, Mirror                  |    9.1 |  3434 |
| 1966-12-15 | Balance of Terror               |    8.9 |  3710 |
| 1967-12-29 | The Trouble with Tribbles       |    8.9 |  3337 |
| 1967-02-16 | Space Seed                      |    8.8 |  3647 |
+---------------------------------------------------------------+
                                               data from IMDB.com

```
**What problem does it solved for you?**

Sometimes captions should be less prominent than showing as centered under the table. Left or right alignment of the caption text can give it more of "footnote" look.

While supporting caption justification, may as well add title justification also.

**Comment by ptmcg** [comment]
See attached patch for proposed code changes.

[Add_title_justify_and_caption_justify_options_to_Table_to_support_left_center_right_justif.patch.txt](https://github.com/willmcgugan/rich/files/5262984/Add_title_justify_and_caption_justify_options_to_Table_to_support_left_center_right_justif.patch.txt)

**Comment by willmcgugan** [comment]
You can set the caption to a Text instance, i.e. `caption=Text("data from IMDB.com", justify="right")` which should have the same effect.

That said, it probably is worth adding those two parameters as you suggest. Just to make it obvious...

**Comment by willmcgugan** [comment]
Thanks for https://github.com/willmcgugan/rich/pull/302 !
