### ISSUE TITLE
[REQUEST] progress bar: round up task.speed

### ISSUE THREAD

**Issue by FedeClaudi** [willmcgugan/rich#304]
**How would you improve Rich?**

I love `rich`'s `ProgressBar`, but I have a very small issue with it: I can't seem to find a way to display `task.speed` without all the decimal numbers. 

This is how I'm defining my `ProgressBar`:
```
progress = Progress(
    TextColumn(
        "[bold magenta]Step {task.completed}/{task.total} - {task.speed} steps/s"
    ),
    # "[progress.description]{task.description}",
    BarColumn(bar_width=None),
    "•",
    "[progress.percentage]{task.percentage:>3.0f}%",
    TimeRemainingColumn(),
)

```
But the `task.speed` get's printed with loads of decimal numbers which doesn't look great:
```
Step 44/3000 - 0.31283405731719177 steps/s 
```

I've tried adding `>3.0f` to `task.speed` to truncate the float number, but this results in an error because before the first iteration is completed `task.speed` returns `None` and `None` cannot be formatted so that gives an error. 

Ideally `task.speed` should return a rounded number (e.g. to the third decimal) or a way should be put in place to have this option (even avoiding to return `None` before the first iteration would be enough). 

Thanks, and thank for developing this awesome library :)

**Comment by willmcgugan** [comment]
You may need a custom column.

Something like this (untested):

```python
class SpeedColumn(ProgressColumn):

    def render(self, task: "Task") -> Text:
        if task.speed is None:
            return Text("")
        else:
            return Text(f"{task.speed:.3f} steps/s")
```

**Comment by FedeClaudi** [comment]
awesome, thanks for the quick response!

I've had to add a couple small changes, posting here what worked for me in case somebody else wants to implement something similar:
``` python
class SpeedColumn(TextColumn):
    _renderable_cache = {}

    def __init__(self, *args):
        print(args)

    def render(self, task: "Task") -> Text:
        if task.speed is None:
            return Text("no speed")
        else:
            return Text(f"{task.speed:.3f} steps/s")
```

thanks again!
