### ISSUE TITLE
[REQUEST] Cycle through Prompt's choices

### ISSUE THREAD

**Issue by codenotworking** [willmcgugan/rich#306]
This request might be similar to [[REQUEST] Arrow Keys and cursor control? #262](https://github.com/willmcgugan/rich/issues/262), but I wanted to know if the ability to cycle through the provided choices of a `Prompt.ask()` method could be implemented in the future.

For example (from <a href="https://rich.readthedocs.io/en/latest/prompt.html">Prompt</a>):
```python
from rich.prompt import Prompt
name = Prompt.ask("Enter your name", choices=["Paul", "Jessica", "Duncan"])
```
And then using `Tab` and/or `cursor` key(s) to cycle through the choices `"Paul"`, `"Jessica"`, and `"Duncan"`.

**Comment by willmcgugan** [comment]
I think you can do this with [readline](https://docs.python.org/3/library/readline.html). Rich uses the builtin `input()` under the hood.

**Comment by codenotworking** [comment]
I looked into readline.  Unfortunately it's outdated and unavailable for Windows.  In addition, the Windows version [pyreadline](https://pypi.org/project/pyreadline/) hasn't been updated for 5 years, and not compatible with Windows 10.  Oh well, no worries.

**Comment by joshuakoh1** [comment]
@codenotworking Did you ever find a solution? I'm trying to use user input to toggle between live display screens (e.g. 1 for screen 1, 2 for screen 2 etc.)

**Comment by codenotworking** [comment]
@joshuakoh1 No.  I never looked further into this.
