### ISSUE TITLE
[REQUEST] Our library uses rich and thought maybe you'd like to add it to the list of users

### ISSUE THREAD

**Issue by joaqo** [willmcgugan/rich#309]
Hi, thanks for creating rich!

Recently we switched to rich in our library, and saw that you list users of the library in your readme, and thought maybe you would be interested in including ours.

In any case, the library is [Norfair](https://github.com/tryolabs/norfair).

Just a random thought that popped up, thanks again for the great library!

**Comment by willmcgugan** [comment]
That's a very cool project!

To be honest, I didn't really intend that section of the Readme to be updated. It was more there for reassurance that Rich is used in big projects. But if you really would like a mention there, I'd accept a PR...

**Comment by joaqo** [comment]
Yeah that makes sense, created the PR just in case, feel free to add it or not, no biggie.
