### ISSUE TITLE
Is it possible to change row style

### ISSUE THREAD

**Issue by ytti** [willmcgugan/rich#31]
While generating row's I'd like to set slightly different colour for every odd row, to make it easier to visually stay in line.

I can do something like this to hack around it:
```python
    def row(self, table, *rows):
        clr = "grey93" if self.row_number % 2 == 0 else "white"
        rows = [self.color(clr, row) for row in rows]
        table.add_row(*rows)
        self.row_number += 1
```

(self.color just wraps the string with the colour)
The problem with this approach is that as I'm not really setting the row style, I remove any existing colours that the row items may have, and I'd only like to change the default colour.

**Comment by willmcgugan** [comment]
Try v0.8.9 on PyPI. I've added `Table.row_styles` which accepts a list of row styles. i.e. construct your table list this:

```
table = Table(row_styles=["grey93", "white"])
```

**Comment by ytti** [comment]
Works grand! Thanks!

![screenshot 2020-4-12 kello 15 52 32](https://user-images.githubusercontent.com/200527/79069273-a0732380-7cd5-11ea-8e52-7a7516941b88.png)
