### ISSUE TITLE
[REQUEST] Document lack of progressive printing on tables

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#312]
One issue with rich tables is that they render at the end and there is no way to gradually print tables row by row.

I can understand why this happens but for tools that produce long lists and likely ones that take significant time to produce for each row, this becomes a deal breaker.

I suspect that using a custom logger could be used to partially alleviate this limitation, at the cost of having less control over the final result.

From the rendering perspective, if user could define the column sizes when creating a table, it should be possible to perform gradual printing.

If this cannot be implemented due to current architecture, it may worth documenting this limitation and the logging workaround.

**Comment by willmcgugan** [comment]
One option would be use the LiveRender class to redraw the table each time. But frankly I think this is a rather niche requirement and I suspect there are better ways of presenting your information.

I don't see the worth in documenting something which I doubt would be expected of a terminal rendering of a table.

Closing this as wontfix. But if you have a concrete proposal of how a progressive table would work / look like I'll listen.

**Comment by giladreti** [comment]
I would love to see this feature too. I have a stream of data that is being received which I want to format as a table. Since I have many rows, I would like to have the ability to print new rows as data is being received without the need to re-render the entire table. As it was said above, we will need to set column widths before printing. 
A code example might look like:
```python
from rich.console import Console
from rich.table import ProgressiveTable

console = Console()
table = ProgressiveTable()

table.add_column('test column', width=12)

table.add_row('first row')
console.print(table)

table.add_row('second row')
console.print(table)

table.finish_border()
console.print(table)
```

Whose output should be 
```
┏━━━━━━━━━━━━━━┓
┃ test column  ┃
┡━━━━━━━━━━━━━━┩
│ first row    │
│ second row   │
└──────────────┘
```

Such a table would probably work by buffering the newly added rows before printing (only) them.

**Comment by ssbarnea** [comment]
@giladreti Rich current main goal is to provide the building blocks for creating TUI applications. As my primary use case was for making console application output easier to read, I created a small extension called [enrich](https://github.com/pycontribs/enrich/) which focuses on progressive and fluid output (soft wrapping, for both console and logging).

Even so this will may not work for tables because they can work only with a fixed layout and rich needs to decide how much space to give to each column and do the wrapping. I think you could emulate it by styling the table to render as a single row and printing each row as an entire table.

To be honest the rendering of UI elements is a very complex issue for which browsers spent decades improving and I doubt @willmcgugan had the superpowers to address it.

For the moment I avoid printing stuff as tables if progressive display is needed or if the total amount of printed rows is likely to be bigger than 1-2 screens.
