### ISSUE TITLE
[REQUEST] Request github to activate discussions

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#313]
In order to avoid cluttering the issue tracker with user questions it would be a good idea to ask github team to enable discussions for this repository.

When enabled it looks like https://github.com/ansible-community/molecule/discussions -- and you have the power to on/off at any time but because is in feature-preview mode you need to add a comment on https://github.community/t/can-one-apply-for-github-discussions-beta/121120/170 thread. It make take a couple of days for them to activate it. I am surprised they still monitor this long standing thread but I guess they want to slow-down the adoption in order to have enough time to scale it or implement other features.

**Comment by willmcgugan** [comment]
I've applied. 👍
