### ISSUE TITLE
[BUG] Logging is unable to log text that already has ANSI escapes in it.

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#314]
**Describe the bug**
I am using logging via RichHandler and I observed that when I include output from external commands that produces ANSI, these are blocked by rich.

**To Reproduce**
A minimal code example that reproduces the problem would be a big help if you can provide it. If the issue is visual in nature, consider posting a screenshot.

**Expected behavior**
I want to be able to tell rich to process nested ANSI when performing logging, so we do not loose the ANSI from the called program.

![example](https://sbarnea.com/ss/Screen-Shot-2020-10-01-10-34-30.40.png)

**Comment by willmcgugan** [comment]
Allowing ansi escape codes verbatim would break much of Rich's formatting, word wrapping in particular, but also style. You also wouldn't want ansi codes such as clear line / screen etc making it in to your terminal.

It would be possible to parse text containing ansi codes, strip dangerous ones, and replicate styles as a Text class. It would be an interesting exercise, but probably isn't going to happen while there are other higher priority tasks. 

TBH though, ansi codes in logging is best avoided. Log output may be configured to go to a variety of sources, most of which are unlikely to support ansi sequences. If you want to preserve the output, I would recommend `repr`ing the string prior to logging it.

**Comment by ssbarnea** [comment]
It's ok, i can understand the limitations, maybe I could make a PR in the future to add few ansi stripping/cleansing utilities.

I am wondering if maybe my decision of using a python logger to stream (line by line) stdout/stderr output from child processes started by the tool may be the root cause for the problem I faced.

Using python logging seemed as a flexible way for this as it allowed even features like logging at warn level the output from stderr.

I am not yet sure which is the best approach for dealing output from child processes, especially for wrapping tools, like those were few but important the output is their own and the >80% of output is from the called tools. Because called tools make take a lot of time to run, you must stream the output, capturing it and displaying at the end is not a viable option (can easily run 10min-30min or even hours).

Maybe someone reading this will have a better idea.
