### ISSUE TITLE
[REQUEST] highlight=False for rich.print

### ISSUE THREAD

**Issue by The-Compiler** [willmcgugan/rich#315]
If I'm using `rich.print` to show simple error messages with colors like here:

```python
rich.print("[red]Error:[/red] Couldn't do the thing, setting isn't defined", file=sys.stderr)
```

the highlighting often will be in my way:

![image](https://user-images.githubusercontent.com/625793/94799951-31ed6380-03e4-11eb-9e08-2236d4674957.png)

I would've expected to be able to do `highlight=False` like with `rich.console.Console`, but that doesn't work:

```
>>> rich.print("...", file=sys.stderr, highlight=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: print() got an unexpected keyword argument 'highlight'
```

I can instead do:

```python
con = rich.console.Console(file=sys.stderr, highlight=False)
con.print("...")
```

but being able to do the same via the `rich.print` convenience alias seems... more convenient :wink:

**Comment by willmcgugan** [comment]
I need to make a faq for this. In the meantime please see https://github.com/willmcgugan/rich/issues/244

**Comment by The-Compiler** [comment]
Ah, thanks! Feel free to close this then, unless you want to use it as a FAQ-reminder. FWIW see #316 for where I'd have expected to find something about it in the documentation - if the reference docs there would say that it's intended to have the same signature as the builtin `print`, that'd have answered things for me.

**Comment by willmcgugan** [comment]
It's mentioned in the [readme](https://github.com/willmcgugan/rich#rich-print-function) but not explicitly in the docs. I'll clarify in the next update.

**Comment by vincerubinetti** [comment]
Took me a while to find this. Perhaps on this page it's worth mentioning that `print()` refers to `console.print()` instead of regular print:
https://rich.readthedocs.io/en/stable/highlighting.html
