### ISSUE TITLE
[BUG] Rich is incompatible with pytest capsys fixture

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#317]
**Describe the bug**
Adopters of rich will eventually discover that their use of [capsys](https://docs.pytest.org/en/stable/capture.html) in pytest unittest gets broken when they integrate the library.

While this is somehow expected we should document a recipe for adapting testing in such way that does not break when using rich.

Example test:

```
import pytest

def test_output(capsys):
 	foo() # expected to produce stdout content
	stdout, stderr = capsys.readouterr()
	assert stdout == "..."
	assert stderr == "..."
```

This has repercussions even for logging functions and I even encountered errors when parametrizing tests like `ValueError: I/O operation on closed file.` which are caused by Console() instance being closed after the first test.

As rich itself makes use of pytest it should not be a big deal to include an example.

**Comment by willmcgugan** [comment]
Please supply more information re what exactly is the problem with capsys.

A working code sample that reproduces the error would be helpful.

**Comment by ssbarnea** [comment]
Assign it to me, I will provide an example for it.

**Comment by tobiasraabe** [comment]
Hi,

first of all, thanks for the amazing package!

I am experiencing the same problem but only with Python 3.6 on all platforms. Here is a repository where I replicated the issue: https://github.com/tobiasraabe/debug-pytest-rich.

Do you have any ideas whats happening?

**Comment by tobiasraabe** [comment]
To add another observetation I extended the test cases with an example where I tried to capture the output with `click`'s test runner, `CliRunner`, which works with `print` and `click.echo`, but not with `rich.print`.

Suprisingly, the first test case always succeeds which is why I duplicated the test files to see that all tests are affected.

**Comment by willmcgugan** [comment]
Can you make sure you are running the latest version of Rich?

An older version cached a copy of sys.stdout which could break anything which replaced stdout with a proxy. Now Rich always refers to sys.stdout so should be functionally identical to print

**Comment by tobiasraabe** [comment]
I assumed only Python 3.6.0 was unsupported and this is true for pypi, but on anaconda python 3.6 is unsupported since version 9.4.0. For future reference, here is the PR which skipped building the package for 3.6: https://github.com/conda-forge/rich-feedstock/pull/42. Thanks for the hint!

**Comment by kat25230** [comment]
I'm having the same issue, I used `click.echo` and it worked, but now I tried using `rich` and when I'm looking at the:
`capsys.readouterr()` I'm seeing partial log was captured, that is some of the output is missing. Any ideas what's causing this? (I'm using rich version `11.1.0`).

**Comment by RhetTbull** [comment]
I'm having the same issue with `rich==11.2.0`, `pytest==7.0.1`, `click==8.0.4` on macOS 10.15.7.  I replaced `click.echo` with `rich.print` and any test using `click.testing.CliRunner` fails when checking the output.  I'd love to use rich instead of click.echo but can't do without the test suite working.  Interestingly, if I run `pytest` with the `-s` flag, everything works fine.

**Comment by RhetTbull** [comment]
Posting this here in case it's helpful for others.  As noted above, I'm still having this issue using latest versions of rich, pytest, and click, causing my test suite to fail.  I really wanted to use rich text with my click app though so I came up with this work-around which is working fine for me.  It's a drop-in replacement for `click.echo` that uses `rich.console.Console.print` to format output with rich markup then `click.echo` to display.  Any additional kwargs are passed to `rich.console.Console.print` or `click.echo` as appropriate (thankfully these functions don't currently share any same-name params).  For an example of this "in the wild", see [here](https://github.com/RhetTbull/osxphotos/blob/master/osxphotos/cli/click_rich_echo.py).

```python
"""click.echo replacement that supports rich text formatting"""

import typing as t
from io import StringIO

import click
from rich.console import Console


def rich_echo(
    message: t.Optional[t.Any] = None,
    **kwargs: t.Any,
) -> None:
    """
    Echo text to the console with rich formatting.

    This is a wrapper around click.echo that supports rich text formatting.

    Args:
        message: The string or bytes to output. Other objects are converted to strings.
        kwargs: any extra arguments are passed to rich.console.Console.print() and click.echo
            if kwargs contains 'file', 'nl', 'err', 'color', these are passed to click.echo,
            all other values passed to rich.console.Console.print()
    """

    # args for click.echo that may have been passed in kwargs
    echo_args = {}
    for arg in ("file", "nl", "err", "color"):
        val = kwargs.pop(arg, None)
        if val is not None:
            echo_args[arg] = val

    # click.echo will include "\n" so don't add it here unless specified
    end = kwargs.pop("end", "")

    # rich.console.Console defaults to 80 chars if it can't auto-detect, which in this case it won't
    # so we need to set the width manually to a ridiculously large number
    width = kwargs.pop("width", 10000)
    output = StringIO()
    console = Console(force_terminal=True, file=output, width=width)
    console.print(message, end=end, **kwargs)
    click.echo(output.getvalue(), **echo_args)
```

**Comment by unparalleled-js** [comment]
I am experiencing this problem only with rich Tree output. Rich tables and other output is testable in `capsys`, but the tree doesn't appear there. I can see the tree happening, it just isn't captured.
