### ISSUE TITLE
[REQUEST] rich Pretty: truncate long variables

### ISSUE THREAD

**Issue by FedeClaudi** [willmcgugan/rich#318]
**How would you improve Rich?**

Hi,

I'm using `Pretty` to style the `locals` panels in [pyinspect's tracebacks](https://github.com/FedeClaudi/pyinspect#tracebacks). However when the object being printed is a list, or a dictionary whose values are long lists/arrays `Pretty` prints the whole thing, cluttering the console and defeating the purpose of trying to have more informative tracebacks. 

I don't if I've missed this option, but it would be great if there was a way to truncate long objects when printing them. (I've tried using the `overflow` argument but didn't make a difference.

Here's some code to reproduce the issue:
``` python

from rich.pretty import Pretty
from rich.console import Console

my_list = [1] * 400

Console().print(Pretty(my_list))
```

Ideally it would only print the start of the list. 

Thank you, 
Federico

**Comment by willmcgugan** [comment]
I have been thinking about some way of abbreviating large pretty printed structures. The problem is there is no clear way to truncate the whole structure in a consistent way. A list of integers may be obvious, but we could be printing a deeply nested data structure.

I will give it some thought.

I like what you are doing with pyInspect. Some good ideas there.

**Comment by FedeClaudi** [comment]
Thanks!
I wanted to have a small project to get myself to learn rich properly since it's such an awesome library!

I agree, it's not a trivial problem given the wide range of objects that might be put through `Pretty`, I'll also try to think of possible solutions.

**Comment by fakhrip** [comment]
My idea on this is, we may be able to truncate the variable by adding a function which take 2 optional parameters, and 1 required parameter such as :
- important_part
- context_num (a number just like [-C option] in grep to   show some lines around the important_part that we don't want to be truncated)  

And the required one which is the variable itself : 
- variable
---
So there will be basically two possibilities here (CMIIW) :
- Long / Deeply nested list / dict
- Long string

if the variable is a long list then it will be truncated like this :  
(Remember the output could be different based on the important part that want to specifically printed out)
```python
case1 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, '...', 1]
case2 = [
    {
        'name': 'test1'
    },
    [
        {
            'name': 'test2',
        }
    ],
    '...'
    {
        'name': 'test3',
    }
]
```

and for a long string:
```python
case1: 'This is a really long blablabla ... string'
```
---
If this idea is somehow accepted, then i will start working on this and later create a pull request for this feature 👌

**Comment by FedeClaudi** [comment]
I think the problem may be, for instance, that in `case2` the first entry in the list or dictionary might itself be a long item etc..

**Comment by willmcgugan** [comment]
The simplest approach may be to set a limit of n items to all containers however they are nested. Then show 'n' items plus an ellipsis (perhaps with text like `... +23`

@fakhrip raises a good point about long strings, and I like the solution.

It's never going to be perfect, even with the above, you could have a very large pretty printed data-structure. But would work for the most part.

I think the Pretty class would have to grow "max_items" and "max_string_size" arguments, which should be optional.

Note that there is a ellipsis unicode character, so ... can be replaced with …

You can see the difference with a fixed width font.

```
...
…
```  

@fakhrip This would be a tricky change! If you are still interested, have a look at [pretty.py](https://github.com/willmcgugan/rich/blob/master/rich/pretty.py)

**Comment by fakhrip** [comment]
Sure ill take a look at the `pretty.py`

But one question remains is that, should i add this truncating stuff as a function in that `pretty.py` class or that i have to add it somewhere else ?

**Comment by willmcgugan** [comment]
In pretty.py

You'll probably need to do the truncation in the `_traverse` function

**Comment by fakhrip** [comment]
Alright i think i will just start to work for the solution...

**Comment by fakhrip** [comment]
> My idea on this is, we may be able to truncate the variable by adding a function which take 2 optional parameters, and 1 required parameter such as :
> 
>     * important_part (specific part that dont want to be truncated)
> 
>     * context_num (a number just like [-C option] in grep to   show some lines around the important_part that we don't want to be truncated)

Just to clarify here, do i have to add this idea (above) too or just implement the solution that @willmcgugan said here :  

> The simplest approach may be to set a limit of n items to all containers however they are nested. Then show 'n' items plus an ellipsis (perhaps with text like ... +23

And i suppose as a result for implementing **just** the solution that @willmcgugan gave, will make the output be like this :
```python
max_items = 5
max_string_size = 20

case1 = [1, 2, 3, 4, 5, '… +23' ] (where real length of list is 28)

case2 = [
    {
        'name': 'test1',
        'date': 'test1',
        'something': 'test1',
        'something': 'test1',
        'something': 'test1',
        '… +5'
    },
    [
        1,
        2,
        3,
        4,
        5,
        '… +10'
    ]
]

case3 = '12345678912345678912 … +5'

case4 = [1, '12345678912345678912 … +5', 3, 4, 5, '… +23' ]
```
---
Please let me know if i'm wrong at some point

**Comment by fakhrip** [comment]
Because i think its better for me to create test before actually start writing on the solution, so that i have to make sure that the output really match your liking...

**Comment by willmcgugan** [comment]
> Just to clarify here, do i have to add this idea (above) too or just implement the solution that @willmcgugan said here :

For the most part there is no "important part" per se, its an arbitrary data structure, so I think just the solution I gave.

Your example is very close to what I had in mind.

Re the ellipsis, I think you can drop the single quotes, so it's obvious it's not a string.

For strings, I think the ellipsis should probably be outside of the quotes.

**Comment by willmcgugan** [comment]
Version 9.1.0 has truncation of long containers. But not long strings as yet. Still considering that one.

**Comment by willmcgugan** [comment]
v9.2.0 Pretty now was a `max_string` parameter to truncate long strings.

There's also a new `pprint` function for a shortcut to pretty printing.

```
from rich.pretty import pprint
pprint(locals())
```

**Comment by hhoeflin** [comment]
Thank you - I have been looking for this abbreviation option. I saw it in pretty, but could not find how to enable it in the logging Handler. Is that possible as well? Thanks!

**Comment by elipapa** [comment]
This is amazing. Any chance it could be expanded to containers such as np.arrays or torch ?

**Comment by willmcgugan** [comment]
It could if the maintainers implement a `__rich_repr__` method.
