### ISSUE TITLE
[BUG] rich.progress.track not respecting arguments

### ISSUE THREAD

**Issue by jdrusso** [willmcgugan/rich#319]
**Describe the bug**
`rich.progress.track` does not appear to respect the `refresh_per_second` or `update_period` parameters.

**To Reproduce**
```
from rich.progress import track
import time

for step in track(range(1000), refresh_per_second=1):
    time.sleep(0.01)
```

or 

```
from rich.progress import track
import time

for step in track(range(1000), update_period=1):
    time.sleep(0.01)
```

both produce output much more frequently than once/second.

**Platform**
This is on Python 3.7.4 on MacOS. First noticed in a Jupyter notebook, and verified in an interactive Python session.

**Comment by willmcgugan** [comment]
I can't reproduce any problem with progress.track with Rich 7.1.0

Auto refresh doesn't work with Jupyter, and it would default to refreshing once per loop.

In the terminal it is `refresh_per_second` argument that determines how often the progress bar is drawn, and AFAICT that works as expected.

The `update_period` doesn't affect refresh rate, so in your second example it would refresh at the default 10 times a second, although the tasks will only be updated once a second. You can probably leave `update_period` as the default for most purposes.

Let me know if you can identify anything that doesn't fit with the above.

**Comment by jdrusso** [comment]
Thanks for looking into this and explaining the distinction between refresh rate, and task update rate! I think I had an incorrect understanding of the parameters.

For my Jupyter usage, I'll just switch to explicitly using a `Progress()` object instead of using `track()` when I can't afford to refresh every loop.
