### ISSUE TITLE
[Suggestion] Use binary prefixes instead of decimal ones

### ISSUE THREAD

**Issue by Rubo3** [willmcgugan/rich#323]
I was tinkering with progress bars and noticed the file size unit is expressed with [decimal prefixes](https://github.com/willmcgugan/rich/blob/33a171d72013f470c0edb5f61e226ca80729cbf6/rich/progress.py#L301) (i.e. KB, MB, GB, etc.) while the actual number is expressed as binary. I suggest you to consider switching to binary prefixes (i.e. KiB, MiB, GiB, etc.) in order to have consistency with the number and its unit of measure and to remove the ambiguity regarding in which base the prefix is expressed: KiB, MiB, etc. are used exclusively with powers of 2, while I've seen KB, MB, etc. used with powers of 10 (as they should be) and powers of 2 (as in this case, but generally in casual conversations).
For instance, I tried with a file with a size of 6'988'379 bytes. Expressed in MiB it's 6,7 and this is the number printed by the progress bar, while in MB it's 6,9. As you can notice, while dealing with MiB vs MB the difference is ~5%, but when the size is bigger it can be ~7% (GiB vs GB), ~10% (TiB vs TB) and so on, so please consider using only one format.

Edit: grammar

**Comment by willmcgugan** [comment]
PRs welcome

**Comment by willmcgugan** [comment]
I think download size should be expressed in decimal prefixes for consistency with file managers, as it is what the user would expect. KiB MiB etc. may be unambiguous, but they are just not in common usage.

So the fix would be changing 1024 to 1000.

**Comment by Rubo3** [comment]
It depends. Dolphin, for examples, expresses it with binary prefixes.

**Comment by devratapuri** [comment]
hi i am new to this can  anyone tell me from where to begin

**Comment by willmcgugan** [comment]
@Rubo3 will be fixed in next version. Thanks to @amartya-dev

**Comment by Rubo3** [comment]
Thank you. What about giving the user the possibility to switch between decimal and binary?

**Comment by willmcgugan** [comment]
Good idea

**Comment by amartya-dev** [comment]
We can give a command-line argument for that flag?

**Comment by willmcgugan** [comment]
@amartya-dev Rich doesn't handle command line switches, except for a few built-in commands, but the application could chose to expose that via a CLI

**Comment by amartya-dev** [comment]
@willmcgugan I guess the way to incorporate this is using a parameter in `render()` function of `DownloadColumn` ?

**Comment by willmcgugan** [comment]
It would be a parameter in the constructor.

**Comment by amartya-dev** [comment]
Oh yeah sorry :), will need to add a constructor there.

**Comment by willmcgugan** [comment]
@amartya-dev Did you want to tackle that one? I play to release a new version in a few days and it would be nice to get that in there.

**Comment by amartya-dev** [comment]
@willmcgugan yes let me get on it
