### ISSUE TITLE
[BUG] Inconsistent formatting of file paths

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#324]
**Describe the bug**
I identified at least 3 different ways file-paths are rendered. The expected behavior would be to have a consistent formatting of these.

Apparently fully qualified paths are rendered correctly, but:

* relative paths are only partially colored (first two dots are missed)
* filenames without any path components are not highlighted at all

All these were printed using logging and simple strings. I tried to look if there is anything documented about how paths are rendered but I was not able to find info.

My guess is that some kind of hinting would be needed because it would be impossible to distinguish if a random string like "foo" is referring to a file or not. 

![sample](https://sbarnea.com/ss/Screen-Shot-2020-10-03-13-12-33.13.png)

**Comment by willmcgugan** [comment]
See the docs on [highlighting](https://rich.readthedocs.io/en/latest/highlighting.html) and https://github.com/willmcgugan/rich/blob/master/rich/highlighter.py#L69

The path regex is looking for absolute paths as its easier to disambiguate from regular text, but its never going to be perfect. 

You could define a style calls "path" then use it in markup, e.g.  `"Missing file [path]{file}[/path]"`
