### ISSUE TITLE
[REQUEST] More examples

### ISSUE THREAD

**Issue by willmcgugan** [willmcgugan/rich#325]
The [examples](https://github.com/willmcgugan/rich/tree/master/examples) directory contains a few .py files that demonstrate a feature of Rich.

It would be nice to have more of these.  No example should short and succinct, demonstrate a feature well, non-trivial, and shouldn't cover features that already exist.

**Comment by surajit-techie** [comment]
I would like to work on this. Could you please assign this to me?

**Comment by willmcgugan** [comment]
Done.

**Comment by FedeClaudi** [comment]
Hi, great idea!

If I can suggest one, it took me a while to figure out how to use rich to get fancy logging working while saving to a file. Perhaps an example would help others?

I got it to work with loguru in the end, happy to share some code if you want.

**Comment by willmcgugan** [comment]
@FedeClaudi Sounds like a good one. What problems did you have?

**Comment by FedeClaudi** [comment]
Looking at the issues I got the rich handler to work with rich's traceback, but I couldn't get them to show up in the file.

I'm the end I saw an issue about loguru, and with that it mostly works. But perhaps not everybody wants to use that, add a dependency etc. So an example of it working with the vanilla logger would be nice!
