### ISSUE TITLE
Importing Console throws AttributeError in Python 3.6.0

### ISSUE THREAD

**Issue by myrmica-habilis** [willmcgugan/rich#33]
Hi, thanks for this wonderful library.

I just randomly discovered this error:
```
$ ./venv36/bin/python -c "from rich.console import Console"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/michal/python/SzT/venv36/lib/python3.6/site-packages/rich/console.py", line 38, in <module>
    from .default_styles import DEFAULT_STYLES
  File "/home/michal/python/SzT/venv36/lib/python3.6/site-packages/rich/default_styles.py", line 18, in <module>
    strike=False,
  File "/home/michal/python/SzT/venv36/lib/python3.6/site-packages/rich/style.py", line 73, in __init__
    self._color = None if color is None else _make_color(color)
  File "/home/michal/python/SzT/venv36/lib/python3.6/site-packages/rich/style.py", line 71, in _make_color
    return color if isinstance(color, Color) else Color.parse(color)
AttributeError: type object 'Color' has no attribute 'parse'
```

Python versions 3.6.2 and 3.6.4 don't exhibit this issue.

The `Color` class clearly does have a `parse` class method. However:
```
$ ./venv36/bin/python -c "from rich.color import Color; print(hasattr(Color, 'parse'))"
False
$ ./venv362/bin/python -c "from rich.color import Color; print(hasattr(Color, 'parse'))"
True
$ ./venv364/bin/python -c "from rich.color import Color; print(hasattr(Color, 'parse'))"
True
```

**Comment by willmcgugan** [comment]
That’s a strange one. Must be a bug in the stdlib for 3.6

Can I just check you’ve got the latest version of Rich installed?

**Comment by myrmica-habilis** [comment]
Yes, all virtual envs have a fresh install of rich 0.8.11.

Different Python versions installed using pyenv. Tried Python 3.6.1 and no error.

**Comment by myrmica-habilis** [comment]
OK, so it seems that prior to 3.6.1, subclasses of `typing.NamedTuple` did not support methods.

> Changed in version 3.6.1: Added support for default values, methods, and docstrings.

https://docs.python.org/3/library/typing.html#typing.NamedTuple

That means none of the methods defined in `rich.color.Color` are recognized as attributes in Python 3.6.0.

```
$ ./venv360/bin/python -c "from rich.color import Color; print(any(hasattr(Color, attr_name) for attr_name in ('system', 'get_truecolor', 'from_triplet', 'default', 'parse', 'get_ansi_codes', 'downgrade',)))"
False

$ ./venv361/bin/python -c "from rich.color import Color; print(all(hasattr(Color, attr_name) for attr_name in ('system', 'get_truecolor', 'from_triplet', 'default', 'parse', 'get_ansi_codes', 'downgrade',)))"
True
```

**Comment by willmcgugan** [comment]
Thanks for investigating!

Is 3.6.0 support important for you? I'm tempted to mark this as a 'wontfix' and set the minimum Python version to 3.6.1.  I've use

**Comment by myrmica-habilis** [comment]
No, I don't need 3.6.0 support, you can close this. Thanks.

**Comment by willmcgugan** [comment]
Updated docs.
