### ISSUE TITLE
[REQUEST] Update for Python 3.9

### ISSUE THREAD

**Issue by willmcgugan** [willmcgugan/rich#340]
Python 3.9 was released today.

- [x] Run tests against Python 3.9
- [x] Update docs (if required)
- [x] Update GH Actions
- [x] Update PyPi

**Comment by Edward-Knight** [comment]
I ran the tests on the `python:3.9` Docker image, one failure: `tests/test_inspect.py::test_inspect_empty_dict`.
At that moment the function signature is:
```python
@skip_py36
@skip_py37
def test_inspect_empty_dict():
```
Shall I put a MR in to make it run `@only_py38`?

**Comment by willmcgugan** [comment]
That’s ok. I have a fix for that in a branch.

**Comment by Edward-Knight** [comment]
With regards to GitHub Actions, looks like we can use 3.9.0 now:

https://github.com/actions/python-versions/releases/tag/3.9.0-83838

https://github.com/willmcgugan/rich/blob/8d53efb4c85430d4af6cf63da4c13373c46433d8/.github/workflows/pythonpackage.yml#L11

**Comment by willmcgugan** [comment]
Master works fine with 3.9. There was one test fail due to additional methods being reported in dict, which was an easy fix.
