### ISSUE TITLE
Add feature of adding ascii arts

### ISSUE THREAD

**Issue by RatanShreshtha** [willmcgugan/rich#35]
It would be nice to feature of printing ascii arts in rich.

**Comment by willmcgugan** [comment]
Do you mean converting an image in to ascii? There are quite a lot of tools to do that already. It's not something I see the need for in the core library, but an extension is possible.

**Comment by RatanShreshtha** [comment]
I mean converting text to ASCII art.

**Comment by willmcgugan** [comment]
I can't do much better than https://github.com/sepandhaghighi/art
