### ISSUE TITLE
Keyerror while using rich.print

### ISSUE THREAD

**Issue by rednafi** [willmcgugan/rich#351]
**Describe the bug**
A `KeyError` saying that key `__rich__` is missing occurs while trying to print the instance of a custom dictionary class. 

**To Reproduce**
Here's the self-contained code snipped to reproduce it.

```python
from rich import print

class Foo(dict):
    def __getattr__(self, key):
        return self[key]

foo = Foo({'1': 1})
print(foo)
```

This raised the following stacktrace
```
Traceback (most recent call last):
  File "issue.py", line 9, in <module>
    print(foo)
  File "/home/rednafi/code/personal/konfik/.venv/lib/python3.8/site-packages/rich/__init__.py", line 48, in print
    return write_console.print(*objects, sep=sep, end=end)
  File "/home/rednafi/code/personal/konfik/.venv/lib/python3.8/site-packages/rich/console.py", line 994, in print
    renderables = self._collect_renderables(
  File "/home/rednafi/code/personal/konfik/.venv/lib/python3.8/site-packages/rich/console.py", line 896, in _collect_renderables
    rich_cast = getattr(renderable, "__rich__", None)
  File "issue.py", line 5, in __getattr__
    return self[key]
KeyError: '__rich__'
```
*PS - The built-in `print` does not suffer from this issue.*

**Platform**
* Linux (Ubuntu 20.04)
* Python 3.8.2
* Rich 8.0.0

**Comment by willmcgugan** [comment]
Your `__getattr__` raises a KeyError which is breaking the `getattr` function. You should only raise an `AttributeError` there. See [Python docs](https://docs.python.org/3/reference/datamodel.html#object.__getattr__) on the subject.

**Comment by willmcgugan** [comment]
Closing this. I'm assuming you are happy with the above!

**Comment by huaxlin** [comment]
> Your `__getattr__` raises a KeyError which is breaking the `getattr` function. You should only raise an `AttributeError` there. See [Python docs](https://docs.python.org/3/reference/datamodel.html#object.__getattr__) on the subject.

The reason is accuracy. Try this:

```python
from rich import print

class Foo(dict):
    def __getattr__(self, key):
        return self[key]

foo = Foo({'1': 1})
try:
    print(foo)
except Exception as e:
    print(repr(e))  # 👉 KeyError('__rich__')


class Bar(dict):
    def __getattr__(self, name: str):
        if name in self:
            return self[name]
        return super().__getattr__(name)
bar = Bar({'1': 1})
print(bar)  # 👉 {'1': 1}
```
