### ISSUE TITLE
[QUESTION] Taking terminal screenshows

### ISSUE THREAD

**Issue by FedeClaudi** [willmcgugan/rich#358]
Hi @willmcgugan, 

I have a quick question. It not exactly rich-related but I was hoping you could help me. 

To create the images in the README.md of [pyinspect](https://github.com/FedeClaudi/pyinspect#tracebacks), I've been using [terminalizer](https://github.com/faressoft/terminalizer).
However panels come out looking a bit weird:

![image](https://user-images.githubusercontent.com/17436313/95323634-66569900-0896-11eb-8b3b-270100677bac.png)

I'm using terminalizer because I can automate most of it and because the terminal image it makes have rounded edges and box-shadows that look much nicer than a simpler screenshot, but I'm open to better alternatives. 

Do you have any advice to improve the output of terminalizer, or better tools to create images showing rich's output as nicely as you do in the README of your repo?

Thanks for the help :)

**Comment by willmcgugan** [comment]
Hi @FedeClaudi 

I had the same problem, as cool as terminalizer is, it doesn't handle more fancy terminal output that well.

I just took screenshots on my Mac. I use iTerm with a minimal window style and Monokai color theme. The Mac screenshot tool includes the drop shadow for the window, which looks nice in a browser.

btw you might want to use the new Discussions tab for Rich questions.

**Comment by FedeClaudi** [comment]
Sorry you're right, would have been more appropriate for the discussions I had forgotten you've added that recently. 

Cool thanks, I will try that instead! 

You can close if you wish.
