### ISSUE TITLE
Sorting by table column(s)

### ISSUE THREAD

**Issue by coobr01** [willmcgugan/rich#36]
Great library!  Would it be possible to add a sorting by columns feature?

**Comment by willmcgugan** [comment]
I'm afraid not. I want Rich to be concerned with rendering only, which is why internally the Table class stores strings or renderable. Ultimately I hope that other projects will implement the rich protocol and they can handle more data-oriented features, and leave the rendering to Rich.

**Comment by coobr01** [comment]
Understood, thanks!
