### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by willmcgugan** [willmcgugan/rich#37]
Test coverage is currently siting at 89%. I'd love to get that up to high nineties before a 1.0.0 release.

If you can, contribute a test. Even if it only adds a single line to coverage, it would be appreciated!

**Comment by edraobdu** [comment]
Hi Will, I just forked and ran the tests with coverage, and it shows a 91%, I know the higher the better, but isn't that an acceptable coverage rate to (at least) release the 1.0.0 version?

_Note: I used ```coverage run -m --source=. pytest```, see attached picture_

In the mean time, I realized some required packages were not listed in the requirement.txt:
**colorama==0.4.3
commonmark==0.9.1
typing-extensions==3.7.4.2**

![Screenshot from 2020-04-26 14-15-44](https://user-images.githubusercontent.com/31775663/80317315-bcdc8900-87c8-11ea-9805-ff7531c1a667.png)

**Comment by willmcgugan** [comment]
Well its not bad... But I would like to be closer to 100%.

You can run the tests with `make test` which will also show the coverage.

I'll update the requirements. They're only needed for development, pyproject.toml stores the requirements for release.

**Comment by willmcgugan** [comment]
Coverage is currently 94%

**Comment by willmcgugan** [comment]
Test coverage is currently 97% which is not bad at all. I'll integrate coveralls at some point so I can brag about it on the readme.

**Comment by willmcgugan** [comment]
Coverage is at 98%. Missing coverage is mostly in rich.progress, which is a little challenging to test.

Still plenty of easy pickings if anyone wants to contribute.

**Comment by willmcgugan** [comment]
Test coverage is now at 99% which is pretty good!

Thanks to @pim-hoeven for picking up the slack there.

There are still gaps in the progress bar, some of which will be tricky due to the dependency on threads. And plenty of one liners to pick up if anyone is interested.

**Comment by Edward-Knight** [comment]
We now have 99.57% coverage, which isn't _truely_ 100% coverage, but is now close enough to be rounded to 100%:

[![codecov](https://codecov.io/gh/willmcgugan/rich/branch/master/graph/badge.svg)](https://codecov.io/gh/willmcgugan/rich)

**Comment by willmcgugan** [comment]
Closing this. Coverage in 99th percentile. 🍻 Will try to keep it there.
