### ISSUE TITLE
[REQUEST] print: print every arguments on the same line

### ISSUE THREAD

**Issue by char101** [willmcgugan/rich#370]
Have you checked the issues for a similar suggestions? Yes

**How would you improve Rich?**

Hi,

Is it possible to print all values given to `rich.print` including data structures on the same line?

Example:
```python
from rich import print
print('a', {'b': 'c'})
```

output:
```
a
{'b': 'c'}
```

Is it possible to make it outputs
```
a {'b': 'c'}
```

Of course while still highlighting `{'b': 'c'}`.

I have tried setting `soft_wrap`, etc. with no effect.

**What problem does it solved for you?**

It is much easier to scan for the output if they are put on the same line, when there are multiple outputs lines.

Example
```
INSERT {'value': 100}
DELETE {'value': 200}
```

Compared to
```
INSERT
{'value': 100}
DELETE
{'value': 200}
```

**Comment by char101** [comment]
Interestingly `rich.print('a', {'b': 'c'}, end=' ')` puts everything on the same line. It seems that `end` is applied not just at the _end_.

**Comment by char101** [comment]
```python
import rich

rich.print('a', {'b': 'c'})
rich.print('a', {'b': 'c'}, end=' ')
rich.print('a', {'b': 'c'}, end='')

print('a', {'b': 'c'})
print('a', {'b': 'c'}, end=' ')
print('a', {'b': 'c'}, end='')
```

```
a
{'b': 'c'}
a {'b': 'c'}
a{'b': 'c'} <- I think this is a bug, there should be a space between a and {'b': 'c'}
a {'b': 'c'}
a {'b': 'c'} a {'b': 'c'}
```

**Comment by willmcgugan** [comment]
Rich works slightly differently because it pretty prints collections like dict and list. The pretty printing always ends on a new line, and may insert additional new lines if the collection doesn't fit in the terminal width.

What is happening is that the strings are concatenated together (with sep). If a collection is encountered, it outputs the string + end + plus the pretty printed collection.

It may be possible to more closely match the builtin print, while still pretty printing. I'll give it some thought. In the meantime, if you want to replicate the builtin behaviour, you could convert any collections to a str.

**Comment by char101** [comment]
Thanks for the explanation.

In my opinion, for a simple print function, pretty printing data structures feels a bit too magical. The highlighting is nice, but printing a large data structures over multiple lines might not be useful in certain use case, like logging data processing execution. It is a nice feature to have, but I prefer to have control over it. Just like python have `pprint`, maybe rich can also provides print for line oriented printing and pprint for pretty printing.

**Comment by NeilGirdhar** [comment]
> It may be possible to more closely match the builtin print, while still pretty printing. I'll give it some thought. In the meantime, if you want to replicate the builtin behaviour, you could convert any collections to a str.

But then you lose Rich's nice formatting?

**Comment by rmekdma** [comment]
I add this code in `.pythonrc.py`

```python
from rich import print as p

def print(*o, sep=' ', end='\n', file=None, flush=False):
    o = [str(x) for x in o]
    p(*o, sep=sep, end=end, file=file, flush=flush)

print.__doc__ = p.__doc__
```
