### ISSUE TITLE
Print progress bar to stderr

### ISSUE THREAD

**Issue by GeekDuanLian** [willmcgugan/rich#374]
I have a file download script, I want the downloaded content to be output directly to stdout, so that I can continue processing using the pipeline.
So I use sys.stdout.buffer.write()
I don’t understand the meaning of redirect_stdout and redirect_stderr in the document, I tried to set them to False, but the progress bar still cannot be displayed.
I hope there is an option to directly specify the progress bar output to stderr.

**Comment by Edward-Knight** [comment]
I think you want something like this:
You can specify a `Console` object which is configured to output to `STDERR` instead of `STDOUT`.
```python
import sys
import time

from rich.console import Console
from rich.progress import Progress

with Progress(console=Console(file=sys.stderr)) as progress:
    task = progress.add_task("Test", total=2)
    time.sleep(0.5)
    progress.update(task, advance=1)
    time.sleep(0.5)
    progress.update(task, advance=1)
    time.sleep(0.5)
```

```bash
$ python progress.py > /dev/null
Test ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
```

**Comment by GeekDuanLian** [comment]
@Edward-Knight 
Oh, yes, this is exactly what i want.
Thanks a lot!

**Comment by willmcgugan** [comment]
Thanks @Edward-Knight
