### ISSUE TITLE
[BUG] nested tables are not justified according to partent table column's justify setting

### ISSUE THREAD

**Issue by pdumoulin** [willmcgugan/rich#375]
**Describe the bug**
When a table is a cell within another table, it is not positioned according to the parent table column's justify setting and always appear to be left justified. Text within the same column will move according to the justify setting.

**To Reproduce**
In the example below, tables with data are placed within a layout table which has one column. The first row contains three tables and the second row contains two tables. In the second row, you can observe the two tables appearing to be left justified.
```
from rich import box
from rich.console import Console
from rich.table import Table

# example of some table with data to be put into other tables
data_table = Table(title='Star Wars Movies')
data_table.add_column('Released', justify='right', style='cyan', no_wrap=True)
data_table.add_column('Title', style='magenta')
data_table.add_column('Box Office', justify='right', style='green')
data_table.add_row('Dec 20, 2019', 'Star Wars: The Rise of Skywalker', '$952,110,690')
data_table.add_row('May 25, 2018', 'Solo: A Star Wars Story', '$393,151,347')
data_table.add_row('Dec 15, 2017', 'Star Wars Ep. V111: The Last Jedi', '$1,332,539,889')
data_table.add_row('Dec 16, 2016', 'Rogue One: A Star Wars Story', '$1,332,439,889')

# table w/ three sub-tables, first row
table_one = Table(title='table_one', expand=True)
table_one.add_row(data_table, data_table, data_table)
table_one.add_row('some text', 'some text', 'some text')

# table w/ two sub-tables, second row
table_two = Table(title='table_two', expand=True)
table_two.add_column(justify='center')
table_two.add_column(justify='center')
table_two.add_row(data_table, data_table)
table_two.add_row('some text', 'some text')

# wrapper layout table
main_table = Table(title='main_table', box=box.ASCII)
main_table.add_row(table_one)
main_table.add_row(table_two)

# print out table
console = Console()
console.print(main_table)
```

**Platform**
* Ubuntu 20.04
* rich==8.0.0
* GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD

Thank you for taking a look, and apologies if there is a way to accomplish this nesting of tables pattern that I am unaware of. I read through much of the docs and was unable to find a solution. I am looking forward to converting projects to use rich as a replacement for tabulate and I appreciate all of the work done on this very helpful library!

**Comment by willmcgugan** [comment]
The column justify only really applies to text, but you can use the [Align](https://rich.readthedocs.io/en/latest/reference/align.html) class to align any renderable

Import it like this:

```python
from rich.align import Align
```

Here's how you would use it in your example:

```python
table_two.add_row(Align.center(data_table), Align.center(data_table))
```

**Comment by pdumoulin** [comment]
Awesome! That works great. Thank you so much for your help, I really appreciate all the hard work that has gone into this library.
