### ISSUE TITLE
[REQUEST] Extend cell background color across entire row

### ISSUE THREAD

**Issue by sanga** [willmcgugan/rich#383]
See: https://github.com/willmcgugan/rich/discussions/363 for details but essentially it's so that the following code:
```python
bg = Style(bgcolor="rgb(40,40,40)")
table = Table(box=box.SIMPLE_HEAD, row_styles=["none", bg])
```
Would produce a table like the following but _without_ the gaps inbetween the grey cells.

![image](https://user-images.githubusercontent.com/2088/95955084-f64f9200-0e04-11eb-8f70-20f999a7858b.png)

**Comment by willmcgugan** [comment]
I'm thinking that the background color should only extend between cells if the box style has no vertical separator.

For example, this doesn't look right to me:

<img width="795" alt="Screen Shot 2020-10-15 at 10 21 33" src="https://user-images.githubusercontent.com/554369/96104031-3fb8e380-0ed0-11eb-9fd3-2e648bf0f99a.png">

But this looks fine:

<img width="795" alt="Screen Shot 2020-10-15 at 10 23 51" src="https://user-images.githubusercontent.com/554369/96104311-97574f00-0ed0-11eb-9731-dd3b1c7952d6.png">

What do you think?

**Comment by sanga** [comment]
Sure that sounds reasonable to me. I agreed that the first screencap there looks a bit odd.

**Comment by willmcgugan** [comment]
Please try v9.0.0

**Comment by sanga** [comment]
Looks primo. Thanks!
