### ISSUE TITLE
[REQUEST] Default padding for panels

### ISSUE THREAD

**Issue by Edward-Knight** [willmcgugan/rich#385]
**How would you improve Rich?**

At the moment panels have no default padding:

```python
>>> from rich import print
>>> from rich.panel import Panel
>>> print(Panel.fit("Hello World!"))
╭────────────╮
│Hello World!│
╰────────────╯
```

I propose adding a default left and right padding to make the output more aesthetically pleasing:

```python
>>> print(Panel.fit("Hello World!", padding=(0, 1)))
╭──────────────╮
│ Hello World! │
╰──────────────╯
```

A quirk of most monospace fonts and how characters are often printed in the terminal, means that a padding of `(0, 1)` gives a more even padding than `(0, 0)`.

**What problem does it solved for you?**

This can be solved by the user by simply suppling the `padding` parameter as I have above.

I am aware that this may just be a suggestion to change the default to my personal preference, but I feel that this extra padding means the edge of the text is more evenly centred in the panel than the current default. This would make the default behaviour of `rich` closer to the default behaviour of many other tools, for example:

HTML `<input>` box (on Chrome):
![image](https://user-images.githubusercontent.com/13382553/96048130-15ced500-0e6e-11eb-955e-d388973c5a50.png)

HTML `<input>` box (on Firefox):
![image](https://user-images.githubusercontent.com/13382553/96047225-b15f4600-0e6c-11eb-8be3-f1bdaf96b1df.png)

Microsoft Word Text Box:
![image](https://user-images.githubusercontent.com/13382553/96047213-ab696500-0e6c-11eb-8710-46fdfb3700f9.png)

**Comment by willmcgugan** [comment]
Ok, that seems reasonable.

**Comment by Edward-Knight** [comment]
Great! I'll put together a small MR later today hopefully

**Comment by willmcgugan** [comment]
No, need. It's already in my local branch. Should be in v9.0.0

**Comment by willmcgugan** [comment]
v9.0.0 is in PyPi now.
