### ISSUE TITLE
[REQUEST] minimal table width

### ISSUE THREAD

**Issue by stolarczyk** [willmcgugan/rich#388]
hey @willmcgugan, great package!

in `Table.add_column` method it would be nice to have an _actual_ minimal with option. [The documentation](https://github.com/willmcgugan/rich/blob/c98bf070e4f3785dbb050b72c09663021c5b1d73/rich/table.py#L303) says that `width` argument sets the minimal with for a column, but in fact in my tests it sets a constant width for one. I'd like my column to be at least `width` wide but expand if there is a longer string to display.

**Comment by Edward-Knight** [comment]
## Docs
For `Table.width`:
https://github.com/willmcgugan/rich/blob/a83ee864e67d97be926894c7b5d3cf470194d6c1/rich/table.py#L93
For `Column.width`:
https://github.com/willmcgugan/rich/blob/a83ee864e67d97be926894c7b5d3cf470194d6c1/rich/table.py#L52-L53
For `Table.add_column(width)`:
https://github.com/willmcgugan/rich/blob/c98bf070e4f3785dbb050b72c09663021c5b1d73/rich/table.py#L303

## Test code
```python
from rich.console import Console
from rich.table import Table

WIDTH_OPTIONS = [None, 10, 0]

console = Console()
for table_width in WIDTH_OPTIONS:
    for column_width in WIDTH_OPTIONS:
        table = Table(show_lines=True, width=table_width)
        table.add_column("Column", no_wrap=True, width=column_width)
        table.add_row("Short")
        table.add_row("Width 10!")
        table.add_row("Very long string that exceeds 10 characters in length")
        console.print(f"Table width: {table_width}, Column width: {column_width}", table)
```

## Test result
```
Table width: None, Column width: None
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Column                                                ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Short                                                 │
├───────────────────────────────────────────────────────┤
│ Width 10!                                             │
├───────────────────────────────────────────────────────┤
│ Very long string that exceeds 10 characters in length │
└───────────────────────────────────────────────────────┘
Table width: None, Column width: 10
┏━━━━━━━━━━━━┓
┃ Column     ┃
┡━━━━━━━━━━━━┩
│ Short      │
├────────────┤
│ Width 10!  │
├────────────┤
│ Very long… │
└────────────┘
Table width: None, Column width: 0
┏━━┓
┃  ┃
┡━━┩
│  │
├──┤
│  │
├──┤
│  │
└──┘
Table width: 10, Column width: None
┏━━━━━━━━┓
┃ Column ┃
┡━━━━━━━━┩
│ Short  │
├────────┤
│ Width… │
├────────┤
│ Very … │
└────────┘
Table width: 10, Column width: 10
┏━━━━━━━━━━━━┓
┃ Column     ┃
┡━━━━━━━━━━━━┩
│ Short      │
├────────────┤
│ Width 10!  │
├────────────┤
│ Very long… │
└────────────┘
Table width: 10, Column width: 0
┏━━━━━━━━┓
┃ Column ┃
┡━━━━━━━━┩
│ Short  │
├────────┤
│ Width… │
├────────┤
│ Very … │
└────────┘
Table width: 0, Column width: None
┏━┓
┃ ┃
┡━┩
│ │
├─┤
│ │
├─┤
│ │
└─┘
Table width: 0, Column width: 10
┏━┓
┃ ┃
┡━┩
│ │
├─┤
│ │
├─┤
│ │
└─┘
Table width: 0, Column width: 0
┏━┓
┃ ┃
┡━┩
│ │
├─┤
│ │
├─┤
│ │
└─┘
```

## Conclusions

* The "width" parameter is definitely not a minimum as the `add_column` docstring states.
* The total width can exceed the table width if both are specified and greater than zero?

**Comment by willmcgugan** [comment]
The width on the column isn't a minimum, the docs are in error and I'll fix.

@stolarczyk I'd consider implementing a minimum width, but I'd like to hear your use-case first. table.py is a complicated beast and I don't want to add anything without good reason. If you really want it now, you could pad your header with spaces to reach your minimum.

@Edward-Knight Rich will shrink columns as a last resort if they don't fit within the table width. But it generally tries very hard to do what the developer asks for.

**Comment by stolarczyk** [comment]
@Edward-Knight, thanks for this thorough presentation. It seems like none of the with combinations suit my needs, though.

@willmcgugan, for use case presentation can you take a look at the issue that references this one? Linked right below my initial comment.

**Comment by Edward-Knight** [comment]
Would the logic be easier (if a bit more verbose) if the user can specify minimum width, maximum width, and absolute width?

* Minimum width would cause the column to be at least that width
* Maximum width would cause the column to be at most that width
* If either minimum, or maximum, or both are specified, width is automatic within the bounds
* Absolute width overrides everything, and sets the width

**Comment by Edward-Knight** [comment]
How that interacts with table-level constraints and ratios between columns is I guess where a lot of complexity comes in

**Comment by willmcgugan** [comment]
I've added a min_width to Column and Table to v9.0.0. Please give it a try, its not been battle tested.

**Comment by stolarczyk** [comment]
Great, thanks! I'll give it a try.

**Comment by stolarczyk** [comment]
can confirm it worked in my use case

**Comment by erezsh** [comment]
Works for me as well. Should probably go in the docstring, at least.
