### ISSUE TITLE
Option for console.print() to print to the specified output stream

### ISSUE THREAD

**Issue by acabal** [willmcgugan/rich#39]
It would be nice if we could specify the output stream that console.print() should output to. For example, a terminal based program often needs to print to standard error. With vanilla Python it's possible with `print("foo", file=sys.stderr)`. But I didn't find that kind of option in rich.

**Comment by willmcgugan** [comment]
You can set a file argument on the Console constructor, so you could have a separate error console. I could be persuaded to add some kind of switch or file object to the print method.

**Comment by acabal** [comment]
OK great! I didn't think to look at the console constructor and it was not in the docs. Thanks!
