### ISSUE TITLE
[REQUEST] Autocompletion support in prompt, as seen in prompt_toolkit

### ISSUE THREAD

**Issue by fmaida** [willmcgugan/rich#392]
**How would you improve Rich?**

Your library is already awesome and I am terribly sorry to appear to you as an insatiable guy, but there is a very nice feature in the library `prompt_toolkit` ( https://github.com/prompt-toolkit/python-prompt-toolkit ) that I think would be fantastic to have in rich as well.

And that is **Autocompletion**.
prompt_toolkit does it through the use of a class named WordCompleter (see for reference: https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#autocompletion )

IMHO it would be great if a user could write something like this:

````python
from rich.prompt import Prompt

names = ["Paul", "Jessica", "Duncan"]
name = Prompt.ask("Enter your name", default="Paul", completer=names)
print("You said: %s" % name)
````

And have rich showing a pop-up dialog where you can choose one of the allowed names, as shown in this mock-up image:

![Schermata 2020-10-18 alle 15 20 15](https://user-images.githubusercontent.com/605017/96368720-c92d1780-1155-11eb-83e6-b56f3fee66bd.png)

If you think it could be an interesting feature, please consider this request for a future update.
Thank you :-)

**Comment by willmcgugan** [comment]
I have thought about adding autocomplete prompts, menus, and other interactive things. It may happen, either in Rich, or another library which uses Rich for rendering. No promises on the time scale though.

In the meantime, a lot of people use prompt_toolkit in combination with Rich.

**Comment by CesarCruzUtec** [comment]
I'm sorry if this is considered necroposting, but i would like some feedback. I was following the example from @tinchit0 from https://github.com/Textualize/rich/issues/262#issuecomment-2546430217 and decided to implement an AutocompleteConsole version like this:

```python
from getpass import getpass

from prompt_toolkit import PromptSession
from prompt_toolkit.completion import WordCompleter
from rich.console import Console


class AutocompleteConsole(Console):
    def __init__(self, *args, **kwargs):
        self._choices = ["test", "test2", "test3"]
        self.session = PromptSession()
        self.completer = WordCompleter(self._choices, ignore_case=True)
        return super().__init__(*args, **kwargs)

    @property
    def choices(self):
        return self._choices

    @choices.setter
    def choices(self, options: list):
        self._choices = options

    def set_choices(self, options: list):
        """
        Set the choices for the autocomplete console.
        Args:
            options (list): The list of choices to set.
        """
        self._choices = options
        self.completer = WordCompleter(self._choices, ignore_case=True)

    def input(
        self, prompt="", markup=True, emoji=True, password=False, stream=None
    ) -> str:
        if prompt:
            self.print(prompt, markup=markup, emoji=emoji, end="")
        if password:
            result = getpass("", stream=stream)
        else:
            if stream:
                result = stream.readline()
            else:
                result = self.session.prompt(
                    "",
                    completer=self.completer,
                    # complete_while_typing=True,
                    # complete_in_thread=True,
                )
        return result
```

and it works, but i have some ui problems, here is how i implement my new console

```python
from rich.panel import Panel
from rich.text import Text

from ..utils.custom import AutocompleteConsole

console = AutocompleteConsole()


def display_title(title: str):
    """
    Display the title of the application.
    Args:
        title (str): The title to display.
    """

    console.print(
        Panel(
            Text(title, justify="center", style="bold white"),
            style="bold blue",
            border_style="bold blue",
        )
    )


def display_menu(options: list):
    """
    Display a menu with the given options.
    Args:
        options (list): The list of options to display.
    """

    console.rule("Menu", style="bold blue")

    for i, option in enumerate(options):
        console.print(f"[{i + 1}] {option}")
    console.print("[0] Exit", style="bold red")

    console.rule(style="bold blue")
```
```python
from ..ui.display import console, display_menu, display_title

from rich.prompt import Prompt

def start_action():
    """
    Start the Dynasty Doujin CLI
    This function starts the CLI and allows you to navigate the website.
    """
    console.clear()
    display_title("Dynasty Doujin CLI")

    options = ["Recently Added", "Directory", "List", "Images", "Forum"]
    display_menu(options)

    console.set_choices(options)
    choice = Prompt.ask("[bold green]Please select an option", console=console)

    print(f"You selected: {choice}")
```

and it works as expected, but this happens.  the prompt from rich is "ignored" and the autocompletion prompt starts from the first character. is this an expected behavior?, if so i could just add an "\n" char to the end of the prompt and it would be fine, but i guess something can be done?

![Image](https://github.com/user-attachments/assets/dad578ac-5118-417c-b540-42f8984e270c)

im using the last version of rich as well as python 3.13 in arch linux in a kitty terminal
