### ISSUE TITLE
[BUG] Rich displays ansi on Windows on Console.input() statements

### ISSUE THREAD

**Issue by naveen521kk** [willmcgugan/rich#393]
**Describe the bug**
Originally this is from https://github.com/ManimCommunity/manim/issues/552

Manim is a project which uses rich for terminal output and as a logging handler.

Here, `console.input()`, at

https://github.com/ManimCommunity/manim/blob/3b6519a58678eb84bb31f550a0a4734df58bded3/manim/utils/module_ops.py#L95-L97

produces raw ansi outputs on command prompt. This bug is seen from `rich>=7.0.0`. This happens to `console.input()` statements and not `console.print()` statements.

**To Reproduce**
![rich-failing-to-show-colour-windows](https://camo.githubusercontent.com/e12d6cc25b842ef0db3d32877429271207cc7fd5/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3538313733383733323634363935373035372f3736363331393434313230393332373732382f756e6b6e6f776e2e706e67)

I don't exactly know how to reproduce this outside of Manim. In manim just the command
```sh
manim basic.py
```
will show that error.

**Platform**
Windows 10.
Command Propmt.
rich>=7.0.0
(anything above v7).

**Comment by willmcgugan** [comment]
It looks like legacy windows doesn't like ansi in `input()` prompts. I'll have a workaround soon. In the meantime, the new Windows terminal should work just fine.

**Comment by willmcgugan** [comment]
Please try with version 9.0.1

**Comment by naveen521kk** [comment]
It's fixed thanks.
