### ISSUE TITLE
[REQUEST] Theme option for pretty

### ISSUE THREAD

**Issue by aroberge** [willmcgugan/rich#394]
**Have you checked the issues for a similar suggestions?**

Yes.

**How would you improve Rich?**

I would like to be able to use a consistent theme for `pretty` and a console.   Based on the fact that `pretty.install()` takes a console option, I expected`hoped that pretty would use my theme if I did the following:

```python
my_console = Console(theme=my_theme)
pretty.install(console=my_console)
```

**What problem does it solved for you?**

It would allow my custom console to have a consistent look and feel. Right now, I have a custom theme for displaying tracebacks  (done by redirecting `sys.stderr`). I would like to explore the possibility of using the same theme when displaying objects the way that pretty does.

**Comment by willmcgugan** [comment]
This works for me...

<img width="942" alt="Screen Shot 2020-10-20 at 09 56 05" src="https://user-images.githubusercontent.com/554369/96564029-8e90bf80-12ba-11eb-88e2-b18815e26fe3.png">

**Comment by aroberge** [comment]
My misunderstanding: I confused the pygments style used for syntax highlighting `Syntax(theme=...)` with the Rich theme for the console.
