### ISSUE TITLE
[REQUEST] Print newline before traceback.

### ISSUE THREAD

**Issue by kpister** [willmcgugan/rich#396]
Super minor detail which you might argue is on the developer not on `rich`:
When receiving the KeyboardInterrupt signal while requesting `input`, `rich` will output the traceback on the same line (where there was already text). Resulting in the image below.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/4607361/96770996-b9f0d880-13a6-11eb-833e-055c4caaaee3.png">

**How would you improve Rich?**

The improvement would just be adding a newline before traceback is printed to ensure that it has its own line.
Or, the more complicated solution could detect where the cursor is in terminal and only print newline if needed.

**What problem does it solved for you?**

Example code to replicate:
```
from rich.traceback import install
install()
name = input("What is your name? ") # send KeyboardInterrupt when prompted here
```

**Comment by Edward-Knight** [comment]
I believe it is reasonable for `rich` to start printing assuming the cursor is at the beginning of the current line. I'm worried that trying to do anything too clever here could result in some obscure bugs (`rich` isn't always outputting to a terminal, it may just be writing to a stream). I do see why this would be useful for a traceback handler though.

Rich here is mirroring the behaviour of the default Python handler:
```
$ echo "input('> ')" > /tmp/test.py
$ python3 /tmp/test.py 
> ^CTraceback (most recent call last):
  File "/tmp/test.py", line 1, in <module>
    input('> ')
KeyboardInterrupt
```

**Comment by willmcgugan** [comment]
A newline before a traceback sounds reasonable enough.

**Comment by willmcgugan** [comment]
On reflection, when the cursor is on a new line, an extra black line looks out of place.

It's not going to happen that often, and as @Edward-Knight said, the default Python handler does the same thing.
