### ISSUE TITLE
[Question] Manually updatable progress bars

### ISSUE THREAD

**Issue by andrzejnovak** [willmcgugan/rich#399]
Hi, first let me just say this lib looks awesome. I am currently using something else to render a histogram like this to command line and was trying in vain to animate it.

![image](https://user-images.githubusercontent.com/13226500/96796764-09172780-1400-11eb-924b-684d43cb45da.png)

It looks to me like I could use something like the multi progress bar example, but looking at the code it was not immediately obvious to my how to do this. Each bin would be a "task" that I could then update. 

I suppose I'd have to create subclass of BarColumn to change the looks and somehow plug it into the Progress class?

Could you point me in the right direction?

**Comment by willmcgugan** [comment]
You *could* render this with the Progress class, by having a task for each data point, but I suspect it would be simpler for you to generate a Table with a row for labels and a row for bars.

Start by creating a grid (table with no lines):

```python
my_table = Table.grid()
my_table.title = "Samples"
```

Then add rows consisting of the label and a Bar.

```python
for i, x in enumerate(data):
    my_table.add_row(str(i), Bar(size=100, end=y)) 
```

As for animation, the simplest solution would be to clear the screen and redraw. Something along these lines:

```python
while True:
    with console:
        console.clear()
        console.print(my_table)
    update_data()
```

See examples/table_movie.py for an example of this kind of animation.
