### ISSUE TITLE
[BUG] Inline markdown formatting for Japanese (probably other languages too)

### ISSUE THREAD

**Issue by 1dancook** [willmcgugan/rich#400]
**Describe the bug**
Using markdown inline formatting doesn't always work as expected for Japanese.

**To Reproduce**

1. This is not an exhaustive list of cases, but put the following text in a file: test.md

```
1. **今日**は木曜日です。  
2. **(きょう)**は木曜日です。  
3. **（きょう）**は木曜日です。  
4. **＜きょう＞**は木曜日です。  
5. **きょう」**は木曜日です。  
6. **きょう』**は木曜日です。  
7. **きょう]**は木曜日です。  
8. **きょう}**は木曜日です。  
9. **きょう-**は木曜日です。 
10. **きょう_**は木曜日です。 
11. **きょう=**は木曜日です。 
12. **きょう+**は木曜日です。 
13. **きょう;**は木曜日です。 
14. **きょう:**は木曜日です。 
15. **きょう、**は木曜日です。 
16. **きょう。**は木曜日です。 
17. **きょう!**は木曜日です。 
18. **きょう@**は木曜日です。 
```

2. run `python3 -m rich.markdown test.md`

3. You will see that the 1st and 4th case is rendered as expected. Everything else is not. Usually Japanese is written without spaces. I suspect that some rules need to be appended for dealing with punctuation/characters within inline formatting.

**Platform**
- Macos Catalina
- iTerm2
- Rich 9.0.1

**Comment by willmcgugan** [comment]
This doesn't appear to be an issue with Asian characters. Any punctuation will cause the `**` to be rendered as literals.

In fact, Github markdown does the same thing. Which makes this easy to demo. Here's the source:

```
**Hello**World
**Hello.**World
```

And here's the output:

**Hello**World
**Hello.**World

This only effects inline styles that are inside a word (i.e. not separated by spaces). Put a space between Hello and World and it renders as you would expect.

I suspect that the common mark spec just wasn't aware of this requirement for Japanese. One solution would be to insert a zero-width-joiner character in place of the space:

```
**Hello.**&#8203;World
```

**Hello.**&#8203;World

Which works, but it's not elegant. There may be a better solution I'm unaware of, you might want to read the [Common mark spec](https://spec.commonmark.org/).

**Comment by 1dancook** [comment]
Okay thank you! I didn't realize that's an actual spec feature for commonmark. I have a variety of things that render markdown and they're all a little different. I will close this.
