### ISSUE TITLE
add support for Spinner

### ISSUE THREAD

**Issue by ibeex** [willmcgugan/rich#401]
Indicator for long running task's that don't have iterator. 

Something like https://pypi.org/project/yaspin/

**Comment by Edward-Knight** [comment]
Would it be worth integrating `yaspin` or another library as a dependency, or implementing a spinner into progress bar?

**Comment by ibeex** [comment]
I would vote for second solution, implementing a spinner into progress bar.

**Comment by willmcgugan** [comment]
It wouldn't be hard to implement a "spinner" with a [ProgressColumn](https://github.com/willmcgugan/rich/blob/master/rich/progress.py#L154)

Ideally there would also be a simplified API for spinners. Something like the following:

```python
with console.spinner("Working..."):
    do_stuff()
```

**Comment by juniorRubyist** [comment]
Could I take on this issue? I've done spinners before, and I like the API example @willmcgugan  made.

**Comment by willmcgugan** [comment]
@juniorRubyist If you're up for the challenge. 

I'd suggest implement a Spinner base class with a render function that takes the time and returns a Text instance.

```
class Spinner:
    def render(self, time:float) -> Text:
        raise NotImplementedError
```

The constructor may take the speed as an argument. I'm sure you could come up with some nice unicode spinners. You could even use color.

**Comment by juniorRubyist** [comment]
@willmcgugan I think I took a different approach so far, but I'll open a PR (WIP) so you can give feedback.

**Comment by willmcgugan** [comment]
Closing this to tidy issues, but keeping a note of it.
