### ISSUE TITLE
Live Display Implementation 

### ISSUE THREAD

**Issue by nathanrpage97** [willmcgugan/rich#406]
There has been [interest](https://github.com/willmcgugan/rich/issues?q=is%3Aissue+live) in live updating when it comes to using rich.

## Proposal
The main goal of this is to provide an abstraction of the Progress feature that can be used with any `RenderableType` -- Live. 

## Progress

I'm currently working on this in #382. 

![rich_live_example](https://user-images.githubusercontent.com/33010515/95882390-a5c62f00-0d47-11eb-96ea-41ed61971045.gif)

Significant portions of the code and logic from `rich.progress` have been re-used for the implementation.  There is a working example going with some extremely raw tests included `python -m rich.live`

### Potential Areas of Concern
- Lots of duplicate code exists between `Progress` and `Live`
   - Perhaps they should share a common abstract parent class?
- Limited by the height of the users console. 
   - Any tables or renderable larger than the display cannot be properly cleared (limitation of consoles). As such, the console begins to expand as parts of the 
   - There is a flag `hide_overflow` turned on by default, that will render "Terminal too small" when the renderable is too tall. This comes with some performance overheads of having to pre-render the Renderable to check its height.
   - I'm curious if something along the lines of the `pager` functionality could be used on an oversized renderable

### Tasklist
- [x] Unit tests
- [ ] Testing / considerations for an IPython console. Currently does the same thing as Progress.
- [x] Documentation of usage
- [x] An assortment of examples

## Feedback

Let me know if there are any features needed or different design decisions you would like to see.

**Comment by willmcgugan** [comment]
Thanks @nathanrpage97 This will be in the next release
