### ISSUE TITLE
fill table rows with dataframe rows

### ISSUE THREAD

**Issue by iMashhadi** [willmcgugan/rich#415]
Hi
How to fill table rows with dataframe rows ?

**Comment by willmcgugan** [comment]
Iterate over the dataframe. Call `table.add_row()`

**Comment by iMashhadi** [comment]
yes but it does not work properly. It's just all of them on first column.
this is my code:

`
for row in range(len(df)):
    table.add_row([str(i) for i in df.iloc[row,:].values.tolist()])
`

**Comment by willmcgugan** [comment]
add_row accepts positional arguments. Unpack your list with `table.add_row(*my_list)`
