### ISSUE TITLE
Fill footer in table

### ISSUE THREAD

**Issue by iMashhadi** [willmcgugan/rich#416]
Hi
How can just fill footer ?
after created table

**Comment by willmcgugan** [comment]
You can set a footer when adding the columns:

```python
table.add_column("Header", "Footer")
```

See the [table reference](https://rich.readthedocs.io/en/latest/reference/table.html) for details.

**Comment by iMashhadi** [comment]
I mean set value on footer after created table. like sum of columns and ...

**Comment by willmcgugan** [comment]
Ideally, calculate your footers before adding the rows. But you could do this if you wanted to:

```python
table.columns[column_number].footer = str(total)
```
