### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by Schira4396** [willmcgugan/rich#417]
Hello, how does rich achieve multi-line refresh in place?
I think that's pretty cool, is Curses used? Or sys.stout.slush? please

**Comment by willmcgugan** [comment]
Rich doesn't use curses. I guess you mean the progress bars. All that's happening is that after displaying the bars, the cursor is moved back to the initial position.

**Comment by Schira4396** [comment]
> Rich doesn't use curses. I guess you mean the progress bars. All that's happening is that after displaying the bars, the cursor is moved back to the initial position.

Ok. So how does rich refresh the output and text boxes in the terminal? As far as I know, only curses can realize it. Can you tell me the realization logic of rich?

**Comment by willmcgugan** [comment]
Rich (and curses) uses [ANSI control codes](https://en.wikipedia.org/wiki/ANSI_escape_code) to move the cursor around the terminal, then writes new content which overwrite what's already there.

**Comment by Schira4396** [comment]
> Rich (and curses) uses [ANSI control codes](https://en.wikipedia.org/wiki/ANSI_escape_code) to move the cursor around the terminal, then writes new content which overwrite what's already there.

thank you very much
