### ISSUE TITLE
[REQUEST] Table Sections

### ISSUE THREAD

**Issue by jorisroovers** [willmcgugan/rich#418]
Hi, thanks for creating rich. I've used it for the first time just now and I like it a lot!

I don't think this exists, I spend ~30 min going through the docs and issues first.
I thought #261 was the same, but that ended being about enabling demarcation between *all* rows, not selectively.

**How would you improve Rich?**

I think it would be useful to be able to add "line rows" to tables in order to create sections in tables.
Like this:
```sh
┏━━━━━━━━┳━━━━━━┓
┃ Team   ┃ Task ┃
┡━━━━━━━━╇━━━━━━┩
│ Team A │ Foo  │
│ Team A │ Bar  │
┡━━━━━━━━╇━━━━━━┩
│ Team B │ Foo  │
│ Team B │ Bar  │
│ Team B │ Bar  │
┡━━━━━━━━╇━━━━━━┩
│ Team C │ Hur  │
│ Team C │ Dur  │
│ Team C │ Dur  │
│ Team C │ Dur  │
└────────┴──────┘
```

My understanding is that rich currently only allows you to add such lines to either all rows, as well as
selectively for the footer and header row, but not to arbitrary rows.
I've tried adding a `Rule` to every column of the row, but that doesn't give the same visual result.

There's probably a few different ways this could work:

1. Adding a new `TableLine` object as a row to the table:
```python
# create table, add columns: skipped for brevity
table.add_row("Team A", "Foo")
table.add_row(TableLine())
table.add_row("Team B", "Bar")
```
Maybe `TableLine` isn't the best name, but I think the idea is clear :-)

2. Add a optional `show_bottom_row`/`show_top_row` styling arguments to `add_row`

```python
# create table, add columns: skipped for brevity
table.add_row("Team A", "Foo", show_bottom_line=True)
table.add_row("Team B", "Bar")
table.add_row("Team C", "Bar", show_top_line=True)
```

A bit more generically, this could also work by passing a `TableRowStyle` (extends `rich.Style`) that
"understands" table cell style language.

```python
# create table, add columns: skipped for brevity
table.add_row("Team A", "Foo", style=TableRowStyle(show_bottom_line=True))
table.add_row("Team B", "Bar")
table.add_row("Team C", "Bar", style=TableRowStyle(show_top_line=True))
```

4. Add a `TableSection` object that can be stylized independently
```python
section1 = TableSection(show_lines=True)
section1.add_row("Team A", "Foo")
section1.add_row("Team A", "Bar")
table.add_section(section1)

section2 = TableSection(show_lines=True)
section2.add_row("Team B", "Foo")
section2.add_row("Team B", "Bar")
table.add_section(section1)
```
This approach is going a bit beyond my specific request and would need more thought. I just included it
as it introduces the concept of table sections as a proper construct which might be useful for other use-cases.

**What problem does it solved for you?**
In my case, I was trying visually split weeks from each-other in a table. Empty rows work, but I think lines might be
more visually pleasing.

Thanks again for creating rich and taking the time to read this far :)

**Comment by willmcgugan** [comment]
@jorisroovers You are right that Table doesn't support that. Thanks for the analysis of API options, I'll give it some thought.

**Comment by willmcgugan** [comment]
Closing this to tidy issues, but keeping a note of it.

**Comment by willmcgugan** [comment]
In v9.4.0 there is a new `end_section` parameter on `Table.add_row`. If you set this to True, then Rich will draw a line after that row.
