### ISSUE TITLE
Bold formatting dropped when wrapped in quotes

### ISSUE THREAD

**Issue by harperj** [willmcgugan/rich#42]
Bold formatting seems to be dropped whenever quotes are places around the square brackets used for format tagging.

## Example code to reproduce:

```python3
from rich.console import Console
console = Console()
console.log("[bold green]hello world![/bold green]")
console.log("'[bold green]hello world![/bold green]'")
```

## Result:
<img width="224" alt="screenshot" src="https://user-images.githubusercontent.com/838406/81036688-da5ac400-8e54-11ea-94cb-758c48badb78.png">

## Environment

rich 1.0.0
Python 3.6.6
macOS High Sierra

**Comment by harperj** [comment]
I've actually realized this is due to the default highlighter behavior.  I think it isn't truly a bug, though I wonder if there might be a way to make the API / docs clearer.

**Comment by willmcgugan** [comment]
Yeah, that's the string highlighting--which I still need to document properly. You can disable highlighting with `highlight=False` on the log method or Console constructor.

It might actually be less astonishing if the markup was applied *after* the highlighter. The way you would get bold text inside the quotes. What do you think?

**Comment by harperj** [comment]
@willmcgugan yeah, I think either highlighting being off by default or being overridden by manual tags would be more intuitive.

Thanks for the great library by the way, other than this minor confusion everything has been perfect!
