### ISSUE TITLE
[BUG] Always expand containers when pretty printing

### ISSUE THREAD

**Issue by ocurero** [willmcgugan/rich#424]
**Describe the bug**
I'm trying to pretty print a rather big dictionary using console.print() and I want each item on a new line, even those that are small. I can set a very small width to get the same effect but looks quite bad when the text overflows the width.

**To Reproduce**
With this code:
```
from rich.console import Console
console = Console()

sth={'key1': 1, 'key2': 1, 'key3': 1, 'key4': 1, 'key5': 1, 'key6': 1, 'key7': 1, 'key8': 1, 'key9': 1, 'key10': 1, 'key11': 1, 'key12': 1, 'key13': 1, 'key14': 1, 'subkeys': [{'skey1': 1, 'skey2': 1, 'skey3': 1, 'skey4': 1, 'skey5': 1}]}
console.print(sth)
```

This is how it looks like:
![Captura_mal](https://user-images.githubusercontent.com/2606647/97818307-09d27800-1ca2-11eb-9784-3cd213aa1118.PNG)

And this is how it should look like:
![Captura_bien](https://user-images.githubusercontent.com/2606647/97818372-528a3100-1ca2-11eb-89d9-def2d9bd403a.PNG)

**Platform**
linux, rich version 9

Thanks!

**Comment by willmcgugan** [comment]
Try the following:

```python

from rich.console import Console
from rich.pretty import pretty_repr
console = Console()

sth={'key1': 1, 'key2': 1, 'key3': 1, 'key4': 1, 'key5': 1, 'key6': 1, 'key7': 1, 'key8': 1, 'key9': 1, 'key10': 1, 'key11': 1, 'key12': 1, 'key13': 1, 'key14': 1, 'subkeys': [{'skey1': 1, 'skey2': 1, 'skey3': 1, 'skey4': 1, 'skey5': 1}]}
console.print(pretty_repr(sth, expand_all=True))
```
