### ISSUE TITLE
AttributeError: 'Syntax' object has no attribute 'line'[BUG]

### ISSUE THREAD

**Issue by mlavasi** [willmcgugan/rich#429]
```
from rich.syntax import Syntax
from rich.console import Console

console = Console

syntax = Syntax.from_path("mission.py")
console.print(syntax)

```
**To Reproduce**
I am running the above code to test out syntax highlighting in OSX terminal and i get the following error output...

`Traceback (most recent call last):
  File "solotion.py", line 38, in <module>
    console.print(syntax)
  File "/Library/Python/3.8/site-packages/rich/console.py", line 983, in print
    self.line()
AttributeError: 'Syntax' object has no attribute 'line'`

**Platform**
What platform (Win/Linux/Mac) are you running on? What terminal software are you using. Which version of Rich?
Using the latest version of OSX Catolina with ZSH terminal

**Comment by willmcgugan** [comment]
Did you mean?

```python
console = Console()
```

**Comment by mlavasi** [comment]
Yes I feel like a right sausage! 

thank you for your quick reply!

Sorry for the bug report

**Comment by willmcgugan** [comment]
No worries! 😄
