### ISSUE TITLE
[REQUEST] Add 'get_time' argument to Console's constructor

### ISSUE THREAD

**Issue by asvetlov** [willmcgugan/rich#432]
I use the following test strategy: create a console with `record=True`, print data, and compare `console.export_text(syles=True)` with expected string.

This approach works pretty fine except `console.log()` calls: the call print the current time by default, I cannot compare the output with the reference easily.

`Progress` class already accepts the `get_time` callable argument.

It would be nice if the `Console` accepts it too, at least for the test simplification.

**Comment by willmcgugan** [comment]
That's probably a worthwhile addition. I'll add that to the next release.

What I did in tests was to set `Console.log_time_format` to `[TIME]`

**Comment by asvetlov** [comment]
Thanks for the `[TIME]` suggestion, I can use it right now.
I have a workaround with `log_time=False` but `[TIME]` looks better, sure.

P.S.
Thanks for the library, I'm very enjoying using it.

**Comment by romasku** [comment]
I see you added `get_datetime` to `Console` class in https://github.com/willmcgugan/rich/commit/dc02178c04e8e6d0075388c051735e3c92c81a6d. Thanks for that!
But as I can see you are not passing this to `Progress` class, so in tests that use some time depended column (like `TransferSpeedColumn`) it will be required to override "time-getter" twice: once in `Console` for log messages and second time in `Progress` for speed estimates.
I think it would be nice if `Progress` used `Console`'s `_get_datetime` to setup default value of `get_time`.

**Comment by willmcgugan** [comment]
Potentially. Although Console requires a datetime, whereas Progress needs the time in seconds. But I guess I could derive the seconds from the datetime.

I'll look in to it...

**Comment by willmcgugan** [comment]
I've added both a get_time and get_datetime to Console in 9.3.0 (on PyPi now). The get_time method will filter down to the Progress class when it renders. Should help with testing.

@asvetlov Glad you like Rich. I feel the same way about aiohttp.

**Comment by asvetlov** [comment]
Cool, thank you very much!
