### ISSUE TITLE
[REQUEST] Support rich warnings

### ISSUE THREAD

**Issue by turbaszek** [willmcgugan/rich#433]
**How would you improve Rich?**

I would love to use similar mechanism as `warning.warn("my message", WarningType)` but with rich text. This would play nicely with applications that already use rich.

**What problem does it solved for you?**

Having this feature rich users will be able to use rich in every aspect of showing messages to users.

**Comment by willmcgugan** [comment]
I don't see any easy way to integrate Rich with the warning module. To be honest, I don't understand why you would want it. Do you want to display warnings in red or something?

**Comment by turbaszek** [comment]
> I don't see any easy way to integrate Rich with the warning module. 

Overriding [`warnings.showwarning `](https://docs.python.org/3/library/warnings.html#warnings.showwarning) may do the trick.

> To be honest, I don't understand why you would want it. Do you want to display warnings in red or something?

That was the main idea - to make deprecation warnings easy to spot between teens of lines of other information. That was something that crossed my mind yesterday when I added a warning that can be missed by users.

**Comment by willmcgugan** [comment]
Interesting. I didn't know that was the recommended way of customizing warnings.

TBH I don't think this belongs in Rich itself. But it looks easy enough to implement a `showwarning` function that uses the Console to print the warning if you wanted that.

**Comment by pbsds** [comment]
For reference here is my implementation:

```python
from rich.traceback import install
from rich.console import Console
import warnings, sys


def showwarning(message, category, filename, lineno, file=None, line=None):
    msg = warnings.WarningMessage(message, category, filename, lineno, file, line)

    if file is None:
        file = sys.stderr
        if file is None:
            # sys.stderr is None when run with pythonw.exe:
            # warnings get lost
            return
    text = warnings._formatwarnmsg(msg)
    if file.isatty():
        Console(file=file, stderr=True).print(text)
    else:
        try:
            file.write(text)
        except OSError:
            # the file (probably stderr) is invalid - this warning gets lost.
            pass
warnings.showwarning = showwarning

def warning_no_src_line(message, category, filename, lineno, file=None, line=None):
    if (file is None and sys.stderr is not None) or file is sys.stderr:
        return f"[yellow]{category.__name__}[/yellow]: {message}\n    ({filename}:{lineno})"
    else:
        return f"{filename}:{lineno}: {category.__name__}: {message}"
warnings.formatwarning = warning_no_src_line
```
