### ISSUE TITLE
[BUG] Progress bar has high overhead

### ISSUE THREAD

**Issue by paw-lu** [willmcgugan/rich#434]
**Describe the bug**

The progress bar ads significant overhead.

Hi! was checking out the progress bars—which look _great_! I was noticing that using them was significantly slowing down the processes I was trying to track.

Thanks!

**To Reproduce**

```python
>>> %%timeit
>>> x = []
>>> for i in range(999):
>>>     x.append(i)
82.5 µs ± 6.88 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

>>> %%timeit
>>> x = []
>>> for i in rich.progress.track(range(999)):
>>>     x.append(i)
12.2 s ± 991 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Platform**
macOS 10.15.7
Rich 9.2.0

**Comment by willmcgugan** [comment]
Are you running this in a terminal or jupyter ?

**Comment by paw-lu** [comment]
This test was run in Jupyter. Sorry for forgetting to specify!

**Comment by willmcgugan** [comment]
It will be slower on Jupyter, which doesn't support the auto_refresh option. Without auto refresh, the bar will be refreshed on each pass through the loop -- which is where most of the time is going.

From your timeit results, the refresh adds around 12ms for each pass, which is unlikely to be significant unless you are doing virtually no work inside the loop. 

If it is significant in a real world scenario, you can either run it in a terminal where the auto refresh ensures that the overhead is virtually nothing, or use the Progress class and call refresh() manually.  See the [note in the docs](https://rich.readthedocs.io/en/latest/progress.html#progress-display) for details.

**Comment by paw-lu** [comment]
Got it!
Makes sense.

Good tip on using `refresh()` manually.

Thanks for the response @willmcgugan , and thanks for the library!
