### ISSUE TITLE
[REQUEST] Allow RichHandler to receive custom log rendered class

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#438]
At this moment RichHandler does use a hardcoded LogRender and the only way to use an alternative one is to modify `_log_render` after instantiation.

**How would you improve Rich?**

I am more than happy to create a very small PR that allows user to specify which class to be used for log renderer. That is a no risk change to do as all existing code would default to current LogRender.

**What problem does it solved for you?**

This would allow implementation of other renderers, like one that does soft wrapping.

The current workaround of using of private attributes is dangerous as it could break on any new rich release.

**Comment by willmcgugan** [comment]
If you want to customize it to that degree, why not extend the class or write your own version?

**Comment by ssbarnea** [comment]
I am already doing this, i will publish a link later today after I clean the implementation. Once I do it will be very easy to see why allowing this would make code cleaner as it would reduce the amount of customization or private API usage.

My desired is to minimize the divergence from core rich logger features in order to avoid bugs and other surprises.

**Comment by ssbarnea** [comment]
It appears that I forgot to include a link to https://github.com/pycontribs/enrich/blob/main/src/enrich/logging.py#L13 -- That is where FluidLogRender is implemented which does not produce output fixed to the terminal width.

**Comment by willmcgugan** [comment]
You are probably better off overriding `emit` that using a private attribute.

What might help is factoring out a separate `render` method that is responsible for just the printing. That would reduce the boiler-plate code, and not require a new public interface.

@ssbarnea you might get better feedback if you ask for advice in solving your problem, rather than asking me to implement your solution to the problem.

**Comment by ssbarnea** [comment]
I think I started this with https://github.com/willmcgugan/rich/discussions/344 but the thread got bit lost in time. Better to continue there. I am more than interested to improve the hacky implementation.

I agree with you that use of private interfaces was far from great and believe me that every time I read about a new release I get bit scared as I wonder if my hacks stopped working.

**Comment by jdumas** [comment]
I think I'm facing a very similar issue. I want to use the `RichHandler` as a handler for the `logging` python module, in a job that is running on Jenkins. The terminal output is captured by Jenkins and the result has a unnecessary hard-wrap that I would like to avoid.

**Comment by jdumas** [comment]
@willmcgugan do you have any suggestion for the use-case I described above? My console log output is captured by jenkins, so I would very much like to not have it truncated. I really need my console output to not assume any maximum width, as it is captured by another process. Right now I create a `RichHandler` on a `Console(soft_wrap=True, width=sys.maxsize)`, which is a bit of a ugly hack.

**Comment by willmcgugan** [comment]
RichHandler was designed for readability on a terminal and uses a table to create the neat columns. There's just no way to soft wrap a table. If you set the console width to `maxsize` I'm afraid you are going to generate an awful lot of padding!

I'd suggest using a different handler for CI. You could implement a logging handler that prints a [Text](https://rich.readthedocs.io/en/latest/text.html) instance with the required fields.  See the [RichHandler](https://github.com/willmcgugan/rich/blob/master/rich/logging.py) source for an example of implementing a logging handler, but your implementation could be much simpler.

**Comment by jdumas** [comment]
Yeah I was hopping I could find something in Rich to support this use-case. I think @ssbarnea implemented such a handler in [enrich](https://github.com/pycontribs/enrich), but sometimes the libs can get out of sync and it's causing compatibility issues.
