### ISSUE TITLE
[REQUEST] Shared base class for rich objects

### ISSUE THREAD

**Issue by erezsh** [willmcgugan/rich#439]
**How would you improve Rich?**

I have several "repr" functions in my program, some of which I want to return a special Rich object, such as `rich.table.Table`, `rich.panel.Panel`, etc., and others to return plain-text or a different kind of object.

It would be very helpful if I could do `isinstance(obj, rich.RichObject)`, and then send it to `console.print`, or otherwise handle it differently.

Right now my choices are to:

1. List every rich object that I use

2. Wrap all rich objects in a `Rich(...)` object, that does nothing but signify the type

3. Use `hasattr(obj, "__rich_console__")`

They all feel a little awkward to me, therefore my suggestion to support `isinstance`.

**What problem does it solved for you?**

It will allow me to mix rich objects with objects from other libraries and from my own program, in a natural way.

**Comment by willmcgugan** [comment]
You can use the `is_renderable` method.

```
from rich.protocol import is_renderable
```

**Comment by erezsh** [comment]
That's actually not great for my use-case, because it will return true for any string, which may contain special characters.

I'm not concerned if rich *can* render it, but if it's specifically meant to.

**Comment by erezsh** [comment]
If you consider `__rich_console__` to be a stable API (i.e. it will always be there) then it's good enough for me.

(but I still think my suggestion makes sense)

**Comment by willmcgugan** [comment]
You could adapt the implementation accordingly.

```python
from typing import Any


def is_renderable(test_renderable: Any) -> bool:
    """Check if an object may be rendered by Rich."""
    return (
        isinstance(test_renderable, str)
        or hasattr(test_renderable, "__rich_console__")
        or hasattr(test_renderable, "__rich__")
    )
```

Removing the str check should give you what you need.

There is intentionally no base class for Rich objects so that it doesn't place a burden on library authors. With duck typing you can add support for Rich without adding Rich as a dependancy.

> If you consider __rich_console__ to be a stable API (i.e. it will always be there) then it's good enough for me.

It will be.

**Comment by erezsh** [comment]
> With duck typing you can add support for Rich without adding Rich as a dependancy.

I don't know why that would be desirable..

> Yeah, it's not going to change.

Alright, thanks!
