### ISSUE TITLE
Formatting lost when piped to `less`

### ISSUE THREAD

**Issue by Chaz6** [willmcgugan/rich#44]
I tried the example code in a script:-

```
from rich.console import Console
from rich.markdown import Markdown

console = Console()
with open("README.md") as readme:
    markdown = Markdown(readme.read())
console.print(markdown)
```

When I run the script and pipe it to `less` to read a file longer than a page, all the formatting is lost. How can one ensure that the formatting persists?

**Comment by willmcgugan** [comment]
Couple of things going on here. Rich detects that it is not writing directly to a terminal and won't output control codes. Normally this is desirable, but you can force it to write control codes by adding `force_terminal=True` to the Console constructor.

I've also noticed that less itself won't display color/style unless you add the `-R` switch.

Hope that helps.

**Comment by NightMachinary** [comment]
I suggest adding this code snippet to the readme, lots of people will find it useful (there are tools like `mdless` just for this, and I like `rich` better.)

```
#!/usr/bin/env python3

import sys, os
from rich.console import Console
from rich.markdown import Markdown

console = Console(force_terminal=bool(os.environ.get("rich_force_terminal", True)))
with open(sys.argv[1]) as readme:
    markdown = Markdown(readme.read(), code_theme="")
console.print(markdown)
```

**Comment by willmcgugan** [comment]
@NightMachinary That's not a bad idea. It could work with `python -m rich.markdown readme.md`

**Comment by willmcgugan** [comment]
I've added a `python -m rich.markdown` command. Hopefully this will do what you need.

If you need any changes I'd be happy to accept a PR. See the end of `markdown.py`
