### ISSUE TITLE
[REQUEST] Support for superscript and subscript

### ISSUE THREAD

**Issue by schneiderfelipe** [willmcgugan/rich#440]
Currently, Rich seems not to support superscripts/subscripts (e.g., `cm⁻¹`).

**How would you improve Rich?**

Something like

```python3
from rich import print

print("1 cm[super]-1[/super]")
# => 1 cm⁻¹
```

would be awesome.

**What problem does it solve for you?**

That could be used in many programs that output things such as simple equations and units, which is what I am looking for.

**Comment by willmcgugan** [comment]
There are ansi codes for super / subscript but they are not well supported, so not implemented in Rich.

The only other option would be to replace each character with the equivalent super/sub version. Doable, but I'm not keen to go down that route, as this simple markup could become hard to maintain with a number of extensions.

Have you seen [unicodeit](https://github.com/svenkreiss/unicodeit)? It turns latex like expressions in to unicode, and works well with Rich.

**Comment by schneiderfelipe** [comment]
@willmcgugan I haven't heard of unicodeit; it probably solves my issue perfectly! Thanks!

Do you have any recommendations on how to best use Rich together with unicodeit? I'm thinking about something like

```python3
import unicodeit
from rich import print

print(unicodeit.replace(r"\alpha"))
```

i.e., replacing LaTeX expressions before passing strings to Rich. Is this the way to go?

**Comment by willmcgugan** [comment]
Yeah. That’s as good approach as any.

**Comment by schneiderfelipe** [comment]
Thanks! I'll close this.
