### ISSUE TITLE
[BUG] Rich is too restrictive on dataclasses dependency

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#446]
**Describe the bug**
Few minutes ago I got some [pip install failures](https://github.com/ansible-community/molecule-podman/pull/25/checks?check_run_id=1459010189) which, IMHO are caused by being too restrictive regarding supported versions. 

```
py36:
rich 9.2.0 has requirement dataclasses<0.8,>=0.7; python_version >= "3.6" and python_version < "3.7", but you have dataclasses 0.8.
```

I know a bump happened on on Nov 10 but no release was made since. Still, I do think that the version compatibility range should not have a ceiling bound unless it is already known to break the library.

This is particularly problematic with rich which is mostly a library, so it needs to play well with other dependencies the project may need.

Lets assume you make 9.2.1 hotfix today to sort this issue. What happens if dataclasses makes release 0.9 tomorrow, it will likely get into conflict with rich again, even if there is no proof that they do not work together. This is even more problematic as the ceiling seams to be applied to the minor version.

If the concerns around possible breakage produced by dataclasses are real, at least the conditions should look more like `<1.0`.

**Comment by willmcgugan** [comment]
I'm not sure if dataclasses follows semver, and even if it does, the 0 major version allows for breaking changes. Until they release 1.0 I think its wise to check compatibility before a release. I'd rather issues were flagged at built time than expose apps to potential bugs.
