### ISSUE TITLE
[REQUEST] Add max_length to RichHandler

### ISSUE THREAD

**Issue by hhoeflin** [willmcgugan/rich#450]
Have you checked the issues for a similar suggestions?

Yes

**How would you improve Rich?**

Pretty recently got the `max_length` keyword to abbreviate printing of long lists. The same issue occurs in tracebacks, but there the `max_length` keyword is not available when printing locals. Tracing the issue, the `render_scope` function uses `Pretty` but does not take or pass the `max_length` option. 

I wonder if making a global option or a console option (similar to a theme) would be a possibility without having to introduce yet another parameter to the logging handler (and in the code pass it down lots of levels).

**What problem does it solved for you?**

The problem it solves is very long tracebacks in certain contexts where errors are thrown with local variables consisting of long lists or dictionaries.

And thank you - rich is awesome!

**Comment by willmcgugan** [comment]
I think the solution is just to pass those parameters. Granted there are a lot of parameters on the handler, but It does seem to be the move obvious place for them. I do like the idea of some kind of configuration at the Console level, I'll think about it.

I suspect that the logging handler should set a max_length and max_string by default. Any suggestions re those default values?

**Comment by hhoeflin** [comment]
Thanks for taking care of this so fast! I don't have any particular opinion about default string length. For max_length, 10 seems reasonable to me (it is e.g. also the default number of rows pandas prints for abbreviated tables) but 20 would also still be ok.
