### ISSUE TITLE
Global suppress

### ISSUE THREAD

**Issue by bandoos** [willmcgugan/rich#453]
Hi,
First of all thanks for the awesome lib!

I tried looking around for this information but maybe i'm just missing it:
Is there any way to suppress the coloring of output? so for example if I have
a program that is sometimes run in interactively (with coloring) and sometimes  in  a pipeline (so no coloring), so
i'd usually have a --no-color flag. 

Of course this can be handled at higher level wrapping rich, but maybe I'm missing a simpler solution somewhere?

**Comment by bandoos** [comment]
I now see that the lib is smart enough to suppress the coloring automatically when 
redirection is on! 

That solves my use case, but i'm still curious if one can control this explicitly

**Comment by willmcgugan** [comment]
You can set `color_system` to `None` to explicitly disable color (see https://rich.readthedocs.io/en/latest/console.html#color-systems)

**Comment by bandoos** [comment]
Thanks, I missed that bit!
