### ISSUE TITLE
[REQUEST] Change dependencies constraints from ^ to >=

### ISSUE THREAD

**Issue by hhoeflin** [willmcgugan/rich#454]
Have you checked the issues for a similar suggestions?

Yes, did not find a similar request.

**How would you improve Rich?**

Make rich less likely to cause dependency resolution issues. For example, currently you have a caret dependency on colorama ^0.4.0. Your package is young enough so that this covers all newer versions. But if colorama outputs a version 0.5.0, and another package would use ^0.5.0, this would lead to an unresolvable dependency - and that although very likely there is no issue at all. 

The caret operator is very conservative, assumes a strict adherence to SemVer on the side of the dependency that is often not the case.

**What problem does it solved for you?**

Forward looking action to prevent dependency resolution problems in the future for projects with many dependencies. Other languages can use ^ much better as they allow multiple versions of the same package to be installed, but python doesn't. So ^ will over the long run lead to incompatible dependencies.

**Comment by willmcgugan** [comment]
If a new version of colorama is released with a backwards compatible change, any software using Rich will break. To my mind, it is more desirable that dependency issues are caught before any code goes in to production. I'd much rather have the opportunity to run Rich's tests against new versions.

The situation is not all that dire, given that we have dependency-bot that automatically creates PRs for updates.

**Comment by hhoeflin** [comment]
I agree - as long as you are as active as you currently are, that is not problem at all. 

Personally I have encountered lots of still useful packages that were semi-abandoned by their developers. It is always a pity then if something breaks for no other reason than an artificial dependency constraint that was unnecessary.
