### ISSUE TITLE
[BUG] Table: Different behavior using `row_styles` vs. styling each row

### ISSUE THREAD

**Issue by mheden** [willmcgugan/rich#457]
**Describe the bug**
There seem to be different behavior using `row_styles` compared to do the styling in the `add_row` command.

**To Reproduce**
```py
console = Console()

bg = Style(bgcolor="rgb(120,40,40)")

table1 = Table(box=box.SIMPLE_HEAD, title="table1", row_styles=["none", bg])
table1.add_column("foo")
table1.add_column("bar")
table1.add_row("1", "2")
table1.add_row("3", "4")
console.print(table1)

table2 = Table(box=box.SIMPLE_HEAD, title="table2")
table2.add_column("foo")
table2.add_column("bar")
table2.add_row("1", "2", style="none")
table2.add_row("3", "4", style=bg)
console.print(table2)
```
![image](https://user-images.githubusercontent.com/8748209/100612273-02d76d80-3313-11eb-9034-672100fa4acc.png)

**Platform**
Windows 10, Windows terminal, rich 9.2.0

**Comment by willmcgugan** [comment]
It may not be clear from the docs, but the add_row applies a style to each of the cells. Were you looking to highlight a specific row or something?

**Comment by mheden** [comment]
Thanks,

from https://rich.readthedocs.io/en/latest/reference/table.html?highlight=add_row#rich.table.Table.add_row I think it looks like the row should be styled and not the individual cells:

`style (StyleType, optional) – An optional style to apply to the entire row. Defaults to None.`

But anyhow, my use case is to highlight specific rows (dependent on a value in a cell on that row) but it is not very convenient to use the method used in `table1` for this use case since it will require that I know all the data when creating the table. Is it possible to style a complete row (so it looks like the output of `table1`) without specifying it in the `Table` creation?

**Comment by willmcgugan** [comment]
You can set `row_styles` to a list of strings after the Table is constructed. But I agree the style on add_row should probably set it for the whole row. I'll look in to changing that in a next release.

**Comment by mheden** [comment]
Thanks for the hint! I did the following which works fine:
```
        for row in rows:
            values, level = row
            table.add_row(*values)
            table.row_styles.append(bgs[level])
```

**Comment by willmcgugan** [comment]
You can also use the `style` parameter on `add_row` now, in v9.4.0
