### ISSUE TITLE
Add table would be better if it took a list rather than multiple strings as input

### ISSUE THREAD

**Issue by bradh11** [willmcgugan/rich#458]
Have you checked the issues for a similar suggestions? 
Yes

**How would you improve Rich?** 
The grid system with Tables would be much better if it took a list as input rather than multiple strings.
```
grid.add_row("Raising shields", "[bold magenta]COMPLETED [green]:heavy_check_mark:")
```
should be 
```
grid.add_row(["Raising shields", "[bold magenta]COMPLETED [green]:heavy_check_mark:"])
```
This would be a much more "Pythonic" way to iterate over data and aligns more closely with other libraries such as `openpyxl` and the `csv` built in module of Python.

**What problem does it solved for you?**
This will make the library MUCH more easy to use with iterables. which is 99% of the time how people will want to use it. (unless you have a better suggestion or example with using this with a for loop?)

**Comment by willmcgugan** [comment]
Not sure why you would prefer one over the other. Some example code might help.

**Comment by bradh11** [comment]
yes, an example with a for loop would be great.  It seemed rather challenging to get it working while iterating over a list of dictionaries (which is super common use case I would think).

**Comment by bradh11** [comment]
There is another similar library called [Pretty Tables](https://github.com/jazzband/prettytable) - This is a pretty popular one I think.  Does not have all your awesome formatting though.  :-D

**Comment by willmcgugan** [comment]
What I meant was, could you give me an example of the code you think would be improved if `add_row` accepted a list?

**Comment by bradh11** [comment]
Well that actually seems to be the trick.  We tried using Rich with a servicenow integration we are doing and hit a roadblock and needed to switch to PrettyTable library because of this issue.  

Thanks much,
Brad

```
from snow import Snow
from prettytable import PrettyTable
from tables import *
import yaml
from pprint import pprint

dev_tab = PrettyTable()
loc_tab = PrettyTable()
user_tab = PrettyTable()

with open('config.yaml', 'r') as cf:
    conf = yaml.safe_load(cf)

dev_tab.field_names = device_columns
loc_tab.field_names = location_columns
user_tab.field_names = users_columns

c = Snow(instance=conf['INSTANCE'], company_id='LIONS001', username=conf['USERNAME'], password=conf['PASSWORD'])

devices = c.get_devices()
locations = c.get_locations()
users = c.get_users()

for x in devices:
    row = [x.get(col) for col in device_columns]
    dev_tab.add_row(row)

for x in locations:
    row = [x.get(col) for col in location_columns]
    loc_tab.add_row(row)

for x in users:
    row = [x.get(col) for col in users_columns]
    user_tab.add_row(row)

print(dev_tab)
print(loc_tab)
print(user_tab)

```

**Comment by willmcgugan** [comment]
Have you ever encountered argument unpacking in Python?

```python
row = ["foo", "bar"] 
table.add_row(*row)
```

**Comment by bradh11** [comment]
in the above example, `devices`, `locations`, and `users` are all lists of dictionaries.  We want to append a new row for each device.  hopefully this gives you the scenario.    So effectively we would have to solve it be doing the following code with the Rich library:

```
for x in devices:
    dev_tab.add_row(x['column1_name'], x['column1_name'],x['column2_name'],x['column3_name'],x['column4_name'],x['column5_name']x['column6_name'],x['column7_name'],x['column8_name'])
```

**Comment by bradh11** [comment]
> Have you ever encountered argument unpacking in Python?
> 
> ```python
> row = ["foo", "bar"] 
> table.add_row(*row)
> ```

ah, that would work...  yes, we did not think of that.  That said, i think you still may have some better adoption from users coming from alternative libraries like csv, Prettytable, openpyxl, etc...  That way the api would be more similar.  Make sense?

**Comment by willmcgugan** [comment]
The positional arguments are cleaner in other scenarios. The table rows can accept any object types (even other tables) where the data may not naturally be in a list. If you do have a list, then unpacking is minimal additional effort.

**Comment by thunder-sword** [comment]
> Have you ever encountered argument unpacking in Python?
> 
> ```python
> row = ["foo", "bar"] 
> table.add_row(*row)
> ```

thank for your trick, it helpd me!!
