### ISSUE TITLE
[BUG] justify does not work for console.log

### ISSUE THREAD

**Issue by bartzy** [willmcgugan/rich#460]
**Describe the bug**
justify doesn't work for `console.log` calls while it does work correctly for `console.print` calls.
The docs state that `console.log` should support `justify`, so I considered this as a bug. Please label it as a feature request if you think otherwise.
  
**To Reproduce**
```
console.log("This should be centered", justify="center")
```

**Platform**
OS: macOS Big Sur
Python 3.7.7
Rich 9.2.0

**Comment by willmcgugan** [comment]
Please try 9.3.0
