### ISSUE TITLE
[QUESTION]The live module can't refresh as expected.

### ISSUE THREAD

**Issue by DarrenIce** [willmcgugan/rich#465]
Hi there.
I want to use rich.live module to show something in real time and I test it with your sample code.
```python
import time

from rich.live import Live
from rich.table import Table

table = Table()
table.add_column("Row ID")
table.add_column("Description")
table.add_column("Level")

with Live(table, refresh_per_second=4):  # update 4 times a second to feel fluid
    for row in range(12):
        time.sleep(0.4)  # arbitrary delay
        # update the renderable internally
        table.add_row(f"{row}", f"description {row}", "[red]ERROR")
```
However, it did't refresh, just show the final result for me.
Could you give me some ideas how to use this module correctly?

**Comment by nathanrpage97** [comment]
```python
import time

from rich.live import Live
from rich.table import Table
from rich.console import Console

table = Table()
table.add_column("Row ID")
table.add_column("Description")
table.add_column("Level")

console = Console(force_terminal=True)

with Live(
    table, console=console, refresh_per_second=4
):  # update 4 times a second to feel fluid
    for row in range(12):
        time.sleep(0.4)  # arbitrary delay
        # update the renderable internally
        table.add_row(f"{row}", f"description {row}", "[red]ERROR")
```

Try this out to see if forcing the console to be a terminal has any effect.

**Comment by DarrenIce** [comment]
> This snippet runs fine on my own setup. What kind of terminal are you running this snippet on?
I have tried it on vscode terminal, powershell and windows terminal, none of them can display correctly.

**Comment by nathanrpage97** [comment]
Can you run:

```python
from rich import get_console, inspect
inspect(get_console())
```

**Comment by DarrenIce** [comment]
I modified code.
```python
import time

from utils.rich.live import Live
from utils.rich.table import Table
from utils.rich.control import Control
from utils.rich.console import Console

table = Table()
table.add_column("Row ID")
table.add_column("Description")
table.add_column("Level")

console = Console(force_terminal=True,color_system='truecolor')

with Live(table, console=console, refresh_per_second=4) as live:  # update 4 times a second to feel fluid
    for row in range(12):
        time.sleep(0.4)  # arbitrary delay
        # update the renderable internally
        table.add_row(f"{row}", f"description {row}", "[red]ERROR")
        live.console.print(Control(""))
```
Now it can display in real time, just flickers

**Comment by DarrenIce** [comment]
> Can you run:
> 
> ```python
> from rich import get_console, inspect
> inspect(get_console())
> ```
> 
> And paste printed results.


Here is the result
![image](https://user-images.githubusercontent.com/34674240/101130653-d25b4080-363e-11eb-8266-fb2223a0362c.png)

**Comment by nathanrpage97** [comment]
The issue is that it is a `dumb_terminal` this means that `rich` treats it as if the terminal doesn't have the ability to use ANSI codes.

**Comment by nathanrpage97** [comment]
As a quick work around

In powershell run:
```powershell
$env:TERM="SMART"
```

Then re-run the initial code.

**Comment by DarrenIce** [comment]
> As a quick work around
> 
> In powershell run:
> 
> ```powershell
> $env:TERM="SMART"
> ```
> 
> Then re-run the initial code.


Thanks a lot, it works!

**Comment by nathanrpage97** [comment]
@willmcgugan Is there anything that the console `is_dumb_terminal` should be added for Windows? Or should 

```powershell
$env:TERM="SMART"
```
just be documented in a "common issues"  section of documentation to force a non dumb terminal.

**Comment by nathanrpage97** [comment]
Acutally, this reference to [console environment variables](https://rich.readthedocs.io/en/latest/console.html#environment-variables) should be enough.

**Comment by willmcgugan** [comment]
Thanks for diagnosing that @nathanrpage97 

`is_dumb_terminal` will be True if TERM is set to "dumb" or "unknown". As far as I know, this convention should apply to Windows.

@DarrenIce Do you recall adding the TERM environment variable? Could have been a workaround for an app that broken on Windows.

**Comment by DarrenIce** [comment]
> Thanks for diagnosing that @nathanrpage97
> 
> `is_dumb_terminal` will be True if TERM is set to "dumb" or "unknown". As far as I know, this convention should apply to Windows.
> 
> @DarrenIce Do you recall adding the TERM environment variable? Could have been a workaround for an app that broken on Windows.


Yes, I add two lines in my code, and now it can work as expect.
```python
self.console = Console(force_terminal=True,color_system='truecolor')
self.console._environ['TERM'] = 'SMART'   
```
