### ISSUE TITLE
[BUG] Persian Name in a screenshot on the README is rendered incorrectly

### ISSUE THREAD

**Issue by blueset** [willmcgugan/rich#466]
**Describe the bug**

Persian Name in a screenshot on the README is rendered incorrectly.

The correct form is `آرمین پارسا`.

**To Reproduce**
A minimal code example that reproduces the problem would be a big help if you can provide it. If the issue is visual in nature, consider posting a screenshot.

Open README, and find the screenshot. 
![](https://github.com/willmcgugan/rich/raw/master/imgs/columns.png)

**Platform**
What platform (Win/Linux/Mac) are you running on? What terminal software are you using. Which version of Rich?

N/A.

**Comment by willmcgugan** [comment]
If I cut and paste the name from GH in to a terminal it renders as in the screenshot. I'm guessing there are some combining rules for Persian that terminals currently don't handle. I'm afraid there isn't likely anything I can do to fix that in Rich.

**Comment by blueset** [comment]
I’ve tried it on my Mac, and it turns out to be indeed a terminal emulator problem. It works properly in the built-in Terminal, but not with iTerm.

Would it be better if the screenshot can be instead taken on a terminal that support Persian text, or just get rid of it completely? Incorrectly rendered text doesn’t really look good on a demo screenshot.
