### ISSUE TITLE
Progress won't automaticly update.

### ISSUE THREAD

**Issue by FilipAndersson245** [willmcgugan/rich#47]
```py
def fetch_file(url, filename):
    with open(filename, "ab") as file:
        headers = create_header()
        pos = file.tell()
        if pos:
            headers['Range'] = f'bytes={pos}-'
        response = requests.get(url, headers=headers, stream=True)


        total_size = int(response.headers.get('content-length'))
        task_id = download_progress.add_task(description="Downloading", filename=filename, total=total_size, completed=pos)

        for data in response.iter_content(chunk_size=1024):
            file.write(data)
            download_progress.advance(task_id=task_id, advance=len(data))
```
This code will not update the progress bar and it will only be renderd once.
Changing the last line to`download_progress.update(task_id=task_id, advance=len(data), refresh=True)` fixes it but makes the progress bar update to frequent.

This was done using Windows Terminal, 

output:  
![image](https://user-images.githubusercontent.com/17986183/81094020-354af480-8f03-11ea-8618-015fb1ab0754.png)

**Comment by willmcgugan** [comment]
The Progress class works as a context manager. If you aren't using a context manager you can call `start` and then `stop` when finished. That launches a thread which does auto refresh.

**Comment by FilipAndersson245** [comment]
> The Progress class works as a context manager. If you aren't using a context manager you can call `start` and then `stop` when finished. That launches a thread which does auto refresh.  

Aha i understand now, this fixed the problem.
Thanks!
