### ISSUE TITLE
[REQUEST]May I Change the font size in jupyter ?  How.

### ISSUE THREAD

**Issue by mc436572** [willmcgugan/rich#470]
**May I Change the font size in jupyter ?  How.**
Thank U!

**Comment by willmcgugan** [comment]
I'm afraid it's not exposed anywhere. Did you want to make it smaller or larger?

**Comment by mc436572** [comment]
Yes， Is there any way to  **use code** to control output font (larger/small/ left/ center/ right....) in jupyter notebook ?

**Comment by willmcgugan** [comment]
You can align text with Rich, but there's currently no way to set the font size.
