### ISSUE TITLE
[REQUEST] pretty.install does not work with IPython InteractiveShellEmbed.

### ISSUE THREAD

**Issue by amal-khailtash** [willmcgugan/rich#471]
Have you checked the issues for a similar suggestions?  I did not find any

**How would you improve Rich?**

pretty.install is great and modifies sys.displayhook, but it does not seem to affect IPython's interactive shell for it has its own displayhook (RichPromptDisplayHook).

**What problem does it solved for you?**

It provides a much nicer printout for data structures.

What problem do you have that this feature would solve? I may be able to suggest an existing way of solving it.

More readable IPython REPL.  The following example does not seem to change IPython displayhook.

```
from IPython.terminal.embed import InteractiveShellEmbed

ipshell = InteractiveShellEmbed(user_ns=globals())
pretty.install(indent_guides=True)
print(sys.displayhook)
print(ipshell.displayhook)
ipshell()
```

Output:

```
<function install.<locals>.display_hook at 0x7f9cbcdcaca0>
<IPython.terminal.prompts.RichPromptDisplayHook object at 0x7f9cbd6021c0>
```

**Comment by canbooo** [comment]
Bump as this would also make Spyder users happy.

**Comment by willmcgugan** [comment]
Works in 9.6.0 Thanks to @nathanrpage97
