### ISSUE TITLE
[REQUEST] Add support for `style` argument for console.log

### ISSUE THREAD

**Issue by bartzy** [willmcgugan/rich#475]
**How would you improve Rich?**

It would be awesome if one could pass a style argument to `console.log`, like `console.print`:
`console.log('foo', style='red')` instead of `console.log('[red]foo[/red]')`

**What problem does it solve for you?**

Makes the callsites nicer and unifying the API.

**Comment by willmcgugan** [comment]
Fixed in 9.4.0
