### ISSUE TITLE
[REQUEST] Extend cell background color across entire row for a single row

### ISSUE THREAD

**Issue by grolinet** [willmcgugan/rich#477]
Hi

First, thanks for this project, my shell applications now look awesome! :+1: 

I just saw this feature request (https://github.com/willmcgugan/rich/issues/383).
Would it be possible to do the same for a single row? 
I can change the background of a single row with the `style` attribute when using `add_row`, but then only the background of every cell is changed even when not using vertical separators.

![image](https://user-images.githubusercontent.com/14868599/101659885-d1fbe480-3a46-11eb-8c14-8c62c2dcb354.png)

The reason is i want to highlight (change color) only specific rows. 

I know i could use `row_styles` when creating the table, and just provide a style for every row, but that seems a bit messy when there are a lot of rows.
Image using the `row_styles`:
![image](https://user-images.githubusercontent.com/14868599/101659994-f3f56700-3a46-11eb-8865-ec7cb12478ca.png)

The second image shows what i actually want to achieve.
Also i would find it cool to have the option to choose if the style should also be used when there are vertical lines. 

Here the code i used to create those two tables:
```python
from rich.console import Console
from rich.table import Table
from rich import box

table = Table(title="Star Wars Movies", title_style="", box=box.HORIZONTALS)

table.add_column("Released", justify="right",  no_wrap=True)
table.add_column("Title" )
table.add_column("Box Office", justify="right")

table.add_row("Dec 20, 2019", "Star Wars: The Rise of Skywalker", "$952,110,690")
table.add_row("May 25, 2018", "Solo: A Star Wars Story", "$393,151,347")
table.add_row("Dec 15, 2017", "Star Wars Ep. V111: The Last Jedi", "$1,332,539,889", style="on green")
table.add_row("Dec 16, 2016", "Rogue One: A Star Wars Story", "$1,332,439,889")

console = Console()
console.print(table)
```

```python
from rich.console import Console
from rich.table import Table
from rich import box

row_styles=["", "", "on green", ""]  #This is a bit messy...?
table = Table(title="Star Wars Movies", title_style="", box=box.HORIZONTALS, row_styles=row_styles)

table.add_column("Released", justify="right",  no_wrap=True)
table.add_column("Title" )
table.add_column("Box Office", justify="right")

table.add_row("Dec 20, 2019", "Star Wars: The Rise of Skywalker", "$952,110,690")
table.add_row("May 25, 2018", "Solo: A Star Wars Story", "$393,151,347")
table.add_row("Dec 15, 2017", "Star Wars Ep. V111: The Last Jedi", "$1,332,539,889")
table.add_row("Dec 16, 2016", "Rogue One: A Star Wars Story", "$1,332,439,889")

console = Console()
console.print(table)

```

**Comment by willmcgugan** [comment]
Fixed in 9.4.0
