### ISSUE TITLE
[BUG] Dupe output in jupyter with `Live`

### ISSUE THREAD

**Issue by jph00** [willmcgugan/rich#485]
**Describe the bug**

When calling `Live` in Jupyter Notebook (most recent version) the output updates correctly, but upon completion, a second version of the output appears.

**To Reproduce**

Here's what happens when using the code from the docs:

----

<img src="https://user-images.githubusercontent.com/346999/102018838-9e5dda80-3d24-11eb-9c2b-48c1f5147fc9.png" width="500">

----

**Platform**

Jupyter Notebook on Ubuntu 20.04.

PS: Thanks for an amazing library! :)

**Comment by willmcgugan** [comment]
Thanks for the bug report. @nathanrpage97 any chance you could take a quick look?

**Comment by nathanrpage97** [comment]
Let me take a look.

**Comment by willmcgugan** [comment]
Fix in master. Will have a release soon.

**Comment by Azharu1** [comment]
Ok Man wait I can help you.

**Comment by jph00** [comment]
On Mon, Dec 14, 2020, at 8:01 AM, Will McGugan wrote:
> Fix in master. Will have a release soon.


Thanks so much! FYI we're planning to port ghtop over to rich, and we're using Jupyter for prototyping, so this is nice to have.

https://github.com/nat/ghtop/

**Comment by willmcgugan** [comment]
Fixed in 9.5.0
