### ISSUE TITLE
[BUG]main stop broadcasting

### ISSUE THREAD

**Issue by ThaGrimeyone** [willmcgugan/rich#489]
**Describe the bug**

**To Reproduce**
A minimal code example that reproduces the problem would be a big help if you can provide it. If the issue is visual in nature, consider posting a screenshot.

**Platform**
What platform (Win/Linux/Mac) are you running on? What terminal software are you using. Which version of Rich?

**Comment by ThaGrimeyone** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> A minimal code example that reproduces the problem would be a big help if you can provide it. If the issue is visual in nature, consider posting a screenshot.
> 
> **Platform**
> What platform (Win/Linux/Mac) are you running on? What terminal software are you using. Which version of Rich?
> 

I think Mac

**Comment by ThaGrimeyone** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> A minimal code example that reproduces the problem would be a big help if you can provide it. If the issue is visual in nature, consider posting a screenshot.
> 
> **Platform**
> What platform (Win/Linux/Mac) are you running on? What terminal software are you using. Which version of Rich?
> 

Yeah diffenetly mac

**Comment by willmcgugan** [comment]
What exactly is the issue?

**Comment by ThaGrimeyone** [comment]
My phone is hacked man it's broadcasting it's screen mirroring it's casting
my Bluetooth won't turn off I got malware I can't install. Help me teach me
coding please

**Comment by willmcgugan** [comment]
Sorry, this is not the type of coding I do.
