### ISSUE TITLE
Traceback defaults to width=88, docs suggest width=100

### ISSUE THREAD

**Issue by davised** [willmcgugan/rich#493]
Hi Will,

Thanks for this awesome package. I'm loving it.

I noticed this slight discrepancy in the traceback code when I was building my own Traceback() object.
https://github.com/willmcgugan/rich/blob/99cd18d9630c4edceb6303afef15f6060a094735/rich/traceback.py#L146
https://github.com/willmcgugan/rich/blob/99cd18d9630c4edceb6303afef15f6060a094735/rich/traceback.py#L160

I noticed if you run `install()` then you do get the 100 width.

https://github.com/willmcgugan/rich/blob/99cd18d9630c4edceb6303afef15f6060a094735/rich/traceback.py#L52

Having a blast using your package. Really makes my command line programs look polished.

Cheers,

Ed

**Comment by davised** [comment]
Just looked at your contributing.md file I can submit a PR if you'd prefer that.

**Comment by willmcgugan** [comment]
Thanks for the PR.
