### ISSUE TITLE
[BUG]Sometimes prints "-.WorkingWoWorkiWWorWWorWorWWoWoWorkiWorkingkiWorking." while doing tasks in the default progressbar

### ISSUE THREAD

**Issue by Franklin-oss** [willmcgugan/rich#494]
**Describe the bug**
prints "WorkingWoWorkiWWorWWorWorWWoWoWorkiWorkingkiWorking" while in a progress bar.

This happened when I resized my terminal window and maximized it back up. 
Also dupes the taskbars when I resize

**To Reproduce**
![image](https://user-images.githubusercontent.com/65860526/102190090-8f6e5800-3edd-11eb-9b32-8ca4d2436eea.png)

**Platform**
I'm am using Windows 10 and this is on cmd.

**Comment by willmcgugan** [comment]
This happens on cmd. I’m afraid there is nothing I can do about it. Windows terminal works much better.
