### ISSUE TITLE
[BUG] Exceptions inside progress

### ISSUE THREAD

**Issue by tgdn** [willmcgugan/rich#497]
I'm not sure this is a bug or if I'm simply unable to find the solution to my problem.

Sorry in advance if this is a duplicate or if it is documented, but I really can't seem to find a solution.

## How do I print/handle/see exceptions when using progress?

I've tried:

```python
progress = Progress(
    redirect_stderr=False,
)

# or

progress = Progress(
    redirect_stderr=True,
)

with progress:
    raise Exception('hello')
```

I have even tried using my own Console, nothing happens, the exception is just invisible, which makes the code within `with` impossible to debug.

**Platform**
macOS 10.15.5
rich==9.3.0
Python 3.8.6

Thank you in advance.

**Comment by willmcgugan** [comment]
That may have been an issue with stderr redirect that was fixed in 9.3.0 Can you try 9.4.0?

**Comment by tgdn** [comment]
Just tried with 9.4.0 and still nothing. I can't `Console.print` and a call to `raise Exception()` does nothing but fail silently.

**Comment by willmcgugan** [comment]
Are you using Jupyter or terminal ?

**Comment by tgdn** [comment]
Terminal

**Comment by willmcgugan** [comment]
Then I'm stumped. Works for me on the same platform. Can you give me a fully working piece of code that shows the problem?

**Comment by willmcgugan** [comment]
I suspect that you're catching the exception somewhere else in your code, but if you do identify a problem in Rich please re-open this issue.
