### ISSUE TITLE
[REQUEST] Enhanced rich prompts

### ISSUE THREAD

**Issue by piyush-das** [willmcgugan/rich#498]
Hi,

Although this feature request in itself is debatable as being a standalone use case in itself. But given that rich is one of the most standout libraries for python, here's a long shot :smile: . 

I think it would be great if rich prompt can be enhanced to support advanced user inputs, something like [enquirer](https://github.com/enquirer/enquirer) in js. Although there are python libraries which currently try to cater to this request e.g [bulltet](https://github.com/bchao1/bullet), these libraries are very limited in being customizable or compatibility with jupyter notebooks etc. Since rich already has a great prompt, I was wondering if it could be extended to offer more enhanced features.

Thanks again for the great work.

**Comment by willmcgugan** [comment]
There's also https://github.com/CITGuru/PyInquirer

This is an often asked for feature. It may happen, but no promises...
