### ISSUE TITLE
Jupyter examples

### ISSUE THREAD

**Issue by donno2048** [willmcgugan/rich#499]
This is not a request for a feature in the actual code but rather a recommendation to introduce Jupyter notebook examples in the _examples_ folder considering this package is completely for visual styling.

**Comment by willmcgugan** [comment]
It’s a good idea. I’ve made a note of it. Feel free to submit a PR if you have any suggestions for examples.

**Comment by donno2048** [comment]
I submitted a PR with corresponding notebooks for some Python scripts...
See back at #500
