### ISSUE TITLE
Cursor movement?

### ISSUE THREAD

**Issue by makkus** [willmcgugan/rich#50]
Really nice work! Is there an abstraction for moving the cursor and/or updating several lines (or renderable objects) in place, or should I just use the terminal control codes? I had a brief look at the code but didn't find the place where the actual drawing is done (e.g. for the progress bars).

**Comment by willmcgugan** [comment]
There is an undocumented [LiveRender](https://github.com/willmcgugan/rich/blob/master/rich/live_render.py) class which is used by Progress to handle moving and refreshing. You could make use of that. Low level rendering is done in `__console__` methods.
