### ISSUE TITLE
[BUG] word joiner characters can break table row layout

### ISSUE THREAD

**Issue by robinwhittleton** [willmcgugan/rich#502]
**Describe the bug**
When the text in a table has [word joiner characters](https://en.wikipedia.org/wiki/Word_joiner) in it, the width of the row can be miscalculated, causing borders to overflow to the next line.

**To Reproduce**
```
from rich.console import Console
from rich.table import Table

console = Console()

table_with_wjs = Table()
table_with_wjs.add_column("Problem with word joiner characters")
table_with_wjs.add_row("word1⁠word2 word1⁠word2 word1⁠word2 word1⁠word2 word1⁠word2 word1⁠word2 word1⁠word2 word1⁠word2 word1⁠word2 word1⁠word2 word1⁠word2 word1⁠word2 word1⁠word2")
console.print(table_with_wjs)

table_without_wjs = Table()
table_without_wjs.add_column("No problem without word joiner characters")
table_without_wjs.add_row("word1word2 word1word2 word1word2 word1word2 word1word2 word1word2 word1word2 word1word2 word1word2 word1word2 word1word2 word1word2 word1word2")
console.print(table_without_wjs)

```
(note that there are word joiner characters in between each `word1` and `word2` strings in the first table)

This renders like this:

<img width="588" alt="Screenshot 2020-12-15 at 23 01 14" src="https://user-images.githubusercontent.com/7414/102278132-91f69f00-3f29-11eb-8001-42d550d904a4.png">

**Platform**
macOS 11.0.1, Apple Terminal (also tested in iTerm2), rich 9.4.0, font is Fira Mono but I’ve tested with most other pre-installed mono fonts and Source Code Pro.

**Comment by willmcgugan** [comment]
I'm afraid terminals have completely inconsistent support for unicode. I've just tried it on three terminals. Two were broken (in different ways). Hyper worked perfectly, probably because it is based on HTML technologies.

Rich correctly identifies it as a zero width character, but it has no way to control how the terminal displays it.

I'd suggest pre-processing your text to remove these characters.

**Comment by robinwhittleton** [comment]
OK! Let’s close this then and I’ll file a bug with Apple (to presumably be fixed in 5 years). Thanks for the investigation 🙂

**Comment by robinwhittleton** [comment]
(Now [fixed in iTerm2 trunk](https://gitlab.com/gnachman/iterm2/-/commit/262fa7f67666086d203571beb8087387c7f4e6c4).)
