### ISSUE TITLE
Line width of logs is highly truncated on Jupyter Lab

### ISSUE THREAD

**Issue by Tzeusy** [willmcgugan/rich#504]
Running with the RichHandler() in Jupyter Lab runs into issues where the output does not seem to be able to access the full width of the Jupyter terminal, while the original logging stream handler performs fine.

I've tried messing with the available params for RichHandler() but none of them seem to solve the issue (in this screenshot you can see I've tried `traceback_width`.

![image](https://user-images.githubusercontent.com/21179283/102292266-c7c67280-3f7f-11eb-9801-d351178ce7f9.png)

**To Reproduce** 
Sample code:
```
import sys
import logging
from rich.logging import RichHandler

logger = logging.getLogger()

formatter = logging.Formatter('%(asctime)s - %(name)s:%(lineno)d - %(levelname)s - %(message)s')
shandler = logging.StreamHandler(sys.stdout)
shandler.setFormatter(formatter)
logger.addHandler(shandler)
logger.addHandler(RichHandler(highlighter=None, rich_tracebacks=True, tracebacks_show_locals=True, tracebacks_width=300, locals_max_string=100))
logger.setLevel(logging.INFO)

logger.info("This is a line that is 168 characters long"*4)

# Traceback box also gets truncated
try:
    1/0
except:
    logger.exception("Error! A really long error message that describes the problem...")
```

**Platform**
Chrome

**Comment by willmcgugan** [comment]
Rich has no way to know how wide the browser is and has to render content with a fixed width. In a terminal it will extend to the full available width.

If you really want to use the logging handler in Jupyter, maybe set the time format to "%X" and disable the path display.
