### ISSUE TITLE
Choose color scheme for logging

### ISSUE THREAD

**Issue by Tzeusy** [willmcgugan/rich#505]
Forgive me if this is already a feature - did a little digging and was unable to find any parameter that could fix this. Essentially, the color scheme for logging is really hardto see in dark mode on Jupyter Lab:

![image](https://user-images.githubusercontent.com/21179283/102292692-aa45d880-3f80-11eb-865c-ee979a0327dc.png)

It would be nice to be able to supply a theme for this!

**Comment by willmcgugan** [comment]
See the docs on themes... https://rich.readthedocs.io/en/latest/style.html#style-themes

The RichHandler class accepts a `console` parameter which you can use to set a theme.
