### ISSUE TITLE
[BUG] overrided print statement change the content

### ISSUE THREAD

**Issue by phamquiluan** [willmcgugan/rich#507]
**Describe the bug**
overrided print statement change the content

**To Reproduce**
```
from progress import print
a = "[val] hello world!"
print(a)
>>  hello
```

**Platform**
What platform (Win/Linux/Mac) are you running on? What terminal software are you using. Which version of Rich?
linux/bash/rich==9.3.0

**Comment by willmcgugan** [comment]
Please see the docs on [Console markup](https://rich.readthedocs.io/en/latest/markup.html), specifically the section on escaping.
