### ISSUE TITLE
[REQUEST] HTML/CSS support

### ISSUE THREAD

**Issue by rcx** [willmcgugan/rich#509]
Have you checked the issues for a similar suggestions? Yes

**How would you improve Rich?**

The goal of Rich is to enable users to create rich displays in the terminal. Instead of re-inventing the wheel, why not use existing industry standard technologies such as HTML, CSS, and JavaScript to define the rich content displays? Web technologies are widely supported and existing frameworks such as Angular, React, and Vue are mature and certainly suitable for real-world workloads. Also, the technology stack has evolved to become increasingly suited towards web technologies: for example, [many processors have hardware support for JavaScript features](https://developer.arm.com/documentation/dui0801/g/hko1477562192868). More close to home, entire [terminal emulators](https://github.com/vercel/hyper) have been built using web technologies. I think that we should not ignore the industry trend.

**What problem does it solved for you?**

This allows would allow many developers to create UIs and displays using the technologies that are most familiar to them. This would allow for a myriad of code reuse opportunities, greatly enhancing the development experience.

**Comment by willmcgugan** [comment]
Terminals are a different medium to browsers. Different capabilities and different use-cases.
