### ISSUE TITLE
Add support for hyperlinks

### ISSUE THREAD

**Issue by acabal** [willmcgugan/rich#51]
In 2017 some terminals [gained support for hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda).

It would be very nice if in addition to the other BBcode-style formats we can use, like `[bold]`, we could also use `[url]`.

Python can output hyperlinks like so: `print("\033]8;;http://example.com\033\\This is a link\033]8;;\033\\")`

An example BBcode-style implementation might be: `[url="http://example.com"]This is a link[/url]`

**Comment by willmcgugan** [comment]
Wow, I didn't know that was possible. Don't suppose you know how to detect that capability of the terminal?

That would be a nice to have.

**Comment by acabal** [comment]
I don't know how to detect terminal capabilities, sorry. It [could be that it's not possible in the general case](https://stackoverflow.com/questions/7445658/how-to-detect-if-the-console-does-support-ansi-escape-codes-in-python) and that there'd have to be a database.

If detecting is not possible and it would be problematic to output unsupported escape codes, we could just say "use [url] at your own risk" and then not auto-linkify plain URLs. Or, enabling hyperlinks could be added as another option to the Console constructor.

**Comment by acabal** [comment]
While you think about this, a side question: is it possible to pass Rich escape codes directly, like the hyperlink, to print to the console when used in a table, while keeping BBcode-style syntax? I've been playing around but Rich seems to do something to the escape codes when printed in a table cell no matter what I do. For example the following prints a hyperlink but eats `bar` and the cell seems misaligned; but removing `bar` garbles the output:

```python
table = Table(show_header=True, header_style="bold", show_lines=True)
table.add_column("test", no_wrap=True)
table.add_row(table.add_row("[red]foo[/red] \033]8;;http://example.com\033\\This is a link\033]8;;\033\\ [blue]bar[/blue]"))

console = Console(highlight=False)
console.print(table)
```

**Comment by willmcgugan** [comment]
I think that's probably going to confound the length calculation of the strings. It's not going to be aware that some characters are invisible.

The link would have to be part of the Style class which is what ultimately generates the control codes. 

I am leaning towards extending the `[url]` tag btw. Probably with a switch on the constructor.

**Comment by willmcgugan** [comment]
@acabal If you're interested in trying it out, there is a branch called "hyperlinks" with working support for links.

The markup is `Hello [link="https://google.com"]World[/link]`.

I chose "link" over "url" because you might want to style something as a url , but not necessarily make it clickable. According to the spec, platforms that don't support links should just not render anything, so I'm leaning towards not having a switch on the constructor.

Thanks for telling me about this, its a nice feature.

**Comment by acabal** [comment]
Awesome!

Looks like links work when sent to `console.print()`. But, if I try to put a link in a table row, I get this dump:

```
  File "/home/alex/projects/standardebooks.org/tools/se/__init__.py", line 27, in <module>
    console.print(table)
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/console.py", line 718, in print
    extend(render(renderable, render_options))
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/console.py", line 507, in render
    yield from self._render(renderable, options)
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/console.py", line 483, in _render
    for render_output in iter_render:
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/table.py", line 308, in __console__
    widths = self._calculate_column_widths(console, max_width)
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/table.py", line 338, in _calculate_column_widths
    for column_index, column in enumerate(columns)
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/table.py", line 338, in <listcomp>
    for column_index, column in enumerate(columns)
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/table.py", line 432, in _measure_column
    _min, _max = get_render_width(console, cell.renderable, max_width)
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/measure.py", line 63, in get
    render_width = get_console_width(console, max_width).with_maximum(
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/padding.py", line 105, in __measure__
    console, self.renderable, max(1, max_width - extra_width)
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/measure.py", line 59, in get
    renderable = console.render_str(renderable)
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/console.py", line 568, in render_str
    rich_text = render_markup(text, style=style, emoji=emoji_enabled)
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/markup.py", line 102, in render
    for position, plain_text, tag in _parse(markup):
  File "/home/alex/projects/standardebooks.org/tools/se/vendor/rich/markup.py", line 67, in _parse
    yield start, markup[position:], None
UnboundLocalError: local variable 'start' referenced before assignment
```

**Comment by willmcgugan** [comment]
Should work everywhere now. Also works in markdown!

I've dropped the quotes from the link tag to make it easier to write in strings.

**Comment by willmcgugan** [comment]
Hyperlinks are in v1.1.0 now.

**Comment by acabal** [comment]
Works great, thanks! Awesome work!
