### ISSUE TITLE
Doesn't show colors in Github Actions

### ISSUE THREAD

**Issue by azrafe7** [willmcgugan/rich#52]
Hey, great project! Really awesome! 
Just read about it and couldn't wait to play with it. :smiley: 

I was trying to make it work in the Github Actions' shell (the online one) to get pretty colored text, but it seems to not be colorized somehow. :cry:  

Trying to gather some info online lead me nowhere... Still clueless (the only - maybe - useful thing being https://github.community/t5/GitHub-Actions/ANSI-color-output-in-webview/td-p/46226).

Posting, as you may be already aware of the issue (although I couldn't find a closed or open one).

As to what's happening, and **how to reproduce**:

I'm using code like this one:

```python
from rich.console import Console

print("python print")

console = Console()
console.log("console.log", [1, "str"], 'https://github.com/willmcgugan/rich/blob/9cba2027f4/tests/test_color_triplet.py', {"k": 'v', "date": '00:46:54'}, None, '2009-11-27T00:00:00.000100-06:39')
console.print("console.print", [1, "str"], 'https://github.com/willmcgugan/rich/blob/9cba2027f4/tests/test_color_triplet.py', {"k": 'v', "date": '00:46:54'}, None, '2009-11-27T00:00:00.000100-06:39')
```

And seeing this locally on my Windows box (via Cmder) - which is fine:

![image](https://user-images.githubusercontent.com/1266447/81127087-6811de80-8f3d-11ea-82b8-ab1058a82a60.png)

But then this is what shows in the Actions section on Github:

![image](https://user-images.githubusercontent.com/1266447/81127148-97c0e680-8f3d-11ea-930f-758da1062f00.png)

Of course I'm open to test on my end, whatever you think might be of help.

PS: I've made a little repo to help reproduce the issue (https://github.com/azrafe7/test_python_rich_on_gh_pages)
Please let me know if and how can I help.

...And thank you for your work.

**Comment by willmcgugan** [comment]
Rich will strip colors if it detects its not writing to a terminal, which is probably what is happening here. If you add `force_terminal=True` to the Console constructor you should get styles back.

**Comment by azrafe7** [comment]
And that was it. :wink: 

![image](https://user-images.githubusercontent.com/1266447/81182481-20776b00-8fae-11ea-863b-cf43b7f50cfa.png)

Thanks.
