### ISSUE TITLE
What themes are there?

### ISSUE THREAD

**Issue by NightMachinary** [willmcgugan/rich#53]
I couldn't find a list in the readme.

**Comment by willmcgugan** [comment]
There's only one (default) theme in Rich, which sets the color/style for the various renderables.

The term 'theme' as a little over-used. Your terminal app also has its own color theme that will override the first 16 colors.

**Comment by NightMachinary** [comment]
@willmcgugan I mean themes for `Markdown(readme.read(), code_theme="WHAT HERE?")`

**Comment by willmcgugan** [comment]
Ah. Those are Pygments themes. There's a list on their [demo page](https://pygments.org/demo/).
