### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by drapado** [willmcgugan/rich#54]
First of all I want to say that this is an amazing project! Thanks for the work :D

I would like to suggest the possibility of creating plots in the terminal as a future feature.

**Comment by willmcgugan** [comment]
Thanks. That would be a nice feature, but I need to draw the line under the features set in the core library. I'm hoping someone will implement things like that with the [console protocol](https://rich.readthedocs.io/en/latest/protocol.html).

**Comment by e0lithic** [comment]
@willmcgugan Great library. I am new to rich and have just started learning it through examples. I am trying to implement something like [termagraph](https://github.com/mkaz/termgraph) using the [console protocol](https://rich.readthedocs.io/en/latest/protocol.html). Although the documentation is clear , are there more thorough or in depth examples of the console protocol usage for reference?

**Comment by willmcgugan** [comment]
Hi @e0lithic 

Thanks for attempting this!

The only other examples are in the project itself. All the renderables, Table, Panel, Align etc are implemented with the console protocol.

Essentially though, you need to define a `__rich_console__` with yields `Segment` objects. You can consider each yield to be like a print statement, with a style.
