### ISSUE TITLE
Colorama Requirement Pinning

### ISSUE THREAD

**Issue by connorlanewhite** [willmcgugan/rich#56]
I'm trying to reconcile the requirements of this (wonderful) library with others in my requirement stack. Most line up; however, colorama seems to be a particular issue with a lot of libraries with the notable one for me being `aws-cli`. Would you be open to changing the pinned requirement with something a bit more fluid such as `colorama >= 4.0.0`? Not sure how you're using the specific version there, but I know being more flexible here will certainly help me/others 😄 .

**Comment by willmcgugan** [comment]
I'll check 4.0.0 works, but I don't see why it wouldn't.

**Comment by willmcgugan** [comment]
Fixed in v1.0.1
