### ISSUE TITLE
does not work with PyInstaller

### ISSUE THREAD

**Issue by frankenstein91** [willmcgugan/rich#58]
I wanted to use the nicer traceback of this application for one of my projects. Unfortunately I can't get this to run on Windows. I have to put the application into an exe and get problems with the import of rich.
Once I insert this source code into my program, I cannot start it after the packing process.

```
from rich.traceback import install
install()
```

I get the following error message on the console.
```
Traceback (most recent call last):
  File "venv\Lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 13, in <module>
    import pkg_resources as res
  File "c:\users\vmuser\pycharmprojects\logdings\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[5020] Failed to execute script pyi_rth_pkgres

```

Since @pyinstaller is a very big project, I wanted to ask here first how to get it running.

**Comment by frankenstein91** [comment]
Also my alternative idea of integration, was unfortunately without success.
```
import rich
import rich.traceback
rich.traceback.install()
```

**Comment by willmcgugan** [comment]
I don't think thats an issue in Rich. I googled for `ModuleNotFoundError: No module named 'pkg_resources.py2_warn'` and it seems quite a common problem. I'm sure there is a solution on the web somewhere.

**Comment by frankenstein91** [comment]
I have tested the application with rich and without rich. Without rich everything works without problems, with unfortunately not. I know it's hard to get the responsibility clear now, but there have been other libs-hooks built into the pyinstaller because of such problems. I just think you can handle it better than I can. After all, you developed the lib.
Maybe your lib is changing sys.path?

**Comment by willmcgugan** [comment]
I don't doubt the bug manifests when you add Rich, it's just unlikely to be an issue in Rich itself. If I were to guess, it could be the colorama dependancy, which may be pulling in 'pkg_resources.py2_warn' in a way that pyInstaller can't detect. Rich doesn't do anything exotic such as changing sys.path.

I'm afraid I can't help you much with this issue.

**Comment by frankenstein91** [comment]
do you think about https://github.com/tartley/colorama ? or a other colorama?

**Comment by willmcgugan** [comment]
That's the one. But I doubt they can help you. The solution probably involves some additional configuration for pyInstaller.

**Comment by frankenstein91** [comment]
i am not the best developer, but still i want to try to make it with enough information. If I can make it work, wouldn't it be a help for you and the people at @Pyinstaller?

**Comment by willmcgugan** [comment]
Good luck. Google is your friend. If you find a solution, post it here for future developers!

**Comment by frankenstein91** [comment]
Thank you for wishing good luck... it helped.
The answer ist to downgrade setuptools.
https://github.com/pypa/setuptools/issues/1963#issuecomment-573675633
