### ISSUE TITLE
The '\r' in console.log() may cause the line to not display correctly

### ISSUE THREAD

**Issue by GeekDuanLian** [willmcgugan/rich#60]
![image](https://user-images.githubusercontent.com/6257434/81447096-93e7cb00-91ae-11ea-92f5-a887e173aa96.png)
Maybe '\r' should be deleted automatically?

**Comment by willmcgugan** [comment]
Yeah, I think so. There are a few other control codes which I need to strip. Anything that moves the cursor will break alignment.

**Comment by willmcgugan** [comment]
Fixed in v1.1.1 I've added stripping of some of the control codes, including "\r". I will also add stripping of ANSI control codes that move the cursor at some point.
