### ISSUE TITLE
Minor doc mistake

### ISSUE THREAD

**Issue by mrozekma** [willmcgugan/rich#61]
The Panel constructor documentation lists the `box` default as `box.SQUARE` (it's `box.ROUNDED`), and the `expand` default as `False` (it's `True`)

**Comment by DarkCode01** [comment]
Good, i can fix that!

**Comment by mrozekma** [comment]
While you're at it, just noticed `Syntax.from_path()`'s `theme` default is listed as `emacs` (it's `monokai`). Thanks

**Comment by willmcgugan** [comment]
Fixed in master by @DarkCode01 And `Syntax.from_path`

Docs will update shortly.
