### ISSUE TITLE
Is it possible to mix use of console.log() and progress bar?

### ISSUE THREAD

**Issue by StephenPCG** [willmcgugan/rich#64]
Hi,

This is an awesome library, I really appreciate your woundful work!

I wonder whether it is possible to mix use `console.log()` or `print()` together with progress bar? That is we have the progress bar sticky to bottom, all printed or logged text appear above the progress bar, not messing up the progress bar.

**Comment by StephenPCG** [comment]
I have figured a dirty way to achieve this, but I don't understand the some internal behaviors.

```py
import time
from rich.console import Console
from rich.progress import Progress

console = Console(log_path=False)

with Progress(console=console, auto_refresh=False) as progress:
    task1 = progress.add_task('Task 1', total=100)
    for i in range(100):
        print('\x1b[2k\x1b[100D\x1b[1A')
        console.log(f'Doing work {i}')
        progress.update(task1, advance=1, refresh=True)
        time.sleep(1)
```

The above code will yield expected output:

```
[17:34:30] Doing work 0
[17:34:31] Doing work 1
[17:34:32] Doing work 2
[17:34:33] Doing work 3
[17:34:34] Doing work 4
Task 1 ━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   5% 0:01:36 ^C
```

The magical `print()` call prints three ansi controls:

```
\x1b[2k    erase current line content
\x1b[100D  move cursor to line heading (assume console width is less than 100)
\x1b[1A    move cursor one line up
```

I do not understand why it has to move cursor one line up (I don't understand how progress bar is rendered). Without this, there will be blank lines between logs.

When there are multiple progress bars, it becomes a little different:

```py
import time
from rich.console import Console
from rich.progress import Progress

console = Console(log_path=False)

with Progress(console=console, auto_refresh=False) as progress:
    task1 = progress.add_task('Task 1', total=100)
    task2 = progress.add_task('Task 2', total=100)
    task3 = progress.add_task('Task 3', total=100)
    for i in range(100):
        print('\x1b[2k\x1b[100D\x1b[3A')  # <- here move cursor up 3 lines
        console.log(f'Doing work {i}')
        print('\x1b[3B')  # <- and need to move cursor down 3 lines
        progress.update(task1, advance=1, refresh=True)
        progress.update(task2, advance=1, refresh=True)
        progress.update(task3, advance=1, refresh=True)
        time.sleep(1)
```

I can't figure out a consistent logic between these two cases, due to lack of understanding of rich internals.

It would be great if this logic can be implemented inside the library. For example, when doing `console.log()` or `console.print()`, check if there are progresses attached to the console instance, if so, tweak the output positions.

**Comment by StephenPCG** [comment]
BTW, I found the [following code](https://github.com/willmcgugan/rich/blob/master/rich/progress.py#L515-L516): 

```py
if visible is not None:
    task.visible = True
```

Even if `visible` is `False`, `task.visible` is assigned `True`, not sure if it is intended or a typo?

**Comment by willmcgugan** [comment]
Hi @StephenPCG 

I'm impressed you got that working, it would be a nice to have feature. 

I think your approach requires the bars to be re-rendered immediately after you move the cursor. For instance, if you put a sleep after your second print, it will break the output. But I'm sure there are ways around that.

I like your idea, I would probably work on it at some point. But if you want to carry on with it, I would accept a PR.

The visible flag is probably a bug...

**Comment by mjlbach** [comment]
I'm also very interested in this (for monitoring tensorflow train loops, printing per epoch statistics in tables, although stylistically I would prefer to print the table in place under the logging bar). So long as the log statement does not extend past multiple lines, the escape code approach works, but if the logs (or table) is variable in terms of number of rows then the solution is a bit more complicated.

**Comment by StephenPCG** [comment]
It would be nice to support multi-line progress, for example, something like:
```
Progress ━━╺━━━━━━━━━━━━━━━━━━━━━━━━━   5% 0:01:36 ^C
Current Processing Item: foobar  <- some job internals can be displayed here.
```

Currently I'm appending that info at the end of progress line, it often exceeds my screen width.

I would like to try to implement this myself, but it may take a while, there's too much work recently :(

**Comment by willmcgugan** [comment]
You can update arbitrary text within a progress column. The `update` methods stores keyword args, which you can refer to in a column.

For instance, if you construct the Progress like this:

```
Progress("{task.fields.job}", BarColumn())
```

You can then call this periodically:

```
progress.update(task_id, job=get_current_job())
```

That would render the text on the same line, but it will wrap nicely.

I suspect it would be a mistake to try and capture all requirements in the progress class, but I could make the rendering part easier to extend, so you can essentially make it render anything in the progress area without working about line wrapping.

Implementing the scrolling log with the progress bar is trickier, but would be a nice feature -- so it's on my list :)

**Comment by willmcgugan** [comment]
Scrolling text above the progress bars works. Coming soon. https://imgur.com/a/3C14GG7

**Comment by willmcgugan** [comment]
Just pushed v1.1.2

You'll need to call `progress.log` or `progress.print` to add text above the progress bars. See [updated docs](https://rich.readthedocs.io/en/latest/progress.html).

**Comment by mjlbach** [comment]
Thanks! One note, progress.print seems to lead to the bar not updating in place.
```
import time
from rich.progress import Progress
from rich.progress import (
    BarColumn,
    DownloadColumn,
    TextColumn,
    TransferSpeedColumn,
    TimeRemainingColumn,
    Progress,
    TaskID,
)


progress = Progress(
    "[progress.description]{task.description}",
    BarColumn(),
    "[progress.percentage]{task.percentage:>3.0f}%",
    TimeRemainingColumn(),
)

with progress:

    task1 = progress.add_task("[red]Downloading...", total=1000)

    while not progress.finished:
        progress.print("Test")
        progress.update(task1, advance=0.5)
        time.sleep(0.02)
```
![image](https://user-images.githubusercontent.com/13316262/81976866-022cf300-95de-11ea-9e7c-e56ec82484ca.png)

Will there also be the option to log in place?

**Comment by willmcgugan** [comment]
Ah, a bug with a single line progress. Try v1.1.3 on Pypi.

progress.print or progress.log should work, and have the same affect as on Console.

**Comment by mjlbach** [comment]
Thank you, 1.1.3 fixed the issue with print!

**Comment by akvail** [comment]
Thanks for adding this feature, was also hacking around it for a while.

Not sure if this is worth a doc note or a code change, but when shifting from `console.log` to `progress.log`, I did encounter that `_stack_offset` needed to be incremented (which, of course, makes sense in retrospect).

If it's meant to be a drop-in/parallel to the console logging, then it might be worth that `+ 1` within the implementation, but it could also just be noted in the documentation that they're not *exactly* identical in this way. That's a preference call, I suppose.

**Comment by willmcgugan** [comment]
@akvail That's a good point. Showing the same `progress.py` line and statement isn't helpful. I'll update that in the next release.

**Comment by willmcgugan** [comment]
@akvail Should be fixed in v1.1.4

**Comment by gmankab** [comment]
is it possible to make logged text to be under the progress bar if task stopeed?

**Comment by eduardz1** [comment]
Is it possible to make the text disappear after the corresponding iteration finishes? So that I can have something like 

```
Training with gamma = 0.36787944117144233 and C = 100.0
  43/44 RBF Kernel SVM ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96% 0:00:00 0:10:48
```

with the "Training with..." part changing and then completely disappearing at the end so that I am left with just the progress bar instead of all the "Training with.." lines and the progress bar?
