### ISSUE TITLE
Using Rich in argparse

### ISSUE THREAD

**Issue by kiran94** [willmcgugan/rich#67]
Is there a way to I can hook up rich to be used as the default help text that is printed out from `argparse`

This is purely aesthetic but if I had something like: 

```py
import argparse
parser = argparse.ArgumentParser()

parser.add_argument('-e', '--example', default='cool example')
parser.add_argument('-i', '--another', nargs='+', choices=['only', 'the', 'coolest'], required=True)

parser.print_help()
exit(0)
``` 

```
usage: reprocessing.py [-h] [-e EXAMPLE] -i {only,the,coolest}
                       [{only,the,coolest} ...]

optional arguments:
  -h, --help            show this help message and exit
  -e EXAMPLE, --example EXAMPLE
  -i {only,the,coolest} [{only,the,coolest} ...], --another {only,the,coolest} [{only,the,coolest} ...]
```

But the colours/formatting of that output follow what you expect from `rich.print` or `rich.console`.

I'm not really sure if this is within the scope of this library but appreciate the time!

**Comment by willmcgugan** [comment]
You would have to extend the ArgumentParser class. There is a `print_usage` method you could implement and use rich.console for the output, rather than print. Let me know if you get it working, I would like to see that!

**Comment by ahopkins** [comment]
> Let me know if you get it working, I would like to see that!

This is basically what I did to implement this. From this basic setup you can of course play around with it more and add some formatting to the description and to the help text themselves.

```python
import argparse
from rich.console import Console

_console = Console()

class RichArgumentParser(argparse.ArgumentParser):
    def _print_message(self, message, file=None):
        _console.print(message)

    def add_argument_group(self, *args, **kwargs):
        group = super().add_argument_group(*args, **kwargs)
        group.title = f"[cyan]{group.title.title()}[/cyan]"
        return group


class RichRawTextHelpFormatter(argparse.RawTextHelpFormatter):
    def _split_lines(self, text, width):
        return [f"[yellow]{line}[/yellow]" for line in text.splitlines()]

```
