### ISSUE TITLE
Integrate into existing logging seamlessly

### ISSUE THREAD

**Issue by keelung-yang** [willmcgugan/rich#69]
```Python3
def setup_logger(level, filename, mode, encoding='utf8',
                 fmt=None, size=0, count=0):
    fmt = fmt if fmt else '%(asctime)s.%(msecs)03d %(levelname)s:\t%(message)s'
    handlers = [
        logging.StreamHandler(),
        logging.handlers.RotatingFileHandler(
            filename, mode, encoding=encoding, 
            maxBytes=size, backupCount=count
        ),
        RichHandler(level),
    ]
    logging.basicConfig(handlers=handlers,
                        level=level,
                        format=fmt,
                        datefmt='%H:%M:%S')
    logging.captureWarnings(True)
```
![image](https://user-images.githubusercontent.com/20385450/81776392-48704c80-9521-11ea-9e71-3ac493b59b12.png)
It's not good at looking, compared to original console output:
![image](https://user-images.githubusercontent.com/20385450/81776694-d8ae9180-9521-11ea-8bc8-e247cc58296d.png)

It's better if both format and datefmt can be specified, and also disable highlight while calling RichHandler()

It's much better if RichHandler can detect and set log level /formatter at runtime automatically, since they maybe changed at runtime.

**Comment by willmcgugan** [comment]
You have a `StreamHandler` also writing to stderr, which is the main reason it doesn't look good.

You can configure RichHandler by passing in a Console instance. e.g. `RichHandler(console=Console(highlight=False, file=sys.stderr))`

I think you can set the handler level by calling `setLevel`. RichHandler extends the base class from logging and inherits most of its features.

**Comment by keelung-yang** [comment]
> You have a StreamHandler also writing to stderr, which is the main reason it doesn't look good.

It works after remove `StreamHandler`.
Thanks.
