### ISSUE TITLE
Console Theme

### ISSUE THREAD

**Issue by fengredrum** [willmcgugan/rich#70]
Hi, very cool work!

I wonder if you could share your console theme too? I think it is also very beautiful.

Anyway, thx 4 sharing this awesome work!

**Comment by willmcgugan** [comment]
Glad you like it! Do you mean the screenshots on the readme? It's iTerm on iOS with dimmed monokai color theme.

**Comment by fengredrum** [comment]
> Glad you like it! Do you mean the screenshots on the readme? It's iTerm on iOS with dimmed monokai color theme.

Thank you very much! I will switch to that theme too 😄😄😄
