### ISSUE TITLE
Console(log_path=False, log_time=False) doesn't work with logging module

### ISSUE THREAD

**Issue by keelung-yang** [willmcgugan/rich#72]
![image](https://user-images.githubusercontent.com/20385450/81889337-ddcd1880-95d5-11ea-8b27-aff3a3c0ebed.png)

```python3
import sys
import logging

from rich.console import Console
from rich.logging import RichHandler

log_fmt = '%(asctime)s.%(msecs)03d %(levelname)s:\t%(message)s'
date_fmt='%H:%M:%S'
level = logging.INFO

console = Console(
    tab_size=4,
    #record=False,
    log_path=False,
    log_time=False,
    #log_time_format=date_fmt,
    #file=sys.stderr,
)

handle = RichHandler(
    level=level,
    console=console,
)

logging.basicConfig(
    level=level,
    format=log_fmt,
    datefmt=date_fmt,
    handlers=[handle],    # comment this line to disable rich
)

logging.info("Hello, World!")
```
And BTW, `msecs` is not supported in rich now? Thanks!

**Comment by willmcgugan** [comment]
Those parameters affect the `Console.log` method, the logging handler works differently, it takes the date format from the logging formatter and there is currently no option to not show the path.

If you want to configure logging more than what is offered, I'd suggest copying the [handler code](https://github.com/willmcgugan/rich/blob/master/rich/logging.py). It's a very simple class and you can modify it to your requirements.
