### ISSUE TITLE
python 3: input(text_to_colored)

### ISSUE THREAD

**Issue by chfw** [willmcgugan/rich#73]
Hi all,

I am evaluating 'rich' for one console app. I loved all the styling features, especially [bold magenta]this capability[/bold magenta], because my app users would have the share of power to do their colors.

Now the blocker for me that I failed to find your api to do the following:

```
import crayons

prompt = 'Hello ' + crayons.red('world') + ':'
input(prompt)
```

<img width="88" alt="Screenshot 2020-05-14 at 23 26 34" src="https://user-images.githubusercontent.com/4280312/81991965-5c5ba180-963a-11ea-94a5-daffd1d70a5a.png">

Would you like to shred some light on this use case?

**Comment by willmcgugan** [comment]
You can set `end=""` on print, which will omit the the new line. This will have much the same effect as your example:

```
>>> from rich import print
>>> print("Hello [red]World[/]:", end=""); input();
```

I could perhaps add a convenience method on Console, so you could do `answer = console.input("Hello [red]World[/]:`)

**Comment by willmcgugan** [comment]
I've added a convenient [input method](https://rich.readthedocs.io/en/latest/reference/console.html#rich.console.Console.input) in v1.1.4
