### ISSUE TITLE
Console.show_cursor doesn't work on Windows

### ISSUE THREAD

**Issue by mrozekma** [willmcgugan/rich#75]
I see from #4 that Windows support is iffy. I'm trying it for the first time and it mostly seems to work, but [`Console.show_cursor`](https://github.com/willmcgugan/rich/blob/master/rich/console.py#L426) tries to write an ANSI escape sequence, which obviously doesn't work, the Windows terminal just prints out those characters. I don't know the equivalent magic to show/hide the cursor on Windows, but at least it should avoid printing those bytes

**Comment by willmcgugan** [comment]
That's an old issue. Windows support is pretty good now.

Much of the ANSI escape sequences are supported via Colorama, but you are correct that show_cursor should probably just do nothing on windows. I'll put that in the next update.

**Comment by willmcgugan** [comment]
Please try v1.1.4

BTW the new Windows terminal handles ANSI escape sequences natively.
