### ISSUE TITLE
Feature Request: Add a pager to long text output

### ISSUE THREAD

**Issue by Dude-X** [willmcgugan/rich#77]
I like this library since it automatically prints pretty tables with automatic word wrap. I would like if there's way to add a way to a pager to the output for large tables with many rows.

**Comment by willmcgugan** [comment]
I added paging to the `python -m rich.README` command which uses the same paging as when you type `help(foo)`, but I have considered making it a more general thing.

It may yet happen, I'll keep this issue open to track it.

**Comment by Dude-X** [comment]
After having looked at the paging code, I see it's simple to implement. If I initialize a `Console` object with a `BytesIO` object then I can pass that to the pydoc pager.
Is there anything else I should do, or should I use the other attributes as defined in the markdown pager?

**Comment by willmcgugan** [comment]
You’ll need a StringIO rather than BytesIO. force_terminal is required so Rich won’t strip control codes. Bear in mind that code in pydoc launches the pager provided by your OS, so you can’t guarantee a consistent user experience.

**Comment by clay584** [comment]
@Dude-X do you have an example snippet of code on how you did that? I cannot seem to get it to work by what you describe. Thanks!

**Comment by Dude-X** [comment]
@clay584 
This works for me:
```
from io import StringIO
import pydoc
from rich.console import Console
from rich.table import Table

console = Console(file=StringIO(), force_terminal=True)

data = [
        ('John Glenn', 'M', '07/18/1921'),
        (Sally Ride'', ''F, '5/21/1951'),
        ('Edwin "Buzz" Aldrin", 'M', '1/20/1930')
        ]

table = Table(show_header=True, header_style="bold cyan")
table.add_column("Name") 
table.add_column("Sex")
table.add_column("Birthdate", justify="right")
for row in data:
    table.add_row(*row)
console.print(table)
pydoc.pager(console.file.getvalue())
console.file.close()
```

On MacOS, before I run this script, I tell `less` to color the output with:
`export LESS=-r`
then I run the script, and everything looks beautiful.

Only downside is that large blobs of text will take time to process, but hopefully Will will implement a proper pager that can stream large objects.

**Comment by clay584** [comment]
@Dude-X That works great! Thank you for the assist!

**Comment by amartya-dev** [comment]
@willmcgugan I would love to take this up, are you willing to incorporate this though?

**Comment by willmcgugan** [comment]
@amartya-dev Sure. If I like the implementaiton!

**Comment by 1dancook** [comment]
+1 for this feature. I have been wanting to use rich for a while and today tried to use it. I have a function implemented to preview markdown files but no paging! I will try to implement a workaround- perhaps with the example above or by using popen and friends. 

btw thanks for the hard work. I'm looking forward to using this for future projects.

**Comment by willmcgugan** [comment]
I've started work on this... https://twitter.com/willmcgugan/status/1314925405040775177

**Comment by 1dancook** [comment]
Looks great. It is unfortunate that on macOS an environment variable comes into play.

Implementing your own pager is... in the realm of rich? This is a lot of other functionality. I don't know what you had in mind but I suppose some expected features of that would be the less-like keyboard navigation / exiting. Then there's search. Etc. 

Maybe there's way with less? Or heaven forbid another pager?

**Comment by willmcgugan** [comment]
Linux uses the same env variable. It's probably a good idea to respect the user's wishes as the default. But I am planning on making it easy to change pager functionality, so I could even supply a pager that uses "less -r".

Even "less -r" isn't without its drawbacks. It doesn't appear to support terminal links, at least not on macOS.

For a builtin pager, I was thinking cursor up/down and page up/down and that's it. That's as much as I ever use personally, and at least this would guarantee the same user experience everywhere.

**Comment by Edward-Knight** [comment]
I believe this is now resolved by #373?

**Comment by Dude-X** [comment]
I think we can close this issue as far as implementing a pager. Only thing left is to add pager stuff to the docs. 
Basically it's:
```
from rich.console import Console
console = Console()
# create your rich data
with console.pager():
  console.print(my_rich_text)
```

**Comment by willmcgugan** [comment]
Yep. Its documented [here](https://rich.readthedocs.io/en/latest/console.html#paging).
