### ISSUE TITLE
Feature Request: dictionaries to tables

### ISSUE THREAD

**Issue by Zethson** [willmcgugan/rich#78]
Hi,

using [tabulate](https://pypi.org/project/tabulate/) I can transform dictionaries into tables and then print them.
I would like to request the same functionality, since building tables manually is annoying and unnecessary.

`table = tabulate(dictionary, headers=['header1', 'header2']`

is currently what works and it would be awesome to have an equivalent in Rich.
The table can then just be printed.

**Comment by willmcgugan** [comment]
This is the [``tabulate_mapping``](https://github.com/willmcgugan/rich/blob/master/rich/tabulate.py) helper function, which does something similar, but it's output is more for debugging than presentation.

I'll consider a layer to simplify making tables from common data types.

**Comment by willmcgugan** [comment]
I've been thinking about this, and I don't think it belongs in the core library. I want to keep Rich focused on rendering things. Implementing something like https://github.com/astanin/python-tabulate is a lot of work, and I don't want to have to maintain that.

If all you need is to tabulate a dict then you could knock up a utility function along these lines (untested):

```python
def tabulate_dict(dictionary, headers):
    table = Table(*headers)
    for k, v in dictionary.items():
        table.add_row(str(k), str(v))
    return table
```

Maybe you could ask @astanin if he could extend tabulate with a "rich" table format?
