### ISSUE TITLE
Traceback output issue when code uses tab indentation

### ISSUE THREAD

**Issue by thebigmunch** [willmcgugan/rich#8]
![Cmder_2020-02-24_09-12-37](https://user-images.githubusercontent.com/118418/75159368-fec45280-56e5-11ea-9883-4476dc1bdb0f.png)

That's what happens to the right border for the code lines when the code uses tabs for indentation.

**Comment by willmcgugan** [comment]
Yeah. I plan on covering tabs to spaces on render. Should be in the next update.

**Comment by willmcgugan** [comment]
Should be fixed with v0.6.0. Any chance you can give it a try to confirm?

**Comment by thebigmunch** [comment]
> Any chance you can give it a try to confirm?

I had actually tested when you committed the change but didn't post. Just checked again to confirm. Works here.
