### ISSUE TITLE
Progress columns for item count

### ISSUE THREAD

**Issue by bdillahu** [willmcgugan/rich#80]
I'm probably missing the obvious, but is there a way to have a progress bar column for item count? I'm processing over 1000's of files and showing each file as an increment. All works great, and percentages work, but would like item count.

I tried using FileSizeColumn (and TotalFileSizeColumn), but FileSizeColumn seems to insist on putting a suffix "bytes" after the number... but I'm not counting bytes :-)

**Comment by willmcgugan** [comment]
Enter the following for your column `"{task.completed}"` for items completed, and `"{task.total}"` for total items. See [task reference](https://rich.readthedocs.io/en/latest/reference/progress.html#rich.progress.Task) for list of available fields you can use.
