### ISSUE TITLE
Total Item count in Progress Bar

### ISSUE THREAD

**Issue by bdillahu** [willmcgugan/rich#81]
I'm probably missing the obvious, but is there a way to have a progress bar column for item count? I'm processing over 1000's of files and showing each file as an increment. All works great, and percentages work, but would like item count.

I tried using FileSizeColumn (and TotalFileSizeColumn), but FileSizeColumn seems to insist on putting a suffix "bytes" after the number... but I'm not counting bytes :-)

**Comment by willmcgugan** [comment]
See (recently updated) [docs](https://rich.readthedocs.io/en/latest/progress.html#columns) for details.

**Comment by bdillahu** [comment]
Great, thanks!
