### ISSUE TITLE
Feature Request: Indeterminate Progress Bars

### ISSUE THREAD

**Issue by mschmidtkorth** [willmcgugan/rich#82]
Hi Will

first - absolutely great library! Really makes working in the CLI a joy.

One thing I was missing are progress bars that do not show a progress, but are basically a waiting indicator ([Example](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/notifications-and-progress-for-visual-studio?view=vs-2019#indeterminate)). I was able to build a version of it by having the bar go to 99% and then reverse back in a loop. Ideally, however, the progress bar would move, i.e. the startValue would change together with the endValue and the completed part would stay the same width.

**Comment by willmcgugan** [comment]
Hi,

Glad you like Rich.  I've had some thoughts along those lines myself. I'll consider it for a future update...

**Comment by willmcgugan** [comment]
Made some progress...

![Screen Recording 2020-05-23 at 17 24 21_5](https://user-images.githubusercontent.com/554369/82735990-01066f00-9d1e-11ea-8e1a-67704605f382.gif)

Looks smoother than in the gif.

**Comment by mschmidtkorth** [comment]
That future update came early!

Wonderful, that's exactly what I was looking for. Is the gradient automatically based on the selected color for the bar?

**Comment by willmcgugan** [comment]
> Wonderful, that's exactly what I was looking for. Is the gradient automatically based on the selected color for the bar?

Yep.

It's in master if you would like to play with it. `progress -m rich.progress` now displays an indeterminate bar.

**Comment by mschmidtkorth** [comment]
I just tried it - it is great. However, for me it was kind of difficult to see the bar (especially when using a shorter width, e.g. 40). I had a `pulse_style = 'cyan'` It became easier once I changed the `style` color to white.

**Comment by willmcgugan** [comment]
Can you send me a screenshot? Mine is dark and I find it quite clear.

> What is the intended way of stopping an indeterminate bar?

The intermediate bar shows when the task hasn't been 'started', to handle the common case where there is a delay in getting the number of steps. You could go direct from an intermediate bar to a 0% bar by calling `stop_task`. Added some [docs](https://rich.readthedocs.io/en/latest/progress.html#starting-tasks)

**Comment by willmcgugan** [comment]
indeterminate bars are in v1.2.3

**Comment by mschmidtkorth** [comment]
![image](https://user-images.githubusercontent.com/45070265/82766471-b836df00-9e1f-11ea-899e-36db952bfffb.png)
![image](https://user-images.githubusercontent.com/45070265/82766486-db618e80-9e1f-11ea-84d8-f5692f9eccf5.png)

Nothing dramatic, and everyone is able to change it themselves anyway.
