### ISSUE TITLE
[REQUEST] Support the input() built-in

### ISSUE THREAD

**Issue by M4cs** [willmcgugan/rich#825]
Haven't seen this as a suggestion

**How would you improve Rich?**

The rich module brings so much functionality to Command Line Interfaces, however when you use the `input()` function, it breaks the styling. If you could override the input function like how the print function is, that would be a great improvement! I'd like to see something like this:

```
input('[bold magenta]Press ENTER to Continue[/bold magenta]')
```

**What problem does it solve for you?**

This would solve using the `input()` function w/ rich to not break the style of your CLI.

**Comment by willmcgugan** [comment]
The [Console.input](https://rich.readthedocs.io/en/latest/console.html#input) method works like that.

**Comment by M4cs** [comment]
Ah okay, thanks!
