### ISSUE TITLE
[BUG] UnicodeEncodeError from console.py

### ISSUE THREAD

**Issue by bphunter1972** [willmcgugan/rich#826]
**Describe the bug**

*Some* of my users are seeing this condition being raised from console.py's _check_buffer():

```
   1315                         except UnicodeEncodeError as error:
   1316                             error.reason = f"{error.reason}\n*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***"
   1317                             raise
```

However, I cannot reproduce this issue on my end. Neither I nor they have PYTHONIOENCODING set in their environments, and we are all running from a virtualenv with the same versions of Python, rich, etc.

The code generating this issue is being called as follows:

```
from rich.console import Console
from rich.markdown import Markdown

console = Console(highlight=False)
rprint = console.print
```
later...

```
        with open('notes.md') as notes_file:
            lines = notes_file.readlines()
        md = rich.Markdown(''.join(lines))
        rprint(md, width=120)
```

**To Reproduce**
A minimal code example that reproduces the problem would be a big help if you can provide it. If the issue is visual in nature, consider posting a screenshot.

**Platform**
Linux, Konsole
rich==9.1.0

**Comment by willmcgugan** [comment]
This happens when `sys.stdout.encoding` is not utf-8. You would get a similar exception using the builtin print when printing non-ascii characters.

The typical cause of this is a missing or incorrect `LANG` env var. Setting `PYTHONIOENCODING=utf-8` would also fix it.

**Comment by willmcgugan** [comment]
Closing this. Re-open if you have anything to add...
