### ISSUE TITLE
[BUG] Console.out() always enables highlighting by default

### ISSUE THREAD

**Issue by serhiy-storchaka** [willmcgugan/rich#827]
`Console.out()` by default enables highlighting even if it is disabled in the Console constructor.

```python
from rich.console import Console
console = Console(highlight=False)
console.print('cd /usr/lib')  # no hightlight
console.out('cd /usr/lib')  # hightlight
```

It is expected that `Console.out()` makes less changes to the output than `Console.print()`.

It happens because the default value of *hightlight* is `True` in `Console.out()` and `None` in `Console.print()`. The fix is making it `None`.

rich 9.3.0

**Comment by willmcgugan** [comment]
Fixed in 9.5.0
