### ISSUE TITLE
[REQUEST] Add chicken-or-egg spinner

### ISSUE THREAD

**Issue by tuukkamustonen** [willmcgugan/rich#829]
**How would you improve Rich?**

One of the great debates is: which one was first - chicken or egg? AFAIK there's still no ultimate answer, which keeps me awake at night. I think awareness of the topic should be raised.

So, create a spinner so we can ponder on the dilemma while waiting for actions to complete:

🥚🐣🐤🐔🥚🐣🐤🐔🥚🐣🐤🐔...

_However_, I'm now assuming that egg was actually first, which might be a terrible mistake! It could as well be:

🐔🥚🐣🐤🐔🥚🐣🐤🐔🥚🐣🐤...

Randomize the starting emoji 50-50.

(As an Easter egg, you could make it sometimes end with:

🍗🍳

That's quite unfortunate... but hey, there's a practical outcome then.

Though, I wonder if an Easter _egg_ should indeed be just 🥚.)

**What problem does it solved for you?**

It would help me sleep.

**Comment by willmcgugan** [comment]
According to https://emojipedia.org/ 🥚 was added to unicode in 2016 and 🐔 was added in 2010. So that answers that question. :)

If you want to add that to https://github.com/willmcgugan/rich/blob/master/rich/_spinners.py I would accept a PR!

**Comment by tuukkamustonen** [comment]
I don't think it currently supports setting 50-50 chances, though? It's a static constant dict, I don't think it's possible to do clever `lambda`/`property` tricks, either?

**Comment by thebigmunch** [comment]
> I don't think it currently supports setting 50-50 chances, though? It's a static constant dict, I don't think it's possible to do clever `lambda`/`property` tricks, either?

Down and dirty:

```
SPINNERS['chicken_or_egg']['frames'] = random.choice(
	  [
		  ['🥚', '🐣', '🐤', '🐔'],
		  ['🐔', '🥚', '🐣', '🐤'],
	  ]
)
```

**Comment by willmcgugan** [comment]
I suspect a random starting point would be problematic for tests. You might have to live without it.

Besides, since chickens evolved from a non-chicken ancestor that also laid eggs, then the egg must have come first.

**Comment by tuukkamustonen** [comment]
@thebigmunch Ah right, wouldn't need to be random each time invoked, just random each time loaded. Good point.

> Besides, since chickens evolved from a non-chicken ancestor that also laid eggs, then the egg must have come first.

We must not haste to make such conclusions, as it's still debatable if the mutation to make a chicken happened in the egg or in the chick inside the egg (https://en.wikipedia.org/wiki/Chicken_or_the_egg). Plus, even if there was a definitive answer, by liberty of making one's mind, people could choose to deny the fact. Pondering on the topic must not stop until everyone agrees.

Anyway, [spinner tests](https://github.com/willmcgugan/rich/blob/master/tests/test_spinner.py) seem to only be testing `dots` so I guess randomizing like @thebigmunch suggested wouldn't break anything, at least now?

**Comment by willmcgugan** [comment]
> Anyway, spinner tests seem to only be testing dots so I guess randomizing like @thebigmunch suggested wouldn't break anything, at least now?

That is true. It's a good joke, but not a worthwhile feature IMHO It will likely be animating so fast you won't see which came first.
