### ISSUE TITLE
[BUG] Progress bar in Jupyter will clear everything except itself

### ISSUE THREAD

**Issue by Mr-Milk** [willmcgugan/rich#830]
When using the progress bar in jupyter, everything print before or print by the `progress.console.print` will be cleaned. Content print after the progress finished is unaffected. 

Running in Jupyter, MacOS.

![In jupyter](https://user-images.githubusercontent.com/23433306/102486170-9646c780-40a3-11eb-9a96-bba050510aab.gif)

Run the same code in the terminal with IPython, work as expected.

<img width="522" alt="WX20201217-200728@2x" src="https://user-images.githubusercontent.com/23433306/102486257-ba0a0d80-40a3-11eb-85af-2d8c37cb44de.png">

```python
from rich.progress import Progress
from time import sleep

def test_rich():
    print("before")
    sleep(0.5)
    with Progress() as progress:
        task = progress.add_task("task1",total=10)
        for job in range(10):
            progress.console.print(f"Working on job {job}")
            sleep(0.1)
            progress.advance(task)

test_rich()

```

**Comment by Mr-Milk** [comment]
Forgot to mention, I'm using version 9.4.0

**Comment by willmcgugan** [comment]
I don't get that behaviour on Jupyter notebook, but I do on Jupyter lab. I suspect this may be a bug in lab, but its hard to say.

**Comment by Mr-Milk** [comment]
I tried the progress bar and the spinner from the latest version on both notebook and lab, the behavior is the same.

**Comment by irahorecka** [comment]
Hello - this is still an issue on both Jupyter Notebook and Jupyter Lab using `rich==13.7.0`.
