### ISSUE TITLE
[BUG] Quadro-quoted string

### ISSUE THREAD

**Issue by serhiy-storchaka** [willmcgugan/rich#832]
There is a string literal which starts with 4 quotes instead of 3 in `console.py`:
https://github.com/willmcgugan/rich/blob/0ea2d45a9527a99fd6a6dbe71dcf06fb9ff1e253/rich/console.py#L104

It breaks syntax highlighting in some poor editors.

**Comment by willmcgugan** [comment]
People are actually looking at my code?!

Fixed in 9.5.0

**Comment by serhiy-storchaka** [comment]
Source code is the best documentation.

Thank you!
