### ISSUE TITLE
[BUG] New method to get terminal dimensions fail in Windows Terminal

### ISSUE THREAD

**Issue by AcidWeb** [willmcgugan/rich#836]
**Describe the bug**
Apparently new method to set console size fail with new Windows Terminal. Old `cmd` is working correctly. On new one rich always detect it as 80x25 console.

**To Reproduce**

- Start Windows Terminal
- Install rich 9.4.0.
- Execute `py -m rich.diagnose`
- Install rich 9.5.0.
- Execute `py -m rich.diagnose`

**Platform**
Windows 10

**Comment by willmcgugan** [comment]
Thanks for the bug report. Please try v9.5.1

**Comment by AcidWeb** [comment]
v9.5.1 is working correctly.

**Comment by blueyed** [comment]
Ref: https://github.com/willmcgugan/rich/commit/8a7f5d82ba7bbe108a17bdc75720d11852968aed
