### ISSUE TITLE
[BUG] Logging results in MarkupError when logging URLs

### ISSUE THREAD

**Issue by Imipenem** [willmcgugan/rich#840]
Hey ;)

**Describe the bug**
I'm running a project with another package called `pygithub` and using `rich` to log if my app runs in verbose mode. The pygithub package actually logs something along the following lines:
`"%s %s://%s%s %s %s ==> %i %s %s"` (actually an URL with some additional data, the result of a request to the github API for some pull requests). However, when it comes to logging this, i get the following error : `MarkupError: closing tag '[//]' at position 27666 doesn't match any open tag` (along with an `KeyError: '/'`). 

I'm not entirely sure, if this is a bug with rich or it's some unlucky interference with the way `pygithub` logs some things? 
So this would be also my question: Is it possible to fix this with rich? Or should it even be no problem?

**To Reproduce**
Code is like the following (as its actually the last lines log that produces the error).
```
g = Github(mytoken)
repo = g.get_repo('some/repo)
# query all open PRs
log.debug('Querying open PRs to check if a sync PR already exists.')
# iterate over the open PRs of the repo
for pull_request in repo.get_pulls(state='open'): # this is the line, where pygithub logs the thing above and the "errors source".
```

**Platform**
What platform (Win/Linux/Mac) are you running on? What terminal software are you using. Which version of Rich?
Running it on Ubuntu 18.04 with rich version 9.4.0

**Comment by willmcgugan** [comment]
Whatever you're logging is interpreted as console markup. See the docs on escaping https://rich.readthedocs.io/en/latest/markup.html#escaping

**Comment by Imipenem** [comment]
@willmcgugan Thanks for the quick response, appreaciate it. So just to make sure I understand it correctly: Since I don't log anything directly in my code (actually the third party package logs something), there's nothing I can do to prevent this error (Besides "handling this in the actual source code of the other package, roughly spoken)? Sorry if this sounds stupid, I just want to make sure.

**Comment by willmcgugan** [comment]
You must have `markup=True` which means anything logged with that handler will use console markup (even if it's not from your code). It's False by default, precisely because of this issue.

You could create a RichHandler with markup enabled for your own code, and another with markup disabled for the other handler (or root handler). Don't know if you've ever configured logging, see the Python docs for details.

**Comment by Imipenem** [comment]
I see, ok thanks for clarification, will try this out ;)
