### ISSUE TITLE
[REQUEST]  Add TimeElapsedColumn class for Progress

### ISSUE THREAD

**Issue by dukea42** [willmcgugan/rich#844]
Have you checked the issues for a similar suggestions? Yes

**How would you improve Rich?**

Please add a Time Elapsed as a standard column for the Progress bar feature.
```
class TimeElapsedColumn(ProgressColumn):
    """Renders elapsed time."""

    # Only refresh twice a second to prevent jitter
    max_refresh = 0.5

    def render(self, task: "Task") -> Text:
        """Show time elapsed."""
        elapsed = task.elapsed
        if elapsed is None:
            return Text("-:--:--", style="progress.remaining")
        elapsed_delta = timedelta(seconds=int(elapsed))
        return Text(str(elapsed_delta), style="progress.remaining")
```
This snippet is refactored from the TimeRemainingColumn class.  An update to the default style may need to also be considered.

**What problem does it solved for you?**
Seeing time Elapsed on long progress jobs is useful for understanding where the long running parts of the application are, and for the user to accept accuracy of the Time Remaining value.

Also, this would close the gap of similar metadata available on the default display of tqdm.  That could reduce an import.

**Comment by willmcgugan** [comment]
Seems reasonable. I’d accept a PR.

**Comment by willmcgugan** [comment]
There's a TimeElapsedColumn in 9.6.0 (just released)
