### ISSUE TITLE
[REQUEST] Add a way to inject `sys.unraisablehook` with Rich

### ISSUE THREAD

**Issue by jack1142** [willmcgugan/rich#849]
Have you checked the issues for a similar suggestions? Yes

**How would you improve Rich?**

Exception raised during garbage collection/object destruction don't get raised in application's main context and are instead passed to `sys.unraisablehook` which is not injected by Rich and is therefore unformatted.

**What problem does it solved for you?**

It allows me to see pretty-printed version of exceptions raised during garbage collection/object destruction.

I'm guessing it's probably possible with right usage of `Traceback` object, but it would be great to have a built-in way to do so.

**Comment by jack1142** [comment]
Some sample code that can be used to test:
```py
>>> class X:
>>>     def __del__(self):
>>>         raise RuntimeError("Error!")
>>>
>>> X()
>>> 123
Exception ignored in: <function X.__del__ at 0x000001F34533D430>
Traceback (most recent call last):
  File "<stdin>", line 3, in __del__
RuntimeError: Error!
123
```

**Comment by willmcgugan** [comment]
This could be installed in `traceback.install`

Would you want it to display any different to usual Rich tracebacks? You could potentially get a lot of these on exit if there is a bug in your `__del__`

**Comment by jack1142** [comment]
> Would you want it to display any different to usual Rich tracebacks?

IMO having them show in the same way is fine. The only thing different from the usual Rich traceback would really need to be the "Exception ignored in" line that isn't present in regular exceptions.

> You could potentially get a lot of these on exit if there is a bug in your `__del__`

Hmm, does Rich do something potentially expensive when showing tracebacks (some additional stack inspection maybe?)? Cause if that were the case and there are a lot of unraisable tracebacks, this could potentially slow down the exiting in which case it might be worth having it do something different. But since I don't know that much about what Rich is doing, I wouldn't want to speculate here too much.

**Comment by willmcgugan** [comment]
It's not especially expensive, it just might result in a lot of scrolling text in the terminal.

Come to think of it, it is a debug thing and probably should not be enabled default. I think I'll add a `unraisable` parameter to `traceback.install` that defaults to False.

**Comment by willmcgugan** [comment]
I'm afraid this is not an easy fix. When those unraisable tracebacks are being printed Python is shutting down and prohibits further imports, which breaks the traceback rendering. The fix would require work that I'm not prepared to do at the moment. Marking this as wontfix, but I may reconsider in the future.

FWIW I generally avoid writing anything in `__del__`, it just has too many side-effects. Most of what you would do with `__del__` can be replaced with context managers.
