### ISSUE TITLE
Suggestion: padding between rows (or skip last bottom padding)

### ISSUE THREAD

**Issue by aroberge** [willmcgugan/rich#85]
First, I want to say that this is a fantastic project, which I have only started to use.

When working with (custom) tables, I found that the existing cell padding options did not fit my need: adding vertical padding at either the top or the bottom gave an unbalanced "table", whereas adding it at both top and bottom introduced too much vertical spacing between rows. I resorted to doing a formatting hack by not using vertical padding, inserting instead an empty row between each existing rows, so as to get the vertical spacing between rows just right (for me).  Here's a screen capture to illustrate what I mean:
![image](https://user-images.githubusercontent.com/629698/82329435-b13f4500-99b7-11ea-964f-aab6155c6e8e.png)

This small hack works for me, but it might possibly be a nice feature to add, using bottom padding with an extra flag `skip_last_bottom_padding` -- if it is not too difficult to implement.

**Comment by willmcgugan** [comment]
Hi André,

I think what's needed here is a "collapse_padding" switch that combines overlapping padding. That way you could set padding to 1, and you would get one space between cells, rather than 2. I'll look in to that in the next update.

**Comment by aroberge** [comment]
Hi Will,

If I understand correctly, compared with my hack, this would leave an extra padding at the top and at the bottom. Still many users might find the option you mention to be more useful than mine.

**Comment by willmcgugan** [comment]
There's already a `pad_edge` option which you can set to `False`. I think the collapse option should give you what you're looking for -- spaces between numbers but not at the edges?

**Comment by aroberge** [comment]
I'm already setting the `pad_edge` option to `False`.

I need to implement a few more features on my own code and document them to
have a more comprehensive example to offer, that would provide a better
illustration of what I do. I will come back to this issue at that time.

**Comment by willmcgugan** [comment]
Try v1.1.7

There was a bug with `pad_edge`, it was only affecting the left and right edges, not top and bottom. I've also added `collapse_padding` which combines padding from neighbouring cells.

**Comment by aroberge** [comment]
Version 1.1.7 with `collapse_padding-True` and `pad_edge=False` definitely works without having to do my hack, making my code look much cleaner.

Thanks
