### ISSUE TITLE
[REQUEST] A way to show the logger name when using RichHandler

### ISSUE THREAD

**Issue by jack1142** [willmcgugan/rich#850]
Have you checked the issues for a similar suggestions? Yes.

**How would you improve Rich?**

I would add a way to show the logger name in `RichHandler`. While you can use a `logging.Formatter` that won't allow you to have the logger name with some color. And enabling `highlight` for all log messages is not really a feasible solution.

**What problem does it solved for you?**

It would allow me to show the logger name and have it colored with Rich.

**Comment by willmcgugan** [comment]
The `RichHandler` has a long list of parameters already, and I would prefer to avoid adding more.

What I might do is factor it out a little to make it easy to extend. For instance there could be a `get_message` method where you could prepend and style the logger name.

**Comment by jack1142** [comment]
> What I might do is factor it out a little to make it easy to extend. For instance there could be a get_message method where you could prepend and style the logger name.

Hmm, that sounds great. Would it be possible to also add a way to put something else instead of the path? I was trying out different options last night and since I didn't want the path to show, I ended up using that place to show the logger name. It is currently a bit of a mess though (I basically had to copy `LogRender.__call__`'s code in a subclass and use the path column for a logger name, and I also needed to do similar with `RichHandler`, so it is bound to break on some update eventually), because that part isn't currently easily extendable.

**Comment by willmcgugan** [comment]
> Would it be possible to also add a way to put something else instead of the path? 

You can set the path, bit It would still style it as a link and add a line number.

It's wouldn't be that hard to completely customize it to your requirements. If you extend RichHandler you can create a table with your columns and print it in `emit()`.

**Comment by jack1142** [comment]
> If you extend RichHandler you can create a table with your columns and print it in `emit()`.

That's true, but it would require me to replace the whole code of `emit()` and have it handle everything which at this point is not really any different from making my own custom logging handler from scratch. It would be a lot nicer if RichHandler maybe had some method for getting formatted text to put in the column used by path so that I could just replace that when extending. Not sure how realistic that is, but it would definitely make it simpler.

**Comment by willmcgugan** [comment]
There's too many configuration options already. Best I can do is factor it out so that rather than copying `emit` you can override a smaller method.

**Comment by jack1142** [comment]
That's what I was proposing in here, right?
> It would be a lot nicer if RichHandler maybe had some method for getting formatted text to put in the column used by path (maybe called `get_right_column` or something like that?) so that I could just replace that when extending

Factoring out would be more than enough - being able to override smaller `get_message()` and/or smaller `get_right_column()` would make it easy to expand RichHandler to do what I or someone else could want.

**Comment by willmcgugan** [comment]
I think there would be too many methods to satisfy everybody's uses case. There's four potential columns in the regular logger, that's 4 methods to get their contents, and you would still need some way to configure the widths / alignment. What I was thinking of is a `render()` method which gives you complete control over how the logs are displayed.

It's not actually that hard to write a new renderer. It would only take a few lines to create a table with your desired columns.

The next version will have the `render` method and a `get_message` method or something like it...

**Comment by willmcgugan** [comment]
See [changes in 9.6.0](https://github.com/willmcgugan/rich/blob/master/rich/logging.py) (just released)
