### ISSUE TITLE
Question: How to install pretty print and beautiful tracebacks permanently in python REPL

### ISSUE THREAD

**Issue by PyGamer0** [willmcgugan/rich#851]
As of now when I run 
```python
>>> from rich import pretty
>>> from rich.traceback import install
>>> install()
>>> pretty.install()
```

This only enables it for the current session, but I want it permanently.

**Comment by willmcgugan** [comment]
You cat put that in your Python startup file. Create a .py file with those lines and set the environment variable PYTHONSTARTUP to point at it. See [docs](https://docs.python.org/3/tutorial/appendix.html#the-interactive-startup-file).

**Comment by PyGamer0** [comment]
Thanks.
