### ISSUE TITLE
Log from existing loggers while progress bar loading

### ISSUE THREAD

**Issue by eulertour** [willmcgugan/rich#87]
It's [recommended](https://docs.python.org/3/howto/logging.html#advanced-logging-tutorial) that each module uses its own logger, but as far as I can tell rich only allows logging from its own dedicated logger while a progress bar is loading.

Is there a way to log from rich using a preexisting logger while a progress bar is loading, and without breaking the output?

**Comment by eulertour** [comment]
I noticed that this would require the logger to have access to the Progress containing the task and managed to hack together this solution:

```python
import logging
from rich.logging import RichHandler
from rich.progress import Progress

global_progress = None

class GlobalProgress(Progress):
    def __enter__(self):
        global global_progress
        global_progress = self
        return super().__enter__()

    def __exit__(self, exc_type, exc_val, exc_tb):
        global global_progress
        super().__exit__(exc_type, exc_val, exc_tb)
        global_progress = None

class GlobalProgressRichHandler(RichHandler):
    def emit(self, record):
        if global_progress is not None:
            console = global_progress.console
            live_render = global_progress._live_render
            if console.is_terminal:
                console.print(live_render.position_cursor())
            super().emit(record)
            if console.is_terminal:
                console.print(live_render)
        else:
            super().emit(record)

logging.basicConfig(
    level="NOTSET",
    format="%(message)s",
    datefmt="[%X]",
    handlers=[GlobalProgressRichHandler()]
)

logger = logging.getLogger("rich")
```

The GlobalProgress is then used as follows:
```python
with GlobalProgress() as progress:
    # Logs handled by a GlobalProgressRichHandler inside this block won't break the
    # progress bar output.
    task = progress.add_task("example task")
    progress.update(task, advance=1)
```

Are there any problems with this I'm missing, or is there an easier way to do it?

**Comment by willmcgugan** [comment]
There isn't any trivial way of doing that. But I do agree it would be nice to have.

Your solution is probably good and quite clever. Only thing I would suggest is using the console object as a context manager, which ensures that the update is written in a single write operation -- which reduces flicker.

Ideally if the logging handler and the progress display share the same Console instance it should just work. I'll have a think about how to accomplish that.

**Comment by eulertour** [comment]
> Only thing I would suggest is using the console object as a context manager, which ensures that the update is written in a single write operation

I tried this and it actually caused the logs to break the progress bar output again. I looked into it for a while but the code is pretty complicated.

**Comment by eulertour** [comment]
If it's at all useful, using the console as a context manager no longer breaks the output if I comment out these two lines:
https://github.com/willmcgugan/rich/blob/55988c6e721cc03ab4f6dc6aeca3089e7c5c13ae/rich/console.py#L329
https://github.com/willmcgugan/rich/blob/55988c6e721cc03ab4f6dc6aeca3089e7c5c13ae/rich/console.py#L333

**Comment by eulertour** [comment]
Thanks for the hint, I was able to solve the problem by modifying the GlobalProgressRichHandler to use the same Console instance as the GlobalProgress:
```python
class GlobalProgressRichHandler(RichHandler):
    """
    A RichHandler which checks a global variable for a GlobalProgress and logs
    without breaking its output if one is set.
    """
    def emit(self, record):
        if global_progress is not None:
            # Save this RichHandler's original Console and use the one from the
            # GlobalProgress.
            console = global_progress.console
            self.saved_console = self.console
            self.console = console

            # Log without breaking the GlobalProgress output.
            live_render = global_progress._live_render
            with console:
                if console.is_terminal:
                    console.print(live_render.position_cursor())
                super().emit(record)
                if console.is_terminal:
                    console.print(live_render)

            # Restore the original Console.
            self.console = self.saved_console
        else:
            super().emit(record)
```

If you ever end up adding this to the repo it'd be helpful to allow passing an external Console to RichHandler.emit() to avoid the all the saving and restoring happening here.

**Comment by calve** [comment]
Hi there, 

i'm having a bit of success to intercept `print()` calls with the following implementation

```python
from contextlib import redirect_stdout

def do_stuff():
    print("some function doing and printing stuffs as usual")

with Progress() as progress:

    class printToProgress():
        def write(self, msg, *args, **kwargs):
            if msg != '\n' and msg != '':
                progress.log(msg, *args, **kwargs)

        def flush(self, *args, **kwargs):
            pass

    with redirect_stdout(printToProgress()):
        do_stuff()
```

albeit not perfect in my setup which involve threads and partials.

Hope this help a lost soul, I'm sure we can improve this.

**Comment by willmcgugan** [comment]
@calve redirecting stout is a good idea. Might also be useful if you don't have control over what does the printing.

**Comment by calve** [comment]
@willmcgugan May I suggest to implement some `capture_stdout` and `capture_stderr` arguments to the `Progress()` class, so we could write something along the lines

```python
with Progress(capture_stdout=True) as progress:
    print("our vanilla stdlib print() but echoing should be handled nicely by rich.Progress")
```

? I can try to provide a PR.

On the other hand I'm not sure if this would play nicely with `logging`. I guess a `capture_logging` argument would be awesome (:

**Comment by willmcgugan** [comment]
It's not a bad idea, but let me think about that one. Might be better for that functionality to go in Console rather than progress.

re logging, I had thought that would be achieved by sharing the same Console instance. You can set the console on both Progress and the RichHandler.

**Comment by willmcgugan** [comment]
For those interested I have a [branch](https://github.com/willmcgugan/rich/tree/transparent-progress) which addresses these issue with the progress display.

With these changes there should be no need to use `progress.print`, as you can print directly to a shared Console. Since Progress and RichHandler will use the same global Console object by default, it means the logging output will be rendered above the progress bars.

I've also added ``redirect_stdout`` and ``redirect_stderr`` options to Progress, as @calve suggested, which is enabled by default.

Still a work in progress, early feedback would be good.

**Comment by willmcgugan** [comment]
Progress bar updated in 2.2.0

**Comment by calve** [comment]
Much thanks, I'll test this release in the coming week

**Comment by willmcgugan** [comment]
Closing for now, works for me. Feel free to re-open if you find any problems with it.
