### ISSUE TITLE
something worng with table displaying

### ISSUE THREAD

**Issue by lsj8924** [willmcgugan/rich#877]
![微信截图_20210105110123](https://user-images.githubusercontent.com/8875594/103601823-750c2500-4f45-11eb-8097-fe2c6ee11f0f.png)

**Comment by willmcgugan** [comment]
Works for me. Suspect your browser hasn't loaded the right font for some reason.

<img width="1115" alt="Screen Shot 2021-01-05 at 11 57 33" src="https://user-images.githubusercontent.com/554369/103643908-5f026280-4f4d-11eb-86ab-59b4583afb1c.png">
