### ISSUE TITLE
[BUG] RichHandler: not able to click links that span over multiple lines

### ISSUE THREAD

**Issue by mr-bjerre** [willmcgugan/rich#886]
Before anything - just wow. Rich is so aesthetically pleasing to use - congrats on that! 

**Describe the bug**
If you have a long url being printed to the console (longer than what can fit in a single line) then you can't easily open the link. You have to mark then whole url, copy it and fix issues around the line breaks. 

**To Reproduce**
You can actually see the issue by simply using `rich.print`. The "fixing url" part is a bit more cumbersome with the `RichHandler` since you have other information mixed in there as well.

If I use the native `print` then it works fine.

**Platform**
Using both Mac and Linux and both hyper terminal as well as vscode terminal. Using rich 9.6.1

**Comment by willmcgugan** [comment]
Clickable URLs is something your terminal does automatically. The hard wrapping in the RichHandler will unfortunately break it. You must have very large URLs or a small terminal window if this is happening.

One solution would be for Rich to generate ANSI links for URLS, which would work even if wrapped on to multiple lines. Unfortunately this type of links don't work on all terminals. Doesn't work on Hyper, but it does on iTerm. You can try it yourself with the following:

```python
console.print(url, style=f"link {url}") 
```

I could potentially add an options to do that automatically in RichHandler

**Comment by mr-bjerre** [comment]
It is indeed a long URL - OAuth2 Code flow has a lot of query parameters.

I tried your suggestion but it still only takes the first line in both hyper and VSCodes integrated terminal. As expected I suppose.

It's not possible to disable hard-wrapping of links?

**Comment by willmcgugan** [comment]
> I tried your suggestion but it still only takes the first line in both hyper and VSCodes integrated terminal. As expected I suppose.

Yes, doesn't work on Hyper or vscode. Works on iTerm and gnome terminal. You could ask the Hyper developers to implement ansi links.

> It's not possible to disable hard-wrapping of links? 

Not in RichHandler which uses a table to render columns.

You could implement logging handler that simply prints the message to the console. You would lose the nice columns, but you could still have color. But at least your links would be clickable.

**Comment by mr-bjerre** [comment]
> You could implement logging handler that simply prints the message to the console. You would lose the nice columns, but you could still have color. But at least your links would be clickable.

But it doesn't work if I just `rich.print(url)` either while `print(url)` works. Is that expected?

**Comment by willmcgugan** [comment]
Yes, see the docs on [soft wrapping](https://rich.readthedocs.io/en/latest/console.html#soft-wrapping).

**Comment by mr-bjerre** [comment]
Ahh my bad. Thanks for your help - I'll close the issue.
