### ISSUE TITLE
Feature Request: Table add columns function

### ISSUE THREAD

**Issue by ThowV** [willmcgugan/rich#89]
Good day,

I recently discovered this library and I am loving it so far, working with it is a breeze. I do have a small idea that came to mind. Adding columns to a table feels unintuitive. As of right now you have to write multiple lines just to add a few columns. Here is my suggestion: An add_columns function for tables. It can take multiple strings and adds multiple columns at once.

Anyways, keep up the good work!

**Comment by willmcgugan** [comment]
Hi. Glad you like Rich.

You can create columns via positional arguments to the Table constructor. The add_column method is useful for setting header style / alignment etc.

**Comment by ThowV** [comment]
Glad to know this. I've looked around but I might've skipped over it in a hurry, my bad. Cleans up the code quite a bit.

Thank you for the quick response!

**Comment by willmcgugan** [comment]
It was burried in the reference. I've added some extra docs.
