### ISSUE TITLE
[REQUEST] Forcing ANSI

### ISSUE THREAD

**Issue by naveen521kk** [willmcgugan/rich#890]
Have you checked the issues for a similar suggestions? YES

I need an Environment variable which forces ANSI output whatever the system may be.
This is particularly useful in GitHub Actions, where it doesn't show any colored output, currently, but setting that a environment variable should print colors.
Is it currently possible to do now?

**Comment by willmcgugan** [comment]
You can construct the Console like this to generate ANSI regardless of environment:

```python
console = Console(force_terminal=True, color_system="truecolor")
```

I think there is an env var that indicates if running on GH Actions, or maybe you can define one.

**Comment by naveen521kk** [comment]
> You can construct the Console like this to generate ANSI regardless of environment:

Looks like it doesn't work? I just tried it. The code was pretty much simple though
```py
logger = logging.getLogger(__name__)
custom_theme = Theme(
    {
        "log.level": "magenta",
        "repr.number": "bold green blink",
        "log.message": "white on red",
        "logging.level.info": "green on white",
        "logging.level.notset":"red on white"
    },
)

console=Console(theme=custom_theme, force_terminal=True, color_system="truecolor")

logger.addHandler(
    RichHandler(
        show_time=False,
        show_path=False,
        console=console,
        rich_tracebacks=True
    )
)
```
I could see no coloured output in [GHA](https://github.com/naveen521kk/msys2-updator/runs/1666330996?check_suite_focus=true#step:6:10) or ANSI locally on Git Bash(#330), where if ANSI is printed it should be turned into colours.

**Comment by willmcgugan** [comment]
That does work. Try printing os.environ or running `python -m rich.diagnose`

**Comment by naveen521kk** [comment]
> Try printing os.environ or running python -m rich.diagnose

I haven't actually, made it based on an environment variable. That is a script is meant to be run in CI so I just forced it.
Just that [poetry's ANSI forcing works](https://github.com/naveen521kk/msys2-updator/runs/1669018595?check_suite_focus=true#step:5:79). I have run `python -m rich.diagnose` [here.](https://github.com/naveen521kk/msys2-updator/runs/1669021535?check_suite_focus=true#step:6:20).
[This](https://github.com/naveen521kk/msys2-updator/blob/main/updator/logger.py) is the place where the logger is present. I would be happy if you could help me :)

**Comment by willmcgugan** [comment]
Ah, you're on Windows. Try also setting `legacy_windows=False`. You might also want to set `width` to say 120 or so.

**Comment by naveen521kk** [comment]
> Ah, you're on Windows.

I am sorry I didn't say this beforehand.

> Try also setting legacy_windows=False. You might also want to set width to say 120 or so.

 I did it https://github.com/naveen521kk/msys2-updator/commit/bd834deccffcfb2f8d784e8772380eb90ff84e6d but there isn't any colour there https://github.com/naveen521kk/msys2-updator/runs/1669125766?check_suite_focus=true#step:6:11

**Comment by willmcgugan** [comment]
Try logging `console.options`

**Comment by naveen521kk** [comment]
See [this](https://github.com/naveen521kk/msys2-updator/runs/1669310086?check_suite_focus=true#step:6:10)

**Comment by willmcgugan** [comment]
I suspect that colorama may be stripping out ansi codes, even when legacy_windows is False. I'll look in to it.

**Comment by naveen521kk** [comment]
Any updates?

**Comment by willmcgugan** [comment]
Can’t do much about this without reinventing colorama. I may revisit this issue in future.

**Comment by naveen521kk** [comment]
Maybe I will make an issue on Colorama about this? Asking them to check for an environment variable?

**Comment by naveen521kk** [comment]
looks like there is a PR upstream https://github.com/tartley/colorama/pull/230

**Comment by naveen521kk** [comment]
Update: I just did a regular dependency update and this seems to be fixed https://github.com/naveen521kk/msys2-updator/commit/4a34e98decd7bc8c1865517554bbd11eed43de85.

https://github.com/naveen521kk/msys2-updator/runs/2739486117?check_suite_focus=true#step:10:284 (I was happy without those colours though)

**Comment by hellow554** [comment]
I have this issue as well and it seems that at least for me this isn't fixed.
What I try is to use `tee` to display it on stdout and to a file. How it doesn't seem to work.

```py3
console = Console(
        force_terminal=True,
        no_color=False,
        color_system="truecolor",
        width=120,
        legacy_windows=False,
        stderr=True,
    )
``` 

are my options for now...

This is what `python3 -m rich.diagnose | tee` shows me:

```
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=188 None>                                                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = None                                                          │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 49                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = False                                                         │
│       is_jupyter = False                                                         │
│      is_terminal = False                                                         │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=188, height=49),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=188,                                            │
│                        is_terminal=False,                                        │
│                        encoding='utf-8',                                         │
│                        max_height=49,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=188, height=49)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 188                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
```

what I want is an option like `force_colors=True` in the Console constructor

**Comment by hellow554** [comment]
Interesting enough: `python3 -m rich | tee` works flawlessly. I cann see all colors, so there must be a way :)

**Comment by hellow554** [comment]
Sorry for the noise! I'm stupid! :) Instead of `console.print(my_tree)` I just did `print(my_tree)`.... It works! I'm really sorry :)
