### ISSUE TITLE
[REQUEST] ANSI Colors autocomplete on IDE

### ISSUE THREAD

**Issue by orensbruli** [willmcgugan/rich#893]
Have you checked the issues for a similar suggestions?
YES

**How would you improve Rich?**
Because of the way the ANSI colors are defined it can't be used for autocomplete on IDE's.
With some changes, it would be easier to know the colors available.
With something like this
```python
class ANSIColors:
    black = "black"
    red = "red"
    green = "green"
    yellow = "yellow"
   ...
```
we could just get the available color names with ANSIColors.[] and the value would be replaced by the needed string.

**What problem does it solved for you?**
It's difficult to find the available ANSI colors for style.

**Could you add a PR for this request?**
YES, with some help.

**Comment by willmcgugan** [comment]
I'm not convinced that will help much. Often when defining styles, it's not just the color, i.e. you might have "bold blue".

BTW you can run this to see available colors:

```
python -m rich.color
```

**Comment by orensbruli** [comment]
Ey! Thank you for the quick answer and for the tip. It's great!
And what about extending my suggestion for all the styles options? That way you could use something like
```style = style.bole+style.blue```
I think this could contribute to quicker development with rich on IDEs and also to avoid some bugs from typos (for example for orange color which doesn't exist itself, right?
```
│            │     94 │ "orange4"             │ #875f00 │ rgb(135,95,0)    │
│            │    166 │ "dark_orange3"        │ #d75f00 │ rgb(215,95,0)    │
│            │    172 │ "orange3"             │ #d78700 │ rgb(215,135,0)   │
│            │    202 │ "orange_red1"         │ #ff5f00 │ rgb(255,95,0)    │
│            │    208 │ "dark_orange"         │ #ff8700 │ rgb(255,135,0)   │
│            │    214 │ "orange1"             │ #ffaf00 │ rgb(255,175,0)   │
```

**Comment by willmcgugan** [comment]
Closing this, but offer still stands if you want to PR
