### ISSUE TITLE
[BUG] Progress indicators not appearing in PyCharm

### ISSUE THREAD

**Issue by zionsteiner** [willmcgugan/rich#897]
**Describe the bug**
Loading bars from `track` from `rich.progress` do not appear in PyCharm run output

**To Reproduce**
```
from rich.progress import track

for _ in track(range(5000), description="Processing..."):
   pass
```
**Platform**
Win, PyCharm 2020.2, Rich 9.6.2

**Comment by willmcgugan** [comment]
Please see the note here https://rich.readthedocs.io/en/stable/introduction.html
