### ISSUE TITLE
[BUG] Seemingly incorrect link for the examples of the html output of 'Exporting' in docs

### ISSUE THREAD

**Issue by realnitinworks** [willmcgugan/rich#918]
**Describe the bug**
Under the [Exporting](https://rich.readthedocs.io/en/stable/console.html#exporting) header of the `Console API` documentation, the link for showing the examples of html output (generated by Rich console) points to the `Standard Colors` in the Appendix section. I believe the original intention was to show examples of html output and hence the link and the text need to be corrected.

**To Reproduce**
![image](https://user-images.githubusercontent.com/45361378/104470187-7392ca80-55df-11eb-9928-db9dca2781d7.png)

Clicking on the link (marked in red above) takes the user to a seemingly unrelated page.

**Platform**
N/A

**Comment by willmcgugan** [comment]
That standard colors page was generated by Rich.

```
python -m rich.color
```

**Comment by realnitinworks** [comment]
I get it now. Thanks for the clarification @willmcgugan.
