### ISSUE TITLE
Printing Markdown referenced links with console.print() gives unexpected output

### ISSUE THREAD

**Issue by legacy-code** [willmcgugan/rich#920]
Not sure if this is a know issue or not, but I found it when writing a script for myself that processes Markdown referenced links.

I included a small example (below) that I created for this after figuring out what the issue was.

So, is there a way to tell Rich to **not** try to do color (or any other interpretation) on a string it is going to print? 

Thanks!
Mike

========================
Example created in Python console
========================

```
>>> from rich.console import Console
>>> console = Console()
>>> testStr = '[nn]: http://something.html "title text"'
>>> console.print(f"this doesn't print right:  {testStr}")

this doesn't print right:  : http://something.html "title text"

>>>
```

There should be a "[nn]: http ..." in the output

**Comment by willmcgugan** [comment]
Please refer to the docs https://rich.readthedocs.io/en/stable/markup.html

**Comment by legacy-code** [comment]
Thanks @willmcgugan - so, if I don't know that I have something that needs to be escaped, but it might, it looks like I can use the `escape()` function?

```
for line in lines:
    console.print(f"{escape(line)}")
```

That would/should do it?

Thanks!

**Comment by willmcgugan** [comment]
Yes, or set `markup=False`

**Comment by legacy-code** [comment]
That worked great.  Thanks for the help @willmcgugan!
