### ISSUE TITLE
[BUG] Explain how to change spinner in docs

### ISSUE THREAD

**Issue by BD103** [willmcgugan/rich#931]
**Describe the bug**
This isn't a bug with the code, but in the [spinner section of the Console class of the docs](https://rich.readthedocs.io/en/latest/console.html#status), it doesn't mention how to actually change the spinner. It just shows how to list all of the spinners.

Maybe just write:

Specify the spinner type using:
```python
with console.status(text, spinner):
  do_work()
```

**Comment by willmcgugan** [comment]
I'd accept a PR for the docs...
