### ISSUE TITLE
[Question] Inline Image display in markdown

### ISSUE THREAD

**Issue by dharmeshkakadia** [willmcgugan/rich#937]
Thanks for rich. Its AMAZING !!! I am trying to "cat" markdown file with it, but the images are shown with just the image tag and not the actual image. Is there a way to display inline images in markdown? I looked around in https://github.com/willmcgugan/rich/blob/master/rich/markdown.py but didnt really find a way. 

Repro example

```python
from rich.console import Console
from rich.markdown import Markdown

console = Console()
markdown = Markdown("![Migrant Mother](https://i.imgur.com/Bt0vnke.jpg)")
console.print(markdown)
```

**Comment by willmcgugan** [comment]
Not currently. There is an extension to terminals which supports images, but it's not widely supported and not implemented in Rich.

**Comment by digitalsignalperson** [comment]
@willmcgugan thoughts on an approach like chafa or timg with images purely as unicode characters?

https://github.com/hpjansson/chafa

> Chafa is a command-line utility that converts image data, including animated GIFs, into graphics formats or ANSI/Unicode character art suitable for display in a terminal. It has broad feature support, allowing it to be used on devices ranging from historical teleprinters to modern terminal emulators and everything in between.

https://github.com/hzeller/timg

> A user-friendly viewer that uses 24-Bit color capabilities and unicode character blocks to display images, animations and videos in the terminal.
>
> On terminals that implement the [Kitty Graphics Protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol.html) or the [iTerm2 Graphics Protocol](https://iterm2.com/documentation-images.html) this displays images in full resolution.

ignoring the fancy kitty/iterm2 stuff

**Comment by khughitt** [comment]
I'm sure this will take some effort, but having support for rendering images in rich / textual would be _huge_.

The authors of Kitty created the [Kitty Graphics Protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/) (mentioned above), which has been implemented in a few other terminals and a handful of apps.

[pixcat](https://github.com/mirukana/pixcat) hasn't been updated in a few years, but it still works and provides a very simple API for rendering images in Kitty/Python.

**Comment by digitalsignalperson** [comment]
I'd add these to the list of tech to consider
https://justine.lol/printvideo.html
https://justine.lol/printimage.html
