### ISSUE TITLE
[REQUEST] When using live output, have an option to highlight differences between successive updates

### ISSUE THREAD

**Issue by juledwar** [willmcgugan/rich#939]
**How would you improve Rich?**

Imagine a live Table output. As things change on a large amount of rows/cols, it gets hard to pick up which cells are changing. If the cell could be highlighted (e.g. invert background/foreground like `watch -d` does) it would make it much easier to spot them.

**What problem does it solve for you?**

Make it easier to see what changed when there's a large number of cells in Tables.

**Comment by willmcgugan** [comment]
That's probably not something that Rich could do automatically, there's too much nuance and it would be hard to capture everyones use case. I think its best left to the developer who knows more about the data in the terminal. You can apply styles to cells and rows manually when you get new data...

**Comment by juledwar** [comment]
I was thinking it could at least automate in-place changes between refreshes? It's obviously harder to do for completely replaced data.

**Comment by willmcgugan** [comment]
You could probably build a Table subclass that highlights new rows for a second or so. But I think it's something best left to the developer.
