### ISSUE TITLE
Feature Request: support latex formula

### ISSUE THREAD

**Issue by fgheng** [willmcgugan/rich#94]
Is it possible to support the display of latex formula？

**Comment by willmcgugan** [comment]
Not currently. But if there is a Python library that can convert latex to a string representation, you could use it with Rich.

**Comment by fgheng** [comment]
Just like [pylatexenc](https://github.com/phfaist/pylatexenc) ?

**Comment by willmcgugan** [comment]
Yeah, that looks like it will work.

**Comment by fgheng** [comment]
Will you support display of latex formula in markdown?

**Comment by willmcgugan** [comment]
Markdown doesn't support native rendering of latex formula, but if you were to paste the output from pylatexenc in to Markdown, I would expect that to work fine.

**Comment by willmcgugan** [comment]
It's possible there will be some integration of pylatexenc with Rich in the future. I imagine it would be another lib rather than a part of the core module.
