### ISSUE TITLE
[BUG] First row in header-less table has a bolded inner border

### ISSUE THREAD

**Issue by jack1142** [willmcgugan/rich#944]
**Describe the bug**
The first row in the header-less table has a bolded inner border.

**To Reproduce**
```py
import rich
from rich.table import Table

t = Table(show_edge=False, show_header=False)
t.add_row("A", "B", "C")
t.add_row("D", "E", "F")
t.add_row("G", "H", "I")
rich.print(t)
```

**Platform**
All that support the Unicode borders. I'm observing this behavior on Windows Terminal (not on cmd as that one doesn't support Unicode borders), Mac, and multiple Linux terminals.

**Diagnose**
Running Rich 9.8.2, the output of the diagnostic commands shouldn't be needed as I can't find a platform where this doesn't happen.

**Comment by willmcgugan** [comment]
Yes, you will need to use one of the other box constants for headerless tables.

**Comment by jack1142** [comment]
Ah, I didn't look carefully at how all of the boxes look. Using `box.MINIMAL` indeed solves my issue. Thanks!
