### ISSUE TITLE
[BUG] "header_style" parameter take no effect on "headers" in the "Table(*headers, header_style)"

### ISSUE THREAD

**Issue by luizyao** [willmcgugan/rich#953]
**To Reproduce**
```python
from rich.console import Console
from rich.table import Table

console = Console()

table = Table("DATE", "NAME", header_style="bold red")
table.add_column("AGE")

console.log(table)
```

![image](https://user-images.githubusercontent.com/30592265/105437223-9a19cb00-5c9b-11eb-927f-f8569ecb29f1.png)

**Platform**
Iterm2 on Mac Big Sur

**Comment by willmcgugan** [comment]
Thanks, please try v9.9.0

**Comment by luizyao** [comment]
Good jobs. 

I have tested on v9.9.0, but i think there is another scenario：the initial header is a **dafault-header-style Column object**.

```python
Table("DATE", Column(header="NAME"), header_style="bold red")
```

![image](https://user-images.githubusercontent.com/30592265/105614660-9ace7080-5e05-11eb-9415-0be673c48368.png)

In this case, the "header_style" parameter should be take effect for it too, right?
