### ISSUE TITLE
In the latest versions of the library, the 'task' function is broken when displaying progress.

### ISSUE THREAD

**Issue by Salim9304** [willmcgugan/rich#963]
rich==6.0.0
code:
```
from time import sleep
from rich.progress import track
from rich.progress import (
    BarColumn,
    DownloadColumn,
    TextColumn,
    TransferSpeedColumn,
    TimeRemainingColumn,
    Progress,
    track
)

progress = Progress(
    BarColumn(bar_width=None),
    "[progress.percentage]{task.percentage:>3.1f}%",
    "•",
    DownloadColumn(),
    "•",
    TransferSpeedColumn(),
    "•",
    TimeRemainingColumn(),
)

for n in progress.track(range(9), description="Processing..."):
    print(n)
    sleep(1)
```
The code above works correctly (showing the given columns and progress in previous rich versions).
It was broken at some point.
In the latest rich == 9..progress is not displayed.
The documentation has a description about .update ().
But this all complicates understanding, it is impossible to accurately set the parameters (advance =). All that is required is an automatic update of the 'progress' at each iteration, and this worked fine in previous versions of the library (code above).
Now it doesn't work and there is no example how to fix it.

**Comment by willmcgugan** [comment]
If you want to use the `track()` method (as apposed to the `track()` *function* from the module), you will need to use the context manager.

```python
with progress:
    for n in progress.track(range(9), description="Processing..."):
        print(n)
        sleep(1)
```

In the code above you are importing `track` function but not using it.

**Comment by Salim9304** [comment]
Thanks.
This new logic works in the new rich version.
