### ISSUE TITLE
[REQUEST] Why not support charts in terminal~?

### ISSUE THREAD

**Issue by Rhythmicc** [willmcgugan/rich#966]
Consider posting in https://github.com/willmcgugan/rich/discussions for feedback before raising a feature request.

Have you checked the issues for a similar suggestions? 1

**How would you improve Rich?**

Support some basic charts, like what `diagram` lib did.
Example for line chart:
```python3
    def __str__(self):
        """
        绘图并返回字符串

        Draw and return a string

        :return: 折线图的字符串
        """
        opt = diagram.DOption()
        opt.size = diagram.Point([self.height, self.width])
        opt.mode = 'g'
        stream = io.BytesIO()
        gram = diagram.DGWrapper(
            data=[self.values, range(len(self.values))],
            dg_option=opt,
            ostream=stream
        )
        gram.show()
        return str(stream.getvalue(), encoding="utf-8")
```

**What problem does it solved for you?**

I can do more things using rich, it's exciting that draw a beautifule chart in rich's containers like table or tree

**Comment by willmcgugan** [comment]
It may happen. But ideally `diagram` or a library like it could add support for Rich.
