### ISSUE TITLE
[BUG] 'auto_refresh=False' Doesn't work out

### ISSUE THREAD

**Issue by Salim9304** [willmcgugan/rich#967]
code:
```
from time import sleep
from rich.progress import track
from rich.progress import (
    BarColumn,
    DownloadColumn,
    TextColumn,
    TransferSpeedColumn,
    TimeRemainingColumn,
    Progress,
    track
)

test=2
if test == 2:
    progress = Progress("[progress.percentage]{task.percentage:>3.1f}%", auto_refresh=False)
else:
    progress = Progress("[progress.percentage]{task.percentage:>3.1f}%")

with progress:
    for n in progress.track(range(5)):
        print(n)
        sleep(1)
```
The expected behavior is that there will be no 'progress'.
Progress remains.

Therefore, there is a problem with 'auto_refresh = False'.
I would like to set up multiple instances of '**Progress ()**' for different cases, but with the [option](https://rich.readthedocs.io/en/latest/reference/progress.html#rich.progress.Progress) '**auto_refresh = False**'.

This worked in past versions of the library.

**Comment by willmcgugan** [comment]
With `auto_refresh=False` the `track()` method will refresh once per-iteration, otherwise it wouldn't display anything.

**Comment by Salim9304** [comment]
Yes, progress shouldn't output anything. Progress has been refreshed once iteration if '**progress.refresh ()**'.
However, now 'progress.refresh ()' has no effect.
In the documentation so.

If you change the code, for example
```
with progress:
     progress = Progress (auto_refresh = False)
     for n in progress.track (range (5)):
         print (n)
         sleep (1)

```
Then progress disappears (but this is wrong).

**Comment by willmcgugan** [comment]
> Yes, progress shouldn't output anything.

Yes, it should. Because `track()` calls `refresh()` after each iteration when `auto_refresh=False`. If you don't want this behavior I'd suggest [adding a task](https://rich.readthedocs.io/en/latest/progress.html#advanced-usage) and updating manually.

The `auto_refresh` refers to a thread which refreshes at a given interval.

Your example is broken because you are trying to work with two Progress instances.
