### ISSUE TITLE
[BUG] Maximum Recursion Depth Exceeded When Using Console with track

### ISSUE THREAD

**Issue by WhiskeyCharlie** [willmcgugan/rich#970]
**Describe the bug**
"RecursionError: maximum recursion depth exceeded while calling a Python object"
![image](https://user-images.githubusercontent.com/24189806/106155139-02c7e280-6189-11eb-85d5-32217c9e2ac2.png)

From cursory debugging, issue seems to be that internal rich functions somehow end up calling themselves (with infinite loops).

**To Reproduce**
Run the below code with Python 3.8, from either a terminal or a PyCharm environment where the "Emulate terminal in output console" checkbox is checked (True). This checkbox is found in the Run Configurations window.

**Platform**
Tested on Windows 10 and Ubuntu 20.04 with identical results (both in Python 3.8)

```
from rich.progress import track
from rich.console import Console


with Console().status("Foo") as status:
    x = track(map(print, [1]), total=1)
    y = list(x)
```

**Comment by willmcgugan** [comment]
You can't use a status context and a progress bar at the same time I'm afraid. But you can have a spinner column in a progress bar.
