### ISSUE TITLE
[BUG] from rich import traceback points to builtin

### ISSUE THREAD

**Issue by daddycocoaman** [willmcgugan/rich#973]
Ohai. My first bug report, I think.

**Describe the bug**
The docs state that the way to install traceback or pretty is in this form:

```
from rich.traceback import install
install()
```
In pretty much all my scripts, in order to install both traceback and pretty, I prefer to do something like this in order to keep the namespaces from colliding. 

```
from rich import pretty, traceback
traceback.install(show_locals=True)
pretty.install()
```

This usually works because import orders know that traceback and pretty are coming from the rich module. However, with the new changes made in recent PRs in how the imports for traceback are working, Python resolves `from rich import traceback` as the built-in traceback module instead, therefore the code above fails with an `AttributeError: module 'traceback' has no attribute install` since it's the wrong module completely. It's likely because with the new changes `traceback` is stomping `rich.traceback`.

**To Reproduce**

```
from rich import traceback
traceback.install()
```

**Platform**
What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

Windows 10/Windows Terminal/Rich 9.10.0

**Thoughts**
Although the way I'm doing it isn't how the docs describe (👀), the import order should generally be preserved to return the expected module. `from rich import traceback` should be expected to return `rich.traceback`.

**Comment by willmcgugan** [comment]
Hi @daddycocoaman 

I can't reproduce this.

Do you have a file called rich.py in your project?

Will

**Comment by daddycocoaman** [comment]
Sooooo nevermind. I went through the debugger and determined that another module that is imported after is importing a bunch of built-ins like `traceback` at the top level for some awful reason and is causing the stomping over `rich.traceback`. Sorry for wasting your time! Gonna close.

**Comment by willmcgugan** [comment]
No worries. Glad you got it sorted!
