### ISSUE TITLE
[BUG] Changed behavior of Progress().finished

### ISSUE THREAD

**Issue by AcidWeb** [willmcgugan/rich#978]
Not sure if it is a bug, regression or just change that missed the changelog but starting from v9.6.0 setting the zero length task no longer set `finished` to True.

```
from rich.progress import Progress

with Progress() as progress:
	progress.add_task('', total=0)
	print(progress.finished)
```

**Comment by willmcgugan** [comment]
It's somewhat undefined behavior. I think if you were to call `progress.update` then it would set the `finished` flag.

I suspect the current behavior is correct. A user might want to set the total to 0 to start the task, and set the actual total later. Do you have a use-case for adding a task already in a finished state?

**Comment by AcidWeb** [comment]
Your assumption is correct. Calling the update is setting the flag correctly.

Current version of my code depended on `finished` flag and this change created some infinite loops. I will just fix it on my side. Thank you for clarification.
