### ISSUE TITLE
Display Pandas DataFrames

### ISSUE THREAD

**Issue by cbrnr** [willmcgugan/rich#98]
I really like how R displays Tibbles (basically extended Data Frames) to highlight important features (such as missing values, negative values, column types), for example:

<img width="939" alt="Screen Shot 2020-06-02 at 16 40 42" src="https://user-images.githubusercontent.com/4377312/83533388-d2dc1880-a4ef-11ea-9ce4-7dd2165006a4.png">

The same data looks much less exciting when printing the Data Frame in Pandas:

<img width="815" alt="Screen Shot 2020-06-02 at 16 42 24" src="https://user-images.githubusercontent.com/4377312/83533591-0f0f7900-a4f0-11ea-9339-e5e5a6222e43.png">

I was wondering if Rich could be used to create a Tibble-like representation (i.e. colorize the index column, missing values, maybe even include the dtypes for each visible column)? If so, what would be a possible approach? Would it make sense to pass the full data frame contents or just the already formatted representation (returned by the Data Frame's `__repr__` method)?

**Comment by willmcgugan** [comment]
Rich could certainly render that. The most flexible approach would be to create a `Table` instance from the data.

Set `box=None, pad_edge=False` to remove the grid lines. You can color a cells with markup, i.e. `"[red]NA[/red]"` or by calling add_row with a Text instance. Headers can have multiple lines, so you could set a header as `"name\n[dim]<chr>[/dim]"`.

**Comment by cbrnr** [comment]
Would I need to input the already shortened representation (in the example, only the first and last five rows are shown, and as many columns as fit on the screen), or could Rich take care of that? I'd prefer the latter option, because I'd like to tweak that a bit as well (e.g. left-justify text columns, add row with column type info).

**Comment by willmcgugan** [comment]
Rich doesn't have any column / row hiding options, so you would have to implement that part yourself.

I could add something like that to the Table class, but I'm not sure what logic it should follow. How would you decide which columns to hide?

**Comment by cbrnr** [comment]
The auto-hiding logic should be optional, and it should be based on the available characters in the console window. Similar to what Tibbles do, I would show as many columns as possible starting from the first column (and possibly abbreviating columns with long contents, see e.g. the column `genus` in the R screenshot). If all columns (even with abbreviated contents) cannot be displayed, there could be a short summary at the end saying how many columns are not shown.

I'd prefer the R behavior (show the first N columns) as opposed to the Pandas behavior (show the first N/2 and last N/2 columns).

The same things should work similarly for rows (with a separate parameter).

I'm not sure if this feature is interesting for objects other than Pandas data frames. If you think so, then it would certainly be a good idea to add this to the `Table` class. If not, there has been some discussion about such a feature in https://github.com/pandas-dev/pandas/issues/18066 - ideally, styling data frame output in the console would be directly integrated in Pandas (but maybe this can be done with Rich as well).

**Comment by willmcgugan** [comment]
I'm not sure about building a column hiding feature in to the Table class itself. I suspect it would be hard to capture everyones use case. I think what I'll do is provide a way of customizing what columns are shown based on the table width. That way the developer can implement their own logic.

**Comment by willmcgugan** [comment]
Going to close this issue for now. I'm open to implementing that column hiding feature, but the Table class is already quite powerful and I want to draw a line under the feature set for now.

If there is enough demand I will revisit this in the future. Maybe if I get sponsorship...

**Comment by markmark1** [comment]
how to get table representation from the panda dataframe will?

**Comment by dtrckd** [comment]
Rich doesn't have to handle this hiding feature of pandas Dataframe and could leave the responsibility to the developers to get in his table what they want to render.

Undoubtedly, this would be a very nice feature.

**Comment by mikedillion** [comment]
Similar discussion over at `pandas-dev`:
https://github.com/pandas-dev/pandas/issues/57572
