### ISSUE TITLE
[BUG]'add_column' Does not automatically wrap content, nor if no_wrap = False / True. Column content is truncated with ellipsis.

### ISSUE THREAD

**Issue by Salim9304** [willmcgugan/rich#982]
[Doc](https://rich.readthedocs.io/en/latest/reference/table.html)
I have a multi-column table that I fill in, in an old version of the rich library (if the content didn't fit in the column, the column expanded downward.). Now this does not work and the content is cut off.
How to fix?
The 'no_wrap' parameter doesn't help.

**Comment by willmcgugan** [comment]
overflow=“fold”

**Comment by Salim9304** [comment]
Thanks.  This is somehow not visible in the documentation.
