### ISSUE TITLE
AttributeError: module 'rich.pretty' has no attribute 'install'

### ISSUE THREAD

**Issue by maxclac** [willmcgugan/rich#983]
Hi!

On Kubuntu 20.04, I just installed rich following the simple instructions and doing 

`$ pip install rich`

Now, when I want to install that for the REPL, I get this;

```
& python
Python 3.8.5 (default, Nov 26 2020, 21:26:46) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rich import pretty
>>> pretty.install()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'rich.pretty' has no attribute 'install'
```
Is there still something missing to my installation?

Thanks!

**Comment by willmcgugan** [comment]
Maybe you have an old version installed. Please try the following:

```
pip install rich -U
```

**Comment by maxclac** [comment]
Thank you! It is working now.
