### ISSUE TITLE
good way to add adapter to rich function

### ISSUE THREAD

**Issue by darcosion** [willmcgugan/rich#986]
Hello, 

I use rich for my project [limier](https://github.com/darcosion/limier).

I wonder how to add correct adapter to the rich function `log`.

Actually, I do : 
```python
from rich.console import Console as richConsole

console = richConsole()

#verbosity management
console.limierVerbose = functionIndicateTrueOrFalse()
#decorator function 
def limierLog(*args):
	if(console.limierVerbose):
		return console.log(*args)
	else:
		return

console.limierLog = limierLog

#using limierLog instead of log :
console.limierLog("some log")
```

It's work, but I want to create stable code for that, and maybe improve your documentation.

Can you confirm this is a good and stable way to add adapter ?

(if you want to see my actual code, unfortunately in french https://github.com/darcosion/limier/blob/master/limier.py#L51-L60 )

**Comment by willmcgugan** [comment]
This sounds like something you would use the [logging](https://rich.readthedocs.io/en/latest/logging.html) module for, which has this functionality built in.

If you don't want to use logging, I'd probably define a function with the logic you want rather than extending Console.

```python
def log(*args):
     if functionIndicateTrueOrFalse():
        console.log(*args)
```

**Comment by darcosion** [comment]
Sound like a good advice, thanks :)
