### ISSUE TITLE
[BUG] Sometimes use console.print render table instance with keywords

### ISSUE THREAD

**Issue by b3wsh** [willmcgugan/rich#987]
**Describe the bug**
Sometimes use console.print render table instance with keywords `[`,  rich will crash. example under below.

ps:
if I change Console param width size bigger than `a`'s length, this crash will disappear, at the same change the `a`'s length little than `width` size, at the same as cancel `justify` or `overflow` param of add_column.

I thought this problem cause by words split when rendering table, and then use "####" to search style.

**To Reproduce**
```
from rich.console import Console
from rich.table import Table

cons = Console(width=100)
a = "[#######.................] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx [#######.................]"
t = Table(title=f"xxx")
t.add_column("Output", justify="full", style="cyan", overflow="fold")
t.add_row(a)
cons.print(t)

```

**Platform**
full platform

**Diagnose**

```
# python -m rich.diagnose
<console width=187 ColorSystem.TRUECOLOR>
# python -m rich._windows
platform="Darwin"
WindowsConsoleFeatures(vt=False, truecolor=False)
# pip freeze | grep rich
rich==9.9.0
```

**Comment by nathanrpage97** [comment]
Take a look at [escaping](https://rich.readthedocs.io/en/latest/markup.html?highlight=escape#escaping).

Your example works with:

```python
from rich.console import Console
from rich.table import Table
from rich.markup import escape


cons = Console(width=100)
a = "[#######.................] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx [#######.................]"
t = Table(title=f"xxx")
t.add_column("Output", justify="full", style="cyan", overflow="fold")
t.add_row(escape(a))
cons.print(t)

```

**Comment by willmcgugan** [comment]
Thanks @nathanrpage97

The markup is parses a style as "######.............", which doesn't exist and is omitted from the output. But when the text wraps it calls the method `get_style_at_offset` which doesn't provide a default style, and throws the exception.

So there is an inconsistency there. It shouldn't matter if it wraps. I think the fix would be to be a bit stricter about the parsing. If the style starts with a # and isn't a valid hex color, then it should raise a markup syntax error.

@b3wsh Nathan is correct, if your string looks like console markup, but isn't, you can escape it. Or use Text class, ie. `add_row(Text(a))`

**Comment by b3wsh** [comment]
Tanks @nathanrpage97 and @willmcgugan for your solutions. I have resolve my problem.

As @willmcgugan  said, there is an inconsistency there, though Rich has provided escape method. 

Do you think  we need some change to make style parsing more robust？

**Comment by willmcgugan** [comment]
> Do you think we need some change to make style parsing more robust？

There will be a fix in the next version.

**Comment by b3wsh** [comment]
Thank you for your excellent job, I have tried to solve this, but do not find a better way, just wanna for some good code to learn. Thanks!
