### ISSUE TITLE
Editing output

### ISSUE THREAD

**Issue by NeuroAssassin** [willmcgugan/rich#99]
Hi there.

Really liking this library so far, the colors, columns and everything are so nice.  I have one question though.  I'm trying to design a bit of a "screen" for my application, with two/three columns, with settings on the left, and the status of threads in the middle/right.  I'm trying to get it with TextColumn, by updating it, however it doesn't seem like the progressbar works well with Text Column.  Everytime I try to use `add_task`, it puts it underneath the table, instead of to the right with it.  Is there a way I could do this, or is it possible there could be a way to put in variables, and update them?  Thanks.

**Comment by willmcgugan** [comment]
Text column will wrap text if the progress doesn't fit comfortably, that may be what's happening.

If you post a screenshot and some code, maybe I can give you some suggestions how to achieve what you are looking for.

**Comment by NeuroAssassin** [comment]
Sure, here's a picture of what it is + where I want it to be moved to:
![image](https://user-images.githubusercontent.com/42872277/83637076-001eda00-a575-11ea-9f2e-d1317ee45b4a.png)
And here's some of my code:
```py
table = Table(title="Settings")
    table.add_column("Setting", style="red", no_wrap=True)
    table.add_column("Value", style="blue", no_wrap=True)

    table.add_row("Host", host)
    table.add_row("Webserver port", str(port))
    table.add_row("RPC Port", str(rpcport))
    table.add_row("Update interval", str(interval))
    table.add_row("Running on", "Development server" if dev else "Production server")
    table.add_row("Logging level", "Debug" if debug else "Warning")

    console.print(Panel("Red Discord Bot Dashboard - Webserver", box=rich.box.HEAVY, expand=False), justify="center")
    console.print(Columns([table, progress.get_renderable()], equal=True))

    vartask = progress.add_task("Update variable", status="[bold blue]Starting...[/bold blue]")
    cmdtask = progress.add_task("Update commands", status="[bold blue]Starting...[/bold blue]")```
After that, I pass the tasks to some threads, which call `progress.update` on them to change it to `Running...`

**Comment by willmcgugan** [comment]
The progress bar is designed to to go at the end of the terminal. If you want to include the progress information as part of some other content, then you would have to extend the Progress bar itself.

Try extending Progress and overriding `get_renderables` to yield your content. Something like this

```python
class MyProgress(Progress):
    def get_renderables(self):
        yield COLUMNS etc
```

**Comment by NeuroAssassin** [comment]
Alright, thanks.  I'll take a look.

**Comment by NeuroAssassin** [comment]
So, I played around a bit with the progress, and realized that `progress.make_tasks_table` is what I want.  However, the issue is that `progress.refresh` prints it out onto the console, but when it does that, it prints it under my settings table because the cursor does not start on the second column I have.  I tried making the tasks not visible at first, then making the table, then making them visible, but when it refreshed it, that made it print under the settings table again.  I tried starting as visible, and that worked a bit, but it printed the tasks before the table and such, which I don't want.  Either way though, when I call refresh on it again after changing it to "Running...", it would send it to underneath the table, since it's using `console.print` and the cursor is below the table.

I'm starting to realize that I don't think this is possible due to the limitation of the console, and has nothing to do with this library.  Thanks for your help though with everything.  Feel free to close this issue, unless I'm missing something.

**Comment by willmcgugan** [comment]
If you use the `print` method on Progress, it should reposition the cursor so that it doesn't break the visions.

Run the following for a demo:

```
python -m rich.progress
```

**Comment by NeuroAssassin** [comment]
Alright, I've looked at the examples, and the rich.progress thing, and I almost have it.  The only issue now is that once I've put it in the columns, it prints it again, and edits that instead of what's in the columns.  Got a screenshot here of what it is:
![image](https://user-images.githubusercontent.com/42872277/83665454-70d7ed80-a599-11ea-80eb-5dc80a0bcab1.png)
And here's the code: ```py
    table = Table(title="Settings")
    table.add_column("Setting", style="red", no_wrap=True)
    table.add_column("Value", style="blue", no_wrap=True)

    table.add_row("Host", host)
    table.add_row("Webserver port", str(port))
    table.add_row("RPC Port", str(rpcport))
    table.add_row("Update interval", str(interval))
    table.add_row("Environment", "Development" if dev else "Production")
    table.add_row("Logging level", "Debug" if debug else "Warning")

    progress.print(Rule("Red Discord Bot Dashboard - Webserver"))
    disclaimer = "This is an instance of Red\nDiscord Bot Dashboard, created\nby Neuro Assassin. This package\nis protected under an MIT\nLicense. Any action that wil\nbreach this license\n(including but not limited to,\nremoval of credits) may result in\na DMCA request, or possibly\nmore.\nYou can view the license at\nhttps://github.com/NeuroAssassin/\nRed-Dashboard/blob/master/LICENSE."

    vartask = progress.add_task("Update variable", status="[bold blue]Starting[/bold blue]")
    cmdtask = progress.add_task("Update command", status="[bold blue]Starting[/bold blue]")
    vertask = progress.add_task("Update version", status="[bold blue]Starting[/bold blue]")

    progress.print(Columns([Panel(table), Panel(disclaimer), Panel(progress.make_tasks_table(progress.tasks))], equal=True))
```

Thanks a lot for helping me with this.

**Comment by NeuroAssassin** [comment]
Actually, I found something I like, using the `rich.prgress`.  Thanks for helping me with this.  I'll close this now.
