### ISSUE TITLE
[REQUEST] Fixed Width Progress Text Column

### ISSUE THREAD

**Issue by phcreery** [willmcgugan/rich#993]
**How would you improve Rich?**

Give as much detail as you can. Example code of how you would like it to work would help.

I would like a text column in a progress bar to be fixed width. I have created a ProgressColumn object (modified TextColumn) that does just that. I am not sure if there is already a better method of doing so by using the `text.truncate` while construction the `Progress()` class, so I created this.

```python
class SizedTextColumn(ProgressColumn):
    """A column containing text."""

    def __init__(
        self,
        text_format: str,
        style: StyleType = "none",
        justify: JustifyMethod = "left",
        markup: bool = True,
        highlighter: Highlighter = None,
        overflow: Optional[OverflowMethod] = None,
        width: int = 0,
    ) -> None:
        self.text_format = text_format
        self.justify = justify
        self.style = style
        self.markup = markup
        self.highlighter = highlighter
        self.overflow = overflow
        self.width = width
        super().__init__()

    def render(self, task: "Task") -> Text:
        _text = self.text_format.format(task=task)
        if self.markup:
            text = Text.from_markup(_text, style=self.style, justify=self.justify)
        else:
            text = Text(_text, style=self.style, justify=self.justify)
        if self.highlighter:
            self.highlighter.highlight(text)
        if self.width:
            text.truncate(max_width=self.width, overflow=self.overflow, pad=True)
        return text
```

More [here](https://github.com/phcreery/rich)

**What problem does it solved for you?**

It makes the visibility of multiple bars with leading text much easier to comprehend. It is also being used in [PR #1098](https://github.com/spotDL/spotify-downloader/pull/1098) of [spotDL/spotify-downloader](https://github.com/spotDL/spotify-downloader)

**Comment by willmcgugan** [comment]
I can see the need for this, but I have an alternative solution...

Since a ProgressColumn is ultimately used to create a table Column, I think it might be useful to explicitly set that. For instance, for a fixed width progress column you would add this:

```python
def get_table_column(self):
    return table.Column(width=40)
```

What do you think?

**Comment by phcreery** [comment]
Mmmkay, I think I see where you are going but I'm not quite sure how to implement that.

Would `make_tasks_table` need to be modified so the `for ... loop` isn't adding generic columns automatically?

**Comment by willmcgugan** [comment]
You can now specify the table column with a `table_column` parameter on the column constructor.
