### ISSUE TITLE
[BUG] Too long dict value, the display will be truncated

### ISSUE THREAD

**Issue by GeekDuanLian** [willmcgugan/rich#995]
![image](https://user-images.githubusercontent.com/6257434/107185849-22c79380-6a1e-11eb-8020-be463603ac00.png)

**Comment by nathanrpage97** [comment]
I'm able to reproduce this issue.

It comes down to [Pretty by default cropping in console.py](https://github.com/willmcgugan/rich/blob/f81b92842a423a2792693371baf7c42a13353da4/rich/console.py#L1114). 

I made a PR that provides a solution when using `console.print()`, but not `rich.print()`.

**Comment by willmcgugan** [comment]
Please try 9.11.0

The default overflow for rich.print is now "fold" which means you will see the full string. However it will hard wrap (insert new lines). You can add `soft_wrap=True` to console.print if you don't want the new lines.

**Comment by GeekDuanLian** [comment]
@willmcgugan Thanks! It looks much better now.
