### ISSUE TITLE
[BUG] whole URL is not formatted

### ISSUE THREAD

**Issue by egils-consulting** [willmcgugan/rich#997]
(edit)  en.wikipedia.org        (!bot)  'List of Kuruluş: Osman characters'
http://en.wikipedia.org/wiki/List_of_Kuruluş:_Osman_characters

the url is not colored or underlined after the "ş"

**Comment by willmcgugan** [comment]
That character isn't valid in a URL, you will need to url encode it. Browsers will do this for you automatically, but Rich is more strict. Here's that URL encoded:

http://en.wikipedia.org/wiki/List_of_Kurulu%C5%9F:_Osman_characters
